### ISSUE TITLE
Handling Zn2+ ions with AMBER forcefields

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1032]
(This is related to #726, but different enough to warrant a new issue.)

@rafwiewiora in our lab has been working on ways to deal with the Zn2+ ions [found in ~10% of all PDB structures](http://dx.doi.org/10.1021/ic401072d).  In fixed charge forcefields Zn2+ ions are not easily treated as simple Lennard-Jones spheres with a 2+ charge because they generally are found in protein structures engaged with Cys or His residues in semicovalent bonds (of the sort we used to call dative bonds).  There was a desire to build in some way to treat these that would be rather universally applicable and less "hacky" than attaching them with springs.

Much to our delight, someone tackled this issue in 1999 with a [very clever approach for fixed-charge forcefields](http://dx.doi.org/10.1007/s008940050119).  His solution was to create four dummy atoms at the tetracoordinate sites around the Zn atom that had both small mass and charge, allowing the Cys and His residues (in their appropriate protonation states) to coordinate in the proper geometry.  The ZN+dummy molecule is held together with valence terms, and is still treated as a separate residue that replaces the Zn atom alone.  The AMBER parameters are available [on a website](http://www.mayo.edu/research/labs/computer-aided-molecular-design/projects/zinc-protein-simulations-using-cationic-dummy-atom-cada-approach).

We have tested this solution in OpenMM through AMBER and it seems to work very well for us, producing reasonable-looking, stable simulations even when we have weird clusters involving two Zn2+ atoms and shared bridging CYX residues.  

We're now looking at including this Zn2+ parameter set along with our conversion of all the AmberTools 15 parameters to OpenMM ffxml format so that users can transparently handle these zinc-containing proteins if they include the appropriate `amber-zinc.xml` file in their arguments to `ForceField`.

However, we likely have to make some modifications to `ForceField` and/or `Modeller` in order to add in the dummy atoms in a plausible geometry, and are soliciting feedback on the most appropriate way to do this.  We could either
- **Modify `Modeller.addExtraParticles` to add the dummy atoms.**  This would probably require the PDB file contain bond entries between Zn2+ and the corresponding heavy atoms of the residues coordinated to them (many do) to allow each of four dummy atoms to be placed along this line.
- **Modify `Modeller.addHydrogens` to add these dummy atoms.**  We would add these to the hydrogen definition file and then modify `addHydrogens` to also consider the bonding to `S` atoms as a potential hydrogen bond acceptor.
- **Something else altogether.**  Perhaps there is a class of these kinds of dummy atoms that could be treated by a separate piece of code?  Or we could have problem-specific code in the `<script>` portion of the forcefield definition, though I'm not sure quite how that would work.

Thoughts/ideas/suggestions?  10% of the PDB is a huge amount, so it would be great if we could deal with these systems in some way.  I know that AMOEBA will eventually provide a much better way of handling these coordinated Zn2+ atoms, but since charge transfer is an important part of this phenomenon, it may still require terms even beyond AMOEBA to treat properly.

**Comment by peastman** [comment]
Could you give more detail on what the model looks like?  For example, are the dummy atoms massless vsites, or do they have mass?  Is the whole unit of zinc plus dummy atoms rigid, or does it have internal flexibility?  What are all the interactions, both within the dummy molecule and between the dummy molecule and the rest of the system?

**Comment by jchodera** [comment]
See the paper here:
http://dx.doi.org/10.1007/s008940050119
and the website here:
http://www.mayo.edu/research/labs/computer-aided-molecular-design/projects/zinc-protein-simulations-using-cationic-dummy-atom-cada-approach

These were linked to above, but duplicated for convenience.  

As noted above, the dummy atoms have mass (3 amu) and charge (0.5 proton units).  The dummy atoms are connected to the central Zn atom and each other through flexible valence terms.  The dummy atoms do not have Lennard-Jones sites---the sole site is on the Zinc, though we could add Lennard-Jones sites if this is problematic in OpenMM.

The website has the parameter files which (obviously) specify the complete details of all of the interactions.  There is also a useful image of the geometry of the system.

**Comment by jchodera** [comment]
I should again note that @rafwiewiora can do the parameter conversion; we're mainly looking for advice on the best way to modify `Modeller` to automatically build in the dummy atoms in an automatic way.  There are four dummy atoms, and they should be built along the appropriate vectors between Zn and the coordinating S of CYX or N of HIS/HIN. Either we could make these changes in a PR or @peastman could---whichever is preferable.

**Comment by jchodera** [comment]
Any input here?

**Comment by rmcgibbo** [comment]
It sounds like you have a reasonable plan, you just have to write the code to iterate over particles of the appropriate types, do the geometry calculations to find the positions, and add the particles in your scripts. That's probably 90% of the work. The remaining 10% would be to integrate your code back into OpenMM's existing ForceField and Modeller classes, but that's not strictly necessary for you to get started testing the method and running calculations.

**Comment by jchodera** [comment]
We're already up and running by creating the systems with AmberTools and loading them into OpenMM.  We're asking which of the two possible implementations (or another approach altogether) we should adopt to implement this into OpenMM so that this would be of maximum utility to OpenMM users so that we can avoid picking one approach and having someone say "that's the wrong way to do it".

**Comment by jchodera** [comment]
"We won't know which is the right approach until somebody tries one..." is also an acceptable answer.  :)

**Comment by rmcgibbo** [comment]
Well addExtraParticles seems more straightforward than addHydrogens. You
probably also need an extra residue template.

**Comment by jchodera** [comment]
> You probably also need an extra residue template.

Can you clarify?

**Comment by jchodera** [comment]
We'd certainly convert the [zinc residue template that includes extra particles](http://www.mayo.edu/research/documents/znblib/doc-10026881) to ffxml format so it could be included in `ForceField`, if that's what you mean.

**Comment by peastman** [comment]
addExtraParticles() seems more natural, since that's essentially what these are.  Extra particles are recognized by the fact that they don't have an "element" attribute in the force field.  So you create a new residue template with the extra particles, and then addExtraParticles() will add them automatically.

The challenge is how it will know where to position them.  Currently it uses two methods: 1) Look for virtual site records, and position the atom based on them, and 2) Look for a DrudeForce, and put Drude particles on top of their parent atoms.  Neither of those methods apply in this case, since your extra particles are neither virtual sites nor Drude particles.  So how will it know where to put them?

One other possible complication: are *all* Zn ions supposed to be treated the same way?  Or will some of them have the extra particles and others not?  If you have two different templates for Zn ions, this won't work properly, since addExtraParticles() won't know which ones you want handled which way.

**Comment by jchodera** [comment]
> addExtraParticles() seems more natural, since that's essentially what these are. Extra particles are recognized by the fact that they don't have an "element" attribute in the force field. So you create a new residue template with the extra particles, and then addExtraParticles() will add them automatically.

Thanks!  That is what we were thinking for the `addExtraParticles` route.

> The challenge is how it will know where to position them. Currently it uses two methods: 1) Look for virtual site records, and position the atom based on them, and 2) Look for a DrudeForce, and put Drude particles on top of their parent atoms. Neither of those methods apply in this case, since your extra particles are neither virtual sites nor Drude particles. So how will it know where to put them?

We would have to implement a new method in this function that is applied in this case.  The question would be how to appropriately generalize it.  The good news is that most of the PDB files have special `CONECT` records between the Zn and the bonded S or N atom; we could use these to figure out along which line segment to place these.  One might imagine that allowing this to be generalized to Fe, Mg2+, and other ions with special coordination geometries might be useful.

> One other possible complication: are all Zn ions supposed to be treated the same way? Or will some of them have the extra particles and others not? If you have two different templates for Zn ions, this won't work properly, since addExtraParticles() won't know which ones you want handled which way.

We would separate out this `Zn` residue definition into a separate `ffxml` file from other ion definitions so that the user can select which definition they want to use.

**Comment by jchodera** [comment]
It looks like this site/paper has more information on other multisite ion models for use with Amber:
http://septlab.engin.umich.edu/multisite-ions.html

**Comment by jchodera** [comment]
We've just discovered that AmberTools15 contains a whole "metal site binding toolbox" in Python that uses OpenMM:
https://github.com/pengfeili1/pymsmt

@rafwiewiora is going to dig into this and figure out how we can incorporate this feature.

**Comment by rafwiewiora** [comment]
I played around and conclude that the AmberTool15 metal code is not useful for this at all - at least not as this stage / for zinc / for model we decided to use. It's mainly good for non-bonded (i.e. pure electrostatic) models and just does parametrization - and parametrizing for every different structure is what we are avoiding by using the dummy atom model. It takes Gaussian outputs, does RESP charges and the bit where OpenMM is implemented - it's energy minimization for induced dipole parameters. Might be useful if we need to do the electrostatic model for any other ions, but for now I'm leaving it. 

Going to update on addExtraParticles / addHydrogens tweaking soon.

**Comment by rafwiewiora** [comment]
correction to above: the Amber metal scripts use a 'bonded-electrostatic' model rather than a pure electrostatic - i.e. there are actual harmonic bonds between Zn and the ligating residues, but the electrostatic interactions are considered too. 

Papers of interest: 
1) The bonded-electrostatic model: http://pubs.acs.org/doi/abs/10.1021/ja00022a010
2) MCPB (Metal Center Parameter Builder - this is the AMBER metal code) / ZAFF (Zinc Amber Force Field). This ZAFF thing is interesting, they made a FF using the MCPB that they say is parametrized well enough to use with any zinc containing protein within the bonded-electrostatic model. It ships with AmberTools15, but for some reason is never mentioned in the main manual. See $AMBERHOME/dat/mtkpp/ZAFF - xml ff files there, works with MTK++ (http://mtkpp.martinpeters.ie/index.html , separate manual at $AMBERHOME/AmberTools/src/mtkpp/doc/mtkpp.pdf . Paper: http://pubs.acs.org/doi/abs/10.1021/ct1002626

Might be useful in the future - e.g. try the bonded-electrostatic approach if any problems with dummy atoms / for comparison.

**Comment by rafwiewiora** [comment]
OK, so here's an update and we would love feedback / thoughts. It seemed to me that the easiest way to do this was to use pdbfixer, as adding the dummy atoms is the same as adding missing heavy atoms and the code to map a template onto a partially existing residue is exactly what pdbfixer has, but addHydrogens or addExtraParticles don't. 

The workflow goes:
1) Modify pdbfixer by adding a ZNB.pdb to the templates folder. 
2) Modify the original pdb file - change Zn's from HETATM to ATOM, change atom names from ZN to Zn, change residue name to ZNB. 
3) Run pdbfixer. 

The downside is you add the dummy atoms randomly in space I assume as there's only one existing atom of the residue (the central Zn) in place - so for now this relies on energy minimization to turn the ZNB around to the right angles with the cysteines. 

OpenMM needs the following modifications before bullding the system:
1) Add CYM (negatively charged cysteine) to the forcefield - CYX is deprotonated, but it doesn't have the right charges for a negatively charged sulfur, right? I re-processed the Amber (99SB in this case) forcefield for this, as that has a CYM. 
2) Add ZNB.xml to the forcefields. 
3) Add ZNB to residues.xml and CYM to hydrogens.xml
4) Modify the pdb made by pdbfixer - change elements of the dummy atoms to Zn  - unknown element error otherwise. 

One thing missing from this - adding the dummy atoms so that they are already on the Zn-sulfur line before minimization. 

Now this is all a bit too hacky and we think it will be best to have this integrated in Modeller, in addExtraParticles or a new method (addDummyAtoms?) even? How would you best see this done - call pdbfixer from modeller.py, / copy the appropriate code geometry code into modeller.py from pdbfixer? (I'm working out which part of the code that is right now)

**Comment by jchodera** [comment]
The main drawback of using PDBFixer to add the dummy atoms is that this doesn't make these ion parameter sets available to users that are just using OpenMM to create their systems.  OpenMM's `simtk.openmm.app.Modeller` already allows dummy atoms to be added for most other cases (virtual and extra sites), so it seems like it would make the most sense to somehow build in the ability to add these dummy sites into the `Modeller` workflow.

If we set the element type to `None` for these dummy atoms, then it seems like we should be able to modify the [`addExtraParticles`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L863) method of `Modeller` to add these dummy atoms correctly.  [Matching of templates](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L936-L973) based on the non-dummy atoms should work fine provided that the user has included only the `ZNB.xml` file and not other Zinc ion definitions.  We mainly need to add a new scheme for placing dummy atoms to the [dummy atom placement routine](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L982-L1017).

Here, we could either use a scheme similar to what `pdbfixer` does and copy over the template coordinates after coming up with a superposition based on matched template atoms using something like `pdbfixer`'s [`addAtomsToTopology`](https://github.com/pandegroup/pdbfixer/blob/master/pdbfixer/pdbfixer.py#L335)---minimization of the newly placed atoms should clean this up.  

Alternatively, if the majority of the PDB files we are working with have `CONECT` records that add bonds between the chelating `S` or `N` atoms and the `Zn2+`, we could use this information to place the dummy atom partway between the chelating atom and the zinc.  That would be my preferred approach.  We may even need to explicitly deal with and remove those bonds if the `PDBFile` class reads them in as bonds, since parameterization will otherwise fail.

**Comment by peastman** [comment]
Here's a potential problem to be aware of.  If the PDB file has a CONECT record between those atoms, then `PDBFile` will record it as a covalent bond.  That means, for example, that it will be included when calculating nonbonded exceptions.  So you won't get any nonbonded interaction at all between the S and the Zn, because it will think they're bonded to each other!

The situation is better with PDBx/mmCIF files, because they have a larger vocabulary for describing different types of "connections" between atoms.  See http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Items/_struct_conn_type.id.html.  That allows us to distinguish actual covalent bonds.

**Comment by jchodera** [comment]
[This recent paper](http://dx.doi.org/10.1021/acs.jpcb.5b10423) may also be good to look at supporting with these changes.

**Comment by jchodera** [comment]
@rafwiewiora : Are we all set here with the changes we needed for this merged in?

**Comment by rafwiewiora** [comment]
Nope unfortunately - still need to code up the choice of ligating residues and adjusting protonation states code so:

* ForceField - add support for this kind of info in the ffxml (ligating residues, coordination number, cutoff for a coordinate bond)

* add the usage of this and the distance-cutoff algorithm to `addHydrogens`.
