### ISSUE TITLE
Update ffxml files for AmberTools15

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1054]
Tagging @rafwiewiora here.  This issue will discuss our conversion and validation of all forcefields distributed with AmberTools15.

@swails: Do you already have some validation scripts to use ParmEd to compare energies between OpenMM-generated energies and Amber-generated energies?

**Comment by swails** [comment]
> @swails: Do you already have some validation scripts to use ParmEd to compare energies between OpenMM-generated energies and Amber-generated energies?

ParmEd makes it easy to compute energies and forces with both OpenMM and Amber (through the sander API), if that's what you mean.

**Comment by jchodera** [comment]
> ParmEd makes it easy to compute energies and forces with both OpenMM and Amber (through the sander API), if that's what you mean.

That's exactly it!  We were just wondering if you had example scripts for this (e.g. the scripts you used to test/validate the GB parameters recently).

**Comment by swails** [comment]
I'll try to dig them up.  Probably won't be until tomorrow though.

I'm not sure how I missed this message in the first place.  Can you open an issue on ParmEd for this with a description of what you're trying to do (for example, what kinds of files you're starting with)?

**Comment by jchodera** [comment]
@rafwiewiora: Can you tackle that?

**Comment by rafwiewiora** [comment]
Done!

**Comment by rafwiewiora** [comment]
I want to touch base on the issues with `sigma = 0` - see #732 and #979 - @jchodera has had expressions blow up because of `sigma = 0`. 

Now, @jchodera thought in #979 that the presence of `epsilon = 0 sigma = 0` atoms in the force fields was caused by [these lines in the process script] (https://github.com/pandegroup/openmm/blob/master/devtools/forcefield-scripts/processAmberForceField.py#L407-L409). This should be changed to `sigma = 1`, happy to do the PR, but I just realized the real culprit is something else. Hydrogens of `class="HO"`, at least in the amber99 fields actually have `epsilon = 0 sigma = 0` parameters. The appropriate line in parm99.dat is 
`  HO          0.0000  0.0000             OPLS Jorgensen, JACS,110,(1988),1657`

It doesn't matter what sigma is when `epsilon = 0`, but clearly we shouldn't have `sigma = 0` 's, so how about adding:
````python
if sigma == 0 and epsilon == 0:
    sigma = 1
````
 to the processAmberForceField.py?

**Comment by swails** [comment]
Really there is never a use-case for having `sigma == 0`.  If either sigma is 0 or epsilon is 0, just set sigma to 1 and epsilon to 0.  It should be equivalent:

```Python
if sigma == 0 or epsilon == 0:
    sigma, epsilon = 1, 0
```

**Comment by rafwiewiora** [comment]
Ok cool, thanks!

**Comment by peastman** [comment]
Very likely all that really needs to be changed is this line: https://github.com/pandegroup/openmm/blob/master/devtools/forcefield-scripts/processAmberForceField.py#L408.  That's probably where the zeros are coming from.

**Comment by jchodera** [comment]
@rafwiewiora: Can you create a PR for this?

**Comment by rafwiewiora** [comment]
@peastman check out the hydrogens class "HO" that I mentioned 2 comments above - that's where zeros are coming from too, even when you've already changed L408. 

@jchodera definitely!

**Comment by jchodera** [comment]
This should be marked as `enhancement`.
