### ISSUE TITLE
MPI support (Platform?)

### ISSUE THREAD

**Issue by stephanmg** [openmm/openmm#1113]
Dear all,

I'm struggling to find a good MD library which I may integrate in my custom C++ Code as a library.
I need MPI parallelism for > 100,000 procs - is there any good choice? Or could one enhance openmm for that?

Best regards,
Stephan

**Comment by swails** [comment]
> I need MPI parallelism for > 100,000 procs - is there any good choice?

Depends.  The major players here in terms of MPI performance are GROMACS, NAMD, and Desmond (Amber is known not to parallelize nearly as well, and typically tops off at no more than ~256 cores).

A quick check of [GROMACS](https://www.mpibpc.mpg.de/14613164/Kutzner_2014_ParCo-conf2013.pdf), [NAMD](http://www.ks.uiuc.edu/Research/namd/performance.html), and [Desmond](https://www.deshawresearch.com/publications/Desmond%20Performance%20on%20a%20Cluster%20of%20Multicore%20Processors.pdf) shows that in almost every case, you will not scale beyond ~1000 processors for the systems 99.9% of the community simulates.  The only result I linked that *could* be considered a counterexample is a NAMD simulation that seems to scale well out to 16K processors.  However, the only reason you see this kind of scaling is because that benchmark used over 220 *million* atoms, and peak performance with >16K processors is less than 2 ns/day.  However, getting a converged ensemble (or anything even close to resembling it) for a system that large would require *much* more simulation than typical systems on the order of 100K atoms.  For all intents and purposes, that renders the problem of a 220M atom simulation intractable in my opinion.  While the achievement is impressive from a scientific computing perspective, it is all but worthless from a science perspective IMHO.

And I don't think that this situation can be improved much more given existing hardware limitations and the long-range nature of the electrostatic force, which means that if you want to take a single system and run it on 100K systems, then there is no good choice, and I highly doubt anybody could write code that will scale out to this many processors.

So the *only* way you can make effective use of >100K processors is through the use of loosely-coupled replica-based simulations.  For example, if GROMACS scales well to 1000 CPUs for your system, you can run a REMD simulation with ~100 replicas to achieve satisfactory scaling up to 100K CPUs.  But that's really your only option.

> Or could one enhance openmm for that?

One could certainly write an MPI platform to give OpenMM distributed parallel capabilities, but earlier I stated my strong skepticism that this problem is tractable at all given current hardware limitations.  And writing an MPI platform would be a *lot* of work (and you would still need to use a *lot* of loosely-coupled replicas in an expanded ensemble simulation to get anywhere close to 100K processor scalability).

**Comment by stephanmg** [comment]
Okay,
I'm looking currently at LAMMPS, it has a nice API and documentation and I could it make run on BlueGene system readily.

How are your opinions on GROMACS and NAMD? I looked into them but could not find an easy approach how to use them as an API from my custom driver code (and the documentation says not much about/if there is an public API)

Best,
Stephan

**Comment by jchodera** [comment]
Wasn't Blue Matter specifically written for Blue Gene (the L architecture)
to scale to at least 65K cores?

**Comment by ctk3b** [comment]
While LAMMPS does _scale_ quite well to thousands of processors, it's absolute performance for standard MD with electrostatics lags pretty far behind GROMACS/NAMD/Desmond so you might end up using a _lot_ more resources to achieve the same throughput but YMMV.

**Comment by swails** [comment]
Ah, yes, I had forgotten about LAMMPS.  Even their benchmarks (http://lammps.sandia.gov/bench.html) only have parallel scalability out to ~60K atoms if they scale the size of their system up.  For fixed-size test systems, even LAMMPS tops out at ~500-1000 processor scalability.

> How are your opinions on GROMACS and NAMD? I looked into them but could not find an easy approach how to use them as an API from my custom driver code (and the documentation says not much about/if there is an public API)

I've looked at the source code for both, and I don't think either one is designed to be used as an API.  You could of course hack build scripts and create a library from which you can call their subroutines, but it won't be a user-friendly API like what OpenMM has.

> I'm looking currently at LAMMPS, it has a nice API and documentation and I could it make run on BlueGene system readily.

If this is true (which I assume it is -- I have no experience with LAMMPS), then this is likely your only choice (with the aforementioned caveats).

**Comment by peastman** [comment]
Hi Stephan,

Could you give more information about your problem?  What are you trying to calculate?  In what sense do you "need" to scale to 100,000 processors?  Do you just mean you have that many processors available, and you want to find some way to use them?

Computationally speaking, the "best" way to use many processors is almost always to just run lots of separate simulations at once.  That way it's easy to get perfect linear scaling.  And if you just need lots of sampling, many independent simulations are just as valuable as one longer one.

**Comment by stephanmg** [comment]
@peastman okay, let's say my problem size is about minimum 10,000,000 atoms. then i think it would be nice to scale at least to 10,000 procs - in essence i need an API to run let's say 10 MD simulations with 10,000,000 atoms in parallel (called from another code).

We are using the JUQUEEN superccomputer: http://www.fz-juelich.de/ias/jsc/EN/Expertise/Supercomputers/JUQUEEN/Configuration/Configuration_node.html

Our other code basis also scales very high to 200,000 procs (MPI) - but this does not include MD code.
Therefore I need an API for MD code fully-fledged with MPI capabilities to be exploited.

I looked into OpenMM which is really good for me on GPU and SMP, but not for MPI obvious.
NAMD, Tremolo-X (commercial), GROMACS, Desmond seem not to have an API.

As an addition question,
could I use OpenMM on an NVIDIA Tesla GPU-card cluster?

Thanks for your help,
and sorry for beeing kinda offtopic here.
But as @swails points out that I have to do much work to make OpenMM ready for MPI i refrain from that task and instead try LAMMPs.

Best,
Stephan

**Comment by peastman** [comment]
That isn't really what I meant.  As @swails explained, a single tightly-coupled MD simulation simply can't scale to 100,000 processors.  Not even for 10 million atoms.  That's just the nature of MD, and attempting to is pretty much guaranteed to result in very poor usage of your computational resources.  There are almost certainly better ways to use those resources to achieve your goals, which is why I asked what those goals are.  What do you want to simulate, and what do you hope to learn from those simulations?  We can then suggest if there are better approaches to take, such as running many loosely-coupled or uncoupled simulations.

>  could I use OpenMM on an NVIDIA Tesla GPU-card cluster?

Yes, but you'll be running a separate simulation on each node, with little communication between nodes.

**Comment by stephanmg** [comment]
@peastman this sounds nice (for the OpenMM on stuff).

I want to simulate protein-protein interaction of a small cluster of a given protein.
Therefore I wanted to employ long MD simulations.

**Comment by VijayPande** [comment]
You can run long simulations with single GPUs.  OpenMM is faster on a single GPU than many other codes are on multiple GPUs.   Check out the benchmarks page for details.


Thanks,

Vijay


Sent from my phone.  Sorry for any brevity or unusual tone.

On Aug 31, 2015, at 1:53 AM, Stephan Grein <notifications@github.com<mailto:notifications@github.com>> wrote:


@peastman<https://github.com/peastman> this sounds nice (for the OpenMM on stuff).

I want to simulate protein-protein interaction of a small cluster of a given protein.
Therefore I wanted to employ long MD simulations.

-

**Comment by swails** [comment]
> I want to simulate protein-protein interaction of a small cluster of a given protein.
> Therefore I wanted to employ long MD simulations.

There is no way you will get this system to scale to 100K processors for a single simulation.  It simply is not going to happen.  Even highly parallelized MD programs require at least 100 times as many atoms as processors in order to provide enough work to the various CPUs to keep them busy (which is why @peastman used 10M atoms as an example, I suspect).

The best way to use 100K CPUs is to figure out how many CPUs your choice of program can scale to, and then run enough simulations with that many CPUs to consume all 100K processors.  There are ways of "building" long-timescale simulations from a series of shorter, independent simulations (e.g., using Markov Models)

**Comment by stephanmg** [comment]
@swails okay, this sounds reasonable, do you have a specific reference for your last suggestions (using Marko Models to build up a long simulation?)

Best regards,
Stephan

**Comment by swails** [comment]
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2933958/ is a good place to start.  If you just do a basic search for "Markov State Models", you'll find a large number of references.

**Comment by stephanmg** [comment]
@swails thanks, looks great,
best Stephan
