### ISSUE TITLE
Reporting on minimisation progress

### ISSUE THREAD

**Issue by mj-harvey** [openmm/openmm#1155]
Hi,

I'd like to be able to monitor the progress of an energy minimisation - ie get a report of the iteration # and system pe.  Reporters attached  via simulation.reporters.append() don't fire during minimisation, only dynamics - is there some other way that i have missed?

Matt

**Comment by peastman** [comment]
Not currently, but it would be a useful feature.  I'll tag this as an enhancement request.

**Comment by mj-harvey** [comment]
Thanks Peter, appreciated!

Matt

**Comment by swails** [comment]
+1

My thought here is to treat this kind of like `Simulation.step` works, and successively call `minimizeEnergy` with some maximum number of steps equal to the report interval until the criteria is met or the real maximum is reached.  I'd thought about this before and that's what I came up with.  If it sounds good, I can try and draft a PR for it.

**Comment by peastman** [comment]
The problem is that the steps aren't independent.  LBFGS uses information from previous iterations to improve its behavior on future iterations.  So if you call it ten times with maxIterations=10, that doesn't work nearly as well as calling it once with maxIterations=100.

Constraints will also cause problems for it.  LBFGS doesn't support constrained optimization, so instead we replace all the constraints with harmonic forces.  We run the whole minimization that way, then check the constrained distances.  If any is violated by more than the allowed tolerance, we increase the strength of the harmonic forces and minimize again.  If the constraints are only violated by a little bit, we continue minimizing from where we left off.  But if they're too far off, then we go back to the beginning and minimize from scratch.  That's important to avoid getting stuck in a bad state and having the minimization completely fail.

**Comment by swails** [comment]
Glad I didn't try this before, then :)

**Comment by ajasja** [comment]
I would also like to monitor minimisation (especially useful when debugging an exploding system:). 

In NAMD the default is that minimisation gets written to the trajectory file. Personally I would argue that the reporters should fire during energy minimization.

**Comment by MJfadeaway** [comment]
I wonder what is the real positions after running energy minimization

**Comment by peastman** [comment]
You can query the positions with `context.getState(getPositions=True).getPositions()`.

**Comment by aizvorski** [comment]
@peastman Continuing discussion here:

> The process works by replacing all constraints with harmonic restraints, then minimizing, then checking whether the constraints are satisfied, then tightening the restraints if they aren't, then possibly doing a bit more minimization or possibly going back to the beginning and restarting the whole minimization from scratch. So what do you report and when?

I think every LBFGS step and/or every coordinate update should callback and/or print.   Basically, if we have a new energy or gradient, or anything else changes, call the callback.  I understand that not all of those would be the same, so the value (namedtuple or similar) passed to the callback can contain some extra info, either in flags or a comment.  

For example: step, total energy, gradient, restraints strength, restraints energy(if available separately?), sum of constraints, max constraint difference, comment="restarting LBFGS because ..." or "changing restraints strength and continuing because ..." or "converged"

**Comment by kirill77** [comment]
Hi! I am trying to simulate a gas made out of H and O atoms and see how water molecules form. I see that right after the first step - all molecules have already formed. I don't see any 'smooth' formation as I was hoping. Is that because of energy minimization? My program is:

```
pdb = PDBFile('./myTest/input.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.0004*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
nSteps = 1
reporter = PDBReporter('./myTest/output.pdb', nSteps + 1)
for uStep in range(0, nSteps + 1):
        state = simulation.context.getState(getPositions=True, getVelocities=False, getForces=False,
                                        getEnergy=False, getParameters=True, enforcePeriodicBox=False,
                                        groups=simulation.context.getIntegrator().getIntegrationForceGroups());
        reporter.report(simulation, state)
        simulation.step(1)
```

**Comment by peastman** [comment]
You're using a force field that doesn't model chemical reactions.  It takes all bonds as given and doesn't let bonds form or break.  To simulate that, you generally need to use a quantum chemistry package, though there also are classical models that try to approximate it.

If you want to discuss this further, could you open a new issue?  Your question is unrelated to this issue.

**Comment by peastman** [comment]
This feature keeps getting requested, so I really feel like we should do something about it.  It just isn't clear to me what would be possible and useful.

The biggest problem is that minimization doesn't work the way people assume it does.  The expectation is that if you call `minimizeEnergy(maxIterations=20)`, the minimizer will perform a series of up to 20 iterations.  Each iteration will hopefully cause the energy to decrease.  Once it finishes 20 of them, or sooner if the forces are small enough, it will return.  People want to be notified of the current energy and iteration count after each iteration completes.

That isn't really how it works.  In fact we replace all the constraints with harmonic restraints and perform minimization of the combined energy+restraints objective.  It isn't actually minimizing the function people assume it is.  Each "iteration" is really a line minimization involving many evaluations of the objective function, some of which may have very high energies.  Then when it finishes the minimization it looks to see if the constraints are sufficiently satisfied.  If not, it tightens the restraints (producing an immediate jump in energy) and does more iterations.  If they're really badly satisfied it may throw out all the work it has done so far and start over from scratch with tighter restraints.

The other problem is that we've never really clarified what the goals of this feature are.  There are some obvious questions people might want to learn from callbacks.  Is minimization succeeding?  How close is it to finishing?  Could I have gotten almost as good results with fewer iterations?  Given the complexity of the real process, it isn't clear that the simple implementations discussed above would give an accurate answer to these questions.  Is a potentially incorrect answer better or worse than no answer at all?

A related question is what callbacks would be used for.  If the goal is simply for a human to watch the progress as it happens, a series of text messages would probably work.  But for other purposes you would want to receive reports in a machine readable form.  What information would you need?  How could we communicate events like tightening the restraints or throwing out work and starting over?

**Comment by aizvorski** [comment]
@peastman Thanks for coming back to this!  I'll try to answer

> The other problem is that we've never really clarified what the goals of this feature are

For me, the main goal is _to decide how long to run the minimization for_.  You can think of it as either early stopping (request a very large number of max steps, then decide to stop at some point before that) or as extending a run (request a small number of steps, then decide whether to do more) but the two are essentially the same feature.  The external code/callback that decides when to stop the minimization can have a significantly more complicated notion of "convergence" than just gradient norm; it can have access to the entire history of coordinate updates and corresponding energies and gradients, which leaves a lot of room for clever algorithms.

The other big use case is manual debugging and/or automated sanity checking.  This probably involves plotting gradient norm per step, coordinate rmsd since the best coordinates to date, and so forth.

>  What information would you need? 

I recommend copying, as much as possible, the `scipy.optimize.minimize(callback=...)` interface which passes an [OptimizeResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult) to the callback.  This can hold whatever information we want; the scipy version contains the coordinates, objective function value, jacobian (if available) and hessian (if available); instead of the hessian it may have the (approximate) hessian inverse (which I'm guessing we do have here with LBFGS, and which is a very interesting bit of info).

Rationale: this is a pretty well thought out API, supports multiple use cases that we may not have thought of in advance, and if people know any similar API it would probably be that one.

> If the goal is simply for a human to watch the progress as it happens

I think that is the less interesting use case, but it would be supported by callback=print

> How could we communicate events like tightening the restraints or throwing out work and starting over?

I see what you mean about the complicated issues with constraints.  Perhaps the "energy due to harmonic restraints" and "rest of energy" can be reported as separate items (maybe also "forces due to restraints" and "rest of forces"?), as well as the "restraint strength" and "error in constraints".  Tightening the restraints would be a callback with higher restraint strength and higher "energy due to harmonic restraints"; starting over would look similar but the coordinates would also jump to older ones, perhaps in that case we can also add a flag to the OptimizeResult to let the user know this is a reset

**Comment by peastman** [comment]
> For me, the main goal is to decide how long to run the minimization.

Be aware that multiple short minimizations are not the same as a single longer minimization.  L-BFGS uses information from past steps to make each step more efficient.  That history doesn't get kept between calls.  Two calls for 10 steps will not produce as good a result as a single call for 20 steps.

This will need to be built on the L-BFGS library's callback interface:

https://github.com/openmm/openmm/blob/d2593f386a627d069b5ec17a3a2f4ecd40d85dd1/libraries/lbfgs/include/lbfgs.h#L396-L427

We can report information that is either provided by it, or that we can compute inexpensively.  It provides the value of the objective function, which is the system energy plus restraint energy.  Recomputing the restraint energy is cheap, so we can separate out the two components.  The maximum constraint error would also be easy to compute.  Hessians aren't available.

What about a callback signature like

```c++
void callback(const vector<double>& x, const vector<double>& grad, const map<string, double>& args)
```

where `x` is the flattened array of coordinates, `grad` is the flattened array of gradients, and `args` contains various other scalar statistics.  That lets us easily add other statistics without breaking the interface.

**Comment by peastman** [comment]
The implementation is in #4207.  Give it a try!

**Comment by peastman** [comment]
Has anyone had a chance to look it over?  I'd really appreciate feedback on the API.

**Comment by sef43** [comment]
It works for me. I think we need a clear example of the Python API in the Documentation or the Cookbook for how to use it for the commonly asked for example of showing how the system energy changes during minimization process. E.g. something like the following:
```python

# Define a subclass of Minimization Reporter
class Reporter(MinimizationReporter):
    interval = 10 # report interval
    energies = [] # array to record progress
    def report(self, iteration, x, grad, args):
        # print current system energy to screen 
        if iteration % self.interval == 0:
            print(iteration, args['system energy'])

        # save energy at each iteration to an array we can use later
        self.energies.append(args['system energy'])

# Create an instance of our reporter
reporter = Reporter()

# Perform local energy minimization 
print("Minimizing energy...")
simulation.minimizeEnergy(reporter=reporter)

# plot the minimization progress
plt.plot(Reporter.energies)
plt.show()

```
