### ISSUE TITLE
GB warning issued even when implicit solvent model not in use

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1374]
We keep getting your GB warnings:

```
/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/simtk/openmm/app/internal/amber_file_parser.py:1010: UserWarning: Non-optimal GB parameters detected for GB model OBC2
  'model %s' % gbmodel)
```

The offending code [is here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/amber_file_parser.py#L1009-L1010).

Is there a way to turn your warning off or to tell `AmberPrmtopFile.createSystem()` to replace the GB parameters with the recommended parameters?  It seems like the current behavior is non-ideal.

**Comment by swails** [comment]
This was specifically discussed [here](https://github.com/pandegroup/openmm/pull/1311#discussion_r50171871) in #1311 (quite recently).

Basically, this behavior [was chosen based on your comment](https://github.com/pandegroup/openmm/pull/1310#issuecomment-166984725).  But I thought it was better to warn than go off and use the wrong radii silently.

**Comment by swails** [comment]
Oh, but this shouldn't happen for explicit solvent simulations.  I'll fix that.

**Comment by jchodera** [comment]
Can we make the warnings optional, then?

And is there a mechanism to actually overwrite the parameters?  That could also be good optional behavior.

We have a case where we use this function many times, and it would be good to specifically disable this warning (e.g. for forcefield optimization) without disabling *all* warnings...

**Comment by swails** [comment]
So I don't see how this code could possibly be hitting when gbmodel is not set...

Also, the `warnings.filterwarnings` function is more than flexible enough to silence this warning without silencing anything else (and it's quite easy to do that, too).  The argument list to `createSystem` is already quite large and complicated, so I try to avoid adding more.

> And is there a mechanism to actually overwrite the parameters? That could also be good optional behavior.

You mean something like

```Python
def createSystem(..., useSuggestedRadii=False, ...)
```

? :wink:

**Comment by jchodera** [comment]
> So I don't see how this code could possibly be hitting when gbmodel is not set...

It wasn't, it seems.  I tracked down one instance where we had accidentally set this.

> Also, the warnings.filterwarnings function is more than flexible enough to silence this warning without silencing anything else (and it's quite easy to do that, too). 

Ah!  Will use this.

> def createSystem(..., useSuggestedRadii=False, ...)

Aha! Yes, thank you!

**Comment by swails** [comment]
> Aha! Yes, thank you!

Sorry, that's not actually an argument.  I was trying to poke fun at the idea of having an argument along the lines of "use the correct parameters" that defaults to False ;).  There is no way to override that specifically.  The current solution is to set the correct radii in the prmtop (using ParmEd, for instance).

**Comment by jchodera** [comment]
> Sorry, that's not actually an argument. I was trying to poke fun at the idea of having an argument along the lines of "use the correct parameters" that defaults to False ;). There is no way to override that specifically. The current solution is to set the correct radii in the prmtop (using ParmEd, for instance).

Ah, OK.

**Comment by jchodera** [comment]
Do the GB subclasses have the ability to automatically assign GBSA parameters?  Or do we still need to tackle this via a `<script>` section in the ParmEd-based conversion of Amber forcefields in order to have GBSA support for small molecules via the `app.ForceField` route?  I think I might have been confusing these features.

**Comment by swails** [comment]
In seriousness though, what is the desired behavior here?  Are we OK with adding an argument to AmberParm's createSystem along the lines of `useRadiiFromPrmtop=True`?  Or should we pick a default behavior and warn when the two approaches differ?

**Comment by swails** [comment]
> Do the GB subclasses have the ability to automatically assign GBSA parameters?

Yes, if you wanted them to.

> Or do we still need to tackle this via a <script> section in the ParmEd-based conversion of Amber forcefields in order to have GBSA support for small molecules via the app.ForceField route?

I was under the impression this was the route you wanted to go so you had more control over the assigned parameters.

The main reason the GB radii assignment was moved to the GB models was so that many of the parsers could use them rather than implementing them on their own (for example, the CHARMM file parsers had the different radius sets hard-coded in those files).  They could also easily be added to the GROMACS topology file system creator.

As I mentioned in one of the previous threads discussing this, a side-effect of that PR is that you can *try* this approach for `ForceField.createSystem` if you wanted to and see how you liked it.

**Comment by peastman** [comment]
What's the status of this?  Is everyone ok with the current behavior, or do we need any changes?

**Comment by jchodera** [comment]
I think we need to modify behavior to handle small molecules, but I don't have the time to gather what needs to be done until early next week.

**Comment by peastman** [comment]
It looks like we still need to determine what, if anything, needs to be done for this.

**Comment by swails** [comment]
I don't see anything that necessarily needs to change.  IMO the "correct" behavior should either be defined as "use the radii from the prmtop file" or "use the radii suggested for the GB model".  We should make whatever we decide is the "correct" behavior the *actual* behavior, and not provide a toggle switch to access the wrong behavior.

That's currently what we have, and we define using the prmtop radii as the "correct" behavior.  The weakness of this argument here is that there may not be consensus on what is "correct", so maybe a toggle option is justified.  I think it's more "correct" to use the suggested radii, which is why I added a warning when it disagrees with the ones in the prmtop.  But the prmtop radii are easily changed for someone that is comfortable with Amber workflows (and can be incorporated directly into Python scripts via the ParmEd API).
