### ISSUE TITLE
openmm in MIC of Intel(xeon-phi)

### ISSUE THREAD

**Issue by Tron-x** [openmm/openmm#1413]
anyone is interesting in transplant the openmm to the mic of Intel (xeon-phi)?

**Comment by pesimov** [comment]
For all I know, transplanting openMM to Xeon-Phi will be a non-trivial task. 

I have to look at Xeon-Phi's requirements again to find out the amount of work required. I have a memory that both openMM's interface and algorithms would require changes.

**Comment by pesimov** [comment]
I plan on starting a Masters this fall. While I considered something different, I might reflect on the idea of using openMM on Xeon-Phi.

**Comment by peastman** [comment]
I spent quite a while trying to get the OpenCL platform working acceptably on Xeon Phi, and eventually concluded it was completely worthless.  Even after lots of effort trying to optimize it, using the card was slower than just running on the CPU.  That was with the first generation Xeon Phi, so maybe it's improved since then.  At the time, though, it had major limitations that made it pretty much unusable.  For example, the kernel launch overhead was about 200 us, compared to about 5 us on a GPU.  And it had no hardware support for thread barriers, so they had to be emulated in software and any kernel that used a barrier was absurdly slow.

**Comment by Tron-x** [comment]
if i just want to transplant the ameoba force feild to the mic(xeon-phi),is it possible?

**Comment by peastman** [comment]
AMOEBA is only implemented in CUDA.  (And reference, but that's a completely unoptimized code that doesn't even attempt to be fast.)

**Comment by Tron-x** [comment]
Can i locate the whole code of  amber force feild? for example ,tinker ,i can exteact the whole MD code from tinker just to run amber force feild .i want have a try to tansplant the code to the MIC(xeon-phi)

**Comment by peastman** [comment]
Take a look at the developer guide: http://docs.openmm.org/6.3.0/developerguide/index.html.  It explains the architecture of OpenMM and how the various pieces of code are structured.
