### ISSUE TITLE
Modeller.addHydrogens() does not add hydrogens to the C terminals at low pH

### ISSUE THREAD

**Issue by aghanbar** [openmm/openmm#1544]
There is this issue I have been struggling with. I have been trying to simulate my peptides at very low ph (2 or 1) and when I use Modeller.addHydrogens() to add hydrogens, it seems that openmm does not make the c terminals neutral, as one would expect in low pH. I have also looked at the hydrogens.xml and forcefiled xml files and it seems that there is no bond term for a hydrogen attached to the terminal oxygen (OXT), so I just couldn't add them manually. Any ideas?

**Comment by peastman** [comment]
The force fields are the real problem.  It wouldn't be hard to make Modeller add hydrogens there, but then you would get a Topology that couldn't be simulated with any standard force fields.  Has anyone published parameters for that case?

**Comment by aghanbar** [comment]
It seems that the only solution is to treat the terminal residues as non-standard residues and build a parameter file and load it in tleap, generate amber inpcrd and prmtop files and feed them to openMM. However, once this approach is taken, I cannot make a modeller object from the files and solvate it using addSolvent(), since it causes to give energy NaN during the simulation. The whole jobs of solvation, setting box dimensions, etc must be done using tleap. I think it would be good to be able to include non-standard residues parameters directly in openMM.

**Comment by peastman** [comment]
addSolvent() should work fine.  There's no reason for that to cause problems.  However, you would then be back to the same problem.  Modeller would give you a new Topology, and ForceField wouldn't be able to process that Topology because it wouldn't have a template for the terminal residues.

> I think it would be good to be able to include non-standard residues parameters directly in openMM.

What did you have in mind?  The force fields we provide are automatically generated from the definition files in the original program (so Amber force fields are generated from Amber's definition files, AMOEBA force fields are generated from Tinker's definition files, etc.).  They include everything that was in those original files.  So if we don't have a modified version of the terminal residue, it's because Amber didn't provide one either.

**Comment by aghanbar** [comment]
What I meant was being able to modify the forcefield object using a parameter file. Something like forcefield.addParam('new_res.prep','new_res.frcmod'). This way, the user can introduce new parameters for non-standard residues without modifying the original forcefield xml files.

**Comment by peastman** [comment]
You can absolutely do that.  Just create an XML file containing the modified residues, then list it along with the main XML file when you create your ForceField object:

```Python
ff = ForceField('amber10.xml', 'modifiedTerminalResidues.xml')
```

See http://docs.openmm.org/7.0.0/userguide/application.html#creating-force-fields.

**Comment by peastman** [comment]
Closing this old issue.
