### ISSUE TITLE
rigid body simulation

### ISSUE THREAD

**Issue by Tron-x** [openmm/openmm#1604]
could openmm run rigid body simulation?

**Comment by peastman** [comment]
Get the rigid body script from https://simtk.org/plugins/moinmoin/openmm/VirtualRepository.

**Comment by peastman** [comment]
> could you provide a rigid body simulation example. a whole simulation.not the script of define rigid body.

I don't specifically have a script that uses it, but here's an example of what the relevant code might look like.  This assumes you've already loaded your Topology and atom positions, and created a System.

```Python
from rigid import createRigidBodies
# Make each residue a rigid body.
bodies = [[atom.index for atom in residue.atoms()] for residue in topology.residues()]
createRigidBodies(system, positions, bodies)
# system has now been modified, so go ahead and use it as normal
```

**Comment by Tron-x** [comment]
thank you !,but this rigid body simulation is not what we want ,we need the simulation like the rigid simulation provided by Tinker ,the force is not on every atom, for example ,the water ,we do not compute the force on every atom,we just regard the water molecule as a whole,we just compute the rotation force and translation force as this paper 
https://www.cs.cmu.edu/~baraff/sigcourse/notesd1.pdf
does openMM provide this module？
or how could we make it, thanks very much!

**Comment by peastman** [comment]
No, OpenMM is for particle based simulation.  You can build up rigid bodies out of particles, but it doesn't provide explicit rigid body integration.

**Comment by Tron-x** [comment]
could openMM add this module,tinker has this module ,but it not good use,

https://www.cs.cmu.edu/~baraff/sigcourse/notesd1.pdf

**Comment by peastman** [comment]
We don't have any plans to do that.  It would require a different architecture, and there are other codes designed for that sort of thing.  And for most molecular simulations, building up rigid bodies out of particles works just as well.

**Comment by jchodera** [comment]
I wonder if something *decent* could be constructed using OpenMM with:
* a clever algorithm to assign constraints between particles in rigid bodies that would try to minimize effort for convergence of the CCMA algorithm
* a multiple timestep integrator that uses no forces for the inner timestep, just constraints, like in the [g-BAOAB integrator](http://rspa.royalsocietypublishing.org/content/472/2189/20160138)

Our  lab doesn't have use for such a thing right now, but I imagine it could be made reasonably efficient in OpenMM.

**Comment by peastman** [comment]
I don't think that would have much advantage over the existing script.  The only one I can see is that the inertia tensor would be exact rather than approximate.  But it would also be a lot more expensive.

**Comment by ajasja** [comment]
@peastman @Tron-x I guess this can be closed due to inactivity?

**Comment by mvanvleet** [comment]
As a related issue, will this rigid body script work (or can it be made to work) for linear molecules? I tried using the script for CO2, and am running into NaN errors (which don't appear in the flexible molecule simulation):

[rigid_co2.zip](https://github.com/pandegroup/openmm/files/1014981/rigid_co2.zip)

**Comment by peastman** [comment]
You would need to modify it a bit for that.  A linear molecule would only require two "real" particles, and all the others would be defined with TwoParticleAverageSites.

**Comment by peastman** [comment]
And along the same lines, a planar molecule would only have three "real" particles.

**Comment by mvanvleet** [comment]
Thanks Peter. I've put in the modifications you suggested. The only caveat I would add (for any future viewers) is that, in order to reproduce the correct moment of inertia, the positions of the "real" particles must be chosen carefully. There's a [tutorial ](http://www.bevanlab.biochem.vt.edu/Pages/Personal/justin/gmx-tutorials/vsites/02_topology.html) in Gromacs for how to do this properly for linear molecules.

**Comment by arjunwadhawan** [comment]
Hello @mvanvleet . Can you share your modified script for Co2 Simulation (which works without NaN) ?  

I am trying to simulate Co2 in water using OpenMM and cannot keep the O=C=O angle fixed to 180 degree. It would be right to make it rigid (as suggested above).
I tried to modify the script but not sure about the positions and still running in NaN.

**Comment by peastman** [comment]
An easy way to do that would be to constrain the distance between the oxygens, then make the carbon a virtual site.  You can use TwoParticleAverageSite to position it directly between them.  You'll have to transfer the carbon's mass to the oxygens (virtual sites must be massless), which will somewhat increase the moment of inertia.

Alternatively you could make one of the oxygens the virtual site.  In that case you could adjust the masses of the other two atoms to keep the moment of inertia unchanged, but then the center of mass will move a bit off center.

**Comment by mvanvleet** [comment]
Sure thing @arjunwadhawan . Attached are my run scripts for a box of pure CO2, which you should be able to modify easily for your simulation. The command
```bash
python run_co2.py
```
runs the simulation for rigid co2 using a Lennard-Jones force field.
The scripts follow the Gromacs tutorial I referenced above, and choose the positions of the mass centers so as to properly conserve both the center of mass and the moment of inertia. 

[rigid_co2.zip](https://github.com/pandegroup/openmm/files/1265046/rigid_co2.zip)

Let me know if you have any questions and I'm happy to help troubleshoot.

**Comment by jchodera** [comment]
@arjunwadhawan : Forcefields like AMBER that use pure harmonic angle bending energies can't handle linear molecules like CO2 because the gradient is underfined near 180-degrees. Instead, alternative functional forms, such as those that use the cosine of the angle, can handle these just fine. For a discussion of this issue, see [this paper by Bill Swope](http://dx.doi.org/10.1002/jcc.540130508), which describes expressions for angle bending that should be easily implementable in OpenMM's [`CustomAngleForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomAngleForce.html#simtk.openmm.openmm.CustomAngleForce).

**Comment by arjunwadhawan** [comment]
@mvanvleet Thanks for replying and sharing.There is an error and it does not run . 
Force Field (lj_co2.xml) does not recognise the changed topology (model_topology) and raises: 
" ValueError: Residue 1 (co2) does not match any template defined by the ForceField. "

Since you were kind enought to help me troubleshoot, i thought of asking the possible reason. I think  : -
1- Virtual Site's  AtomTypes is not defined in the force field file (lj_co2.xml) for new topology (after addMassCenters's) ? or 
2- Virtual Site's bonds not defined in the force field file (lj_co2.xml) but present in the new topology
which fails it 

I tried to add AtomTypes and bond  (attached xml) but it still fails. Can you help me find why it does not work ? 
[lj_co2_edited_by_arjun.xml.zip](https://github.com/pandegroup/openmm/files/1266821/lj_co2_edited_by_arjun.xml.zip)


thanks @peastman for the description. It is much clear now 
thanks @jchodera for the info and paper. i will try to use CustomAngleForce.

**Comment by arjunwadhawan** [comment]
@jchodera : I tried to use [CustomAngleForce](http://docs.openmm.org/latest/userguide/application.html#harmonicangleforce) using the equation 2 of the paper you mentioned (as it seem simple).  
<img width="674" alt="equation" src="https://user-images.githubusercontent.com/21062948/29941424-d4faaf1c-8e92-11e7-87e2-fdeb76d0587b.png"> 


The angle does not remain fixed if I use CustomAngleForce instead of HarmonicAngleForce . Attached is a test system where I simulate 4 Co2 molecules for 20 ps with different Angle force function. If you run the script (in python 2) , it would generate a graph of angle with time. There is very much fluctuation in angle .

I may have done something wrong and if so ill be glad if someone can help. 
[simulate_co2_for_angle.zip](https://github.com/pandegroup/openmm/files/1268280/simulate_co2_for_angle.zip)

**Comment by jchodera** [comment]
@arjunwadhawan : I think you just forgot to convert your force constant `k` when switching from a harmonic form in `theta` to a harmonic form in `cos(theta)`. Recall that `k = 451.9 kJ/mol/rad^2` in your parameter set, but when transforming to `cos(theta)`, your new `k` will have units of `451.9 kJ/mol`. 

I'd imagine the correct way to relate these two is to expand the `cos(theta)` form in a Taylor series about `theta = \pi`, but I note that the quadratic term in `(theta-\pi)` actually vanishes, and only the quartic term survives. So I'm not actually sure how best to map the two spring constants onto each other directly, other than to say you will likely ned to make the spring constant much larger for the `cos(theta)` form, or derive a new fit to the QM vibration data using the new functional form.

**Comment by mvanvleet** [comment]
@arjunwadhawan : Apologies, I forgot to update the Lennard-Jones force field I gave you to include the new dummy residues. Attached is an updated set of scripts which should run properly.

[updated_rigid_co2.zip](https://github.com/pandegroup/openmm/files/1350068/updated_rigid_co2.zip)

**Comment by sohviluukkonen** [comment]
Hello,

I'm trying to simulate a rigid quinoline molecule (C9H7N) in spce water. I use the @peastman 's rigid.py script to make the solute rigid. 
It works if a use CPUs and a timestep of 0.5fs (or less). If I use a larger timestep (i would like to use 2fs timestep)or GPUs (Tesla K80) it gives me the error "Exception: Particle coordinate is NaN".

Do you have any clues why it does not work on GPUs or have any suggestions how to increase the timestep?

Thank!

[Rigid_quinoline.zip](https://github.com/pandegroup/openmm/files/1406670/Rigid_quinoline.zip)

**Comment by peastman** [comment]
It looks like it's getting confused by the fact that your molecule is entirely planar.  Within each rigid body, it selects four particles to act as the "real" particles, constrains all the distances between them, and then turns all the other particles into virtual sites.  That works when the four real particles form a tetrahedron.  But if they're all in a plane, it leads to an ill conditioned constraint matrix.  In that case, you really want to have only three real particles.

**Comment by XingchengLin** [comment]
Hi,

I would like to apply this rigid body script to simulate a rigid body with many atoms. I am wondering if we can turn off the intra-rigidbody bonded and nonbonded forces to save computational expenses?

It seems the addException function of the NonbondedForce is a good choice (https://github.com/openmm/openmm/blob/1344f2e0714dc035d7abf7bc4b4435793da8e7ab/openmmapi/src/NonbondedForce.cpp#L160). I am wondering if there is a similar function for the CustomNonbondedForce and the various Bond Forces?

Thanks,

**Comment by peastman** [comment]
Adding exceptions (to a NonbondedForce) or exclusions (to a CustomNonbondedForce) makes it slower, not faster.  It has to do extra work to keep track of which interactions it should skip.

For bonded forces, simply don't include bonds that are internal to the rigid body.

**Comment by XingchengLin** [comment]
Thanks, Peter!

For the nonbonded force, Lammps has a function of "neigh_modify exclude" (https://docs.lammps.org/neigh_modify.html) to turn off pairwise interactions by excluding them from the neighbor list. Do you think there is a similar way to implement that in OpenMM?

Thanks!

**Comment by peastman** [comment]
You can add exclusions, but adding a lot of them will make it slower, not faster.

**Comment by smliu1997** [comment]
So recently I run coarse-grained simulation for a protein with rigid body settings for its ordered domains. I found with Nose-Hoover integrator, it seems like the protein extends dramatically compared to the same rigid body simulation with Langevin middle integrator at same temperature. I wonder if this is because with rigid body setting the degrees of freedom are decreased and this increases the effective temperature when using Nose-Hoover integrator?

**Comment by peastman** [comment]
No idea.  Are you sure it's really a difference between integrators, and not just a random difference between two runs?

**Comment by smliu1997** [comment]
The only difference between two runs are integrators, and for Nose-Hoover integrator I have about 300 ns temperature replica exchange simulation trajectory so I think the result is not just random fluctuation.

**Comment by peastman** [comment]
But it's based on only a single run of each integrator?  That doesn't tell you whether it's a reproducible effect of the integrator.

Anyway, Nose-Hoover should work correctly with constraints and virtual sites.  The temperature doesn't depend on the number of degrees of freedom.

**Comment by smliu1997** [comment]
So for Langevin middle integrator, I have temperature replica exchange simulation (6 replicas with temperatures from 300K to 400K) and each replica trajectory is 3000 ns long. The same simulation system with Nose-Hoover integrator, I also have 6 replicas and each replica trajectory is about 300 ns long (though the trajectory is shorter than Langevin middle integrator, I think Nose-Hoover gives faster dynamics). The radius of gyration (Rg) sampled by Nose-Hoover is more than 2 times of the Rg sampled by Langevin middle integrator at the same temperature. I think the result is robust instead of just random fluctuations.

**Comment by sef43** [comment]
How large are the rigid bodies? How are you doing the temperature replica exchange? Errors/incorrect sampling in the replica exchange could also produce differences in the Rg

**Comment by smliu1997** [comment]
We use torch.distributed to do the replica exchange and we have tested the simulation protocol without rigid body setting and with Langevin middle integrator, and the Rg is comparable to the benchmark, so I believe the replica exchange protocol is correct. 

The system includes 382 CG beads, and there are three rigid bodies of size 56, 62, and 56 (three ordered domains of the protein), so each rigid body is of medium size. Rigid body setting + Langevin middle integrator performance looks reasonable, but rigid body + Nose-Hoover integrator dramatically extends the system, which makes me doubt if the combination of rigid body and Nose-Hoover integrator change the effective temperature.

**Comment by peastman** [comment]
Can you open a new issue?  This one has already been closed, and your question is only tangentially related to the original question.  If you can provide all code and files needed to reproduce it, that will be a big help.

**Comment by smliu1997** [comment]
Ok let me prepare all the files and I will open a new issue.
