### ISSUE TITLE
Travis tests are timing out

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1620]
Has anyone noticed the travis tests are timing out only a fraction of the way through the unit tests?

e.g. 
https://travis-ci.org/pandegroup/openmm/jobs/165684947

**Comment by jchodera** [comment]
@peastman : Is there a way to have `make tests` run just a subset of tests? If so, we can split the testing up into separate travis branches so that we can ensure all tests are actually run.

**Comment by peastman** [comment]
The timeouts only happen on the VM that runs OpenCL tests.  If we try to make it run all tests, it exceeds the limit allowed by travis.  We discussed this a while ago and settled on the current arrangement: set a timeout short enough that travis won't complain, knowing that it won't get through all tests in that time.  But we tell it to run the tests in a random order, so every test gets run pretty often, even though it doesn't run every time.

**Comment by jchodera** [comment]
That strategy may work in the long run, but it sounds like it won't allow us to necessarily catch bugs in PRs that may introduce them, making it possible to commit buggy code to `master` and frustrating identification of which PR was responsible for introducing the buggy code.

It looks like [ctest supports running specific test ranges](https://cmake.org/Wiki/CMake/Testing_With_CTest#Running_Individual_Tests). Why not just run multiple testing branches that split up the tests into groups of 50. This could potentially actually *speed up* the time it takes to run the tests since the branches can run in parallel.

**Comment by peastman** [comment]
Something like that could work, but we need to be a little careful.  The number of tests gradually increases with time.  I worry about an arrangement where every time it reaches a new multiple of 50, we need to update the travis script.  Because chances are high no one will think to do that, and there will then be a set of tests that *never* get run, and no one will notice they aren't getting run.

What about breaking it up by precision?  Have one VM run the single precision tests, a second one do mixed precision, and a third one do double precision?  Hopefully each of those could run in the allowed time without problem.

**Comment by jchodera** [comment]
> What about breaking it up by precision? Have one VM run the single precision tests, a second one do mixed precision, and a third one do double precision? Hopefully each of those could run in the allowed time without problem.

Sounds like it would be worth a try! Is that as simple as specifying four branches, like this?
```bash
ctest -R Single # run all tests with "Single" in the name
ctest -R Mixed # run all tests with "Mixed" in the name
ctest -R Double # run all tests with "Double" in the name
ctest -E "{Single,Mixed,Double}" # run everything else
```

**Comment by peastman** [comment]
That looks reasonable to me.
