### ISSUE TITLE
New desmond performance

### ISSUE THREAD

**Issue by giadefa** [openmm/openmm#1719]
http://www.deshawresearch.com/publications/Desmond-GPU%20Performance%20as%20of%20November%202016.pdf

I have not seen any comment on this, but the new Desmond finally showed good performance. 
They don't show timestep 4 with PME, but otherwise they would be faster than everybody else I believe.
Also it will be interesting to see the new alternative scheme for long range electrostatic.

**Comment by jchodera** [comment]
DESRES quotes 339.5 ns/day with PME on a GTX TITAN X Pascal, and 383.3 with u-series. Note that this uses an MTS scheme with a 2.5 fs inner timestep and 5.0 fs outer timestep.

A Sep 2016 benchmark of a development version of OpenMM run on a GTX TITAN X Pascal gives 368 ns/day, which scaled up to 2.5 fs timestep (without any MTS) is already 460 ns/day:

https://github.com/pandegroup/openmm/issues/1576#issuecomment-244530021

So I guess OpenMM is 35% faster, even without MTS?

**Comment by swails** [comment]
My experience is that the scaling isn't perfect.  Longer timesteps mean fewer steps are run between pairlist builds (which are expensive), so a 2.5 fs timestep will spend more time building pairlists per total simulation time compared to a 2 fs timestep.  That said, I don't know what the actual reduction would be.

For example, Amber runs 347.91 ns/day with a 4 fs timestep, and 180.13 ns/day with a 2 fs timestep on the same card with the same system.  The reduction won't be much (only ~5% slowdown for doubling the timestep in Amber), but it'll probably be some.

**Comment by giadefa** [comment]
Hi,
sorry you are right. I misremembered the performance on TitanX compared to 1080.  This is using acemd v3 based on openmm7.1 kernels at 4fs.

`#   Timestep      Time/ps           PE           KE       TotalE       Temp/K         nm^3       ns/day
            0         0.00   -68629.382      481.077   -68148.305        8.739      240.990        0.000
         5000        20.00   -73196.079    15382.939   -57813.139      279.425      240.990      576.000
        10000        40.00   -71605.566    16220.202   -55385.364      294.633      240.990      691.200
        15000        60.00   -71107.508    16477.781   -54629.727      299.312      240.990      648.000
        20000        80.00   -71245.947    16585.008   -54660.939      301.260      240.990      691.200
        25000       100.00   -71319.962    16445.622   -54874.340      298.728      240.990      664.615
        30000       120.00   -71052.121    16590.845   -54461.276      301.366      240.990      691.200
        35000       140.00   -71100.760    16575.320   -54525.439      301.084      240.990      672.000
        40000       160.00   -70969.877    16556.635   -54413.242      300.745      240.990      658.286
        45000       180.00   -71014.717    16481.754   -54532.963      299.384      240.990      676.174
        50000       200.00   -71214.172    16544.543   -54669.629      300.525      240.990      664.615
`

We could quickly add multi time steps and see the performance gain. PME is stable at 8fs, this was the normal way of running on acemd v2.

**Comment by giadefa** [comment]
Still looking forward to the new paper on electrostatics

**Comment by VijayPande** [comment]
we should be making a big deal of this!!!!


On Jan 12, 2017, at 12:18 PM, John Chodera <notifications@github.com<mailto:notifications@github.com>> wrote:


DESRES quotes 339.5 ns/day with PME on a GTX TITAN X Pascal, and 383.3 with u-series. Note that this uses an MTS scheme with a 2.5 fs inner timestep and 5.0 fs outer timestep.

A Sep 2016 benchmark of a development version of OpenMM run on a GTX TITAN X Pascal gives 368 ns/day, which scaled up to 2.5 fs timestep (without any MTS) is already 460 ns/day:

#1576 (comment)<https://github.com/pandegroup/openmm/issues/1576#issuecomment-244530021>

So I guess OpenMM is 35% faster, even without MTS?

**Comment by jchodera** [comment]
@swails: On a GTX TITAN X Pascal (which I think is clocked slower than the one used for the benchmark numbers quoted above), I get for OpenMM `master`:
* 2.0 fs : 350.444 ns/day 
* 2.5 fs : 424.475 ns/day (21% faster, short of the expected 25% speedup)

DESRES quotes 339.5 ns/day with PME on a GTX TITAN X Pascal, and 383.3 with u-series, so OpenMM at 2.5 fs (without MTS) is still faster than DESMOND with u-series by 10%. 

An apples-to-apples comparison of PME DESMOND against OpenMM using the same PME settings may be insightful, though.

**Comment by giadefa** [comment]
Hi John,
I think that we are confusing ourselves and my first impression was right,
Desmond is faster.

Desmond is 595.8 ns/day on a GTX Titan X Pascal with timestep 2.5. Desmond
is 339 ns/day on an old TITAN X with timestep 2.5. So it is faster than
openMM even using PME.  Desmond is a lot faster using mu-series with
timestep 4 with 1us/day, while openMM is around 670 ns/day with timestep 4
as in my acemd3-openMM test above (but it should be identical on openMM).


gianni

**Comment by swails** [comment]
> Desmond is 595.8 ns/day on a GTX Titan X Pascal with timestep 2.5.

That's still using an MTS integrator, which I'm pretty sure @jchodera did not use (to achieve 424 ns/day).  MTS will probably not bring the performance up to Desmond's numbers, but it will probably get a fair bit faster so the comparison is again not fully apples-to-apples (also turn off trajectory printing, as that is probably orders of magnitude slower in OpenMM than Desmond).

If you really wanted to compare Desmond with OpenMM in terms of raw performance, you'd probably have to run both programs on the same card with the same input (preferably without MTS, as OpenMM requires a custom integrator for that).

**Comment by jchodera** [comment]
@giadefa: You're right---I read the wrong "GTX TITAN X" entry!

**Comment by giadefa** [comment]
I think that it's likely that openmm is on par with Desmond on PME if
openmm starts using MTS, even if just a simple Trotter expansion. Why there
is not MTS? It's rather simple to implement. Any specific reason.

**Comment by VijayPande** [comment]
I’m pretty sure Peter has implemented it some time ago.  People must need to run the benchmarks with it.


On Jan 16, 2017, at 10:26 AM, Gianni De Fabritiis <notifications@github.com<mailto:notifications@github.com>> wrote:

I think that it's likely that openmm is on par with Desmond on PME if
openmm starts using MTS, even if just a simple Trotter expansion. Why there
is not MTS? It's rather simple to implement. Any specific reason.

**Comment by jchodera** [comment]
MTS *is* implemented in OpenMM as [`MTSIntegrator`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.mtsintegrator.MTSIntegrator.html#).

However, OpenMM is not heavily optimized to achieve large speedups through the use of MTS. Simply splitting the reciprocal-space contribution into the "slow" group (5 fs timestep) and doing all other calculations in the "fast" group (2.5 fs timestep) while keeping the PME cutoff at 9 A doesn't show a speedup at all:
* 2.5 fs without MTS: 424.475 ns/day
* 2.5 fs with MTS: 358.786 ns/day

This could be because the use of `CustomIntegrator` by `MTSIntegrator` slows things down. Using an `MTSIntegrator` where all the forces are in a single group and propagating with 2.5 fs timestep gives 303.059 ns/day.

Much of the key to speeding things up with MTS relies on good force splittings.

The most exciting scheme for using clever integrators to speed things up is the recent [g-BAOAB integrator from Leimkuhler](http://rspa.royalsocietypublishing.org/content/472/2189/20160138). This uses several tricks:
* The outermost timestep propagates only waters, which are rigidly constrained analytically by SETTLE
* The innermost timestep just propagates the force-free SHAKE/RATTLE to achieve good adherence to the constraint manifold
* The middle timestep propagates the rest of the forces, though additional clever force splittings can be used if desired

This could give big speedups in principle, since the forces involving waters only need to be evaluated every ~8 fs or so, but would also require some way for us to exclude the waters from the middle timestep force evaluations to achieve significant speedup.

**Comment by peastman** [comment]
Comparing the performance of different codes is *hard*.  A couple of years ago I wrote up a proposal for a way to meaningfully benchmark different codes against each other.  I sent it out to a bunch of people, but no one seemed to be very interested in it.  I'll repost it here in case anyone thinks this is now worth pursuing.

----
Creating benchmarks that are truly comparable between different codes is a challenging task.  I suggest beginning from the following principle.  We should distinguish which properties of a simulation typical users (biologists and chemists) will care about, and which ones can be treated as implementation details.  We should then precisely specify all the properties that users will care about, while leaving everything else unspecified so that each code can tune them for optimal performance.  Here are some examples of what I mean.

Integration Algorithms

The most common choice for MD simulations is some variation of the Verlet integrator, but many other choices also get used: rRESPA, Beeman, Runge-Kutta, various types of predictor-corrector, etc.  Any of these algorithms can integrate the equations of motion to arbitrary accuracy.  We therefore should set requirements for integration accuracy, but not specify that one particular algorithm must be used.

Thermostats and Barostats

Lots of methods are commonly used for temperature and pressure regulation.  For example, Langevin, Anderson, and Nose-Hoover are all generally regarded as "good" thermostats that produce a correct thermal distribution.  In contrast, the Berendsen algorithm is generally regarded as a "bad" thermostat that does not produce a correct distribution.  Codes should be free to use any thermostat and barostat algorithms they choose so long as they produce correct results.

Numerical Accuracy

Some codes use double precision floating point exclusively.  Others make extensive use of single precision.  Some codes even use fixed point math.  What matters is the accuracy of the final results.  We should set requirements for accuracy, but not specify that a particular numeric representation should be used internally.

PME

There are lots of parameters that affect the accuracy of forces computed with PME: the direct space cutoff, the grid size, the B-spline order, and the separation parameter (alpha).  By changing two or more of these parameters at once, you can trade off work between different parts of the calculation without changing the accuracy of the computed forces.  The optimal parameter values for a given accuracy depend on the relative costs of different parts of the calculation, and that may vary between codes.  We should therefore set a requirement for the accuracy of the forces, but allow each code to use any parameter values that satisfy the requirement.

In contrast to the above examples, there are some aspects of the simulation that users will legitimately care about.  We therefore should specify a unique choice for them, even if it is not the only reasonable choice.  Here are some examples.

Constraints

The most common arrangement for protein simulations is to make water molecules rigid and constrain the length of bonds that involve a hydrogen.  When using a Verlet integrator, the time step is then usually set to 2 fs.  Some codes allow the time step to be further increased through some combination of additional constraints, virtual sites, and mass redistribution.  This is often a useful thing to do, but it is still a meaningful change to the simulation.  Constraints and virtual sites alter the energetics of the system.  Mass redistribution does not change energetics, but it does alter the dynamics.  These are things users may genuinely care about.  The basic benchmarks should therefore use only the standard constraints (water, bonds involving hydrogen).  On the other hand, codes that support other modes are still free to publish additional benchmarks that use them.  They just should make it clear that those benchmarks are not directly comparable to the standard ones.

Periodic Box Shape

Some codes support non-rectangular periodic boxes.  Changing the shape of the box is a meaningful change to the simulation.  If you take a rectangular box and simply cut off the corners, that reduces the size of the water bath, and also reduces the average distance between periodic copies.  This makes the simulation less accurate.  On the other hand, if you hold the number of water molecules fixed but reformat them into a non-rectangular box, that increases the average distance between periodic copies, which makes the simulation more accurate.  And of course, the word "accurate" here is neither uniquely defined nor well understood.  It isn't clear how to compare two simulations with different periodic box shapes.  The basic benchmarks should therefore specify a rectangular periodic box.  Once again, codes that support non-rectangular boxes are free to publish additional benchmarks that use them, but those cannot be directly compared to the standard ones.

This leaves us the task of defining a set of requirements that simulations must satisfy.  Some obvious candidates include

* the absolute error in the computed energy
* the median (over all atoms) relative error in the computed forces
* the maximum (over all atoms) absolute error in the computed forces
* the rate of energy drift in an NVE simulation
* statistical properties of simple liquids (e.g. water), such as density, diffusion coefficients, etc.

We need to think carefully about how to define each of these.  For example, what are the "correct" values for the forces and energy?  Even when two codes claim to be using the same force field, there tend to be enough subtle differences between them (e.g. the ordering of atoms in improper torsions) that they cannot be expected to match exactly.  Likewise, "energy drift" can be measured in various ways that give very different values.

The tolerance we set for each of these metrics should be chosen to be typical of real simulations, neither excessively strict nor excessively loose.  A good rule of thumb would be that about 50% of users would consider that value "good enough" for their simulations.

A useful approach could be to distinguish between two types of simulations: ones to validate parameters, and ones to measure performance.  For example, simple liquids make very useful systems for validation.  They are simple enough that all force field parameters can be precisely specified, so different codes should be able to produce nearly identical forces and energies.  Also, statistical properties converge quickly enough that we can calculate them to high accuracy.  For the actual benchmark, we would then specify a protein in water with the same total number of atoms and same shape for the periodic box.

As another example, precise energy conservation is much more important in constant energy simulations than in constant temperature ones.  The majority of MD simulations are done with constant temperature, so we should pick an energy conservation tolerance that is appropriate for that.  To actually measure it, though, we need to do a constant energy simulation (recognizing that the energy drift will be greater than what would be acceptable in a "real" constant energy simulation).

These requirements should not be taken as an invitation to hyper-optimize every parameter.  Different codes should use identical parameters except when there is a good reason not to.  For example, the generally accepted step size for a Verlet integrator with hydrogen-containing bonds constrained is 2 fs.  All codes that use a Verlet integrator should therefore use that value, even if you find you can increase it to 2.084 before the energy drift exceeds the allowed value.

Here is a related way of thinking about this.  The goal is not just to achieve the required accuracy in one evaluation.  The parameters should be chosen so you can reasonably expect it to always be achieved.  If you run many simulations, the energy drift should never exceed the allowed value.  If you compute the energy and forces for every step of a simulation, their errors should never exceed the allowed values.

Finally, we need to consider what benchmarks to include.

Choice of Systems

DHFR has become a standard benchmark, so we should definitely include that.  We probably should also include something larger, in the 50,000-100,000 atom range.  And we might consider also including something smaller, perhaps around 5000-10,000 atoms.

Electrostatics

We should definitely include a benchmark using PME.  Should we also include a benchmark for another method such as reaction field?  Should there be an implicit solvent benchmark?

Ensembles

NVE?  NVT?  NPT?  For the actual benchmark simulations, NPT is probably the best choice, but as noted above we need to do an NVE simulation first to measure the accuracy of energy conservation.

**Comment by okpatil4u** [comment]
Is it possible to calculate self and transport diffusion coefficient using Openmm ?
