### ISSUE TITLE
Context seems to be left in an inconsistent state after NaN

### ISSUE THREAD

**Issue by andrrizzi** [openmm/openmm#1920]
In `openmmtools` we have implemented a system to recover from NaNs. Briefly, if after integrating the energy is NaN, we restore positions/box vectors in the last working state, we randomize the velocities and we try again for few times before giving up and interrupt the simulation. This works most of the time, but I've noticed few weird things.

I'm running a protein-ligand system in a dodecahedral box with `openmm 7.1.1` and CUDA platform on a GTX1080. After 4 consecutive failed recovery attempts (using a `LangevinIntegrator`), I tried these:

1. If I delete the `Context` object and create a new one in the last working state (i.e., with last working positions/velocities/box vectors), the integration does not result in a NaN anymore.
2. If I call [`context.reinitialize()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.Context.html#simtk.openmm.openmm.Context.reinitialize) and set the last working state, the integration does not result in a NaN.
3. I serialized `System`, `Integrator` and `State` objects and created a checkpoint in the last working state. I can reproduce the persistent NaN if I load the checkpoint, but I can't if I recreate the `Context` using simply the serialized `State`.

This makes me think that the first NaN can sometimes trigger an inconsistent internal state in the `Context` object or on the GPU. Is this known/to be expected? And are there workarounds that avoid recreating the `Context`?

**Comment by jchodera** [comment]
Would calling `context.reinitialize()` do the trick?

If so, I wonder if we should have OpenMM automatically trigger a `context.reinitialize()` the next time someone tries to reuse the context after an `NaN` exception.

**Comment by andrrizzi** [comment]
> Would calling `context.reinitialize()` do the trick?

I tried that, but I often got some sort of memory corruption (see point 2 above).

**Comment by andrrizzi** [comment]
Ah, the segfault seems to happen only with `CustomIntegrator`s, so it's possible that this part of the issue (the segfault) is caused by our implementation. I'll investigate. For now I'll update my first post.

**Comment by jchodera** [comment]
Do we have to call `integrator.reset()`?

**Comment by andrrizzi** [comment]
> Do we have to call `integrator.reset()`?

Probably something like that (it may not be sufficient).

**Comment by andrrizzi** [comment]
I've managed to create a minimal script to reproduce the segfault. Here are [all the files needed](https://github.com/pandegroup/openmm/files/1439252/reproducesegfault.zip). I can reproduce this on CUDA and OpenCL.

Notice the weird workaround: if I access any integrator's global variable between the integration and the reinitialization, it doesn't segfault anymore.
```python
import sys
from simtk import openmm

def read_serialized_objects():
    deserialized_objects = []
    for file_name in ['system', 'state', 'integrator']:
        with open(file_name + '.xml', 'r') as f:
            deserialized_objects.append(openmm.XmlSerializer.deserialize(f.read()))
    return deserialized_objects

def recreate_context():
    system, state, integrator = read_serialized_objects()
    platform = openmm.Platform.getPlatformByName('CUDA')  # OpenCL fails too.
    context = openmm.Context(system, integrator, platform)
    context.setState(state)
    return context

if __name__ == '__main__':
    context = recreate_context()
    integrator = context.getIntegrator()

    # If I don't integrate, there's no segfault.
    integrator.step(1)

    # Workaround: decomment this line to fix the segfault.
    # integrator.getGlobalVariable(0)

    context.reinitialize()

    print('This call causes a segfault')
    sys.stdout.flush()
    integrator.getGlobalVariable(0)
```

**Comment by peastman** [comment]
I just sent a PR to fix this: #1924.  It turned out to just be a missing return statement.  Could you try it out and verify if it fixes the problem for you?

**Comment by andrrizzi** [comment]
Thanks! I'll give it a go.

**Comment by andrrizzi** [comment]
The segfault is fixed on the OpenCL platform, thanks!

I couldn't test the first part (the chain of NaN) because the cluster's ccmake is too old. For that, I'll wait for the `dev` release to be up, and I'll reopen the issue in case I still notice a weird behavior.

**Comment by jchodera** [comment]
Once @peastman merges the PR, I can trigger a rebuild of the `dev` conda package.

@andrrizzi : You might want to ask the HPC group to install an updated ccmake module if this isn't conda-installable.

**Comment by jchodera** [comment]
I spoke too soon: CMake (which provides `ccmake`) is conda-installable: https://anaconda.org/anaconda/cmake

@andrrizzi : In general, it's a good idea to use `conda` to manage your build environment. You can install the same dependencies as the [`build` section of `meta.yaml` for `openmm` does](https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml#L19-L38) to portably create an environment you can build in.

**Comment by andrrizzi** [comment]
Ah, sorry. I searched conda only for ccmake, and that didn't come up. I'll give it a go then.

**Comment by jchodera** [comment]
We could even build a cknda metapackage just for the openmm 7.2 build environment dependencies if that could be useful!

**Comment by andrrizzi** [comment]
Sorry, but I'm still observing this behavior, even if the segfault was fixed. To summarize:
* After the first NaN, using a `LangevinIntegrator`, if I restore positions/box vectors and randomize the velocities, the next `step()` ends again in a NaN ~50-75% of the time, but calling `context.reinitialize()` and doing the same always makes the next `step()` successful.
* Also, I noticed that the same systems nans out very consistently on `CUDA` (at least once every ~50fs), but never on `OpenCL` on the same machine and using the same precision (mixed).

Any idea of what could be going on?

I don't have the rights to reopen the issue. Should I open a new one instead?

**Comment by jchodera** [comment]
@andrrizzi : Do you mean `openmmtools.integrators.LangevinIntegrator` or `simtk.openmm.LangevinIntegrator`?

**Comment by andrrizzi** [comment]
I tried with both and I obtained the same results.

**Comment by peastman** [comment]
I reread your original post to make sure I'm clear on exactly what you're observing, and I realized I'm not.  I'd like to clarify a few points.

> I serialized System, Integrator and State objects and created a checkpoint in the last working state. I can reproduce the persistent NaN if I load the checkpoint, but I can't if I recreate the Context using simply the serialized State.

Does that mean that you save either a checkpoint or a serialized state just before the error happens?  That is, it's a point when you can compute forces and energies and they're fine, but if you take just a few (how many?) more steps, you get a NaN?  But that's only reproducible if you load the checkpoint, not if you load the serialized state.  Is all of that correct?

A checkpoint includes all internal information, including the state of the random number generator, so that behavior is (hopefully) completely deterministic.  If you load a checkpoint and integrate from there, you should get exactly the same results you got on the original system.  But a state doesn't store all of that.  When you create a new context and load the state, it just reinitializes the random number generator with a new seed.  So it's not surprising if loading the checkpoint leads to reproducible results and loading the state doesn't.

It's strange that you get NaNs with CUDA but not OpenCL.  I'm not sure why that would happen.  Is it possible for you to provide a test case that would let me reproduce that?

**Comment by jchodera** [comment]
I don't believe @andrrizzi is saving either a check point or a serialized state. As he notes in the original issue, he caches the original positions and box vectors, and when he hits a NaN, he sets the original box vectors and positions (in that order!) and randomizes the velocities. When he does this, the integrator always gives Naan. But if he INSTEAD used the same box vectors, positions, and velocities in a new Context restored from a serialized state (otherwise identical), it works fine.

**Comment by peastman** [comment]
> I don't believe @andrrizzi is saving either a check point or a serialized state.

He specifically mentioned both of them in the bit I quoted.

> When he does this, the integrator always gives Naan.

Yummy!  How did you create an integrator that produces naan?

**Comment by jchodera** [comment]
Whoops, you're right, of course. I didn't think our original failure used checkpoints at all---that must have been a feature of his debugging.

I would pay dearly for an integrator that produced naan, as well as a phone that understood "NaN" in autocorrect.

**Comment by jchodera** [comment]
@andrrizzi, doesn't that mean we can just reinitialize the context and set box vectors, positions, and velocities and integrate along our merry way?

**Comment by peastman** [comment]
Are you resetting context parameters too?

**Comment by andrrizzi** [comment]
I did both experiments (the serialization/checkpoint and the reinitialization)

> A checkpoint includes all internal information, including the state of the random number generator, so that behavior is (hopefully) completely deterministic.

Good point! However, I'm not sure this is just a problem with the number generator because I can loop this process several times (nan -> reset positions/box vectors + randomize velocities -> step) using the same context and the pseudorandom numbers should be all different at each cycle.

> It's strange that you get NaNs with CUDA but not OpenCL. I'm not sure why that would happen. Is it possible for you to provide a test case that would let me reproduce that?

I'll work on this! Hopefully, the two things are related.

> doesn't that mean we can just reinitialize the context and set box vectors, positions, and velocities and integrate along our merry way?

Correct! This is the plan if I can't find the source of the problem in the short term. However, I'd like to avoid that if possible since reinitialization takes a lot of time, and this system nans a lot.

> Are you resetting context parameters too?

Nope! I'll try this too, thanks! Just to check, this entails querying the `State` before every integration and setting it back if it fails, correct? Or is there a smarter way?

**Comment by jchodera** [comment]
Just to clarify, @andrrizzi: after a NaN you'd like to simply set the box vectors, positions, and then randomize velocities  and simply continue integrating, but this causes nothing but NaNs?

**Comment by andrrizzi** [comment]
Pretty much! Or at least stopping the NaNs by performing an extra operation on the `Context` that is cheaper than reinitializing. Even better would be if it doesn't NaN at all, of course, which is why I'm trying to understand why `OpenCL` never NaNs in the first place.

**Comment by bb30994** [comment]
Not that it's going to help much (since I know nothing about the construction of the model -- and the FAHCore wasn't built with contemporary software) but we've seen the same behaviour in FAH.  Sometimes when a model explodes, the simulation can be restarted from a checkpoint and often continues to completion -- or sometimes it runs for quite a while and then explodes again.

From a scientific perspective absolute reproducibility after a checkpoint is restored may not be 100% required -- since one random number is just as good as another.

Without internal knowledge of OpenMM, I ASSUMED it progressed  only because the random number generator was restarted with a new seed.  You're contradicting that assumption (fine) so my secondary assumption is that whatever integration method is being used has some higher order terms that are NOT preserved, but rather the integrator is reinitialized based on some values that were NOT preserved in the checkpoint.  (I don't like that theory much better.)

Of course a third option is that the FAH hardware platform isn't perfectly stable -- which does happen from time to time in that context.  Hopefully that's not what is going on in andrrizzi's context.

BTW, John: naan is Farsi (Persian) for bread.  NaN, well, that's something else.

**Comment by bb30994** [comment]
Not that it's going to help much (since I know nothing about the construction of the model -- and the FAHCore wasn't built with contemporary software) but we've seen the same behaviour in FAH.  Sometimes when a model explodes, the simulation can be restarted from a checkpoint and often continues to completion -- or sometimes it runs for quite a while and then explodes again.

From a scientific perspective absolute reproducibility after a checkpoint is restored may not be 100% required -- since one random number is just as good as another.

Without internal knowledge of OpenMM, I ASSUMED it progressed  only because the random number generator was restarted with a new seed.  You're contradicting that assumption (fine) so my secondary assumption is that whatever integration method is being used has some higher order terms that are NOT preserved, but rather the integrator is reinitialized based on some values that were NOT preserved in the checkpoint.  (I don't like that theory much better.)

Of course a third option is that the FAH hardware platform isn't perfectly stable -- which does happen from time to time in that context.  Hopefully that's not what is going on in andrrizzi's context.

BTW, John: naan (نان) is Farsi (Persian) for bread.  NaN, well, that's something else.

**Comment by peastman** [comment]
> I ASSUMED it progressed only because the random number generator was restarted with a new seed.

That's correct.  FAH uses serialized states, which don't include information about the random number generator, so it gets restarted with a new seed.  Checkpoints do record the state of the random number generator, but they're specific to the particular hardware you were running on.  You can't save a checkpoint on one computer, then load it on a different computer with a different GPU, so they aren't useful for FAH.
