### ISSUE TITLE
collective rotational restraints in OpenMM?

### ISSUE THREAD

**Issue by sstolzenberg** [openmm/openmm#1921]
Dear All,

I am trying to explore a way to switch from ACEMD to OpenMM.

Unfortunately, I have some mandatory harmonic restraints (i.e. that restrain the off-diagonals of the moments of inertia tensor of a group of atoms), which I can't seem to readily implement in OpenMM (not even with the openmm-plumed interface due to some odd installation issues:
https://github.com/peastman/openmm-plumed/issues/7
).
To me, it seems that within OpenMM alone, a CustomForce class is the way to go, but all such classes already implemented seem not to allow the definition of global parameters (in my case the three off-diagonal) that can get automatically & efficiently updated for per particle force evaluations after every integration step.
Is there an easy for me to implement this, without requesting another CustomForce implementation? (I do need CUDA).

Thanks a lot,
Best,
Sebastian

**Comment by jchodera** [comment]
It sounds like this should be very easy with custom forces, but I'm not quite understanding (1) which atoms you want to restrain, and (2) what the functional form for these restraints should be (including the global parameters). Could you post some pseudocode that does what you envision?

**Comment by sstolzenberg** [comment]
# assume the principal components of moments of intertia
# of a set of atoms are initially
# aligned with x,y,z axes, i.e.:
# I_xy, I_xz, I_yz     equal  0
# (I_xy, I_xz, I_yz are the global parameters that change at every MD iteration)
# I_xx, I_yy, I_zz not equal 0
# restraining potential:
# U_rst = 0.5k( I_xy**2 + I_xz**2 + I_yz**2)
for i in MD_iterations:
    I_xy, I_xz, I_yz = compute_Ixyz(coordinates)
    F = compute_restraining_forces_per_particle(I_xy, I_xz, I_yz,coordinates, k)
    apply_restraining_forces_on_every_paricle(F)
    
Thanks!
- Sebastian

**Comment by sstolzenberg** [comment]
Hello and Happy New Year,

Does my pseudo code above make sense?

Thanks,
Sebastian

**Comment by peastman** [comment]
There are a couple of problems.  The first is just that there isn't any force that computes the principle components of inertia.  You could write a plugin that does that, but you couldn't do it with just a custom force.

The other problem is that this approach is inherently unstable.  It could work as long as the molecule is sufficiently asymmetric so that the inertia tensor is very different along the three axes, and there aren't any large conformational changes.  But what if the moment of inertia happens to be the same (or very close) along two axes?  Then the principle axes become poorly defined.  Small conformational changes could cause totally different directions to get picked, and your molecule will start swinging around wildly.

I would think that a better approach would involve aligning it to a reference conformation.
