### ISSUE TITLE
OpenMM 7.2 documentation improvements

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1953]
@peastman : I'm just looking through the documentation updates in the User Guide for the new forcefields:
http://docs.openmm.org/development/userguide/application.html#force-fields

Some observations:
* Since you put most of the files into `amber14/` and `charmm36/` subdirectories, does that mean `openmm-forcefields` should no longer install the directly converted files in `amber/` and `charmm/` subdirectories? I hadn't realized you were going to create your own amber and charmm subdirectories when we settled on that naming convention.
* Do you want to mention `amber14-all.xml` in the amber table as well?
* Should we create a metapackage with `amber14-all.xml` and a recommended water model?
* Is your `charmm36.xml` without waters, meaning that you would also need to include a water model as well?
* Should we really have `amber14-all.xml` with the `-all` suffix but just `charmm36.xml` without it?
* If we don't build metapackages with water, what about including an example users can cut-and-paste, like 
```python
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
```
in each section for Amber14 and CHARMM36
* Let's definitely state the provenance of where Amber14 comes from (AmberTools17.5) and CHARMM36 (http://mackerell.umaryland.edu/charmm_ff.shtml from the July 2017 update)
* Let's also state where the conversion scripts are found:
https://github.com/choderalab/openmm-forcefields
* Under [Acknowledgments](http://docs.openmm.org/development/userguide/introduction.html#acknowledgments), we'll have to add a few more grants---I'll get these to you soon.

**Comment by peastman** [comment]
> I hadn't realized you were going to create your own amber and charmm subdirectories when we settled on that naming convention.

My goal was to keep the file names consistent between force fields.  For example, TIP4P-Ew should always be defined in a file called `tip4pew.xml`, just with a possible directory prefix in front of it.  Also, it's likely that future force fields will involve yet more files with similar or identical names, so that's why I used the force field name as a directory prefix.

I guess that means you might want to reconsider how you name directories.  I don't expect to ever have directories with the exact names "amber" or "charmm", but they still might be confusing.

> Should we create a metapackage with amber14-all.xml and a recommended water model?

I don't think there's really a single recommended water model.  I believe the force field was parametrized with TIP3P, so that might be the natural choice.  But on the other hand, it's a really bad water model, and TIP3P-FB has been shown to produce good results with Amber force fields.  Then again, if you don't mind the performance cost, a four point water model is more accurate.

Anyway, what I decided to do with amber14-all.xml is to combine all the files that are specifically recommended in the Amber manual.  Since they don't recommend a particular water model, I didn't include one.

> Is your charmm36.xml without waters, meaning that you would also need to include a water model as well?

Correct.

> Should we really have amber14-all.xml with the -all suffix but just charmm36.xml without it?

That's because amber14-all.xml is just a shortcut for including several different files at once.  charmm36.xml is a single monolithic force field, not a collection of swappable pieces, so "all" doesn't apply to it.

> what about including an example users can cut-and-paste, like

Already done.  I modified the "first example" script to use those files.  simulatePdb.py in the examples folder also uses them.

> in each section for Amber14 and CHARMM36

Good idea.

**Comment by jchodera** [comment]
> I guess that means you might want to reconsider how you name directories. I don't expect to ever have directories with the exact names "amber" or "charmm", but they still might be confusing.

Suggestions? Should I call ours `amber14/source/` and `charmm36/source/` to imply direct conversions of the source files or something?

> Already done. I modified the "first example" script to use those files. simulatePdb.py in the examples folder also uses them.

I was suggesting you duplicate the code snippet at the beginning of "Forcefields" with an equivalent recommended cut-and-paste snippet at the top of the Amber14 and Charmm36 sections:
![image](https://user-images.githubusercontent.com/3656088/33638470-5a0065c4-d9f4-11e7-92c4-4e88bca64af7.png)

Whatever we can do to get users up and running quickly by suggesting code they should copy-and-paste is helpful to them!

**Comment by peastman** [comment]
> Should I call ours amber14/source/ and charmm36/source/ to imply direct conversions of the source files or something?

It might be best to create a unique top level directory and put everything inside that.  You could call it "forcefields" or something like that.  Make it very easy for users to tell exactly which files were installed by the separate package.

**Comment by jchodera** [comment]
> It might be best to create a unique top level directory and put everything inside that. You could call it "forcefields" or something like that. Make it very easy for users to tell exactly which files were installed by the separate package.

Maybe `forcefields/amber/converted/` and `forcefields/charmm/converted/`?

**Comment by jchodera** [comment]
Or maybe `converted-forcefields/amber/`?

**Comment by peastman** [comment]
What does "converted" indicate?  I mean, all the force fields were converted from some other source.
