### ISSUE TITLE
What's the OpenMM's mechanism of finding GPU device id?

### ISSUE THREAD

**Issue by ymwangg** [openmm/openmm#2000]
I'm running replica exchange simulations using OpenMM c++ API and MPI using GPUs. Now I'm trying to use the CUDA platform without specifying the device id. 

I found a strange behavior that when I'm using 10 GPUs on 10 different nodes, some MPI processes could use the CUDA platform and some could not. This behavior is not specific to any particular nodes and sometimes a node could use CUDA and sometime it could not. The failed process gives an error message "what():  No compatible CUDA device is available".

I'm wondering what's the mechanism for OpenMM CUDA platform to find the device id to use? 

Though I could figure out some way to specify the device id for each process, this is not easy because each process may get a different device id and it's not straight forward to find a direct mapping between MPI process id and the device id. 

I really appreciate it if anyone could help.

**Comment by jchodera** [comment]
This is a tricky problem to solve in general. OpenMM leaves it up to you to select which device id to use, though it selects the fastest *platform* by default if multiple platforms are available. Usually, this is just gpu 0.

For [YANK](http://getyank.org), our solution with MPI and batch queue systems is to make use of a script that builds an MPICH runfile to set the `CUDA_VISIBLE_DEVICES` mask separately for each MPI process in order to make sure each MPI process sees only one unique GPU. You can use the same script if you are using a compatible batch queue system:
https://github.com/choderalab/clusterutils

It's even conda-installable: https://anaconda.org/omnia/clusterutils

**Comment by ymwangg** [comment]
Thank you for providing this solution. I tried build_mpirun_configfile.py and I found the following issues.

1. It seems that my cluster could cause a bug in build_mpirun_configfile.py
If I dump the hosts_cvd in the class `class SLURMHydraConfigCreator(HydraConfigFileCreator):`
```python
hosts_cvd = sp.check_output("srun python -c 'import os; print(os.environ.get(\"SLURMD_NODENAME\") + "
                                    "\" \" + "
                                    "os.environ.get(\"CUDA_VISIBLE_DEVICES\"))'", shell=True)
```
```python
hosts_cvd=[u'export SLURM_LOCAL_SCRATCH=/scratch/ymwang/1461378', u'export SLURM_REMOTE_SCRATCH=/export/lustre/ymwang/1461378', u'export PMI_TIME=4000', u'export BASH_ENV=/etc/profile.d/module.sh', u'export OMP_NUM_THREADS=1', u'export OPENMM_CPU_THREADS=1', u'gollum011 0,1', u'gollum012 0,1', u'gollum013 0,1', u'gollum011 0,1', u'gollum015 0,1', u'gollum014 0,1', u'gollum012 0,1', u'gollum013 0,1', u'gollum015 0,1', u'gollum014 0,1']
```
It also include other irrelevant environment variables, gollumXXX is the hostname. I suspect this is caused by some environment variable configuration script after each `srun` call.

I could solve this issue by using some regex match, so it doesn't really matter.

2. Another issue is that when I'm running MPI jobs using `mpiexec.hydra -f hostfile -configfile configfile`, the OpenMM only works when the deviceIndex=0.

The following are the error messages for all MPI threads with deviceIndex=1.
```
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Illegal value for DeviceIndex: 1
```

I tried the following CUDA code, compile it to `a.out` and run `build_mpirun_configfile.py --nocheckmpich ./a.out; mpiexec.hydra -f hostfile -configfile configfile` in the SLURM job script.
```c++
#include <stdio.h> 

int main() {
    int nDevices;

    cudaGetDeviceCount(&nDevices);
    for (int i = 0; i < nDevices; i++) {
        cudaDeviceProp prop;
        cudaGetDeviceProperties(&prop, i); 
        printf("Device Number: %d\n", i); 
        printf("  Device name: %s\n", prop.name);
        printf("  Memory Clock Rate (KHz): %d\n",
                prop.memoryClockRate);
        printf("  Memory Bus Width (bits): %d\n",
                prop.memoryBusWidth);
        printf("  Peak Memory Bandwidth (GB/s): %f\n\n",
                2.0*prop.memoryClockRate*(prop.memoryBusWidth/8)/1.0e6);
    }   
}
```
Each process returns the same output
```
  Device Number: 0
  Device name: GeForce GTX 980
  Memory Clock Rate (KHz): 3505000
  Memory Bus Width (bits): 256
  Peak Memory Bandwidth (GB/s): 224.320000
```

I looked at the source code of OpenMM, I suspect this is caused by the following code in `openmm/platforms/cuda/CudaContext.cpp`

```
        int numDevices;
        CHECK_RESULT(cuDeviceGetCount(&numDevices));
        if (deviceIndex < -1 || deviceIndex >= numDevices)
            throw OpenMMException("Illegal value for DeviceIndex: "+intToString(deviceIndex));
```

Since each MPI process all get either `CUDA_VISIBLE_DEVICES=0` or `CUDA_VISIBLE_DEVICES=1`, then, `numDevices` will always be 0 and therefore for the processes with `CUDA_VISIBLE_DEVICES=1` will have `deviceIndex < numDevices`. 

I also tried to run jobs with normal `mpiexec` on 5 nodes, 2 GPUs on each node, and I use `deviceIndex=pid%2` to assigne `deviceIndex` to each OpenMM process. In this case, each process have exactly the same environment variable `CUDA_VISIBLE_DEVICES=0,1` and everything works.

Do you think I could solve this issue by removing this exception check `deviceIndex >= numDevices`?
I really appreciated if you could help me solve the second issue.

**Comment by jchodera** [comment]
@lnaden can hopefully address the slurm issue with the MPI configfile build script, but it's important to remember that when CUDA_VISIBLE_DEVICES is set to a single integer, OpenMM will think there is only one device available, id 0, and it should use that default GPU. So the goal of the script is just to ensure that each MPI process is using a different physical GPU.

There are other potential approaches that can work. I think Amber instead has each process wait for a random delay, then try to access GPU id 0. If this fails, it waits for another random delay and tries the next device id 1, and so on. If you are using process exclusive mode for the GPUs, this may work well for you.

**Comment by ymwangg** [comment]
I just figured out a new way to solve this issue. First, use `build_mpirun_configfile.py` to let each MPI process get the correct `CUDA_VISIBLE_DEVICES` and then trick OpenMM by resetting `CUDA_VISIBLE_DEVICES` using the following code.
```
    const char* deviceId = std::getenv("CUDA_VISIBLE_DEVICES");
    char newEnv[128] = "CUDA_VISIBLE_DEVICES=0,1,2,3";
    putenv(newEnv);
    platform->setPropertyDefaultValue("DeviceIndex",deviceId);
```
Though not elegantly enough, but it works.

Thank you so much for your help!

**Comment by Lnaden** [comment]
Its really hard for me to say exactly what is happening without knowing how your SLURM scheduler assigns GPUs. The `build_mpirun_configfile` makes some assumptions about how the scheduler is set up, but every cluster could be different. For instance, SLURM does not have a built-in way to access GPUs specifically, they get folded into how the General Resource `-gres` flag is configured. What the script is trying to do is the following:

1. Figure out which nodes are available to this job
2. Figure out what those node host names are as far as MPI/SLURM will see them
3. Figure out what the CUDA_VISIBLE_DEVICES variable is on each node as the job sees them.
4. Assigns a single MPI process per GPU (assumes there are equal number of CPU processors as GPUs)

That CUDA_VISIBLE_DEVICES variable controls which GPUs you have access to by device index on that node. I'll come back to that in a second.

The extra entries in the start of the `hosts_cvd` variable you reference earlier appears to be commands which are executed and captured by the `subprocess` model from attempting to access the remote node. The `build_mpirun_configfile` script expects that `srun` command it executes to return the list of entries each being `host_name, CUDA_VISIBLE_DEVICES` which can be a single digit, empty, or a comma separated list of ints. The extra stuff at the start is probably confusing the script and its not assigning the correct indices per node that it expects. What does your `hostfile` and `configfile` look like for example (although this is probably not the right repo to debug this since Clusterutils is something managed by our group and not the OpenMM itself).

What I suppose is happening is that the MPI hostfile/configfile gets confused and tries to access a device you dont have access to because CUDA_VISIBLE_DEVICES does not make sense on the node its attempting to execute that job on.

Now a warning: You really should not be adjusting CUDA_VISIBLE_DEVICES on a cluster you don't manage, it will probably interfere with other user's jobs trying to access the GPUs and cause problems. But thats a conversation to have with your cluster's admins since I don't know what the policies are

**Comment by ymwangg** [comment]
Your `build_mpirun_configfile` script could successfully capture the correct device id after I add some filters on the environment variables. 

Though I set `CUDA_VISIBLE_DEVICES=0,1,2,4` after the program got the `CUDA_VISIBLE_DEVICES` set by MPI, this only serves to let OpenMM not complain, it still used the SLURM allocated device id provided by MPI configfile. 

The `build_mpirun_configfile` program helped me a lot.

Thank you!

**Comment by bb30994** [comment]
Another source that might help is FAHBench.  It enumerates both CUDA devices and OpenCL devices.

**Comment by MauriceKarrenbrock** [comment]
Hello,
to give my 2 cents, on the HPC cluster I am working on right now you can solve this problem much easier by adding
```#SBATCH --gpu-bind=verbose,single:1```
to the sbatch script, without the need to use ```clusterutils```

ps because of how the cluster is set up I have to use a version of mpi4py that links to the system MPI library (by installing it with pip and not conda), I have no idea if this trick might work with the conda installed mpi4py too
