### ISSUE TITLE
Particle coord is nan after 2-25ns membrane protein simulation, 4fs/step HMR

### ISSUE THREAD

**Issue by ljmartin** [openmm/openmm#2026]
My ion channel system (150k atoms) is consistently hitting Particle coordinate is NaNs with CHARMM and GROMACS as input, but determining why is a slow process. Occurs with all combinations of HBonds, AllBonds, and rigidWater

Using 4fs timesteps, with hydrogenMass = 4*amu, lasts 2-25 nanoseconds before giving: 
```
  File "gro_CUDA3.py", line 41, in <module>
    simulation.step(25000000)
  File "/home/lewis/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/lewis/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 197, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/lewis/miniconda3/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 4436, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Particle coordinate is nan
```
The RMSD of the protein seems stable, and other than that there's just water/ions/popc. The difference in time to fail makes me think its just stochastic. It occurs within one or two steps, where energy and temperature blow up:

```
...
233403,-1450778.8571479702,298.390728158625
233404,-1451377.6661688657,298.9751162742576
233405,-1446386.6915784357,320.94868063890533
233406,3845882930204.495,5235554927.377074
233407,1102560154.8806431,19462846020.64992
```

Anyone diagnosed this before? Currently experimenting with hydrogenMass=3*amu as recommended in the amber paper on HMR.

**Comment by peastman** [comment]
That sounds like it's hitting a rare event where an unusually large force causes an atom to move too far, and it happens to come out right on top of another atom.  I notice there's a sudden jump in temperature on the step before the energy blows up.  That likely means a few atoms have suddenly acquired a very large velocity.

I don't know of any universal laws for determining what will be stable.  Actually, most simulations are fundamentally not stable, since most water models don't put a repulsive term on the water hydrogens.  So it's just a matter of time before a hydrogen gets too close to a negative charge (the time is exponential in the barrier height, but still that's just a matter of time), and then the simulation is guaranteed to blow up.

Anyway, experiment with settings to see what's the largest time step that's stable for your system.  You should have `rigidWater=True` and `constraints=AllBonds`.  Then try different hydrogen masses and time steps.  Monitor the temperature to make sure it's stable.  The mean temperature over time should be very close to whatever value you've set for the thermostat.  If it's higher by more than a degree or so, and especially if you see occasional spikes in temperature, that's a sign you're pushing the limits of stability and you should reduce the step size.

On the other hand, if everything really seems totally stable, and then after a few ns it suddenly blows up in the space of a couple of time steps, that suggests something else might be going on and we should investigate further.

**Comment by ljmartin** [comment]
Cheers!
lll test it out and report back. I can say now though that the temperature seems within spec:
![screenshot from 2018-03-22 16-10-02](https://user-images.githubusercontent.com/8262765/37752327-b3f39c5e-2deb-11e8-91be-a11cf8e04c54.png)
(points are 4 picoseconds apart ~ 16 nanoseconds before it exploded). Although - it looks to be centred on 300.5 Kelvin rather than the 300 that was set. Not sure if that is significant. 
I know that membrane simulations can handle HMR - for example the Dror lab have used it (with amber) for GPCRs for a while. Ill report back once I know the max timestep that is stable.

**Comment by jchodera** [comment]
There are some `nan`-rejection schemes where you can essentially discard regions of the phase space that lead to non-integrable solutions by backtracking and integrating---the stochastic velocity perturbations lead to a different trajectory. I wonder if adding something like that into `Simulation` would be useful to users.

**Comment by peastman** [comment]
Your temperature looks fine.  You expect the mean temperature to be slightly above what you set, since any source of error (e.g. finite step size) will push it up, but half a degree shouldn't be a problem.  And the distribution around it is both narrow and symmetric, with no sign of spikes.

4 fs with HMR is a pretty standard simulation protocol.  I believe some of the users on Folding@Home have generated huge datasets using that, hundreds of microseconds or even milliseconds of total sampling.  So I'm pretty sure there's nothing fundamentally preventing that.

Are you sure this problem is actually related to that protocol?  Have you tried running with a 2 fs time step, `constraints=HBonds`, and no HMR?  I just want to make sure we've ruled out other possibilities and the problem isn't coming from some totally different source.

**Comment by ljmartin** [comment]
You're right - I should not assume its the timestep. Last night I ran a 1fs / HBonds simulation with no HMR, which still crashed after 30ns. Going to do a few things: try with 1fs / no constraints, run memory tests on my cards (using http://folding.stanford.edu/2009/04/28/nvidia-gpu-memory-checker/ , could memory be an issue? Theyre brand new), and try to run on a GPU available on an HPC service I use. Will report back

**Comment by peastman** [comment]
What kind of GPU are you using?  Teslas are usually pretty robust, but with the consumer grade ones a small fraction of them are just flaky.  I think they don't test them as much.  Running a memory test is a good way to check for that.

Another thing to check is that it isn't overheating.  That can happen if it's in a box that doesn't have enough cooling, or if the room gets too warm.  You can use `nvidia-smi` to monitor the GPU temperature.

**Comment by ljmartin** [comment]
Using Titan XPs. So no ECC memory. Temperature is fine - I plot it during the runs and it stays below ~84 degrees (94 is where it would shut off). Fans are at max 60%. Ive run NAMD and GROMACS for about a day without crashing, but maybe they handle errors differently

**Comment by ljmartin** [comment]
Still getting this behaviour using 1fs timestep and no constraints (except rigidWater). Tempted to think its a software fault now (not openmm) - Occam would suggest its unlikely _both_ the new cards are faulty. 

Having said that, running the memtestg80 (https://github.com/ihaque/memtestG80 ) on either card does show errors, eg
`Test iteration 50 (GPU 0, 128 MiB): 45528 errors so far`
Seems like a lot. Im not an expert here so Ive contacted the dealership. 

Does the conda version have an equivalent of the `test` program that comes with the source code of openmm?

**Comment by peastman** [comment]
You can do `python -m simtk.testInstallation`.  That's just a very basic test to catch the most obvious problems.  The full test suite is only included with the source, not the conda package.  Even the full test suite is really designed to find errors in the code, not the hardware.

Another interesting test would be to try running with OpenCL instead of CUDA and see if that has the same problem.

The memory errors are a bit worrying.  I'm not sure exactly what it's looking for, though.  Also, I notice that program was last updated four years ago, so it's possible it makes assumptions that aren't valid on modern GPUs.  I should try it out and see if it reports errors on my GPUs.

**Comment by ljmartin** [comment]
OK so on a clean install with Ubuntu, which is officially supported by nvidia, and by not using the precompiled memtestg80, I don't see any errors. But the NaNs persisted. 

I tried running the mtor system available in the SI of the openmm7 paper, and it can run for long times with no NaNs. The difference appears to be the friction coefficient - for some reason, the mtor LangevInintegrator has a friction coefficient of 91/picosecond. Using this on my protein system 'solves' the issue.
 
Im studying peptide binding, so Im trying to figure out if such an overdamped regime is appropriate, or if it will show artificially strong binding due to the high viscosity of the water.

**Comment by jchodera** [comment]
Does running with a high collision rate for a while to clean things up a bit before switching to a low collision rate help?

**Comment by jchodera** [comment]
Did you say you were using `hydrogenMass = 4*amu`? Won't that cause problems with methyl groups, where there are 3 hydrogens on a carbon (mass ~12 amu) since that subtracts 4x3 = 12 amu from the carbon? Have you tried 3 amu?

**Comment by ljmartin** [comment]
I tried 3*hydrogen mass but that still had the same issue. Since it takes several hours or a day to reproduce the crashing, it takes a long time to find out whats working. But I was still seeing this behaviour on a pre-equilibrated system (equilibrated in NAMD) so i dont think the system needs cleaning up. So far I've been running with friction coefficient = 10/picosecond with no crash, I'll see how low it can go.

**Comment by peastman** [comment]
91/ps is the friction coefficient of water.  That's a reasonable value to use when you have implicit solvent and you want realistic dynamics.  For explicit solvent that's way too high a value, since you already have friction from water and the thermostat friction is just the (much weaker) coupling to an external heat bath.

> Won't that cause problems with methyl groups, where there are 3 hydrogens on a carbon (mass ~12 amu) since that subtracts 4x3 = 12 amu from the carbon?

It only subtracts 3 amu for each hydrogen, not four, since you're increasing their masses from 1 to 4.

**Comment by ljmartin** [comment]
Is there a way to report which particle has become NaN? Im running out of ideas

**Comment by peastman** [comment]
You can call `getState()` and check the positions yourself, but that probably won't help.  If any particle becomes NaN, every other particle will be too within one or two time steps.  And it only runs the check for NaN coordinates every 250 steps, so by that point the cause is probably long past.

Did you try using OpenCL instead of CUDA?  I don't know that will help, but it's at least an interesting experiment.

Ok, there *is* a way we can track down more precisely where and why it's blowing up.  It's not hard, but it's going to be really slow to run, which is why I've put off suggesting it.  Call `getState()` after every time step.  Keep a running buffer of the most recent 30 or so states in memory.  At every time step, check if the potential energy has blown up, and also be prepared to catch exceptions.  When that happens, write all the states out to disk.  The code should look something like this.  (I'm just writing this in the web browser, so it might have mistakes, but it should give the idea.)

```python
states = []
for i in range(steps):
  try:
    state = context.getState(getPositions=True, getVelocities=True, getEnergy=True, getForces=True, getParameters=True)
    states.append(state)
    if len(states) > 30:
      del states[0]
    if state.getPotentialEnergy() > 0*kilojoules_per_mole:
      break
    integrator.step(1)
  except:
    break
for i, state in enumerate(states):
  with open('state%d.xml' % i, 'w') as out:
    out.write(XmlSerializer.serialize(state))
```

**Comment by ljmartin** [comment]
Can confirm that same error occurs with OpenCL. Will report back soon with this reporter function

**Comment by peastman** [comment]
Just to be safe, the line

```python
if state.getPotentialEnergy() > 0*kilojoules_per_mole:
```

should probably be changed to

```python
if state.getPotentialEnergy() > 0*kilojoules_per_mole or not math.isfinite(state.getPotentialEnergy()):
```

That way it will also stop if the energy jumps directly to NaN.

**Comment by ljmartin** [comment]
Thanks for the code. It turns out you were right to test OpenCl - although I said it didn't work that was using 5fs timesteps which is ambitious for any system. I've since been running long uninterrupted simulations with OpenCL and 4fs/step. I can use CUDA if I run 1ns at a time, and restart after an exception. But I don't really trust that even though protein RMSD seems unaffected since its a bit of coarse measure.
