### ISSUE TITLE
Undefined symbols -- OpenMM 7.2.1 installation

### ISSUE THREAD

**Issue by mjg0** [openmm/openmm#2075]
When I try to install OpenMM 7.2.1, I run into what feels like a linking issue; I'm a novice at software installation, though, so it could be anything.

OS is RHEL 6
Software:
llvm 4.0.1
python 2.7.11
cuda 8.0
doxygen 1.8.14
swig 3.0.6

How I install:
```# Make stuff easier to read
export SRC=/openmm/source/dir # it's already extracted and such
export PREFIX=/where/i/put/it
export LLVM4=/where/clang/stuff/is
export CUDA8=/cuda/8/root/dir

# CMake with too many arguments
CC=`which clang` CXX=`which clang++` \
cmake -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=$PREFIX \
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
-DCMAKE_INSTALL_RPATH=$PREFIX/lib:$PREFIX/lib/plugins:$LLVM4/lib:/usr/lib64:/$CUDA8/lib64 \
-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
-DCMAKE_EXE_LINKER_FLAGS="-Wl,--enable-new-dtags,--no-undefined" \
-DCMAKE_SHARED_LINKER_FLAGS="-Wl,--enable-new-dtags,--no-undefined" \
-DCMAKE_POSITION_INDEPENDENT_CODE=TRUE \
$SRC

# Make stuff
make -j 24 &> make.log
make install -j 24 &> install.log

# Test
export OPENMM_LIB_PATH=$PREFIX/lib
export OPENMM_INCLUDE_PATH=$PREFIX/include
export OPENMM_CUDA_COMPILER=$CUDA8/bin/nvcc
make test -j 24 &> test.log & # Pretty sure -j 24 is futile, this takes FOREVER

# While tests are running, do python stuff...
cd python
python setup.py build &> python_build.log
export PYTHON_PREFIX=/where/to/put/the/python/crap
python setup.py install --prefix=$PYTHON_PREFIX &> python_install.log

# Happily test installation since all seems to be going well
export PYTHONPATH=$PYTHON_PREFIX/lib/python2.7/site-packages
python simtk/testInstallation.py # PROBLEM HERE
```

`testInstallation.py` gives the following:
```Failed to import OpenMM packages; OpenMM will not work.
Make sure OpenMM is installed and the library path is set correctly.

Error message: [PYTHON_PREFIX]/lib/python2.7/site-packages/simtk/openmm/_openmm.so: undefined symbol: _ZN6OpenMM14RPMDIntegrator12setPositionsEiRKSt6vectorINS_4Vec3ESaIS2_EE
```

Suspicious...what do ldd and readelf have to say?
ldd (I replaced stuff with PREFIX to make it less annoying to read):
```	linux-vdso.so.1 =>  (0x00007ffc57f76000)
	libOpenMM.so => [PREFIX]/lib/libOpenMM.so (0x00007fc129de9000)
	libOpenMMAmoeba.so => [PREFIX]/lib/libOpenMMAmoeba.so (0x00007fc129b8f000)
	libOpenMMRPMD.so => [PREFIX]/lib/libOpenMMRPMD.so (0x00007fc129984000)
	libOpenMMDrude.so => [PREFIX]/lib/libOpenMMDrude.so (0x00007fc129773000)
	libpython2.7.so.1.0 => /apps/python/2.7.11/gcc-5.3.0/lib/libpython2.7.so.1.0 (0x00007fc12936e000)
	libstdc++.so.6 => /apps/gcc/5.3.0/lib64/libstdc++.so.6 (0x00007fc128ff3000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc128d6f000)
	libgcc_s.so.1 => /apps/gcc/5.3.0/lib64/libgcc_s.so.1 (0x00007fc128b59000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc12893c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc1285a8000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc1283a0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc12819c000)
	libc++.so.1 => LLVM4/lib/libc++.so.1 (0x00007fc127eaf000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fc127cac000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc12a74c000)
```
readelf -d:
```dynamic section at offset 0x268590 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libOpenMM.so]
 0x0000000000000001 (NEEDED)             Shared library: [libOpenMMAmoeba.so]
 0x0000000000000001 (NEEDED)             Shared library: [libOpenMMRPMD.so]
 0x0000000000000001 (NEEDED)             Shared library: [libOpenMMDrude.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000f (RPATH)              Library rpath: [/apps/python/2.7.11/gcc-5.3.0/lib:/apps/intel_parallel_studio_xe/2015/mkl/lib/intel64:/apps/gcc/5.3.0/lib64:[PREFIX]/lib]
 0x000000000000000c (INIT)               0x5dcd0
 0x000000000000000d (FINI)               0x16481c
 0x0000000000000019 (INIT_ARRAY)         0x467000
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x467010
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x158
 0x0000000000000005 (STRTAB)             0xe000
 0x0000000000000006 (SYMTAB)             0x2f00
 0x000000000000000a (STRSZ)              148789 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x469200
 0x0000000000000002 (PLTRELSZ)           25272 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x57a18
 0x0000000000000007 (RELA)               0x334d8
 0x0000000000000008 (RELASZ)             148800 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x333f8
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x32536
 0x000000006ffffff9 (RELACOUNT)          5234
 0x0000000000000000 (NULL)               0x0
```

It feels like everything should be all good, but nm shows a ton of undefined symbols: `$ nm -Du [PYTHON_PREFIX]/lib/python2.7/site-packages/simtk/openmm/_openmm.so | wc -l` gives 1081 which feels high. Some of the symbols are obviously libc things like memcpy, but that's a minority of the undefined symbols.

I tried to compile CHARMM 42 with OpenMM support and had issues with quite a few undefined symbols, for example:
```[CHARMM_DIR]/lib/gnu_M/openmm_plugins/libOpenMMCharmm.so: undefined reference to 'OpenMM::Platform::getPlatformByName(std::string const&)'
[CUDA8]/lib/gnu_M/openmm_plugins/libOpenMMCharmm.so: undefined reference to 'OpenMM::KernelImpl::KernelImpl(std::string, OpenMM::Platform const&)'
[CHARMM_DIR]/lib/gnu_M/openmm_plugins/libOpenMMGBSW.so: undefined reference to 'OpenMM::throwException(char const*, int, std::string const&)'
...
```

Again, I'm a beginner and I don't know where to go from here. I probably missed/put in too many CMake options or something.

**Comment by michaelgreenburg** [comment]
At the time of this comment, 218 of the 413 tests have passed, and based on previous attempts I suspect they will at least almost all pass.

**Comment by peastman** [comment]
```
# CMake with too many arguments
```

That's for sure! 😀  The only one of those arguments you really need to specify is `CMAKE_INSTALL_PREFIX`.  All the others should be set to appropriate values automatically.

The easy way to install the Python modules is

```
make PythonInstall
```

Assuming you set `PYTHON_EXECUTABLE` correctly in CMake, that will take care of everything for you.  Once you've done that, the correct way to run the test is

```
python -m simtk.testInstallation
```

And I'm pretty sure you should not be setting `PYTHONPATH`.  It's not needed if you've installed correctly, and can easily break things.

**Comment by michaelgreenburg** [comment]
Sorry, I was unclear--a user would load an environment module to get access to OpenMM, e.g.:
```
$ python
>>> import simtk.openmm.app
[ImportError message]
>>> quit()
$ module load openmm
$ python
>>> import simtk.openmm.app
>>> # Success!
```

**Comment by peastman** [comment]
>     CC=`which clang` CXX=`which clang++`

Why are you even specifying those?  One of CMake's jobs is to select compilers automatically.  Have you tried just compiling exactly as described in the manual (http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code)?

> a user would load an environment module to get access to OpenMM, e.g.:

That's certainly going to complicate your life.  Unfortunately, I don't know much about how environment modules are implemented.  What's the reason for doing that?  Python modules serve roughly the same function already.

**Comment by michaelgreenburg** [comment]
I had originally tried to compile it as described in the manual; the only things I changed were the CMAKE_INSTALL_PREFIX, and using setup.py directly to specify an installation directory for python. I had gradually added in options to try to help libraries find their dependencies.
When I don't specify compilers, it uses the native compiler (GCC 4.4.7), which has some trouble that I think is due to the old age of GCC 4.4. When I `make` (not in parallel this time), it stops with the following:
```
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp: In static member function ‘static void OpenMM::AndersenThermostatImpl::tagParticlesInGroup(int, int, std::vector<int, std::allocator<int> >&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&)’:
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp:97: error: expected initializer before ‘:’ token
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected primary-expression before ‘}’ token
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected ‘;’ before ‘}’ token
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected primary-expression before ‘}’ token
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected ‘)’ before ‘}’ token
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected primary-expression before ‘}’ token
/apps/src/openmm/src/openmm-7.2.1/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected ‘;’ before ‘}’ token
```
Using GCC 5.4.0:
```
module load gcc/5.4
CC=`which gcc` CXX=`which g++` cmake \
-DCMAKE_INSTALL_PREFIX=$PREFIX \
$SRC
```
...yields similar results to clang 4--libOpenMM.so isn't found by the other libOpenMM*.so.
Putting python wrappers for software into environment modules helps to compartmentalize code, and have worked well thus far. Python support is a secondary goal, though--if it doesn't want to work it isn't a big deal, but it is an easy way to ensure that the cogs all fit together well. The primary goal is to use OpenMM for CHARMM, but it seems that if the python issue is fixed, it's very likely that the CHARMM one will be as well since they both involve undefined references.
Once I can figure out how to compile such that libOpenMMDrude.so, libOpenMMRMPD.so etc. can find libc++.so.1 and libOpenMM.so, I'll see if letting the python packages live where they want solves the issue--keeping them separate is desirable but not necessary.

I think that my main issue is compiling so that e.g. libOpenMMRMPD.so can find the libraries it needs--if you have any ideas on that I would love to hear them! The issue arises right after I `make install`--does this imply that I need to tweak CMake parameters?

**Comment by peastman** [comment]
Just as a guess, I suspect there is an inconsistency between how the OpenMM libraries were compiled and how the Python wrapper was compiled.  Python 2.7 is a really old version, and there have been some big changes since then that might cause things to get compiled in an incompatible way.  Those include the switch from libstdc++ to libc++, the introduction of C++11, and the adoption of the gcc dual ABI.  Let's focus on the error message you're getting.

```
Error message: [PYTHON_PREFIX]/lib/python2.7/site-packages/simtk/openmm/_openmm.so: undefined symbol: _ZN6OpenMM14RPMDIntegrator12setPositionsEiRKSt6vectorINS_4Vec3ESaIS2_EE
```

The Python wrapper is looking for `_ZN6OpenMM14RPMDIntegrator12setPositionsEiRKSt6vectorINS_4Vec3ESaIS2_EE`, but possibly the actual function in the library used a different name mangling due to one of those changes.  Try this command:

```
nm -D [PATH TO LIBRARIES]/libOpenMMRPMD.so | grep setPositions
```

What's the output?

**Comment by michaelgreenburg** [comment]
The symbol is there, but undefined:
```
$ nm -D [PATH TO LIBRARIES]/libOpenMMRPMD.so | grep setPositions
                 U _ZN6OpenMM11ContextImpl12setPositionsERKNSt3__16vectorINS_4Vec3ENS1_9allocatorIS3_EEEE
0000000000004fb0 T _ZN6OpenMM14RPMDIntegrator12setPositionsEiRKNSt3__16vectorINS_4Vec3ENS1_9allocatorIS3_EEEE
                 U _ZN6OpenMM5State12StateBuilder12setPositionsERKNSt3__16vectorINS_4Vec3ENS2_9allocatorIS4_EEEE
                 U _ZN6OpenMM7Context12setPositionsERKNSt3__16vectorINS_4Vec3ENS1_9allocatorIS3_EEEE
```
80 of the 156 symbols are undefined; 44 of these undefined symbols have something to do with OpenMM:
```
$ nm -D [PATH TO LIBRARIES]/libOpenMMRPMD.so | wc -l
156
$ nm -Du [PATH TO LIBRARIES]/libOpenMMRPMD.so | wc -l
80
$ nm -DCu [PATH TO LIBRARIES]/libOpenMMRPMD.so | grep OpenMM | wc -l
44
```

**Comment by peastman** [comment]
The symbols are actually different.  Compare:

```
_ZN6OpenMM14RPMDIntegrator12setPositionsEiRKSt6vectorINS_4Vec3ESaIS2_EE
_ZN6OpenMM14RPMDIntegrator12setPositionsEiRKNSt3__16vectorINS_4Vec3ENS1_9allocatorIS3_EEEE
```

That's why it isn't being found.  Running those through a name demangler gives for the two versions respectively:

```
OpenMM::RPMDIntegrator::setPositions(int, std::vector<OpenMM::Vec3, std::allocator<OpenMM::Vec3> > const&)
OpenMM::RPMDIntegrator::setPositions(int, std::__1::vector<OpenMM::Vec3, std::__1::allocator<OpenMM::Vec3> > const&)
```

The difference is the extra `__1` in the namespace in the second one.  According to https://stackoverflow.com/questions/29293394/where-does-the-1-symbol-come-from-when-using-llvms-libc, this means the Python wrappers are getting compiled against libstdc++, while the libraries are getting compiled against libc++.  So when you run setup.py, you need to tell it to use libc++.  I *think* that can be done by doing something like this:

```
export CFLAGS=-stdlib=libc++
```
