### ISSUE TITLE
TabulatedFunction should provide  Python API for evaluating the function

### ISSUE THREAD

**Issue by forcefield** [openmm/openmm#2240]
It appears that the TabulatedFunctions, such as the Discrete2DFunction, does not provide a python API to evaluate the function for given input.  e.g.

`tbf = openmm.Discrete2DFunction( 2, 2, [0.1, 0.2, 0.3, 0.4])`
`tbf(0,1)`
should return the corresponding function value.

**Comment by peastman** [comment]
A TabulatedFunction object contains the definition of a function, but no code for evaluating it.  It's up to each platform to implement function evaluation in an appropriate way, which may be done differently for each Force.  It also often involves a lot of precalculation to convert the function definition into a form more suitable for evaluation.

In principle we could create a generic implementation that would be built directly into the TabulatedFunction.  But it might be very slow and/or require a lot of memory, since it would have to redo all the spline fitting and other precomputation.
