### ISSUE TITLE
Odd failure of CustomExternalForce

### ISSUE THREAD

**Issue by egallicc** [openmm/openmm#2244]
I am encountering some sort of memory corruption with the python interface of CustomExternalForce. It is reproducible in various circumstances and with various builds. 

For example, the script below works with up to 10 restrained particles. However with 11 particles the minimization locks up. The expression of the force does not seem to matter. The number of per-particle parameters does.

I wonder if it is my specific build environment? Or maybe I am missing something silly. This is with python 2.7.

```
from simtk import openmm as mm
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

pdb = PDBFile('ala_ala_ala.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)

c_force = mm.CustomExternalForce("hk*step(dist-tol)*(dist-tol)^2; dist = sqrt((x-x0)^2+(y-y0)^2+(z-z0)^2)")
c_force.addPerParticleParameter("x0")
c_force.addPerParticleParameter("y0")
c_force.addPerParticleParameter("z0")
c_force.addPerParticleParameter("hk")
c_force.addPerParticleParameter("tol")
system.addForce(c_force)


p = 0
for pos in pdb.positions:
    xp = pos[0].value_in_unit(nanometer)
    yp = pos[1].value_in_unit(nanometer)
    zp = pos[2].value_in_unit(nanometer)
    if p < 11:
        c_force.addParticle(p,[xp, yp, zp, 0.0, 0.15])
        p += 1
     
platform = Platform.getPlatformByName('Reference')
properties = {}
    
simulation = Simulation(pdb.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)

state = simulation.context.getState(getEnergy = True)
print(state.getPotentialEnergy())

simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 10, step=True, potentialEnergy=True, temperature=True))
simulation.step(1000)

```

**Comment by jchodera** [comment]
I can reproduce this behavior, and it's quite puzzling. 
Switching to the `CPU` platform, even if the `CustomExternalPotential` is applied to just the first atom, the forces are `nan`, even though the potential should be zero because there is zero displacement from the center and the force constant is set to zero!

**Comment by jchodera** [comment]
Oddly enough, the forces are fine if we just replace `sqrt((x-x0)^2+(y-y0)^2+(z-z0)^2)` with `periodicdistance(x,y,z,x0,y0,z0)`, despite the fact that this system uses `NoCutoff`.

Any ideas here @peastman?

**Comment by egallicc** [comment]
Thanks. I checked the body of the force calculation of the resulting OpenCL kernel. I did not see anything obviously wrong there.

**Comment by egallicc** [comment]
The problem goes away also if a small epsilon is added to the reference positions. I think it's due to the (x-x0)/sqrt(x-x0) removable singularity of the derivative of the distance function at zero distance.

Good to know. Unless there is an interest in trying to fix this in general, I will close the issue ... Thanks again.

**Comment by peastman** [comment]
The problem comes from this part of the expression:

```
step(dist-tol)*(dist-tol)^2
```

The intent of that is to set the energy to 0 whenever `dist-tol` is < 0.  The problem is that 0*nan = nan.  Because of the way IEEE floating point works, multiplying by 0 isn't enough to mask a singularity.  Instead you can use the `select()` function, which was created to deal with situations like this.  Change the above to

```
select(step(dist-tol), (dist-tol)^2, 0)
```

With that change, your code runs successfully.

**Comment by jchodera** [comment]
> The problem comes from this part of the expression:
> `step(dist-tol)*(dist-tol)^2`

@peastman: `(dist-tol)^2` is never `nan` or infinite---in fact, that quantity is `(-0.15)^2`, which is very much finite.

The issue is that the derivative involves a term
```
hk*step(dist-tol)*2*(dist-tol)*(1/2)/dist*2*(x-x0)
```
where `dist` appears in the denominator. 

Is there a way to make something like this more numerically stable? Your custom function `periodicdistance(x,y,z,x0,y0,z0)` is numerically stable. Could we define a corresponding function `distance(x,y,z,x0,y0,z0)` that has the same stability properties, where it recognizes that the ratio
```
(x-x0)/dist
```
should be zero if dist=0?

**Comment by jchodera** [comment]
I'm not sure there's a general solution to making arbitrary algebraic expressions numerically robust, but the strategy of packaging very common operations (such as distance computations) into numerically robust single function calls is the best idea there is at the moment. It certainly makes it *easier* for someone to "do the right thing" by using `distance(x,y,z,x0,y0,z0)` instead of `sqrt((x-x0)^2+(y-y0)^2+(z-z0)^2)` than to have to look up a advice like they should convert `step(dist-tol)*(dist-tol)^2` into `select(step(dist-tol), (dist-tol)^2, 0)`.

**Comment by egallicc** [comment]
Thank you @peastman for the select() trick.

IMHO a distance() function would make sense in this case.  A user would expect to be one given that there is already periodicdistance(). (Are they interchangeable for a non-periodic system?) 

I agree that people will continue to run into trouble with math expressions with hidden singularities regardless.

**Comment by peastman** [comment]
> (Does periodicdistance() return the actual distance in the case of a non-periodic system?)

If you use `periodicdistance()` then by definition your system is periodic.  There always is some set of box vectors stored in the context, whether any force looks at them or not.  Also, if you use `periodicdistance()` in your CustomExternalForce, that will cause `System.usesPeriodicBoundaryConditions()` to return true, since there is now a force that uses them.
