### ISSUE TITLE
AMOEBA GK setSurfaceAreaFactor not included by updateParametersInContext

### ISSUE THREAD

**Issue by mjschnie** [openmm/openmm#2259]
Setting a new surface area factor using the method:
AmoebaGeneralizedKirkwoodForce setSurfaceAreaFactor

Followed by calling:
AmoebaGeneralizedKirkwoodForce updateParametersInContext

Does not have any effect. I'm happy to try generating a pull request to address this, but I'm not sure where to start?

**Comment by peastman** [comment]
For the reference platform it's easy.  The factor is stored in a field of the `ReferenceCalcAmoebaGeneralizedKirkwoodForceKernel` object, so you just need to change that:

https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.h#L688

For the CUDA platform it's a bit more complicated, since the value gets compiled into the kernel.  See

https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/platforms/cuda/src/kernels/amoebaGk.cu#L35

and

https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp#L2212

So either you need to recompile the kernel (expensive!), or else modify the kernel so it's passed in as an argument.
