### ISSUE TITLE
Position restraints via zero-mass dummy atoms

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm#2262]
Hi, regarding these threads https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10049&p=0&start=0&view=&sid=cedeacdb61ad5dec69e9c6032051195e, https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10059&p=0&start=0&view=&sid=0db03b773fa7d97e6881b8a10c62938b,  and https://github.com/pandegroup/openmm/issues/988, could you help us by showing an example how to define restraints via dummy atoms? We spent a lot of time trying to use position restraints but in the end were unsuccessful and the simulation blows up with huge forces resulting from actual coordinates mismatched with their restraint positions. periodicdistance() does not seem to work on our dimer. Peter at some point suggested defining a dummy atom with zero mass/charge/epsilon and tether the real atom to the dummy to achieve restraint in NPT ensemble. This sounds straightforward but after trying to do it, we couldn't figure out how to actually define the dummy atoms and the tether in OpenMM. Moreover, we have ~100 CA atoms that we want to restrain. Could you show us an example how to do this? We greatly appreciate your kind help. Many thanks, Istvan

**Comment by jchodera** [comment]
I just read through the [dimer jumps with protein restraints](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10059&p=0&start=0&view=&sid=0db03b773fa7d97e6881b8a10c62938b) post. While I'm not quite sure what's going on there---it would be good to figure out exactly what is happening!---I can explain what we did in [yank](http://github.com/choderalab/yank) when we wanted to restrain some protein atoms to reference positions for a quick alchemical scouting protocol.

Because the `MonteCarloBarostat` would scale the macromolecule positions toward the origin---creating large energies that would lead to rejected barostat moves---we had to first compute the center of geometry of the restrained atoms and apply a translation to the entire system so that the barostat scaling would not induce a translation in the macromolecule we were restraining. We then used a `CustomExternalForce` to restrain the atoms of interest. 

There is a function you can use available in [`openmmtools.forcefactories.restrain_atoms`](https://openmmtools.readthedocs.io/en/0.17.0/api/generated/openmmtools.forcefactories.restrain_atoms.html#openmmtools.forcefactories.restrain_atoms) (source [here](https://github.com/choderalab/openmmtools/blob/master/openmmtools/forcefactories.py#L101-L174)) you can use for this!

**Comment by gitkol** [comment]
Thank you, John. I'll give it a try. I had the same problem with NVT, though. I still hope it is pilot error somehow, but very difficult to debug, because the blow-up happens within basically two time steps, and writing out debugging info at every time step slows down the simulation about 70 fold. I would still like to test the zero-mass dummy atom tethering option as well, but I am no sure how to add the dummy atoms. I don't seem to be able to define an atom type with no element assignment, but if I assign, say carbon or hydrogen, or anything else, I always get a force field error. Modeller's addAtom() requires an element. Maybe the way to add dummy atoms is quite different, I am not fully versed in OpenMM objects.

**Comment by peastman** [comment]
Let me see if I can put together a working example.

**Comment by peastman** [comment]
Here you go.  This did turn out to be a little tricky to get working.  Note the call to `nonbonded.addException()`.  That turned out to be essential.  Otherwise you got a nan from the restrained atom and dummy atom being at exactly the same position.

```python
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *

# Build the system.

ff = ForceField('amber14-all.xml', 'amber14/tip3p.xml')
pdb = PDBFile('5dfr_solv-cube_equil.pdb')
system = ff.createSystem(pdb.topology, nonbondedMethod=PME, constraints=HBonds)
system.addForce(MonteCarloBarostat(1*bar, 300*kelvin))

# Add some restraints.

restraint = HarmonicBondForce()
restraint.setUsesPeriodicBoundaryConditions(True)
system.addForce(restraint)
nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
atomsToRestrain=[0,1000,10000]
dummyIndex = []
positions = pdb.positions
for i in atomsToRestrain:
    j = system.addParticle(0)
    nonbonded.addParticle(0, 1, 0)
    nonbonded.addException(i, j, 0, 1, 0)
    restraint.addBond(i, j, 0*nanometers, 100*kilojoules_per_mole/nanometer**2)
    dummyIndex.append(j)
    positions.append(positions[i])

# Run a simulation.

integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
context = Context(system, integrator)
context.setPositions(positions)
print('Initial energy:', context.getState(getEnergy=True).getPotentialEnergy())
integrator.step(100)
print('Final energy:', context.getState(getEnergy=True).getPotentialEnergy())

# Print out the distances of the restrained atoms from their reference positions.

finalPos = context.getState(getPositions=True).getPositions()
for i,j in zip(atomsToRestrain, dummyIndex):
    print(i, j, norm(finalPos[i]-finalPos[j]))
```

**Comment by gitkol** [comment]
Thank you so very much, Peter. Lots of people will appreciate this code.
Restraints are under rated, they can be extremely useful. Istvan

**Comment by jlmaccal** [comment]
@peastman: Funny timing. I'm running into a similar issue, but with GBForces.

The `GBSAOBCForce` does not have a method to add exclusions. `CustomGBForce` does, but all of the existing amber custom GBForces use `ParticlePairNoExclusions`, which ignores the exclusions.

I would like to add particles to the system that have no effect on the GB force, but I can't seem to figure out how.

**Comment by peastman** [comment]
It looks like some of the GB models already handle this case correctly, but not all of them.  For example HCT has the calculation

```python
self.addComputedValue("I", "step(r+sr2-or1)*0.5*(1/L-1/U+0.25*(r-sr2^2/r)*(1/(U^2)-1/(L^2))+0.5*log(L/U)/r);"
                           "U=r+sr2;"
                           "L=max(or1, D);"
                           "D=abs(r-sr2)",
                      CustomGBForce.ParticlePairNoExclusions)
```

Where it divides by r, that will produce inf when r is exactly 0.  That gets multiplied by `step(r+sr2-or1)`, which should be 0 in that case, leading to nan.  On the other hand, GBn writes the corresponding expression slightly differently:

```python
"Ivdw=select(step(r+sr2-or1), 0.5*(1/L-1/U+0.25*(r-sr2^2/r)*(1/(U^2)-1/(L^2))+0.5*log(L/U)/r), 0);"
```

It uses a `select()` function in place of multiplication, which will avoid the nan.  So it should be fine.  And the other models could be trivially modified in the same way to handle this case.

**Comment by jlmaccal** [comment]
OK, I see how using select can be used to avoid propagating the NaNs.

What exactly is needed to have a particle not contribute the the GB force in any way? Is it sufficient to set the charge and radius to zero? What about the scale factor?

Also, which expressions need to have `step` replaced with `select`?

Can we make these changes to the main release of OpenMM, or is there a downside to using `select` vs `step`? I would rather just use the canonical OpenMM implementations of the GB forces, rather than maintaining our own mirror versions.

Also, none of this addresses OBC, which uses the CUDA implementation, rather than a CutomGBForce. I suppose it would be easy to add a check for zero charge and radius.

**Comment by peastman** [comment]
Changing all the GB models to use `select()` would be very reasonable.  I really should have changed all of them at the same time I did the GBn models.

I checked the code for GBSAOBCForce and it looks like it should be fine.  The division by r is already inside an if block.

I *think* that if you set both charge and radius to 0, that will cause the particle to have no effect.  From looking through the code, that appears to be the case.  But it's complicated code, so you should test that to be sure.

**Comment by sghosh123** [comment]
I am trying to fix a protein molecule in my simulation box, so that it does not roam around.

So I wanted to have some positional restraints on 7/8 atoms. I took help from your previous code :

> # Add some restraints.
> 
> restraint = HarmonicBondForce()
> restraint.setUsesPeriodicBoundaryConditions(True)
> system.addForce(restraint)
> nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
> atomsToRestrain=[0,1000,10000]
> dummyIndex = []
> positions = pdb.positions
> for i in atomsToRestrain:
>     j = system.addParticle(0)
>     nonbonded.addParticle(0, 1, 0)
>     nonbonded.addException(i, j, 0, 1, 0)
>     restraint.addBond(i, j, 0*nanometers, 100*kilojoules_per_mole/nanometer**2)
>     dummyIndex.append(j)
>     positions.append(positions[i])


I was using this piece of code to add dummy atoms for position restraint, but got an error:

>Exception: CustomNonbondedForce must have exactly as many particles as the System it belongs to.

Can you help me out on this? @peastman @jchodera

**Comment by peastman** [comment]
You added a particle to the system.  You also added a corresponding particle to the NonbondedForce, but apparently there's also a CustomNonbondedForce in the system.  You need to add the new particle to it too.

**Comment by sghosh123** [comment]
That is the problem I am surprised about. Apparently, I haven't created any Customnonbonded force object.

So, I don't understand why it is throwing an exception.

Can you please help me understand where the CustomNonbondedForce is coming from?

**Comment by peastman** [comment]
You didn't show the code you used to create the System.  Clearly whatever mechanism you used to create it (a force field? a psf file?) included a CustomNonbondedForce.
