### ISSUE TITLE
Particle coordinate is nan issue

### ISSUE THREAD

**Issue by jy634** [openmm/openmm#2308]
This is a general issue that I ran into regarding the 'Exception: Particle coordinate is nan'. I'm using Amber generated files to create the system for several combination of two set of molecules, but some simulation crashes with above exception while some passes without any error. Is there any specific reason why this error occurs? I would love to understand where this exception is coming from!

**Comment by peastman** [comment]
That means the simulation blew up.  There are many different things that can cause that.  Here are some of the more common ones.

- Using a time step that's too large.
- Starting from a conformation that hasn't been minimized well enough.
- Having conflicting or redundant constraints.
- Initializing the periodic box vectors incorrectly (e.g. using the ones from the prmtop file rather than the ones from the inpcrd file).
