### ISSUE TITLE
Simulated tempering weight update 

### ISSUE THREAD

**Issue by ljmartin** [openmm/openmm#2366]
Hi,
Thought this was more appropriate for the github since its not just about usage.

Thankyou for the simulated tempering script. I looked into the Wang-Landau paper and found that it says the weight update factor `f` is a number `>1` that is then updated by `f' = sqrt(f)`. The simulated tempering script currently uses an update of `f *= 0.5` which in the limit goes to zero rather than 1. I believe the effect of this is that the traversal time becomes infinitely long. Not sure if this is intentional or a typo so I thought I would bring it up. 

weight update factor is updated at line 234 https://github.com/openmm/openmm/blob/0153fa3b3c0ada2752e71732f1ca3213a0067115/wrappers/python/simtk/openmm/app/simulatedtempering.py#L234

Cheers
lewis

**Comment by peastman** [comment]
The difference is that they're converging a density of states, whereas we're converging a free energy which depends on the log of the density of states.  `log(sqrt(x)) = 0.5*log(x)`.  That's why we multiply by 0.5 instead of taking a square root.

(By the way, sorry I haven't replied to your forum post yet.  I saw it and I've been meaning to look into the issue, but I've been busy with other things.  I'll try to do that today!)

**Comment by ljmartin** [comment]
Thankyou that makes sense! No problem about the forum I figured that’s the case. 
Cheers
Lewis
