### ISSUE TITLE
Should default OpenCL precision be `single` or `mixed`?

### ISSUE THREAD

**Issue by maxentile** [openmm/openmm#2398]
Hi!

@c-matthews has noticed that using the default OpenCL precision setting in OpenMM (`single` precision) at small stepsizes (here, 0.2fs) can have dramatic effects. Should the default be `mixed` precision instead?

Here, we run a few different time-discretizations of Langevin dynamics on the [`AlanineDipeptideExplicit`](https://openmmtools.readthedocs.io/en/0.18.1/api/generated/openmmtools.testsystems.AlanineDipeptideExplicit.html) testsystem from openmmtools, which should all be similar at sufficiently small stepsizes. However, in `single` precision, the average potential energy can be off by thousands(!) of kcal/mol.
![opencl_single_precision](https://user-images.githubusercontent.com/5759036/65290830-b8f3d480-db1e-11e9-8e5b-4afbd0c7116d.png)

I suspect this is due to numerical underflow in constraint projection steps, which rely on precise subtraction of very similar vectors. For the time-discretizations where this issue was more pronounced, there are more of these constraint projection steps, and the vectors involved are more similar. I'm not sure if there are other common situations where floating-point precision-related issues like this might become pronounced.

The behavior is completely as expected if `platform.setPropertyDefaultValue('OpenCLPrecision', 'mixed')` is included:
![opencl_mixed_precision](https://user-images.githubusercontent.com/5759036/65290828-b5f8e400-db1e-11e9-85f7-5716f910442a.png)

([script](https://gist.github.com/maxentile/8b8ed73ee40fc5a5004856a88161f050) for single precision figure, [script](https://gist.github.com/maxentile/f813431f9ac8af681f02dd34490fbe20) for mixed precision figure)

**Comment by peastman** [comment]
With CustomIntegrator I normally recommend that people use mixed precision.  With the standard integrators single precision is usually good enough for constant temperature simulations.

There turns out to be one very specific place in the integration when doing the calculation in a straightforward way in single precision just isn't accurate enough.  Effectively you compute `dt*(1/dt)` and get a result that isn't exactly equal to 1, leading to a steady loss of energy.  So the built in integrators have special handling for it.  Even if you're using single precision mode, they still compute `1/dt` in double precision.  Or if you're using a GPU that doesn't support double precision (many laptop GPUs don't), it adds in a correction term to get better than single precision.  For example, see https://github.com/openmm/openmm/blob/master/platforms/opencl/src/kernels/langevin.cl#L35-L40.

But custom integrators don't do this, so mixed precision is more important for them.
