### ISSUE TITLE
Update values for physical constants

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2427]
Earlier this year there was a major redefinition of the SI unit system: https://en.wikipedia.org/wiki/2019_redefinition_of_the_SI_base_units.  As part of that, several values that used to be experimental quantities (and hence varied depending on which experiment you took them from) were redefined to have precise values.  That includes Planck's constant, Boltzmann's constant, Avogadro's number, and the electron charge.

Should we update the values in OpenMM to use the new definitions?  That will of course change people's results, though only very slighly.  For example, OpenMM uses 6.0221367e23 for Avogadro's number, but it's now defined to be 6.02214076e23.

**Comment by jchodera** [comment]
We should follow the standards set by [CODATA](http://www.codata.org/committees-and-groups/fundamental-physical-constants) in using best-practices consistent units:
![image](https://user-images.githubusercontent.com/3656088/67059150-d4ee9400-f125-11e9-9067-58e81d51f559.png)
This has been repeatedly [advocated for](https://link.springer.com/article/10.1007/s10822-016-9977-1) as a way for the whole simulation community to collectively move forward to rectify historical problems that arise from using arbitrary or inconsistent units.

There as apparently a recent CODATA recommendation update based on the new SI units:
![image](https://user-images.githubusercontent.com/3656088/67059184-13844e80-f126-11e9-8d42-10769d2f0628.png)
The CODATA 2018 recommended values are available [here](https://pml.nist.gov/cuu/Constants/).
CODATA begin accounting for the 2019 SI adjustment in [CODATA 2017](https://iopscience.iop.org/article/10.1088/1681-7575/aa950a).

**Comment by peastman** [comment]
I haven't heard of CODATA before.  In any case, if we're going to change the values we use we should change them to the correct values.  Given the new definitions there is no longer any question about what values are right.  Each quantity has a precise value that is correct by definition, and any other value is wrong.

**Comment by jchodera** [comment]
@peastman: Just because you haven't heard of CODATA doesn't mean that they're not the internationally trusted standards body that is tasked with providing recommended best practices for exactly this situation. Even [NIST](https://pml.nist.gov/cuu/Constants/) follows their guidance.

We should do _exactly_ as CODATA recommends. 

> Each quantity has a precise value that is correct by definition, and any other value is wrong.

The issue is not with the newly defined physical constants, but with measured quantities that depend on these exactly-defiend constants. By using _incompatible_ sets of constants, we can introduce significantly more error than intended. That is what CODATA attempts to solve by using consistent least-squares fits to available, trustworthy data.

**Comment by peastman** [comment]
You clearly aren't familiar with the 2019 units redefinition.  Please see the article I linked to above.  The entire point of it was to create a fully consistent, internationally agreed to set of physical units defined entirely in terms of easily measurable quantities.  As of May of this year, the kilogram in the SI unit system is no longer defined as the mass of a particular block of metal sitting in a vault in Paris.

**Comment by jchodera** [comment]
That's funny, because your Wikipedia article describes how "The values are the work of the CODATA Task Group on Fundamental Physical Constants"
https://codata.org/blog/category/si-redefinition/

See [this paper](https://iopscience.iop.org/article/10.1088/1681-7575/aa950a/pdf).
"The next regular CODATA periodic adjustment of the fundamental constants, CODATA 2018, will also be unique as it will be the first one based on the exact fundamental constants of the revised SI."

We should follow CODATA's guidance on any physical constants used in OpenMM to make sure any derived and measured constants are fully consistent. It wouldn't help to update some of the constants that were redefined but not update others.

The wikipedia article you cite [also cites the CODATA 2018](https://en.wikipedia.org/wiki/Committee_on_Data_for_Science_and_Technology#2018).

**Comment by peastman** [comment]
If the values are the same, great.  There's no problem then.  But if there's any disagreement, we should follow the official values as established by the International Bureau of Weights and Measures.

**Comment by jchodera** [comment]
> But if there's any disagreement, we should follow the official values as established by the International Bureau of Weights and Measures.

Guess what? That's [CODATA](https://www.bipm.org/extra/codata-tgfc/).

**Comment by peastman** [comment]
Sounds like we're in agreement then.  But that leaves the question: should we update them?  That will break consistency with old results, but hopefully eventually lead to better consistency with other codes.

**Comment by jchodera** [comment]
> Sounds like we're in agreement then. But that leaves the question: should we update them? That will break consistency with old results, but hopefully eventually lead to better consistency with other codes.

I think we should, but if we raise this question at the [MolSSI MD software interoperability workshop Nov 3-5](https://molssi.org/2019/07/29/molssi-workshop-molecular-dynamics-software-interoperability/), we have the potential to get everyone to commit!

**Comment by peastman** [comment]
Ok, good plan.

**Comment by andysim** [comment]
FWIW, we had a similar decision to make in psi4 and decided to update some time ago.  We now pull in conversions and constants from [QCElemental](http://docs.qcarchive.molssi.org/projects/QCElemental/en/stable/), which makes it very easy for us to update to any future standards.  A number of tests had to be updated, but that was just an annoying hour or so of typing.

**Comment by peastman** [comment]
We didn't really get a decision about this at the MolSSI meeting.  Do we want to go ahead and make the change?

**Comment by jchodera** [comment]
I think we should go ahead and make these changes for OpenMM 7.5.0.
