### ISSUE TITLE
addHydrogens should only optimize positions of new atoms.

### ISSUE THREAD

**Issue by JoaoRodrigues** [openmm/openmm#2432]
My understanding of `addHydrogens` is that it adds only "missing" atoms, so it should not change anything else in the structure. The code however, when performing the post-addition optimization, restrains only heavy atoms. I think the restraints should include all atoms that were previously in the structure. Since `addHydrogens` already keeps track of the indices of the atoms it adds, it's trivial to check who to restraint later on. 

This change would help people (like me) that might want to make small changes to a structure but want to keep the rest of the structure intact. Would it be a welcome change, or is this a feature and not a "bug"?

**Comment by jchodera** [comment]
[`Modeller.addHydrogens()`](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L938-L961) already has the behavior that heavy atom masses are set to zero prior to minimization so that they should not move during minimization. If they _are_ moving, I suppose this is a bug, and we should track down what is going on.

**Comment by JoaoRodrigues** [comment]
Indeed. But I'm talking about hydrogens that _already exist_ in the structure, not only heavy atoms.

**Comment by jchodera** [comment]
Yep, sorry, I originally misread your comment and just updated this above!

**Comment by JoaoRodrigues** [comment]
Thanks for the reply! I saw your updated comment as I was typing :)

I'm in favour of such an option. I think there are some cases where it's helpful and it's sort of an unexpected behavior from the docstring/function name. I will make the PR later this weekend and if it's fine with you and @peastman , you can merge.

**Comment by peastman** [comment]
Sounds reasonable to me.  I'm not sure an option is even needed.  If the model contains existing hydrogens, can we reasonably assume they're at locations that aren't totally absurd?

**Comment by JoaoRodrigues** [comment]
@peastman if there are locations that are absurd, they can also be cleared anyways with a more explicit call to a minimizer, so yes, maybe an option doesn't make that much sense other than add some sort of backwards compatibility.

**Comment by peastman** [comment]
Having said that, I do need to add: I think both behaviors are reasonable, and it's not obvious that either one is necessarily better than the other.  I suspect this may be a case where about 98% of the time it doesn't matter which way it works, and then each of the behaviors is more convenient than the other about 1% of the time.

**Comment by jchodera** [comment]
> Sounds reasonable to me. I'm not sure an option is even needed.

I thought you might be worried about making a change that changes the behavior of existing code in a potentially surprising way, so that there might be a desire to preserve the previous behavior by default. 

But I do agree that the vast majority of the time, only optimizing _newly_ placed atoms is probably the way to go.
