### ISSUE TITLE
Don't use OpenCL platform if no implementations are available

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2433]
cc: https://github.com/conda-forge/openmm-feedstock/pull/7 and https://github.com/choderalab/openmmtools/pull/442

It appears that OpenMM will try to use the OpenCL platform if an OpenCL loader is found. If a loader is present (such as `ocl-icd`) but no implementations are available, this will cause OpenMM to fail with `Error initializing context: clGetPlatformIDs (-1001)`.

Instead, it seems like we should [check the number of available implementations](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clGetPlatformIDs.html), and checking that [both `CL_SUCCESS` is returned and `num_platforms` returned is not 0](https://github.com/conda-forge/openmm-feedstock/pull/7#issuecomment-544208758). 

This would seem to be required to make sure that OpenMM doesn't break if another conda-forge package installs `ocl-icd`.

**Comment by jchodera** [comment]
@peastman: I think you're the only one who has the expertise to add this. Could we squeeze this into 7.4.1 as well, since it would mean that (even without OpenMM using `ocl-icd`) installation of other `conda-forge` packages that depend on `ocl-icd` could cause OpenMM to break?

**Comment by peastman** [comment]
I'll look into it and see how practical it is.

**Comment by isuruf** [comment]
Sorry to bring this up late, but there are some implementations like Beignet/NEO which show that the platform is available, but no device is available. In the case of Beignet/NEO, this can happen if there are no Intel graphics card available. So, you should check that at least one platform with at least one device.

**Comment by peastman** [comment]
Checking the device at this stage is impossible, since it depends on information that isn't yet available.  If OpenCL is installed but no suitable device is available, the desired behavior is to register the OpenCL platform but throw an exception if the user tries to start a simulation using it.  This will also happen if there is a device available, but it doesn't support the features the user has requested (for example, if they request double precision but their GPU only supports single precision).
