### ISSUE TITLE
GromacsTopFile bug

### ISSUE THREAD

**Issue by thempel** [openmm/openmm#2462]
Loading a gromacs topology file that contains a calcium ion will load a carbon atom instead. After loading it with `app.GromacsTopFile('topol.top')`, the simulations still run without any sign of a problem. Pinging @franknoe as this affects a couple of months of simulation time (nothing published or submitted).

I'll attach a minimum example of a single calcium topology. It was generated with a standard `pdb2gmx` command. I'm using openmm 7.4.

[openmm-carbon-issue.tar.gz](https://github.com/openmm/openmm/files/3803728/openmm-carbon-issue.tar.gz)

**Comment by peastman** [comment]
Thanks!  I'll take a look.

**Comment by peastman** [comment]
The fix is in #2464.  It turns out determining elements is a little complicated.  The records in the `[ atomtypes ]` section sometimes list atomic numbers and sometimes don't.  When they don't, it's impossible to be certain of the element and the best you can do is guess from the atom name.  So that's what we were always doing.  But when the atomic number is given, we can use that to definitely tell what the element is.  I've modified it to do that.

**Comment by thempel** [comment]
Thanks @peastman! I see that this is not straight forward, especially as different gromacs versions might produce different topology files. From a user perspective however, it would be of great help to have a warning in cases when the atom type is simply guessed. It's sometimes difficult to tell which parts of the forcefield parameters should be double checked, especially with large systems.

**Comment by peastman** [comment]
> It's sometimes difficult to tell which parts of the forcefield parameters should be double checked

This doesn't affect any forcefield parameters at all.  Those are all loaded directly from the file.

**Comment by thempel** [comment]
Okay, right, apparently I messed up something else on top of that. Thanks for fixing this so quickly.
