### ISSUE TITLE
u-series electrostatics

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2465]
DESRES has apparently been using this for many years, but the manuscript has only been posted to arXiv this month:
https://arxiv.org/abs/1911.01377

Is this something OpenMM could support?

**Comment by peastman** [comment]
They finally published it after all these years?  Who would have believed it!  I'll take a look.

**Comment by peastman** [comment]
Do you know if they've released an implementation of this?  The paper leaves out a lot of details that make it really hard to evaluate it.

This part in their discussion of charge spreading particularly concerned me:

> In GSE, charges are spread from particles to grid points within a certain radius; the tradeoff between speed and accuracy is principally controlled by the ratio of this charge-spreading cutoff radius to the grid spacing. We have found through experience that a reasonable compromise between speed and accuracy is obtained when this ratio is 3.8, a value we have used extensively in simulations of a variety of systems, and which we also choose here.

Does that mean they're spreading each charge onto an 8x8x8 grid region?  In OpenMM, charge spreading and force interpolation are already the most expensive parts of the reciprocal space calculation, and that's spreading each one onto a 5x5x5 region.  Going up to 8x8x8 would make it significantly slower.

This also makes me suspicious of their comparisons to PME.  They don't say what spline order they're using.  If they spread charges onto a larger region with u-series than PME, then *of course* they can get higher accuracy with a smaller grid.  You could do the same with PME, but people generally don't because the increased cost of charge spreading cancels out any benefit.

**Comment by jchodera** [comment]
Does the [GSE paper](https://aip.scitation.org/doi/abs/10.1063/1.1839571) provide any more concrete details of this charge-spreading operation?

**Comment by peastman** [comment]
Based on that paper, it looks like they're relying on the fact that they spread the charge onto a spherical rather than cubic region of the grid, and a sphere has only about half the volume of a cube with the same width.  But a sphere with radius 3.8 still has almost twice the volume of a cube of side 5.  Also, spreading charges onto spherical regions will produce thread divergence on a GPU, so you probably won't get the full 2x speedup they're assuming.

So I'm doubtful about this method.  I think it's going to end up being slower than PME for the same accuracy.

**Comment by jchodera** [comment]
> spreading charges onto spherical regions will produce thread divergence on a GPU

Couldn't this be treated as the cube that encloses the sphere (weighting the spreading appropriately) to avoid thread divergence?

**Comment by peastman** [comment]
That's exactly the point.  You'll loop over every point in the cube, which has nearly twice the volume of the sphere.  Then you'll check each point to see if it's within the cutoff radius and skip the spreading/interpolation if it isn't.  But for points that are within +/- 1 of the cutoff, you'll usually end up with different threads doing different things.

**Comment by jchodera** [comment]
@peastman: Any further thoughts here? Are there any regimes in which this could be faster than PME on the GPU?

**Comment by peastman** [comment]
I don't really see any regime when this would be faster than PME, even on CPU.  They're spreading charges onto a much larger region than what people normally use.  That's going to make the reciprocal calculation a lot more expensive.

Honestly, I think they're overselling it.  The GSE paper also has some serious technical errors in the way they compare to PME.
