### ISSUE TITLE
v7.4.0: CPU vs. reference discrepancy with Installation test

### ISSUE THREAD

**Issue by des2037** [openmm/openmm#2470]
Hi everyone,

I have recently compiled OpenMM 7.4.0 on ppc64le (ORNL Summit), and I'm running into an issue when performing the installation test:

```python -m simtk.testInstallation```

Results in:
```OpenMM Version: 7.4
Git Revision: b71e92d9ccef7c98cfd6b862eb34095d94fa1b05

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 0.194358  *** LARGE DIFFERENCE **
Reference vs. CUDA: 6.72332e-06
CPU vs. CUDA: 0.199485  *** LARGE DIFFERENCE **
```

This also occurred in other recent versions #2321 (comment). To do the compiling, I used @jchodera 's [compile recipe](https://github.com/inspiremd/conda-recipes-summit), as I wasn't able to compile successfully following the official documentation's instructions. 

The issue boils down to this: if I compile with gcc v8.1.1 then CUDA is happy, but we get the weird CPU discrepancy; if I compile with gcc v4.8.5, then the CPU results look fine, but CUDA segfaults. 

Interestingly, this problem seems to be confined to POWER9, as it doesn't occur on x86_64 systems.

**Comment by peastman** [comment]
I have ideas about where the problem is most likely to be, but I could be wrong.  So let's just approach this methodically and try to narrow it down.

The test script is at https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/testInstallation.py.  You can make a copy of that and add debugging code to it.  The first thing we want to do is identify which force the difference is coming from.  We can do that by putting each force into its own force group.  Add the following immediately after the call to `createSystem()` at https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/testInstallation.py#L39.

```python
for i,f in enumerate(system.getForces()):
  f.setForceGroup(i)
```

Now in the loop over platforms just below that, have it print the energy of each one.

```python
for i,f in enumerate(system.getForces()):
  print(f, simulation.context.getState(getEnergy=True, groups={i}).getPotentialEnergy())
```

Compare the values to see which Force or Forces have significantly different energy between platforms.  It's possible the energies will agree and only forces disagree, but that's unlikely.  If that happens, we can directly compare forces which is a little more work but still straightforward.

**Comment by peastman** [comment]
Also, it the difference turns out to be in NonbondedForce (which it probably will, because that's the most complicated and painful to debug one, and the universe it out to get us), try modifying the call to `createSystem()` to specify `nonbondedMethod=CutoffPeriodic`.  That will tell us whether the difference is coming from the real space or reciprocal space part.

**Comment by des2037** [comment]
@peastman thanks a lot for the detailed diagnostic method! I got slammed at work today, but I'll pick this up on Monday and let you know how it goes.
