### ISSUE TITLE
NVT Simulations with AllBonds constraint tend  to crash when sytem has multiple patches

### ISSUE THREAD

**Issue by Poruthoor** [openmm/openmm#2487]
Hi,

[github_issue.zip](https://github.com/openmm/openmm/files/3897860/github_issue.zip)

I was running a heme protein with oxygen bound. I found that NVT with AllBonds constraint crashes within a few steps while NVT with HBonds was stable. I could reproduce the same with a minimal system, attached here.

The problem does not occur when a) Heme alone present, b) Heme attached with protein but no oxygen, c) Heme attached to oxygen but no protein, d) Protein alone present

I suspect that the issue has to do with the system having two patches ( between heme-protein, between heme-oxygen) simultaneously.

I could reproduce the same problem in CPU and GPU(Cuda)
(Used both openmm/7.2.1 (Cuda version - 9.0) and openmm/7.4 (Cuda version - 10.0.130))

All the simulations are NVT (Langevian Integrator) but the crash occurs with Verlet integrator as well

**Comment by peastman** [comment]
I'm looking into this now.  I confirmed that you're getting very large constraint forces within the heme.  Probably this means the constraint matrix is ill conditioned.  I'll see if I can figure out exactly how.

**Comment by agrossfield** [comment]
Thanks, Peter -- we appreciate it (Ashlin is a student in my lab).

**Comment by peastman** [comment]
Actually, I don't think it's really anything to do with the constraints.  Your initial conformation has a lot of severe clashes in it.  Constraints make minimization harder, so adding more constraints makes it less likely that the energy minimizer will be able to resolve them.  But the real problem is the bad starting conformation.

Here's one example.  (There are hundreds of others.)

```
ATOM  27988 OH2  TIP3 9281       0.103   0.333  14.983  0.00  0.00      BULK    
ATOM  29451 H2   TIP3 9768       0.124   0.257  13.956  0.00  0.00      BULK    
```

The distance between those two atoms is 1.03 A.  Standard TIP3P doesn't have a Lennard-Jones term on water hydrogens, but CHARMM uses a modified version that does.  The combined sigma for that interaction is 1.77 A.  So it's way inside the repulsive sphere, leading to a very large force.

How did you create the water box?

**Comment by agrossfield** [comment]
The exact same box runs fine if you have HBonds instead of AllBonds. The crash occurs reproducibly. The original symptom occurred using a snapshot multiple microseconds into a trajectory — the original system is too large to share easily — but the system crashes in under a nanosecond once you cut over from HBonds to AllBonds.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Dec 2, 2019, at 2:10 PM, peastman <notifications@github.com> wrote:

﻿

Actually, I don't think it's really anything to do with the constraints. Your initial conformation has a lot of severe clashes in it. Constraints make minimization harder, so adding more constraints makes it less likely that the energy minimizer will be able to resolve them. But the real problem is the bad starting conformation.

Here's one example. (There are hundreds of others.)

ATOM  27988 OH2  TIP3 9281       0.103   0.333  14.983  0.00  0.00      BULK
ATOM  29451 H2   TIP3 9768       0.124   0.257  13.956  0.00  0.00      BULK


The distance between those two atoms is 1.03 A. Standard TIP3P doesn't have a Lennard-Jones term on water hydrogens, but CHARMM uses a modified version that does. The combined sigma for that interaction is 1.77 A. So it's way inside the repulsive sphere, leading to a very large force.

How did you create the water box?

**Comment by Poruthoor** [comment]
I used psfgen tool. Also, the same system works fine when used with Hbonds instead of AllBonds. This is true for the actual heme protein that I was working with initially.

**Comment by peastman** [comment]
If you remove the call to `minimizeEnergy()`, it crashes with HBonds too.  The crash is caused by the huge forces, not anything directly related to constraints.  Immediately after you call `context.setPositions()`, add the following lines to print the maximum force on any atom:

```python
forces = simulation.context.getState(getForces=True).getForces()
print(max(norm(f) for f in forces))
```

That prints

```
35724265.898048185 kJ/(nm mol)
```

Constrained optimization is much harder than unconstrained optimization, so the more constraints you add, the less likely it is that the minimizer will be able to fix the clashes.  But again, the root of the problem is the huge forces in your initial conformation.

Try creating a system with `constraints=None`, call `minimizeEnergy()` on that, then use the resulting coordinates as the starting conformation for the simulation with `constraints=AllBonds`.  Does that work?

**Comment by agrossfield** [comment]
Perhaps this wasn’t the best system to share — Ashlin threw it tother to avoid having to send the big system (70k+ atoms).  However, I repeat: the original system we identified the problem in was more than a microsecond in, and it ran for at least another microsecond after, using HBonds.  Switching to AllBonds caused a crash almost immediately, and no amount of minimization prevents it.

Ashlin — can you do a good minimization without constraints, then verify the problem still occurs?

Alan

________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789


On Dec 2, 2019, at 2:39 PM, peastman <notifications@github.com<mailto:notifications@github.com>> wrote:


If you remove the call to minimizeEnergy(), it crashes with HBonds too. The crash is caused by the huge forces, not anything directly related to constraints. Immediately after you call context.setPositions(), add the following lines to print the maximum force on any atom:

forces = simulation.context.getState(getForces=True).getForces()
print(max(norm(f) for f in forces))

That prints

35724265.898048185 kJ/(nm mol)


Constrained optimization is much harder than unconstrained optimization, so the more constraints you add, the less likely it is that the minimizer will be able to fix the clashes. But again, the root of the problem is the huge forces in your initial conformation.

Try creating a system with constraints=None, call minimizeEnergy() on that, then use the resulting coordinates as the starting conformation for the simulation with constraints=AllBonds. Does that work?

**Comment by Poruthoor** [comment]
>Try creating a system with constraints=None, call `minimizeEnergy()` on that, then use the resulting coordinates as the starting conformation for the simulation with constraints=AllBonds. Does that work?

Sure. I will get back once it is done.

**Comment by Poruthoor** [comment]
I apologize for this late reply.

For minimal system:

I created the system with  `constraints=None` , used `minimizeEnergy()` and ran NVT for 1000 ps. Used the resultant xml files to start NVT with `constraints=AllBonds` with and without `minimizeEnergy()`. In both cases, simulation crashed.

I checked the max force on any atom after energy minimizing the system without constraints. It was reduced to  4033.776778532193 kJ/(nm mol)

For the original system:

Here I'm taking a restart file from a NPT simulation ( at 2500 ns) of the heme protein attached to oxygen ( but has `HBonds` as constraints).

Checked the max force on any atom before energy minimizing the system without constraints. It was  5209.8555949729825 kJ/(nm mol)

After energy minimizing the system without constraints. It was  5292.911995650607 kJ/(nm mol).

Used the resultant xml files to start NVT with `constraints=AllBonds` with and without `minimizeEnergy()`. In both cases, simulation crashed. ( Both CPU and GPU)

When I used `constraints=HBonds` to restart NVT from xml file (which I got after minimizing without constraints), it does not crash. This is true for both original and minimal system. I tested this in CPU platform only.

I have attached the script (that I used to make restart file after energy minimization without constraints) and the xml file here
[test_results.zip](https://github.com/openmm/openmm/files/3923668/test_results.zip)

**Comment by peastman** [comment]
Is this issue now resolved, or is there still something that needs to be investigated?  Since it runs without crashing after you energy minimize, clearly the problem with the example you posted was just the starting conformation.  But if you have another case where that doesn't fix the problem, we can try to figure out what's going on there.

**Comment by agrossfield** [comment]
I think Ashlin’s comment was unclear. If I understand him correctly, it reproducibly bombs only with AllBonds, but runs fine with HBonds or no constraints.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Dec 10, 2019, at 8:07 PM, peastman <notifications@github.com> wrote:

﻿

Is this issue now resolved, or is there still something that needs to be investigated? Since it runs without crashing after you energy minimize, clearly the problem with the example you posted was just the starting conformation. But if you have another case where that doesn't fix the problem, we can try to figure out what's going on there.
