### ISSUE TITLE
Discrepancy in results between OpenMM versions

### ISSUE THREAD

**Issue by jrossyra** [openmm/openmm#2496]
I have been running simulations of chignolin with OpenMM that mimic the conditions from the paper “How fast-folding proteins fold” that used the Anton supercomputer (Charmm22star forcefield, 340 K, 4nm**3 box, neutralizing charges only). About a year ago I ran a relatively long simulation using version 7.0 with results that matched the Anton data. Recently using version 7.3 I see a very large discrepancy in simulated structural ensembles and folding transition rates.
 
All of my simulations have used the same starting structure, which was created by hydrating a frame from early in the protein-only Anton trajectory, running a short NPT, and short NVT for pre-production. All of the OpenMM simulations I ran have used the AllBonds constraint along with mass-repartitioning to make the hydrogens 4amu, and then used 5 femtosecond timesteps.
 
Below are plots of Calpha RMSD vs simulation time for new OpenMM simulations where it is clear that the folded/unfolded state residence times are quite different from the Anton trajectory.  

RMSD Data:
- Anton, charmm22star
- DGX, charmm22star, OpenMM 7.3   w/ CUDA 10.0

![image](https://user-images.githubusercontent.com/28569164/70261519-9ad26380-1760-11ea-9127-2787652e6f33.png)

![image](https://user-images.githubusercontent.com/28569164/70261543-a887e900-1760-11ea-87d7-2cf6758b9f26.png)

**Comment by jchodera** [comment]
Initial thoughts on discrepancies between OpenMM and Anton trajectories:

I believe we changed the CustomTorsionForce because we found a bug in how we were treating CHARMM impropers. See [the issue](https://github.com/openmm/openmm/issues/1760) and [PR](https://github.com/openmm/openmm/pull/1761) that addressed it. The old behavior was incorrect, but the new behavior should be correct.

However, you said this didn't produce a qualitative difference, so we should see what else might be going on.

One immediate concern is whether the Anton simulation also used constraints on all bonds. Constraining all bonds (instead of just hydrogen bonds) can cause significant differences in the effective torsion potentials. I'd worry that the potential may be significantly deformed between all-bonds and h-bond constraints, but I'd be surprised if it would be as drastic as you note.

A more minor issue is which integrator was used. Driving to very large timesteps with poor Langevin integrators (pretty much anything but BAOAB) could significantly distort the shape of the landscape. But again, I'd be surprised if it caused this large of a deviation.

One big question is how closely the energies and forces agree between Anton and OpenMM in their implementation of the charmm22star forcefield. DId you prepare your system in CHARMM format and load it into OpenMM with the CHARMM reader, did you covert via ParmEd, or did you use the OpenMM native ForceField reader?

The big worry is what may have changed between 7.0 and 7.3 that could cause this issue (aside from the aforementioned CHARMM improper fix). Peter would be better equipped to identify any changes to OpenMM that might have impacted things.

Was there some data (e.g. system, state, and integrator XML files) you wanted to attach for us to look into the 7.0 vs 7.3 differences?

**Comment by peastman** [comment]
Have you looked at the trajectories?  If something different is happening in the newest simulation, can you tell what that something is?  Or does everything still appear normal, just in a slightly different area of configuration space than the other simulations?

**Comment by jrossyra** [comment]
I did see the discussion on improper torsions. That led me to scanning the formulation in my system.xml files made with the different OpenMM versions, and reverting the new version's formulation back to run a bit of MD with it (and see that the ensemble was still shifted in TICA space).

I have a run with the amber99-sbildn forcefield made via the openmm forcefield class with the 5fs timesteps and all rigid bonds. So far this system seems to reversibly fold and unfold, but it is not so far along as the charmm simulation. I can also start a run with the built-in charmm36 forcefield to see how that stacks up.

I can run a setup that more closely matches the integration parameters and bond constraints used in the Anton simulation to make sure these parameters aren't a major factor. When I ran this on Titan I was using the identical MD parameters as the more recent MD, all bonds constrainted and 5fs timesteps, that resulted in the very nice match to the Anton conformation ensemble in TICA space.

I have not specifically looked at or compared energies (I don't have the data I generated with OpenMM 7.0, just the TICA ensemble plots in the email), but I would be happy to run the older version. I have never built OpenMM myself, and now all the resources I am on have CUDA 10. Would you guys be able to compile Openmm 7.0 against CUDA 10.0 on the dev channel or something to that effect? I would be able to run it right away in that case to try reproducing the old data I am missing.

I will pull together my files used to start each simulation. My workflow was the same in each case, I have a copy of the Charmm22* forcefield from J.C. Gumbart in Charmm format. I read these with the parmed charmm file readers, then saved system.xml & integrator.xml files for using with OpenMM. I diff'ed the system.xml files for each version, and the bulk of the files were identical. Only 10 or so lines were different, namely the version strings and customtorsionforce formula produced differences along with a few other lines. All of the parameters stored in the file appear to be identical.

I also have not dug into the actual structures yet, but I will spend some time looking at structures from the newer run to do sanity checking. 

Input files I used for each of the versions coming soon, thanks!

**Comment by jchodera** [comment]
Thanks for pulling together serialized `System`, `State`, and `Integrator` files! It should be straightforward for us to compare energies and forces between OpenMM versions (using the `conda`-installable packages) to see if anything might have impacted them between versions, and to drill down into which force components may have changed once we have those.

**Comment by peastman** [comment]
What's the status of this?  You said on Dec. 6 you would post input files to reproduce this, but as far as I can tell you never did?
