### ISSUE TITLE
System Neutralization

### ISSUE THREAD

**Issue by ElSmaele** [openmm/openmm#2526]
How does openmm handle non-neutral systems with NonbondedMethod=CutoffPeriodic? 
I have run free energy calculations (ligand-protein affinity) of -2 charged system, and I am surprised 1. calculations run without error; 2. the resulting affinities seem reasonable. I'd be happy to have insights/comments on that.

**Comment by peastman** [comment]
It doesn't do anything particular in that case.  Each atom only sees the other atoms within the cutoff distance of itself, so it has no idea whether the system as a whole is neutral.  But since the cutoff is handled with the reaction field method, it implicitly assumes that everything beyond the cutoff can be approximated as an uncharged dielectric.

Neutrality is much more important when using PME, since then each atom really does interact with every other atom.  In that case it effectively adds a uniform charge density throughout the whole box in order to make the system neutral.

**Comment by ElSmaele** [comment]
Great, thank you for your answer!

**Comment by jchodera** [comment]
There is one consideration here that is important: The reaction field energy expression [used by OpenMM](http://docs.openmm.org/latest/userguide/theory.html#coulomb-interaction-with-cutoff) does add a constant to each pair interaction within the cutoff so that the Coulomb U(r) goes to zero at the cutoff. This can cause issues in some instances where you're trying to compute, say, hydration free energies, because the electrostatic energy doesn't match what you would expect for Born solvation of an ion. If you're computing free energies between two different configurations, it's probably OK, but if you're looking at differences between `CustoffPeriodic` and `NoCutoff`, these pair-dependent constants could make things tricky.
