### ISSUE TITLE
If it is possible to get force or energy terms from OpenMM?

### ISSUE THREAD

**Issue by dhl2011dj** [openmm/openmm#2530]
Dear all,

I am trying to write a c++ code that coupling molecular dynamics  with another molecular mechanics method, This requires the extration of different force or energy terms (bond/angle/dihedral/improper/vdw/electrostatic...) from MD package. So I am wondering if it is possible to get these terms from the c++ layer of OpenMM?
For example, if I can get the force value on one atom that exerted by a specific bond.

Thanks in advance.

**Comment by peastman** [comment]
You can use force groups to break it up at the level of different interaction types.  Call `setForceGroup()` on any Force object to assign it to a particular force group.  Then when you call `getState()`, use the `groups` argument to select which group or groups you want to evaluate.

There's no option to break it up all the way down to individual bonds.  But if that's what you want, it's trivial to compute the force from a single bond yourself, since it's just `k*r`.
