### ISSUE TITLE
Discretizations of Langevin integrator

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2532]
I've been running more tests of BAOAB.  In #2396 and #2520 I tested it on alanine dipeptide in a box of water, using hbond contraints and rigid water.  I found that it produced excellent potential energies, but the temperature was too low at large step sizes.  I also wanted to see how it worked without constraints, since we might want to use it for AMOEBA.  So I repeated those tests with flexible water and no constraints.  Here are the results.  The columns are step size (in fs), mean potential energy, and mean temperature.

```
0.5 -35605.70052568342 kJ/mol 297.62917866031023 K
1.0 -35609.767674540715 kJ/mol 290.01451980187807 K
1.5 -35640.367635378985 kJ/mol 277.7200127610364 K
2.0 -35623.32820068326 kJ/mol 260.3315873536176 K
2.5 -35591.90934715343 kJ/mol 238.60981627728958 K
```

The potential energies are excellent.  Even at 2.5 fs it still has very little error.  But the kinetic energies are terrible!  Before we handwaved this as, "It has less error in configurational quantities than kinetic ones."  But this isn't just a matter of the error being a bit larger.  The temperatures aren't even in the right range.

But clearly there must be accurate velocities in there somewhere.  You can't get an accurate trajectory (and hence accurate potential energy distribution) otherwise.  That implies the problem must just be in how we're calculating the temperature.

Since openmmtools makes it easy to use any discretization of the integrator you want, I decided to repeat the test with all possible cyclic permutations of `V R O R V`.  Keep in mind that all of these are equivalent.  When running a simulation with any one of them, it cycles through exactly the same sequence of operations.  The only difference is what point in the cycle you interpret as the "break between steps".  Here are the results.

```
V R O R V

0.5 -35638.50715852432 kJ/mol 297.44406396220063 K
1.0 -35611.054894770445 kJ/mol 290.0160817851261 K
1.5 -35625.51474560968 kJ/mol 277.8675158094801 K
2.0 -35664.53782076183 kJ/mol 260.17400740815174 K
2.5 -35575.531359334906 kJ/mol 238.43197405628177 K

V V R O R

0.5 -35616.709575415734 kJ/mol 300.16092415193197 K
1.0 -35632.38941835361 kJ/mol 299.88658398452867 K
1.5 -35642.16039110886 kJ/mol 300.0406027048148 K
2.0 -35636.90849051754 kJ/mol 300.0756093508294 K
2.5 -35573.218970007474 kJ/mol 302.09220953946925 K

R V V R O

0.5 -35703.033396773084 kJ/mol 300.0059357696807 K
1.0 -35962.15707769471 kJ/mol 299.78669020251635 K
1.5 -36249.157901376406 kJ/mol 300.02509772648847 K
2.0 -36771.86778721861 kJ/mol 300.0954166688417 K
2.5 -37408.47504859062 kJ/mol 302.4584345887388 K

O R V V R

0.5 -35708.3051064537 kJ/mol 300.05461671506856 K
1.0 -35937.06525132866 kJ/mol 299.7084628213554 K
1.5 -36285.485792754305 kJ/mol 300.0714472598585 K
2.0 -36750.93079633593 kJ/mol 300.2960435429621 K
2.5 -37395.53765795346 kJ/mol 302.3787520536727 K

R O R V V

0.5 -35658.89274174247 kJ/mol 299.7312231314666 K
1.0 -35602.84066143191 kJ/mol 300.19659045010724 K
1.5 -35631.42077158848 kJ/mol 299.9624030452655 K
2.0 -35629.41289981576 kJ/mol 299.87705344743586 K
2.5 -35620.44282742511 kJ/mol 301.8949595144138 K
```

It's clear that two of these are much better than the others.  VVROR and RORVV both give excellent measures of both kinetic and potential energy.  RVVRO and ORVVR both give accurate temperatures but the potential energy distribution is off.  And VRORV gives good potential energies, but the velocities are way too low.  That doesn't mean the simulation is inaccurate.  Again, all of these lead to identical simulations.  It's just that in between the two V substeps, the "velocity" parameter doesn't actually correspond to the velocities at any point in the physical trajectory.

VVROR happens to be the "LFMiddle" method that Amber uses.  It looks to me like they knew what they were doing when they chose it over VRORV (which they refer to as "VVMiddle").  In fact, I found the following in the Amber manual explaining their choice:

> For any general systems, “LFMiddle” shares the same accuracy as “VVMiddle” for sampling the marginal distribution of coordinates. In addition, “LFMiddle” leads to the exact marginal distribution of momenta in the harmonic limit.

And they cite this paper for it: http://engine.scichina.com/doi/10.1360/N972018-00908 

Given that, I think we should consider switching to that discretization.  The "velocities" you get from VRORV are simply wrong.  They don't correspond to physical velocities at any point in the trajectory.

**Comment by jchodera** [comment]
I'm tagging @maxentile, who has generated some great plots for various discretizations (and cyclic permutations) that illustrate the pathologies present at these partial steps.

The short story is: No, we don't want to recommend these other cyclic permutations be used because they mess up the configurations substantially. Take a look at what happens with a quartic system when you plot the phase space *error* at different stages in the integrator cycle (which correspond to different cyclic permutations above):
![image](https://user-images.githubusercontent.com/3656088/72779136-06757080-3be9-11ea-9e11-ba62732798b6.png)
The configurational marginals are shown in the bottom. I think @maxentile generated one with the velocity marginals as well, but you can clearly see that the only symmetric (symplectic) splitting with good configuration behavior is VRORV.

> Before we handwaved this as, "It has less error in configurational quantities than kinetic ones."

This isn't handwaving. This is a [mathematical truth arising from superconvergence](https://aip.scitation.org/doi/abs/10.1063/1.4802990) that we [have verified numerically holds for complex biomolecular systems by direct measurement](http://www.choderalab.org/publications/2018/2/16/quantifying-configuration-sampling-error-in-langevin-simulations-of-complex-molecular-systems). The "temperature" you are computing is based on a fictitious intermediate variable (the velocity) that is not an accurate estimate of the temperature, but that's OK---we know the temperature analytically.

Incidentally, this is the [same reason why assigning the velocities from a Maxwell-Boltzmann distribution at the beginning of a leapfrog-lagged timestep generates a biased configuration distribution](https://github.com/openmm/openmm/pull/2518#issuecomment-574856560) at the end of the timestep.

Were you to estimate the temperature via [configurational methods](https://physics.nyu.edu/~dg86/codef04b/node5.html), I think you'd find it is correct.

**Comment by jchodera** [comment]
I can see what you mean about the velocity marginals being improved for VVROR, but we trade the symmetric (symplectic) nature of the timestep for that, which means that flipping the sign and integrating a step doesn't get you anywhere close to the previous step (even at high precision).

On the other hand, I do see your point that people may be surprised if the default integrator gives great configuration space sampling, but we'd get a lot of complaints about weird velocities. So maybe there is merit to considering the default "LangevinIntegrator" being VVROR, but recommending VRORV if they just need configuration space sampling to be accurate.

Important question: Will VVROR cause the same problems if combined with AndersenThermostat that our current leapfrog method does? Then again, we may not have to worry about that if these shouldn't be combined, but `setVelocitiesToTemperature()` does the same thing.

**Comment by peastman** [comment]
> but we trade the symmetric (symplectic) nature of the timestep for that

Not correct.  All of these splittings are symplectic.  All of them produce exactly the same trajectory.  The *only* difference between them is what point in the cycle they interpret as the break between steps:

```
...V V R O R V V R O R V V R O R V V R O R V V R O R V...
            ^ ^
            A B
```

If you query the velocities, VVROR returns the ones at point A, and VRORV returns the ones at point B.  The ones at point A are an accurate measure of the physical velocities at a particular point in the trajectory (on the half step, since this is a leapfrog integrator).  The ones at point B are not an accurate measure of the physical velocities anywhere.  We can tell that because the physical velocities at all times follow a Boltzmann distribution at 300K, and the "velocity" parameter at point B isn't anything close to that.

The positions returned at points A and B are identical.  No position updates happen between those points.

**Comment by peastman** [comment]
By the way, this bears on the issue discussed starting at https://github.com/openmm/openmm/pull/2518#issuecomment-572741719.  The velocities at point A match the thermostat temperature.  The ones at point B are lower.  So if you initialize a simulation by setting the velocities at point B to a Boltzmann distribution, you're actually making the system too hot.

I should add that I really don't understand why the distributions are so different at those two points.  I need to spend some time with the paper cited in the Amber manual and see if it makes things clearer.

**Comment by peastman** [comment]
It appears that article is in Chinese.  They have an English translation of the abstract, but nothing else.  On the other hand, Google translate seems to do a remarkably good job on it, so it may be readable anyway.

**Comment by jchodera** [comment]
> @jchodera -- I'm not sure I see how the on-timestep configurations sampled by the cyclic permutation "VVROR" could be different from the configurations sampled by "VRORV" at steady-state -- the only difference in system state between the two methods is whether you've updated the velocities based on forces at the final positions for another half-timestep before measuring the configuration. Could you explain?

My mistake---`VVROR`, `VRORV`, and `RORVV` both produce identical configuration distributions at steady-state. The difference is whether (1) the action of the integrator step is reversible, and (2) the velocity distribution achieved at the end of the timestep. 

> By the way, this bears on the issue discussed starting at #2518 (comment). The velocities at point A match the thermostat temperature. The ones at point B are lower. So if you initialize a simulation by setting the velocities at point B to a Boltzmann distribution, you're actually making the system too hot.

If you're talking about velocity Verlet (`VRV`) with an initial `X` momentum refresh step (`XVRRV`), it is evident from the configuration distribution that `XVRRV` gives the right configuration distribution, but `XVVRR` leads to a configuration distribution that appears too "hot". That seems like the opposite of what you're saying, but it's possible I misunderstood.
![image](https://user-images.githubusercontent.com/3656088/72860933-5f4f1280-3c96-11ea-8f9e-0744debe2a63.png)
It should be very easy to test whether there are any pathologies by refreshing monentum `X` at the beginning of each step: `XVVROR`, `XVRORV`, and `XRORVV`.

> All of these splittings are symplectic

All the splittings are symplectic, but the grouping into asymmetric symbol sequences would not be reversible, would it? If we use `VVROR`, then flipping the velocity sign and applying another `VVROR` would not get us back to the initial phase space point with inverted velocity. That may have ramifications for some uses. 

We should probably ask Ben Leimkuher to weigh in on this, since he has a much better understanding of the practical implications (via their [MIST project](https://bitbucket.org/extasy-project/mist)).

**Comment by peastman** [comment]
I've spent much of the day pondering that paper, and also http://dx.doi.org/10.1021/acs.jpca.9b02771, which is a followup paper (in English!) that focuses on the use of constraints with it.  I'm still very mystified about what's going on.  They present an explanation of why the leapfrog version produces better velocities, but it's the sort of abstract derivation that's mostly unenlightening if you're looking for a mechanistic understanding.  Basically they just show that a particular distribution is invariant under a particular operator.

Before you perform the velocity update, the velocities perfectly follow a Boltzmann distribution.  After you perform a full step velocity update, they still do.  But if instead you perform only a half step velocity update, that consistently produces velocities that are much too small.  Why?

I suspect there must be a resonance effect that causes oscillatory motions to become synchronized with the integration time steps.  But my arguments for why are handwaving ones, not rigorous ones.

And it's a huge effect.  Using VRORV with a step size of only 0.5 fs, the error in the temperature is larger than for any of the other four cyclic permutations with a step size of 2.5 fs!

> All the splittings are symplectic, but the grouping into asymmetric symbol sequences would not be reversible, would it?

Deterministic leapfrog integrators are both reversible and symplectic.  But of course, stochastic integrators are never symplectic or reversible, by definition.  If you remove the `O` substep, all these integrators just turn into Verlet (either velocity Verlet or leapfrog Verlet, depending on where you break between steps).

> We should probably ask Ben Leimkuher to weigh in on this

That would be great!  I would love to get his insight on this.

**Comment by maxentile** [comment]
>VVROR, VRORV, and RORVV both produce identical configuration distributions at steady-state.

Okay! I think we're all on the same page about that now.

>All of these splittings are symplectic. All of them produce exactly the same trajectory.
>All the splittings are symplectic, but the grouping into asymmetric symbol sequences would not be reversible, would it? If we use VVROR, then flipping the velocity sign and applying another VVROR would not get us back to the initial phase space point with inverted velocity.
>Deterministic leapfrog integrators are both reversible and symplectic. But of course, stochastic integrators are never symplectic or reversible, by definition.

To be honest I am a bit confused about usage of the terms "symplectic" and "reversible" throughout this thread. (There are a few related concepts here that don't all imply each other: "symmetric" splitting, "time-reversibility", "symplecticness", "volume-preserving", ...)

I don't think that even a method formed by a palindromic sequence of updates like "VRORV" or "OVRVO" will have a time-reversibility property like the one described -- a property like "if simulate_timestep(x_0, v_0) = (x_1, v_1), then simulate_timestep(x_1, -v_1) = (x_0, -v_0)" -- because the OU-process step is not deterministic or time-reversible. (Consider what happens if the collision rate is inf. Then simulate_OU_step(v_0) will produce velocities v_1 distributed as Normal(0, velocity_scale) regardless of v_0 (and regardless of the sign of v_0).)

Does the current OpenMM default Langevin integrator have some special property related to time-reversibility that we risk breaking?

>We should probably ask Ben Leimkuher to weigh in on this, since he has a much better understanding of the practical implications (via their MIST project).

Agreed!

**Comment by jchodera** [comment]
> To be honest I am a bit confused about usage of the terms "symplectic" and "reversible" throughout this thread. (There are a few related concepts here that don't all imply each other: "symmetric" splitting, "time-reversibility", "symplecticness", "volume-preserving", ...)

My fault here. I'm referring to the limit as the collision rate goes to zero, where the O step is eliminated. There are certain nice properties that integrators have if they are symmetric. For example, computing nonequilibrium work is something that is easy to do with a symmetric integrator like `VRORV` because the forward and reverse steps can easily be paired as ratios.

I was just going to say I'm not sure how to compute the nonequilibrium work for a non-symmetric splitting like `VVROR`, but I realize that our `openmmtools.integrators.LangevinIntegrator` will actually compute a work in this case. However, I'm not sure if what we do is valid because it would require the reverse trajectories be simulated with `RORVV`, and we'd have to make nonequilibrium switches that use either `VVROR` or `RORVV` with equal probability in something like NCMC.

This may be a very special case, but in general, there are corner cases like this that make nonsymmetric integrators (which do not reduce to their symplectic counterparts as the collision rate goes to zero) potentially problematic to deal with. But that's why we should bring in the experts!

**Comment by peastman** [comment]
Shall I also write to Mark Tuckerman?  He's an author on one of the LFMiddle papers (the one in English), so he can likely answer our questions about it.

**Comment by jchodera** [comment]
Great idea. Could you do this and loop me in? I think you're probably more conversant on those specific papers at the moment.

**Comment by peastman** [comment]
Based on offline discussions, I think we're in agreement that we'll move to the leapfrog version of the integrator (VVROR aka LFMiddle).

The name BAOABLangevinIntegrator doesn't make sense anymore, since it isn't using BAOAB.  I suggest renaming it to LangevinMiddleIntegrator to match the name used in Amber for the same integration method.

**Comment by jchodera** [comment]
Oh, I thought we were going to follow up and schedule a chat with Ben Leimkuhler first to talk through the ramifications! But I agree this sounds very promising.

We still have to figure out the issue with velocity randomization, and the dependence of the sampled configurational distribution on when in the cycle we randomize velocities.

**Comment by peastman** [comment]
Good point.  We can run some tests of it.  How about this protocol:

1. Equilibrate a system by running for a while with the temperature set to 300 K.  The measured temperature will fluctuate around 300 K, but as long as the system is reasonably large the fluctuations should be small.
2. Replace the velocities with new random values, either with or with the half step shift.
3. Run a few more steps and see what the velocity distribution is.
4. Repeat this a bunch of times to measure the average change in temperature immediately after velocity randomization.

**Comment by peastman** [comment]
Summarizing the conference call we just had about this, it sounds like the decision is that we'll use the leapfrog version, but we need to be sure we clearly document that and educate users about the significance of it (e.g. there can be strange correlations between the positions and velocities coming from the fact they're at different times).  Fortunately, leapfrog integrators are pretty common, so most (but not all!) users should already be familiar with the concept.

**Comment by jchodera** [comment]
I think we also decided to keep the non-leapfrog (velocity Verlet) version as `BAOABIntegrator` and use it in the documentation/examples when appropriate, right?

**Comment by peastman** [comment]
I interpreted that part of the discussion as just saying, "We'll tell people there are multiple integrators available and include discussion of the different options."  I don't see any value in providing both versions of BAOAB as standard integrators.  The only real difference between them is that one outputs velocities that are useful for a few limited purposes (like monitoring equilibration), while the other outputs velocities that shouldn't be used for anything, and that users shouldn't even really think of as "velocities".

If for some reason someone really wants the velocity verlet version, they can always use the one from openmmtools.  Come to think of it, we should also add a link to openmmtools in the manual where it discusses integrators.

**Comment by jchodera** [comment]
@peastman: We _need_ both versions of the integrator. In our discussion, we specifically talked about applications where one discretization is superior to the other, and Ben's specific proposal was to use _both_ forms in the examples as appropriate. I have no idea how you came away from that conversation with the above interpretation.

The velocity Verlet version in `openmmtools` has poorer performance than the native integrator---especially for small systems. Can't we just leave both in OpenMM?

**Comment by peastman** [comment]
> we specifically talked about applications where one discretization is superior to the other

What applications are those?

**Comment by peastman** [comment]
> The velocity Verlet version in openmmtools has poorer performance than the native integrator

Also note that's strictly because it does way too many constraint applications.  See the version I added in the documentation for CustomIntegrator.  It should be just as fast as the built in one.

https://github.com/openmm/openmm/blob/484e6b99eddc47d66fa724f073b6dd2130313f7c/openmmapi/include/openmm/CustomIntegrator.h#L242-L259

**Comment by jchodera** [comment]
> What applications are those?

We talked about this on the call. For example, [`openpathsampling`](http://openpathsampling.org/) requires the use of symmetric integrators that are the same shooting forward or backward. BAOAB will work, but the asymmetric leapfrog version will not.

Similarly, as we found with the current `LangevinIntegrator`, if we need to randomize the velocity from Maxwell-Boltzmann for some reason, the symmetric version will behave correctly while the leapfrog version will not.

The point of Ben's comment was that some applications benefit from leapfrog discretization, others require the symmetric discretization, and we should do the right thing by educating our users by using the right discretization for the right application in the examples. 

I'm happy to help update the examples, but I think we need _both_ discretizations within OpenMM to do this correctly.

Separately, let me try to update the constraints in `openmmtools` to see if this is really equivalent in speed.

**Comment by jchodera** [comment]
@peastman: Would you object if I contributed a PR to OpenMM that removes redundant constraint steps at the level of `CustomIntegrator`, rather than doing it within `openmmtools`? Or is there some valid reason we may want to apply redundant constraint calls?

**Comment by peastman** [comment]
> For example, openpathsampling requires the use of symmetric integrators that are the same shooting forward or backward. BAOAB will work, but the asymmetric leapfrog version will not.

When integrating backward you use the transpose of the propagator.

> if we need to randomize the velocity from Maxwell-Boltzmann for some reason, the symmetric version will behave correctly while the leapfrog version will not.

We already agreed we'll handle this automatically as part of #2518.  So it will do the right thing either way.

A key to creating and maintaining a healthy codebase is knowing what features to leave out.  In the long term, this is often more important than what features you add!  Every extra feature adds a maintenance burden for developers and a cognitive burden for users.  That's why I try to set the bar so high for adding new features.  I don't think this feature comes close to reaching that bar.  The cases where I'd recommend the velocity verlet version over the leapfrog version are few and far between.  The cost of not adding it is negligible: it just means people type `openmmtools.BAOABIntegrator` instead of `openmm.BAOABIntegrator`.  The maintenance difference between the two is huge: the CustomIntegrator version is 18 lines, while the built in version takes over 1000 lines of code split between about a dozen files.

> Would you object if I contributed a PR to OpenMM that removes redundant constraint steps at the level of CustomIntegrator, rather than doing it within openmmtools?

How would it decide what to remove?  CustomIntegrator is basically a programming language.  It does exactly what you tell it to, as a programming language should.  I wouldn't want it to start skipping steps because it decided you probably didn't really mean what you told it.

**Comment by jchodera** [comment]
> When integrating backward you use the transpose of the propagator.

As I understand it, integrating forward and backward in time is the same if you use a symmetric integrator like BAOAB, but integrating forward and backward are different if you use an asymmetric splitting like the leapfrog version. @dwhswenson can correct me if I'm incorrect here.

> A key to creating and maintaining a healthy codebase is knowing what features to leave out.

I totally agree, but there's something to be said for providing features found in many many other codebases within the main `openmm` package. You don't even want to include `numpy` as a dependency for the Python layer because it might be overly burdensome, even though it is completely ubiquitous. Asking folks to install `openmmtools` just to get a standard velocity Verlet version of integrators is orders of magnitude more burdensome.

> How would it decide what to remove? CustomIntegrator is basically a programming language. It does exactly what you tell it to, as a programming language should. I wouldn't want it to start skipping steps because it decided you probably didn't really mean what you told it.

The idea would be to just go through the stack and eliminate duplicate constraint applications to positions if there were no updates to 'x' in between, or to velocities if there were no updates to 'v' in between. It would be quite simple to add, and you suggest it would eliminate the speed issues that have spawned roughly [25 issues so far](https://github.com/openmm/openmm/issues?utf8=%E2%9C%93&q=is%3Aissue+customintegrator+slow).

**Comment by dwhswenson** [comment]
In principle, I think that using the transpose of the propagator could work. I don't think you can tell whether a trajectory was generated forward from the first frame with VVROR, backward from the final frame (starting from reversed velocities) with its transpose, RORVV, or starting in the middle and doing some of each. I thought that the bigger problem we once had with the OpenMM leapfrog `LangevinIntegrator` came because coords/vels were not synchronized, not because it wasn't symmetric (though I could be wrong).

On the other hand, actually implementing something that uses the transpose integration is probably not trivial. Would that be easily accessible in OpenMM? At best, it would still require some significant changes on our side, since we currently assume symmetric integration, but that's adjacent to areas I'd like to restructure anyway. 

As it stands now, we tell users that they need to use symmetric integrators (although, looking at our docs, perhaps we should be a bit louder about this). And no matter what, that will remain true for other engines.

**Comment by peastman** [comment]
> I totally agree, but there's something to be said for providing features found in many many other codebases within the main openmm package.

But we're talking about a feature that isn't found in *any* other codebase.  Amber is the only one that currently includes any version of this integrator, and it has only the leapfrog version.

> On the other hand, actually implementing something that uses the transpose integration is probably not trivial. Would that be easily accessible in OpenMM?

It wouldn't be difficult: you'd just use a CompoundIntegrator to select between the forward and backward versions.  But since that would involve a CustomIntegrator anyway, you might as well just use the symmetric version (unless you want to monitor the temperature, which the symmetric version doesn't do accurately).

> The idea would be to just go through the stack and eliminate duplicate constraint applications to positions if there were no updates to 'x' in between

That would only eliminate two of the seven constraint applications in your version.  The others are more subtle: applying constraints at times when there's no need to apply them, because they'll get fixed up by a later application after another update.

> it would eliminate the speed issues that have spawned roughly 25 issues so far.

Your link leads to a list of issues that have nothing to do with this.  "Long-range correction computation times"?  "OpenMM-Amoeba crashes"?

**Comment by jchodera** [comment]
> But we're talking about a feature that isn't found in any other codebase. Amber is the only one that currently includes any version of this integrator, and it has only the leapfrog version.

Velocity Verlet style integrators---where the positions and velocities are synchronized---are found in all other MD codes. Only having the leapfrog forms (where velocities are lagged in respect to positions) is pretty rare---just OpenMM and AMBER do this, to my knowledge.

BAOAB is just a "better" Langevin integrator in the velocity Verlet (synchronized coordinates/positions) style. Saying "no other code implements this" as an argument to going for the version that uses lagged velocities isn't really a persuasive agrument.

**Comment by jchodera** [comment]
> That would only eliminate two of the seven constraint applications in your version. The others are more subtle: applying constraints at times when there's no need to apply them, because they'll get fixed up by a later application after another update.

Good point. We'll have to engineer a less conservative version of this CustomIntegrator tailored for speed, rather than work measurements. I'll look into this.

> Your link leads to a list of issues that have nothing to do with this. "Long-range correction computation times"? "OpenMM-Amoeba crashes"?

Whoops, well, I just searched for "CustomIntegrator slow".

**Comment by peastman** [comment]
This isn't any kind of general policy on velocity verlet style integrators.  It really is just about this one specific integrator and whether there should be a built in implementation of it or not.

There are two approaches to creating a powerful package.  One is to add every feature anyone might ever want.  That's the approach taken by LAMMPS, for example.  It's a vast codebase with millions of lines of code.  It has tons of features only used by a small number of people.  That's one approach, but it's not the one taken by OpenMM.

Instead, I try to provide a small number of very flexible features.  We don't need built in versions of all possible potential functions, because you can easily define whatever you want with custom forces.  We don't need built in versions of all possible integrators, because you can define new ones with just a few lines.

So the question isn't, "Should we support this integration algorithm?"  We do!  The question is whether it's important enough to add to the very small set of built in integrators.  (Even though that set is small, it's already bigger than it needs to be.  I wish I could get rid of BrownianIntegrator, which is only very rarely used.)  The only ones that really ought to get added are ones that either can't be implemented with CustomIntegrator, like the Drude integrators, or ones that we're going to recommended as the preferred integrators most people should be using for most simulations.

**Comment by jchodera** [comment]
> Instead, I try to provide a small number of very flexible features.

I agree with this philosophy! I think we are just reasonable people disagreeing in a reasonable manner on which integrators we would consider the "essential core set" we should provide our users.

We do have two different kinds of users:
1. folks who use OpenMM out of the box to do MD simulations
2. folks who build apps on top of OpenMM

I think we're just discussing what we think is the right way to approach problem 1 in a responsible manner for the community. We've written our [own paper](http://www.choderalab.org/publications/2018/2/16/quantifying-configuration-sampling-error-in-langevin-simulations-of-complex-molecular-systems) on what we think is important and why; we've heard from Ben L that the best practice is unsettled, the leapfrog version doesn't magically fix things because it still messes up the joint distribution `p(x,v)`, and that there are real scenarios where both leapfrog and vv synchronizations are called for. At this point, we're just deciding whether we want just leapfrog, just vv, or both, and which to recommend or use as default. That's a really reasonable discussion to have considering its significant impact on new users.

I'm still in favor of having both forms and trying to use the documentation to help educate users about what integrators can and cannot do and why, as Ben L suggested. It's a bit more work, but it does have benefits in producing more informed users as a result.

>  I wish I could get rid of BrownianIntegrator, which is only very rarely used.

We can add a deprecation warning that this will be removed in 8.0 if we want! We don't just have to only _add_ features---we can also take them away, especially if there are alternatives (like `CustomIntegrator`) to encourage good practices.

**Comment by craabreu** [comment]
Hi all,
How about just having the leap-frog version as default, but implementing a setter/getter that turns the integrator into its BAOAB version? Would that be a reasonable compromise?

**Comment by peastman** [comment]
> I think we are just reasonable people disagreeing in a reasonable manner on which integrators we would consider the "essential core set" we should provide our users.

Absolutely!  I hope it didn't sound like I was interpreting you differently.  It's very hard to convey tone in writing...

If the practice is still unsettled, how about adding only one version now, choosing the one we think is most useful based on current information?  It's much harder to remove a feature once you've added it than to make the decision not to add it in the first place!  If in the future we conclude there are compelling arguments for having both versions, we can add it then.

> the leapfrog version doesn't magically fix things because it still messes up the joint distribution p(x,v), and that there are real scenarios where both leapfrog and vv synchronizations are called for.

Hmmm, that doesn't match my recollection of what was said in the discussion.  Here's what I recall as being the relevant points:

- There are a *few* purposes (but not many) for which the half step velocities are useful, such as monitoring equilibration and identifying signs of instability.
- No one was able to suggest any purposes at all for which the on step velocities are useful.  Ben's comment was that you really shouldn't think of them as being velocities at all.  They're just an internal parameter of the algorithm that only poorly approximates the physical velocities.
- I said that if I were doing an analysis that required velocities, I would ignore the "velocity" parameter and instead compute them from the positions using a five point stencil.  Ben agreed that was a good approach.

**Comment by peastman** [comment]
Are you ok with the plan above?  That is, we'll initially include only the leapfrog version as a built in integrator.  Once a consensus emerges about best practices, if people decide there are compelling advantages to the velocity verlet version then we can add it as well.

**Comment by jchodera** [comment]
> No one was able to suggest any purposes at all for which the on step velocities are useful. Ben's comment was that you really shouldn't think of them as being velocities at all. They're just an internal parameter of the algorithm that only poorly approximates the physical velocities.

The on-step velocities are used for (1) application of the Andersen thermostat (something we incorrectly do with `AndersenThermostat` right now), (2) [transition path/interface sampling](https://aip.scitation.org/doi/abs/10.1063/1.475562) methods (such as `openpathsampling`, built on OpenMM) where trajectories are initiated forward and backward or must be initiated with perturbed velocities via shooting steps, (3) [hybrid Monte Carlo](https://www.sciencedirect.com/science/article/abs/pii/037026938791197X) or Metropolized Langevin methods, where the on-step velocities are required to compute the acceptance probability, and a variety of other applications. I _thought_ we mentioned all three on the call. These methods require the velocities synchronized with the positions, and are used directly in these algorithms---even though they do not represent physical properties and merely intermediate variables.

> I said that if I were doing an analysis that required velocities, I would ignore the "velocity" parameter and instead compute them from the positions using a five point stencil. Ben agreed that was a good approach.

I really like the idea of adding a method to compute the true physical velocity from a stencil, but I'm still not sure if the correlated phase space distribution you get this would be an accurate representation of the joint (position, velocity) distribution you intended to sample.

> Are you ok with the plan above? That is, we'll initially include only the leapfrog version as a built in integrator. Once a consensus emerges about best practices, if people decide there are compelling advantages to the velocity verlet version then we can add it as well.

Let's at least get it in there in _any_ form. 

I do think that there is likely more we can do to educate users to properly use on-step vs off-step vs stencil-estimates of velocities at the right times, and would love to see us support all of these via convenient API calls so that users must _consciously_ make a choice about the correct one to use.

**Comment by peastman** [comment]
> (1) application of the Andersen thermostat

Why would someone combine an Andersen thermostat with this integrator?  It already has a thermostat built in.  I can't imagine a situation where you'd want to apply both thermostats at once.

> (3) hybrid Monte Carlo or Metropolized Langevin methods

This integrator doesn't do either of those.  I know you have HMC and metropolized integrators in openmmtools, but those are their own integrators.

> I do think that there is likely more we can do to educate users

Fair enough!  Additions to the documentation are welcome.

Anyway, unless someone objects I'm going to go ahead and merge #2561.

**Comment by jchodera** [comment]
> Why would someone combine an Andersen thermostat with this integrator? It already has a thermostat built in. I can't imagine a situation where you'd want to apply both thermostats at once.

Someone may want to use Andersen + the Verlet integrator. Currently, that's done incorrectly in OpenMM since we only support leapfrog.

Langevin integrators gently raise the temperature from 0K. To correctly reinitialize the velocities to be appropriate for a given temperature, we must redraw the velocities from Maxwell-Boltzmann. If this is a leapfrog integrator, we also need to back up a half-kick using the current forces. 

Similarly, if we implement parallel tempering, most algorithms rescale the velocities when a swap of two temperatures is accepted. To do this with a leapfrog integrator, we would need to use a half-kick to get the on-timestep velocities, rescale them, and then do a half-kick back. This is complicated.

> This integrator doesn't do either of those. I know you have HMC and metropolized integrators in openmmtools, but those are their own integrators.

Right, but if someone tried to construct an HMC or Metropolized Langevin integrator out of VerletIntegrator or LangevinIntegrator, they would not be able to do so correctly easily without managing their own half-kicks. 

Recall that this was in all in answer to your mis-recollection that "No one was able to suggest any purposes at all for which the on step velocities are useful."

> Fair enough! Additions to the documentation are welcome.

Let's create an issue assigned to the 7.5 release to make sure we don't cut the release before one of us expands the documentation.

**Comment by peastman** [comment]
> Someone may want to use Andersen + the Verlet integrator.

I said this before, but let me repeat it: I'm *only* talking about this particular integrator!  This isn't meant to be any sort of general argument against velocity verlet integrators.  There could definitely be situations where an energy conserving symmetric integrator would be useful.  This discussion is just about the VRORV and VVROR discretizations of the Langevin integrator.

> Recall that this was in all in answer to your mis-recollection that "No one was able to suggest any purposes at all for which the on step velocities are useful."

For this particular integrator!  VRORV produces "velocities" that are a very poor approximation to the thermal distribution for constant temperature dynamics.  VRV produces "velocities" that are a pretty good approximation to constant energy dynamics.  That's why the latter are useful and the former aren't.

By the way, if you want to use an Andersen thermostat, that should really be done using the "middle" scheme as well.  Putting the thermostat between steps of a VRV integrator is much less accurate than putting it in the middle of the position update.

**Comment by jchodera** [comment]
>  This discussion is just about the VRORV and VVROR discretizations of the Langevin integrator.

I was under the impression we were talking more broadly about which discretizations we are using for VerletIntegrator and LangevinIntegrator, the two primary integrators that users encounter when they use OpenMM>

> By the way, if you want to use an Andersen thermostat, that should really be done using the "middle" scheme as well. Putting the thermostat between steps of a VRV integrator is much less accurate than putting it in the middle of the position update.

Didn't we prove this leads to the incorrect distribution here?
https://github.com/openmm/openmm/pull/2518#issuecomment-574856560

**Comment by peastman** [comment]
> I was under the impression we were talking more broadly about which discretizations we are using for VerletIntegrator and LangevinIntegrator

Perhaps you are, but I'm not! :)

> Didn't we prove this leads to the incorrect distribution here?

That was based on doing the randomization at the end of the position update, not in the middle of it.
