### ISSUE TITLE
How to tell OpenMM which linker to use and/or to set RPATH ?

### ISSUE THREAD

**Issue by mboisson** [openmm/openmm#2552]
Hi,
We have OpenMM installed on a system on which we *do not* use LD_LIBRARY_PATH. Our linker is configured to automatically add RUNPATH to all compiled binaries so that the shared objects are resolved this way. This, however, does not seem to work with OpenMM. I get : 

```
$ python3 -m simtk.testInstallation
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform

CUDA platform error: Error compiling program: nvrtc: error: failed to open libnvrtc-builtins.so.
  Make sure that libnvrtc-builtins.so is installed correctly.

Median difference in forces between platforms:

Reference vs. CPU: 2.00232e-06
``` 

I can however make it work with `LD_LIBRARY_PATH`, but `LD_LIBRARY_PATH` is bad and we don't use it : http://xahlee.info/UnixResource_dir/_/ldpath.html

``` 
$ LD_LIBRARY_PATH=$EBROOTCUDA/lib64:$LD_LIBRARY_PATH python3 -m simtk.testInstallation
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 2.00401e-06
Reference vs. CUDA: 2.15363e-05
CPU vs. CUDA: 2.13819e-05
```

**Comment by mboisson** [comment]
And, our compiler is very much able to find `libnvrtc`, it's just that for whatever reason, the RPATH does not get set. Here is a strace showing that it can find it : 
```
[mboisson@helk20n01 ~]$ strace -f -e trace=file python3 -m simtk.testInstallation |& grep 'nvrtc'
open("/opt/software/slurm/lib64/libnvrtc.so.10.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/cudacore/10.1.243/targets/x86_64-linux/lib/libnvrtc.so.10.1", O_RDONLY|O_CLOEXEC) = 3
[pid 142346] open("/opt/software/slurm/lib64/libnvrtc-builtins.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 142346] open("/cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libnvrtc-builtins.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 142346] open("/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libnvrtc-builtins.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 142346] open("/usr/lib64/nvidia/libnvrtc-builtins.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
CUDA platform error: Error compiling program: nvrtc: error: failed to open libnvrtc-builtins.so.
  Make sure that libnvrtc-builtins.so is installed correctly.
```

**Comment by peastman** [comment]
That seems to be a problem internal to the nvrtc compiler.  OpenMM just links to libnvrtc.so.  It looks like that library in turn tries to dynamically load libnvrtc-builtins.so.  I don't know how they define their search path.  I found this thread discussing the same error in another code: https://github.com/yusuketomoto/chainer-fast-neuralstyle/issues/107.  They managed to solve it, though their solution involved things that really shouldn't be necessary.

Instead of using the CUDA runtime compiler, it's possible to instead have OpenMM write out kernels to temporary files and compile them with nvcc.  Try setting `OPENMM_CUDA_COMPILER` to point to nvcc.  Does that fix the problem?

**Comment by mboisson** [comment]
ah, this seems to work!
```
$ OPENMM_CUDA_COMPILER=$(which nvcc) python -m simtk.testInstallation
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 2.00762e-06
Reference vs. CUDA: 2.15452e-05
CPU vs. CUDA: 2.13679e-05
``` 

Why is it not the default ? Does it have drawbacks ?

**Comment by peastman** [comment]
It tries the default location `/usr/local/cuda/bin/nvcc`, but since you have CUDA installed somewhere else, it didn't find it.  So instead it tried to use the runtime compiler.

By the way, it looks to me like you're using an older version of OpenMM?  The output of `testInstallation` is a bit different in the current release.

**Comment by mboisson** [comment]
Ah, I see, so it does not look in the PATH to find it. 
Yes, this is version 7.1.1. I was reinstalling a known version on our clusters.

**Comment by mboisson** [comment]
With this workaround, this issue can be closed, although I would suggest that OpenMM tries to find executables in the PATH instead of hard-coding default locations. But that's a design decision I guess.

**Comment by peastman** [comment]
Thanks!
