### ISSUE TITLE
Inconsistent energies from energy minimization on Mac OSX (OpenCL + single precision)

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#2573]
I ran energy minimization on the same complex 10 times and am seeing very different energies across iterations. I am using Mac OSX (with OpenCL and single precision). When I run the same code on linux (with OpenCL single or mixed precision), I am seeing the same energy across iterations (with different degrees of precision depending on which precision I used).

Note: The code provided is part of an MM/GBSA script.

[example.zip](https://github.com/openmm/openmm/files/4246879/example.zip)

**Comment by peastman** [comment]
The local energy minimizer tries to find a local energy minimum.  It doesn't guarantee which one it will find, or that it will find the same minimum every time.  As far as it is concerned, any local minimum is as good as any other.

Whether it actually does find the same minimum every time depends on a variety of factors: how rough the energy landscape is, what precision you're using, whether your GPU supports 64 bit atomic operations (since it accumulates forces differently depending on that), how your GPU schedules threads, etc.

**Comment by zhang-ivy** [comment]
Thanks for the explanation. To investigate whether the variations in minimized energies across iterations can be explained by non-deterministic computation of forces (possibly due to differences in GPU scheduling of threads), I set `DeterministicForces` to `true` (using CUDA) and ran 10 iterations on the same protonated structure above. I hypothesized that I would see smaller variation in the minimized energies across iterations. However, I don't see any difference in variation compared to when I run with `DeterministicForces` to `false`. Additionally, the initial energies (before minimization) seem to vary across iterations. What does setting `DeterministicForces` do under the hood? Are the results I am seeing consistent with your expectations?
[energies.zip](https://github.com/openmm/openmm/files/4252295/energies.zip)

**Comment by peastman** [comment]
Those numbers are essentially identical.  There can be a little bit of nondeterminism in summing the contributions to energy, but it's only affecting the last few bits.  All the numbers agree to 15 decimal places.

**Comment by maxentile** [comment]
I've previously assumed that setting `DeterministicForces` to `true` would prevent any nondeterministic energy-term-summing behavior. In this case it appears deterministic up to the last couple bits -- and I don't think a little non-determinism in the last couple bits would affect almost anything in practice -- but any variation at all deviates from what I (maybe mistakenly) expected would happen here.

Out of curiosity: is there another platform property that can be set to guarantee the energies and forces are fully deterministic on the CUDA platform, even if it incurs a performance hit?

**Comment by jchodera** [comment]
Agreed---it would be useful to have `DeterministicForces = true` actually give deterministic forces.

**Comment by peastman** [comment]
`DeterministicForces` only guarantees deterministic forces, not deterministic energies.  That's because force accumulation is done in fixed point, which is unaffected by the order you add values in, but energy accumulation is done in floating point, which is affected by it.

**Comment by jchodera** [comment]
Oh, I had no idea! 

Deterministic energies are really important for reweighting techniques to not give garbage as output---should we open a new feature request for a `DeterministicEnergies` option?

**Comment by jchodera** [comment]
I'll note that, since we only compute energies infrequently, we can definitely tolerate performance hits to achieve deterministic energies.

**Comment by peastman** [comment]
Since you're getting energies that are deterministic to 15 significant digits, how about just taking the energies it gives you and truncating them to, say, 13 significant digits?  The result will probably still be more accurate than what you would get if we did the accumulation in fixed point (which effectively just means throwing out all digits beyond some fixed level of precision).

You really want floating point for energies, because they have so much more dynamic range.  Energy, unlike force, scales with the size of the system.  It's rare to find a force bigger than about 10,000, but energies over 1 million are common.  Yet a difference of 1 between two energies can easily be significant.

**Comment by jchodera** [comment]
> Since you're getting energies that are deterministic to 15 significant digits, how about just taking the energies it gives you and truncating them to, say, 13 significant digits? The result will probably still be more accurate than what you would get if we did the accumulation in fixed point (which effectively just means throwing out all digits beyond some fixed level of precision).

Could `DeterministicEnergies` do this under the hood?

**Comment by peastman** [comment]
I'd hesitate to do that.  The amount of variation in the energies will depend on your GPU, your precision mode, whether you're using `DeterministicForces`, the size of your system, and the particular forces it contains.  For a given system on a given GPU, it's easy to compute the energy a few times and see how much they vary.  But it would be very hard to accurately predict that in advance.

**Comment by maxentile** [comment]
If the number of non-deterministic bits is hard to estimate or bound, that sounds like a possibly important argument for having a "deterministic mode" for energies.

Are the main options available for returning a deterministic energy sum on the CUDA platform: (1) truncating all of the likely-to-be-non-deterministic bits from the accumulated result, or (2) switching the accumulator from floating-point to equal-width fixed-point? Neither of those sound like great options.

For example, is there a design constraint that rules out picking the summation order deterministically based on, say, the number of threads, blocks... available for a given GPU?

**Comment by peastman** [comment]
Those are pretty much the options.  Working in fixed point basically means you truncate every individual contribution to the energy, and every one of them has to be truncated at exactly the same point.  The error from doing that scales as sqrt(N), where N is the number of terms you're adding.  With forces, doing that isn't too bad because there are rarely more than a few hundred contributions to the force on any atom.  But energy can be the sum of many millions of individual contributions.

**Comment by maxentile** [comment]
I agree that accumulating energies in fixed-point would not be a good idea.

Sorry if this is a basic question, but why can't the energy summation order be made deterministic?

(I had mistakenly imagined that was what was already happening under the hood in deterministic mode -- using numerically non-associative floating-point accumulators, but doing the accumulation in a deterministic order. For example, the [parallel sum reduction in CUB](https://nvlabs.github.io/cub/structcub_1_1_device_reduce.html) "Provides "run-to-run" determinism for pseudo-associative reduction (e.g., addition of floating point types) on the same GPU device. However, results for pseudo-associative reduction may be inconsistent from one device to a another device of a different compute-capability because CUB can employ different tile-sizing for different architectures.")

**Comment by peastman** [comment]
Actually, the only thing `DeterministicForces` does is to switch PME charge spreading to be done in fixed point rather than floating point.  Everything else in force computation is already deterministic, since we accumulate them in fixed point.  But that was really just an accident.  The main reason for using fixed point force accumulation is that it lets us use atomic operations, which is much faster than how we had to do it before (and how the OpenCL platform still does it on low end GPUs that don't support 64 bit atomics).

When running on a massively parallel architecture like a GPU (or even a mildly parallel one like a CPU), nondeterministic ordering is your friend!  You don't want synchronization between threads, because that's expensive.  You also don't want a fixed division of work between threads, because some threads finish before others and you get poor parallel efficiency.  So instead you create a single queue of all the work that needs to be done, and then threads grab tasks off it as they finish their previous tasks.  This gives much better performance, but it means you don't know in advance which thread will execute a particular task, or what order tasks will be completed in.

**Comment by maxentile** [comment]
Thank you for clarifying. I appreciate that introducing thread syncs to fix a deterministic order can only reduce parallel efficiency, and the [platform documentation does warn](http://docs.openmm.org/7.4.0/userguide/library.html#cuda-platform) to expect slower performance when deterministic behavior is requested.
