### ISSUE TITLE
Reduce radius of dummy atoms

### ISSUE THREAD

**Issue by MDcanSomehowBeFrustrating** [openmm/openmm#2606]
Hey everyone :)

How do I reduce the radius of dummy atoms? Clashes cause my system to blow up. Any ideas?

Thx

**Comment by peastman** [comment]
What dummy atoms are you referring to, and how are they created/defined?

**Comment by MDcanSomehowBeFrustrating** [comment]
Dummy atoms are used for Zn2+. Defined -> see below
![GitHub](https://user-images.githubusercontent.com/62425837/77337116-bfab1080-6d28-11ea-83fc-30f808208972.PNG)

**Comment by peastman** [comment]
Your problem isn't that the radius is too small.  They don't have any LJ term on them at all:

```xml
<Atom epsilon="0.0" sigma="1.0" class="D"/>
```

Epsilon is 0.  Presumably the LJ repulsion on the Zn atom is supposed to keep anything from coming too close to them?  But you don't have any kind of bonded force (like a HarmonicBondForce) to make the dummy atoms stay close, so they're free to drift away.

**Comment by MDcanSomehowBeFrustrating** [comment]
![GitHub2](https://user-images.githubusercontent.com/62425837/77340558-c425f800-6d2d-11ea-9367-d7098e145b58.PNG)
I implemented the HarmonicBondForces as well as the angles. But the system keeps blowing up :(

The Energy in my system before the minimizatio is 404544 kJ/mol, is this too much?

**Comment by peastman** [comment]
You need to identify exactly why it's blowing up.  Can you tell exactly what interactions are causing it to happen?  For example, is there a particular nonbonded pair that's producing a very large force?  Then figure out why that force is so large.  Are two atoms closer than you expect them to be?  If so, how did they manage to get so close?

I notice some inconsistencies in your XML file.  The `<Residue>` tag lists four bonds: each of the dummy atoms is bonded to the Zn, but the dummy atoms aren't bonded to each other.  That seems reasonable, since you can then use bonds and angles to maintain the tetrahedral geometry.  On the other hand, the `<HarmonicBondForce>` and `<HarmonicAngleForce>` tags list parameters for Dy-Dy bonds and Dy-Dy-Dy angles, as if you were expecting them to be bonded to each other.  Which behavior did you intend?

**Comment by MDcanSomehowBeFrustrating** [comment]
You definitely got a point with this. I removed the HarmonicBondForces and Angles as I intend a tetrahedral dummy set-up around the Zn.

I also tried:
```python
forces = system.context.getState(getForces=True).getForces()
for i, f in enumerate(forces):
  if norm(f) > 1e4*kilojoules_per_mole/nanometer:
    print(i, f)
```
The radius of the dummy atoms seems to big, which might causes the system to blow up. I should be able to reduce the radius right?

![GitHub3](https://user-images.githubusercontent.com/62425837/77348359-9941a100-6d39-11ea-9f47-bed4f08710ec.PNG)

It doesn't tell me which atom might cause the pr-minimization energy of arounf 400000 kJ/mol

**Comment by peastman** [comment]
> The radius of the dummy atoms seems to big

What do you mean by "the radius"?  Atoms in MD simulations don't have any intrinsic radius.  They just interact with each other according to various functions.  Since you've set epsilon to 0 for them, they have no Lennard-Jones interactions.  That means their only nonbonded interaction is Coulomb, which decreases as 1/r.
