### ISSUE TITLE
Same initial structure gives different result

### ISSUE THREAD

**Issue by lx19930** [openmm/openmm#2641]
I have ran two simulation with that same .rst file and the same .inp file and I am sure that I didn't generate velocity. But the trajectories are different. I am wondering is it the feature of openmm or is it my problem?

**Comment by peastman** [comment]
Did the simulation include a thermostat?  If so, did you set the same random seed for each run?  If not, the random forces will be different and you'll get different results.

Even when using the same seed, the CUDA platform can produce nondeterministic results.  That's because the order in which sets of numbers are added together can vary, leading to tiny differences in the forces.  You can set the property `DeterministicForces` to `true` to instead sum them in a way that is slightly slower but deterministic.  See http://docs.openmm.org/latest/userguide/library.html#cuda-platform.

**Comment by lx19930** [comment]
After using double precision and set DeterministicForces to true the
simulations are more close to each other but still not exactly the same.
But thank you still.
