### ISSUE TITLE
Allow Context.{get|set}State() to save/restore CustomIntegrator variables

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2649]
It would be useful if we could allow `Context.{get|set}State()` to save and restore `CustomIntegrator` variables.

We've recently discovered a use case where suspending/resuming a simulation in the Folding@home core could make use of this feature without requiring we store `CustomIntegrator` parameters outside of the serialized `State`.

The only API extension required would be to add a `getIntegratorParameters=True` optional argument to `Context.getState()` which would also retrieve any integrator parameters.

If present in the `State` object, they would automatically be reset when `Context.setState(state)` is called.

**Comment by jchodera** [comment]
This could be a good feature for 7.5.0, since it would allow us to use `XmlSerializer` instead of checkpoints. This would help us debug any issues we run into with `CustomIntegrator`.

**Comment by jchodera** [comment]
This is going to be critical for moving forward with future Folding@home OpenMM core releases so we can easily diagnose failures. We can't currently bring back binary checkpoints to quickly reproduce issues because these are not portable across platforms.

Could we get this into 7.4.3 or 7.5.0?

**Comment by jchodera** [comment]
@peastman : How much effort would be required to implement this? We're looking into some `CustomIntegrator`s that would allow us to make better use of Folding@home that would require this, and wonder if it could be incorporated into 7.5.0.

**Comment by peastman** [comment]
I'm having trouble figuring out how this could work.  The problem is that integrator variables are completely up to the integrator to define.  We currently have three integrator classes that need to save variables, and there could easily be more in the future:

- CustomIntegrator has both global and per-dof variables, all of which would need to be saved.
- NoseHooverIntegrator needs to save the chain states.
- CompoundIntegrator needs to let each of its component integrators, whatever they happen to be, save their variables.

This wasn't a problem for checkpoints because those are opaque objects.  But State would need to provide a public interface for accessing all of these, and any others that might come along in the future.  I don't have a good design for how to do that.

I did think of a workaround for your particular case though: use context parameters instead of global variables.  Instead of having the integrator define the global variables, have a force define them as global parameters.  The integrator can still access them exactly the same way, and they'll get saved in the State.

**Comment by jchodera** [comment]
The workaround is a good suggestion, but would only work for global variables (and not per-particle variables) that we could define outside of the integrator. There would be no way to persist per-particle parameters.

The real question here is "what would the object model be for accessing any dynamic variables associated with an `Integrator`, especially if it is a container for multiple other `Integrator`s"? The `State` object is supposed to provide a clean way of separating any dynamic variables from the fixed parameters, but that becomes somewhat muddled by `Integrator` objects that can contain their own state.

One alternative would be to create a _portable_ checkpoint scheme, but it would seem to be redundant with just sorting out the object model for the `State` object, which is intended to serve the same purpose.

Another alternative that may be much easier to tackle is to leverage the fact that we already have an `Integrator` serialized XML format, but since this format currently only stores the current default values, provide a way to update the `Integrator` from the `Context` object. For example, we currently support
```python
# get the Integrator, but with all default parameters
integrator = context.getIntegrator()
```
Instead, we could use
```python
# get the Integrator, but with the current values of all parameters
integrator = context.getIntegrator(updateFromContext=True)
```

Relatedly, I've just noticed the API docs for `Context.getIntegrator()` [are broken](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.Context.html#simtk.openmm.openmm.Context):
![image](https://user-images.githubusercontent.com/3656088/86420062-288c1800-bc8a-11ea-88d7-1c27245f44cc.png)

**Comment by peastman** [comment]
This isn't a great option, but State could have a `getIntegratorParameters()` method that just returns a string containing serialized XML.  That's not very useful for anything other than checkpointing, but possibly that's the only real application of this.  If someone wants to programmatically examine the parameters, they can already get them directly from the integrator.

Another option would be to have it return a SerializationNode or some other object providing a structured representation of the parameters.  But I'm not sure who would really benefit from that.  It's much easier to get them from the integrator, so the only case I see where it would be useful is if you wanted to load a state from disk, then examine the parameters it contains before loading the state into a context.  That's a pretty obscure case.

**Comment by jchodera** [comment]
What about the idea of just updating the Integrator default parameters and step from the Context object and then serializing the Integrator the standard way?

**Comment by peastman** [comment]
There's no need to update them, because the integrator is already tied to a context.  If you serialize and reload the integrator, it will already contain the correct values for all parameters.  So I suppose that could be an easy solution for your particular situation: just save both the state and the integrator.  It doesn't solve the more general problem of users who save a state and don't realize important parameters aren't getting restored.

**Comment by jchodera** [comment]
> There's no need to update them, because the integrator is already tied to a context. If you serialize and reload the integrator, it will already contain the correct values for all parameters. So I suppose that could be an easy solution for your particular situation: just save both the state and the integrator.

Just so I'm clear on this, you're saying this should be equivalent to checkpointing and resuming?
```python
# Create an integrator with global and per-particle variables
integrator = MyFancyStatefulIntegrator()
# Create a context with this integrator and set the state
context = openmm.Context(system, integrator)
context.setState(state)
# Take some steps
integrator.step(nsteps)
# Now store the state, including which step we're on and all the global and per-particle integrator variables
state = context.getState(getPositions=True, getVelocities=True, getParameters=True)
# Serialize state
state_xml = openmm.XmlSerializer.serialize(state)
# Serialize integrator, including which step we're on, current value of all per-particle and global variables, pulled from the Context just now?
integrator_xml = openmm.XmlSerializer.serialize(integrator)
# Clean up
del integrator, context
##### RESTART #####
integrator = openmm.XmlSerializer.deserialize(integrator_xml)
state = openmm.XmlSerializer.deserialize(state_xml)
# Pick up from exactly where we left off
context = openmm.Context(system, integrator)
context.setState(state)
integrator.step(...)
```

> It doesn't solve the more general problem of users who save a state and don't realize important parameters aren't getting restored.

Gosh, if the above works, why not cram all the integrator state variables in `State` in some inaccessible way by making a deep copy of `Integrator` when you do
```python
state = context.getState(getIntegrator=True)
```
and then just make sure to properly serialize that out during `XmlSerializer.serialize(state)` and restore the integrator parameters when doing `context.setState(state)` if they are present? 

Allowing the user to manipulate the integrator parameters programmatically via a `State` API is secondary because, as you point out, they can already do that via the `Integrator` API.  If anything, I guess you could have `state.updateIntegrator(integrator)` that would do the setting for you.

Certainly we don't want to have anything return XML that isn't `XmlSerializer` because there could be other serialization formats supported in the future that aren't quite so verbose.

**Comment by peastman** [comment]
> Just so I'm clear on this, you're saying this should be equivalent to checkpointing and resuming?

Yes, I believe so.  Please test it to be sure!

> Gosh, if the above works, why not cram all the integrator state variables in State in some inaccessible way by making a deep copy of Integrator when you do

That's roughly what I suggested above, except I don't think anything should be inaccessible.  It's important to be able to examine a state and see exactly what's in it.

**Comment by jchodera** [comment]
Will test!

I agree re examining the State, but the Integrator already provides the API for doing this. So perhaps just State.{get|set}Integrator() is what we want, where it essentially does what you suggest above but constructs the Integrator for you instead of just returning the serialized form?

**Comment by peastman** [comment]
Generally we wouldn't be constructing the integrator from the state.  The normal use of a state for checkpointing is that you've already created your system/integrator/context, then you call `setState()` to restore all the mutable information.  That's why I suggested the design I did.  Conversely, we can't have a `setIntegrator()` method.  The integrator is specified when you create the context and you can't change it after that.  Allowing it to be changed would be very complicated.

**Comment by jchodera** [comment]
I think we want to keep the XML-specific serialization encapsulated wholly within the `XmlSerializer` API so that, in future, we can support other serialization formats. That's why I really don't like the idea of a `State` object being able to return or consume XML.

I think there may have been some misunderstanding of the concrete suggestion. 

Here's an updated version of the example above
```python
# Create an integrator with global and per-particle variables
integrator = MyFancyStatefulIntegrator()
# Create a context with this integrator and set the state
context = openmm.Context(system, integrator)
context.setState(state)
# Take some steps
integrator.step(nsteps)
# Now store the state, including the integrator state
state = context.getState(getPositions=True, getVelocities=True, getParameters=True, getIntegrator=True)
# If I wanted to inspect the integrator state, I could retrieve it
integrator2 = state.getIntegrator()
# Or I could change it
integrator2.setGlobalVariableByName('work', 0.0)
state.setIntegrator(integrator2)
# I can also serialize it, which also serializes the integrator state by serializing the integrator within the state
state_xml = openmm.XmlSerializer.serialize(state)
# Clean up
del integrator, context
##### RESTART #####
# Now I restart from a previously serialized integrator with default values
integrator = openmm.XmlSerializer.deserialize(integrator_xml)
state = openmm.XmlSerializer.deserialize(state_xml)
# This initializes the context with default integrator values
context = openmm.Context(system, integrator)
# This step will now update the integrator state (assuming the integrator is compatible)
# since the integrator is already present; if the integrator is not the same, we'd get an exception
context.setState(state)
# Now continue dynamics
integrator.step(...)
```

- [x] Allows `state.xml` to persist integrator state without changing existing workflows except to add `getIntegrator=True`
- [x] Doesn't allow the kind of integrator to be changed after `Context` creation, but simply provides a convenient way to update all integrator variables from the copy in the `State`
- [x] Provides a programmatic way to get/set the `Integrator` info stored in the `State` by leveraging the existing `Integrator` APIs
- [x] Minimizes the number of new methods added to the public API

**Comment by jchodera** [comment]
> Yes, I believe so. Please test it to be sure!

I can confirm that the example in https://github.com/openmm/openmm/issues/2649#issuecomment-653701631 works! I'll integrate this into the checkpointing mechanism for the FAH core for now.

**Comment by jchodera** [comment]
I had forgotten that `State` is immutable and [provides no `set`er methods in the API](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.State.html#simtk.openmm.openmm.State), so to summarize my proposal:
* Extend `Context.getState()` to accommodate a `getIntegrator=True` optional argument that would essentially call `Context.getIntegrator()` and store a serialized (frozen) copy
* Extend the behavior of `State.setState()` so that, if a serialized `Integrator` is present, it will also (1) check that the integrator is the "same" (perhaps by making sure all global and per-DOF parameters match in name and order), (2) update all the integrator global and per-DOF parameters of the existing `Context` integrator, and (3) throw an exception if an issue is encountered. This should work for compound integrators too, where the current integrator will be set to match the serialized integrator stored in `State`.
* Add a `State.getIntegrator()` which will deserialize the stored integrator if present, or throw an exception if not.
* Ensure that serializing/deserializing `State` handles the stored serialized `Integrator`.

Does that sound reasonable? It doesn't add much, but will ensure that `Context.{get|set}State()` will be able to persist integrator parameters if desired, while still providing a way to access the integrator stored in the `State` via the `Integrator` APIs that already exist.

**Comment by peastman** [comment]
My proposal is even simpler.  It only adds two new elements: another option in `getState()`, and a `getIntegratorParameters()` method.  Users would rarely have reason to even call the latter.  It's there mainly for completeness, and because it's sometimes useful to inspect the contents of a State for debugging purposes.  In practice, people would just call `getState()` to create a snapshot and `setState()` to restore it.

I prefer this because it's conceptually cleaner and stays closer to the current design.  A State is supposed to be a snapshot of mutable information.  It doesn't include immutable information that's stored elsewhere.  For example, it includes the values of parameters defined by Forces, but it doesn't record the immutable definitions of those Forces themselves.  They're part of the System, not the State.  Likewise, I would have it store the values of mutable parameters defined by the Integrator, but not the immutable definition of the Integrator itself.

If you change that, it creates difficult questions and leads to user confusion.  Suppose your State includes a full representation of the Integrator, and then you call `setState()` on a Context that has a different Integrator (say, another CustomIntegrator with identical parameters but a different series of steps).  What should happen?  Should it throw an exception, because it's impossible to make the Integrator identical to the one in the State?  Or should it actually modify the Integrator to be identical to what's in the State?  Most users would expect it to do one or the other, but it isn't obvious which.  In fact, it does neither one.  It modifies only the parameters, and doesn't care that the Integrators are different.

If, on the other hand, the State contains only integrator parameters, not the Integrator itself, then the behavior is obvious.  Calling `setState()` will modify only parameters.  It won't (and can't) modify the Integrator itself, because it doesn't store any information about that.  The requirements for a State to be compatible with an Integrator are likewise obvious.  The set of parameters needs to be identical, but it doesn't matter what sequence of operations the Integrator performs.

**Comment by jchodera** [comment]
How would getIntegratorParameters() work? You'd have to engineer an API that would allow access to both custom integrators and compound integrators. We already have an API for this through the existing integrator APIs. Why create another?

> Suppose your State includes a full representation of the Integrator, and then you call setState() on a Context that has a different Integrator (say, another CustomIntegrator with identical parameters but a different series of steps). What should happen? 

Exactly the same thing that happens when you try to set the positions or velocities using an array of the wrong size: if the object you are trying to set doesn't match, you get an exception. This behavior is the same for any mismatch of information stored in State, such as AndersenThermostat parameters.

Having a mutable Integrator and immutable IntegratorParameters sounds perfectly reasonable, but I'm worried that the flexibility of integrators will make it difficult to keep these in sync. Similarly, XML is not a useful thing to return for things that aren't XmlSerializer.

**Comment by peastman** [comment]
> You'd have to engineer an API that would allow access to both custom integrators and compound integrators.

That's true either way.  There's no existing API that can take two integrators of unknown type and copy all information from one to the other.

> Exactly the same thing that happens when you try to set the positions or velocities using an array of the wrong size: if the object you are trying to set doesn't match, you get an exception.

What does it mean to "not match"?  Assume the two integrators define identical parameters but different sequences of calculations.  Do those match, since all the mutable state is identical?  Or not match because the immutable state is different?  What would you expect the behavior of `setState()` to be in that case?  Copy over all information stored in the State, including the definition of the Integrator itself?  Or throw an exception because some aspects are different?

Then of course there are other aspects of the integrator that don't change automatically during a simulation but can be changed manually, like the step size and constraint tolerance.  Should `setState()` copy those as well?  Suppose you do an initial equilibration with a small step size, save the state at the end, then load it at the start of the main simulation which uses a larger step size.  Will loading the state cause it to switch back to the smaller step size you used for equilibration?

**Comment by jchodera** [comment]
> That's true either way. There's no existing API that can take two integrators of unknown type and copy all information from one to the other.

As I understand it, the public Integrator APIs can be used to check if the integrator(s) are of the same class (and, if `CompoundIntegrator`, the component integrators are of the same class), as well as inspect whether all parameters and integrator steps for `CustomIntegrator` are identical. While there's no convenient API to compare integrators, performing this check does not seem to require extending the APIs.

> What does it mean to "not match"? Assume the two integrators define identical parameters but different sequences of calculations. Do those match, since all the mutable state is identical? Or not match because the immutable state is different?

If the sequence of calculations is different, the parameters would not have the same behavior in the new integrator, and it would not make sense to update their state during `Context.setState()`. This doesn't seem to be conceptually difficult, but perhaps I'm coming at this from a different perspective where `Context.setState()` is primarily used to restore a state that was previously stored?

> Then of course there are other aspects of the integrator that don't change automatically during a simulation but can be changed manually, like the step size and constraint tolerance. Should setState() copy those as well? 

Yes, since the primary use of `setState()` is to restore mutable state retrieved via `getState()` that may have been changed at some point (manually or automatically) during a simulation.

>Suppose you do an initial equilibration with a small step size, save the state at the end, then load it at the start of the main simulation which uses a larger step size. Will loading the state cause it to switch back to the smaller step size you used for equilibration?

If the `State` was retrieved via `Context.getState(getIntegrator=True)`, it would seem reasonable that the desire was to restore all mutable aspects of the the integrator state during `Context.setState()`. This is because the other behavior doesn't make any sense: The user would be expecting the API to "guess" what they wanted restored and what they didn't want restored, which would seem to violate the rule of "do the least surprising thing" for API design.

**Comment by peastman** [comment]
> as well as inspect whether all parameters and integrator steps for CustomIntegrator are identical.

That's exactly what doesn't currently exist.  There doesn't exist any routine for taking two integrators of arbitrary type and comparing every element of their definitions.  We could write such a routine for CustomIntegrator.  And another for NoseHooverIntegrator.  And another for CompoundIntegrator.  But currently it doesn't exist.

So one way or another we're going to have to write some new code for each integrator class.  That's true with either design.

> If the sequence of calculations is different, the parameters would not have the same behavior in the new integrator, and it would not make sense to update their state during Context.setState().

That assumption isn't well justified.  There are lots of situations where two integrators would have slight differences, but define identical sets of parameters with identical meanings.  The most common situations are when you're using one integrator for equilibration and a slightly different one for production.  This is directly analogous to the current situation where we allow you to load a state even if immutable aspects of the System were different.  We require only that the number of particles and the set of context parameters is the same.  We don't tell the user, "You aren't allowed to load this state because you had restraint forces during equilibration, and they aren't present now."

Likewise, you might use one integrator during equilibration and a different one during production.  As long as those integrators define identical parameters, we shouldn't prevent that.

**Comment by peastman** [comment]
Are you ok with the design described above?  I'd like to start working on this.

**Comment by jchodera** [comment]
> Are you ok with the design described above? I'd like to start working on this.

Do you mean [this design](https://github.com/openmm/openmm/issues/2649#issuecomment-654361921)? I don't think you described what `getIntegratorParameters()` would return or how we would set the integrator parameters in a context.

> That's exactly what doesn't currently exist. There doesn't exist any routine for taking two integrators of arbitrary type and comparing every element of their definitions. We could write such a routine for CustomIntegrator. And another for NoseHooverIntegrator. And another for CompoundIntegrator. But currently it doesn't exist.

These could be implemented in C++ and simply use the public API. While you're correct that we would need to implement something like an `updateFromIntegrator(other_integrator)` method for any integrator with special parameters, this would seem (1) useful, and (2) required for only a small number of integrators, and (3) a simple and clear use of the existing public APIs to do this.

> That assumption isn't well justified. There are lots of situations where two integrators would have slight differences, but define identical sets of parameters with identical meanings. The most common situations are when you're using one integrator for equilibration and a slightly different one for production. This is directly analogous to the current situation where we allow you to load a state even if immutable aspects of the System were different. We require only that the number of particles and the set of context parameters is the same. We don't tell the user, "You aren't allowed to load this state because you had restraint forces during equilibration, and they aren't present now."

We already do that. For example, if you equilibrate your system with an `AndersenThermostat`, serialize the `State` (I think this may require `getParameters=True`?), and then try to reload it with a `System` that omits the `AndersenThermostat` so you can run with `LangevinIntegrator`, an exception will be thrown.

I'm in agreement with you that it seems fine to allow just the parameter names to match.

**Comment by peastman** [comment]
> I don't think you described what getIntegratorParameters() would return

Here's what I said above:

> This isn't a great option, but State could have a getIntegratorParameters() method that just returns a string containing serialized XML. That's not very useful for anything other than checkpointing, but possibly that's the only real application of this. If someone wants to programmatically examine the parameters, they can already get them directly from the integrator.

> or how we would set the integrator parameters in a context.

Exactly the same way we always have: by calling methods on the integrator like `setPerDofVariable()`.

**Comment by jchodera** [comment]
We should not be returning anything that has an XML-specific serialization outside of XmlSerializer. We may have a JSONSerializer or BSONSerializer in the future and this API would have to be forcibly deprecated because it doesn't make any sense anymore.

> Exactly the same way we always have: by calling methods on the integrator like setPerDofVariable().

How would that even work? By parsing an XML string and then calling `setPerDofVariable()` and `setGlobalVariable()`? 

Is there another way to do this without returning a specific serialization of an object model? That's antithetical to the notion of having an object model in the first place.

**Comment by peastman** [comment]
> We may have a JSONSerializer or BSONSerializer in the future and this API would have to be forcibly deprecated because it doesn't make any sense anymore.

That wouldn't make any difference.  As I described above, the serialization format it uses is purely an internal implementation detail.  We could even skip having the `getIntegratorParameters()` method altogether, except I think it's useful for debugging.  Really the point is just that you can save a state and reload it, and the integrator parameters get restored properly.

> How would that even work? By parsing an XML string and then calling setPerDofVariable() and setGlobalVariable()?

Exactly.  But again this is purely an internal implementation detail.  It's up to the integrator to decide what data to store in the state.  Users wouldn't interact with it directly.  I also suggested the possibility of [having it store a SerializationNode](https://github.com/openmm/openmm/issues/2649#issuecomment-653643126) instead of the serialized representation, but that would complicate some things and I don't think there's really any benefit.  Better to keep all the logic in the integrator rather than splitting it between the integrator and the state.

**Comment by jchodera** [comment]
So...why make this part of the public API at all if it's intended to be part of the private API?

I'm just confused here because I was under the impression we were solely discussing how we would extend the public API to allow the integrator state to be captured as part of the `State` object so that `Context.{get|set}State()` would also be able to store and restore the integrator state. Methods that are part of the private API because they are implementation details should in general be kept private. 

I like the idea of making it possible to inspect the XML for debugging purposes, but I don't see any benefit in that beyond just getting the entire XML serialized state and inspecting that.

**Comment by peastman** [comment]
If you really object to having the `getIntegratorParameters()` method, I'm ok with leaving it out.

**Comment by jchodera** [comment]
OK---sounds like this is a path forward, then!
