### ISSUE TITLE
Cannot specify local python package?

### ISSUE THREAD

**Issue by jvermaas** [openmm/openmm#2652]
I've been tasked with testing if OpenMM can run on our local supercomputer, and I'm running into the issue that `make PythonInstall` assumes the user has root, and will try putting it into places it cannot write to.

> error: could not create '/sw/summit/python/3.6/anaconda3/5.3.0/lib/python3.6/site-packages/simtk': Permission denied

Normally, I'd get around this in a traditional `setup.py` style installation by specifying `--local`, which would put this into a directory in the users home directory, avoiding permission issues. There does not seem to be a way of specifying this through the `cmake` system used to build new versions of OpenMM from source. How is this supposed to be done? The old solution from [a previous issue](https://github.com/openmm/openmm/issues/1428) is no longer applicable.

**Comment by peastman** [comment]
`make PythonInstall` is really just a shortcut for setting a couple of environment variables and then running setup.py.  After you `make install`, cd to the `python` subdirectory inside your build directory and execute these:

```
export OPENMM_INCLUDE_PATH=/usr/local/openmm/include
export OPENMM_LIB_PATH=/usr/local/openmm/lib
python setup.py build
python setup.py install
```

where you should substitute the correct locations for where you have OpenMM installed.

Another option is that, instead of using the system Python, you can use a Python you've installed in your home directory.

**Comment by jvermaas** [comment]
Thanks you kindly! That part was obfuscated enough that I didn't figure that out. Now it works!
