### ISSUE TITLE
No module named '_openmm' Python3.7 Google Colab 

### ISSUE THREAD

**Issue by claudiaqw** [openmm/openmm#2660]
I am having trouble with **openmm**, it throws the following exception:

> File "/usr/local/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 20, in swig_import_helper
>     import _openmm
> ModuleNotFoundError: No module named '_openmm'

I am running this in a Google Colab Notebook. Here's my local environment

```
%%capture
%tensorflow_version 1.x
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local
!conda install -y -c deepchem -c rdkit -c conda-forge -c omnia deepchem-gpu=2.3.0
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')
```

After invoking a deepchem library function I got the main error

>  File "/usr/local/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 20, in swig_import_helper
>     import _openmm
> ModuleNotFoundError: No module named '_openmm'

After that I followed this instructions [http://docs.openmm.org/latest/userguide/application.html#installing-openmm](http://docs.openmm.org/latest/userguide/application.html#installing-openmm) I do this:
`!conda install -c omnia -c conda-forge openmm` like it is 

I got this:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

When I run   

```
import simtk.testInstallation
simtk.testInstallation.main()
```
 I still get this error:

> Failed to import OpenMM packages; OpenMM will not work.
> Make sure OpenMM is installed and the library path is set correctly.
> 
> Error message: No module named '_openmm'
> An exception has occurred, use %tb to see the full traceback.
> 
> SystemExit: 1

**Comment by jchodera** [comment]
I think the installation of conda packages is still pretty tricky, since you're essentially trying to overwrite the already-installed-and-running Python with miniconda python.

The error indicates that this wasn't completed correctly.

Here was my last attempt at this (no guarantees, but may be useful for inspiration!):
https://colab.research.google.com/drive/1plcW4ublYMHpR3NFyXjKPJBJlueYrbFC

**Comment by jchodera** [comment]
[This thread](https://stackoverflow.com/questions/59330876/install-conda-package-to-google-colab) may also be helpful!

**Comment by peastman** [comment]
Take a look at https://github.com/deepchem/deepchem/blob/master/examples/tutorials/01_The_Basic_Tools_of_the_Deep_Life_Sciences.ipynb.  It's an example notebook that installs and runs DeepChem (and therefore OpenMM) in colab.

**Comment by Anthoni-Alcaraz** [comment]
Hi,

I run something like this:

`!wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh`
`!bash Anaconda3-2020.02-Linux-x86_64.sh -b -f -p /usr/local/`
`!conda install -c omnia -c conda-forge openmm
!python -m simtk.testInstallation
!conda config --add channels omnia --add channels conda-forge
!conda install openmmtools`
`from google.colab import drive`
`!python /content/drive/My\ Drive/MyScript.py`

This works for me! I hope it helps you.

**Comment by BJWiley233** [comment]
Hi @jchodera, It might be useful to either add that link you posted to SO or to add under [8.1.6. Step 3: Install the Python API](http://docs.openmm.org/latest/userguide/library/02_compiling.html#step-3-install-the-python-api)  since `make PythonInstall` or `python3.* setup.py install` installs to the site-packages and if you install `python3.*-dev` on Debian system for some odd reason doesn't have `site-packages` as default like conda python.
