### ISSUE TITLE
Langevin dynamics with multiple time steps

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2689]
MTSIntegrator only performs constant energy dynamics.  If you want constant temperature you can add an AndersenThermostat, but that isn't necessarily the best way of doing it.  A MTSLangevinIntegrator class that uses something resembling BAOAB would presumably give better results.  But it's not obvious how to combine BAOAB with multiple time steps.  Should you insert velocity randomization in the middle of the innermost position updates?  Or the outermost ones?  Or every update?

I found one paper on this subject: https://pubs.acs.org/doi/10.1021/acs.jpclett.9b00901.  They put velocity randomization into the innermost time steps.  They report good results, but they don't offer any justification for that choice or try out any other ways of doing it.

**Comment by jchodera** [comment]
> But it's not obvious how to combine BAOAB with multiple time steps.

This is actually quite straightforward. @maxentile has effectively solved this problem in the most general case with his modular [`LangevinIntegrator`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L1010). This builds on the work from Leimkuhler and Matthews in [g-BAOAB](https://royalsocietypublishing.org/doi/full/10.1098/rspa.2016.0138), which is a straightforward MTS generalization of BAOAB with three force groups (solvent-solvent energies, solute-{solute,solvent}, and force-free).

**Comment by jchodera** [comment]
See especially the [examples](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L1039-L1048):
```
        - VVVR
            splitting="O V R V O"
        - BAOAB:
            splitting="V R O R V"
        - g-BAOAB, with K_r=3:
            splitting="V R R R O R R R V"
        - g-BAOAB with solvent-solute splitting, K_r=K_p=2:
            splitting="V0 V1 R R O R R V1 R R O R R V1 V0"
```
The last example uses two force groups, 0 and 1, and includes a third implicit force-free group (for the high-accuracy geodesic integration of constraints):
```
        - g-BAOAB with solvent-solute splitting, K_r=K_p=2:
            splitting="V0 V1 R R O R R V1 R R O R R V1 V0"
```

**Comment by peastman** [comment]
My understanding is the g-BAOAB primarily relates to how you apply constraints?  The main use I'm interested in this for is AMOEBA, which generally doesn't use constraints but does benefit a lot from splitting up the forces.

In the examples you gave, you put the randomization into the inner position updates, which is certainly one way of doing it, but has it been proven to be the best way?

**Comment by maxentile** [comment]
>In the examples you gave, you put the randomization into the inner position updates, which is certainly one way of doing it, but has it been proven to be the best way?

It's not clear to me what order of steps would be best (I imagine the answer must depend on details of the force group definitions that are hard to prove things about), but a nice aspect of splitting is the flexibility to change the order pretty flexibly and still have a recipe for a valid method.

**Comment by jchodera** [comment]
> My understanding is the g-BAOAB primarily relates to how you apply constraints? The main use I'm interested in this for is AMOEBA, which generally doesn't use constraints but does benefit a lot from splitting up the forces.

The [g-BAOAB](https://royalsocietypublishing.org/doi/full/10.1098/rspa.2016.0138) paper describes  a multiple timestep BAOAB scheme where there are three energy classes:
* the solvent-solvent interactions (computed as infrequently as once every 9 fs)
* the solute-{solute,solvent} interactions (computed every e.g. 3 fs)
* a force-free inner timestep (the "geodesic" part), which may not be necessary to do more frequently than the solute-{solute,solvent} interactions

See especially Section 5 for the explicit construction of MTS for BAOAB.

Since we understand how to do MTS for BAOAB, I think your question focuses more on "how should we split the potential for AMOEBA?", it seems. AMOEBA has very stiff valence terms, and would seem to benefit from at least including those in the innermost timestep, along with any other terms that are tightly coupled to them.

**Comment by peastman** [comment]
No, I'm not asking about potential splitting.  I'm asking about how to adapt BAOAB to a multiple time step scheme.  You've implemented it in one particular way, but I'm asking if anyone has considered other ways of doing it, or proven that way is the best one.

**Comment by jchodera** [comment]
Yes, [the paper](https://royalsocietypublishing.org/doi/pdf/10.1098/rspa.2016.0138) examines several ways of doing it:
![image](https://user-images.githubusercontent.com/3656088/82491925-39961680-9a9a-11ea-809b-227857f54628.png)

Forgive me, but I don't think I'm understanding exactly what you are asking. Could you elaborate about what, _specifically_, you are looking for?

**Comment by jchodera** [comment]
Whoops, I think that figure compares only the force-free part. There are some comparisons of other splittings for MTS later in the paper, but it looks like they may not systematically examine the multiple timesteps for other splittings.

**Comment by jchodera** [comment]
If you had a force splitting in mind, you could easily use [`openmmtools.LangevinIntegrator`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L1010) to regress over many symplectic MTS splittings for test systems in [`openmmtools.testsystems`](https://openmmtools.readthedocs.io/en/0.18.1/testsystems.html) to identify superior splittings.

**Comment by peastman** [comment]
> If you had a force splitting in mind, you could easily use openmmtools.LangevinIntegrator to regress over many symplectic MTS splittings for test systems in openmmtools.testsystems to identify superior splittings.

You mean propagator splittings, not force splittings?  Yes, I think the best thing to do is try them out and see how they work.

**Comment by jchodera** [comment]
Yes, propagator splittings!

@maxentile : Did you have some scripts or notebooks around that explored the MTS splittings over a set of test systems? I seem to recall you looked into this at one point.

**Comment by maxentile** [comment]
I had written some tools [to systematically enumerate or randomly sample MTS splittings](https://github.com/choderalab/integrator-benchmark/blob/bb307e6ebf476b652e62e41ae49730f530732da3/benchmark/utilities/mts_utilities.py#L111-L307), and had presented preliminary results of evaluating some of these in a pretty limited fashion (just checking acceptance rate as a function of stepsize for the Metropolized version of each scheme -- since there are a lot of force-group permutations to look at, and acceptance rate can be estimated very cheaply given a cache of equilibrium samples). Different permutations led to different acceptance rate profiles, but unfortunately I didn't pursue this direction far enough to yield results we should base decisions on. I think this was a pretty interesting direction though, and it would be neat to revisit this at some point, armed with cleverer ways for exploring and scoring the space of valid splittings...

**Comment by peastman** [comment]
Yes, that would be very interesting to explore further!
