### ISSUE TITLE
Use of Ampere TF32 

### ISSUE THREAD

**Issue by giadefa** [openmm/openmm#2706]
Just a reminder that with 10x times more flops than FP32, these could be useful to use.
https://devblogs.nvidia.com/nvidia-ampere-architecture-in-depth/

For normal MD, we should be checking that TF32 is as good as FP32 due to reduced precision. For ML, it is probably fine.

gdf

**Comment by peastman** [comment]
I believe TF32 is only used by the tensor cores, which are specialized for doing matrix multiplies.  We would need to identify operations which 1) can be mapped to matrix multiplies, and 2) can tolerate low precision.  I can't think of any such operations in MD.

**Comment by giadefa** [comment]
It might be possible to arrange 4 atoms together and have a 4x4 matrix to
operate on.

The only place where these things make sense to try is in the inner loop of
the nonbonded pair interactions

**Comment by peastman** [comment]
There's no way 10 bits of precision would be enough for actually computing nonbonded interactions.  It might be enough for building neighbor lists though.  But I don't see how to make that look like a matrix multiply.

**Comment by giadefa** [comment]
The 10 bits are only used in one part, the multiplication. All the rest
including adds are normal. I don't know why they decided to do that, but we
cannot esclude that it could be enough. We would need to test it.

**Comment by peastman** [comment]
It's still a bottleneck to the precision.  Whatever the inputs to the multiplication are, all but ten bits (three significant digits) is thrown out.  I can say quite confidently that if we throw out all but ten bits of a position, a displacement, or a distance, that won't be nearly accurate enough.  Even single precision is pushing the limits, and we have to be careful about how we do calculations.  We could probably limit sigma and epsilon to that precision and it would be ok, but you don't get to multiply a TF32 by a FP32.  If you want to use the tensor cores, all inputs have to get truncated to that precision.

Building neighbor lists is a different matter.  It's ok to have occasional mistakes, as long as those mistakes always consist of including an unnecessary pair rather missing a real one.  If your result is only accurate to three significant digits, just multiply your cutoff distance by 1.001 to give a margin for safety.  So that seems to me the most promising place to look.

**Comment by giadefa** [comment]
It is also possible/likely that Nvidia will move TF32 to FP32 in
tensorcores in the next GPU  generation if people show that the precision
is not enough. In particular, if we say, look we would get 30% speedup
overall by using tensorcores, but we cannot use it.
