### ISSUE TITLE
Restarting from checkpoint

### ISSUE THREAD

**Issue by Gareth-elliott** [openmm/openmm#2744]
Hi OpenMM developers,

I have recently been running some simulations and find myself needing to restart from a checkpoint (thankfully I saw the part about it in the manual and added the checkpoint reporter so that I can restart them)

I tried to see if there were any other issues about this, and all I could find were #1645 and #1599, but they don't really spell out how to do it.

The manual says that to restart from a checkpoint, I need the following line:
simulation.loadCheckpoint('state.chk')

however, I'm just wondering what other things I need in my script to allow it to restart?
 I.e. 
- do I need to respecify the force field and topology, integrator etc?
- does it know what timestep its up to (as of the checkpoint, which im dumping every 1000 steps) or do I need to subtract off the number of steps the checkpoint is at from "simulation.step(N)"
- does the pdb reporter open the file in append mode - i.e. will the trajectory keep adding to the existing pdb file, or will it try and overwrite it?

Would it be possible to get an example script (maybe based off one of the examples that are used in the manual) for how to restart?

Thanks,

Gareth

**Comment by peastman** [comment]
> do I need to respecify the force field and topology, integrator etc?

Yes.  You still need to create your system and integrator as usual.  The checkpoint stores the current values of everything that changes during a simulation: positions, velocities, etc.  Everything in your script as far as creating the Simulation is the same.  Then you load in the checkpoint to restore all the changeable information.

> do I need to subtract off the number of steps the checkpoint is at from "simulation.step(N)"

Yes.  `step(N)` means, "Run for N steps."  It does not mean, "Run until a total of N steps have been executed."  For example, if you repeatedly call `step(100)`, each call will advance the simulation by another 100 steps.

> does the pdb reporter open the file in append mode - i.e. will the trajectory keep adding to the existing pdb file, or will it try and overwrite it?

PDBReporter doesn't support appending, because that's really hard to do with PDB files.  DCDReporter does support it.  Just add the argument `append=True` when you create it.  DCD is generally a much better format for trajectories than PDB, so I'd recommend it in any case.  The files are a lot smaller, and it stores coordinates to much higher precision.

**Comment by Gareth-elliott** [comment]
Thanks @peastman got them running again fine :)
