### ISSUE TITLE
Truncated octahedral solvent box

### ISSUE THREAD

**Issue by atbogetti** [openmm/openmm#2745]
Hello, Am I able to take a prepared PDB and solvate with a truncated octahedral box of water molecules from within OpenMM?  Is this done with addSolvent?  I would like to use this truncated octahedral solvent box with periodic boundary conditions in OpenMM.  How would I set that up?

**Comment by peastman** [comment]
Yes.  The easiest way is with [OpenMM-Setup](http://docs.openmm.org/latest/userguide/application.html#the-openmm-setup-application).  It provides a simple GUI for this.

**Comment by atbogetti** [comment]
Thank you, this is exactly what I was needing.

**Comment by atbogetti** [comment]
Though I have used Openmm Setup to create my processed pdb (solvated with truncated octahedral waters) the water box appears cubic in vmd and pymol.  Is there any way to check this?  My pdb file reads: CRYST1   98.053   98.053   92.445  77.56 110.70  70.53 P 1           1.  Is there any way to check the clearance from the molecule to the edges of the box?  That also appears to not be what I entered into openmm setup.

**Comment by peastman** [comment]
That line looks correct.  If it were really rectangular, all the angles would be 90.

It turns out that any tiled box, including truncated octahedron and rhombic dodecahedron, is exactly equivalent to a triclinic box, a sort of generalized rectangle in which the angles aren't 90 degrees.  And that in turn is exactly equivalent to a rectangular box in which adjacent periodic copies are offset from each other.  So that's how MD engines represent them internally.  See https://doi.org/10.1002/(SICI)1096-987X(19971130)18:15%3C1930::AID-JCC8%3E3.0.CO;2-P for more information about how this works.

**Comment by djhuggins** [comment]
Hello. I am responding to this as I'd like to know whether there is a way to solvate using a non-orthorhombic box that doesnt use OpenMM-Setup? I am hoping to use a function in python such that this can be done in an automated fashion.

**Comment by peastman** [comment]
When adding solvent, you can use the `boxVectors` argument to specify any box shape you want.  Here is [the code in OpenMM-Setup](https://github.com/openmm/openmm-setup/blob/931bddaf9fa185e44c79af2c638c22eed3cbe7d4/openmmsetup/openmmsetup.py#L251-L256) that selects the box vectors for standard types of non-rectangular boxes.

```python
elif geometry == 'truncatedOctahedron':
    vectors = mm.Vec3(1,0,0), mm.Vec3(1/3,2*sqrt(2)/3,0), mm.Vec3(-1/3,sqrt(2)/3,sqrt(6)/3)
    boxVectors = [(maxSize+geompadding)*v for v in vectors]
elif geometry == 'rhombicDodecahedron':
    vectors = mm.Vec3(1,0,0), mm.Vec3(0,1,0), mm.Vec3(0.5,0.5,sqrt(2)/2)
    boxVectors = [(maxSize+geompadding)*v for v in vectors]
```
