### ISSUE TITLE
Question: Water model in AMOEBA13 forcefield

### ISSUE THREAD

**Issue by k79-cyber** [openmm/openmm#2748]
Hello,

I am new to openmm. I am interested to use the AMOEBA13 polarisable forcefields and I want to try it with different water models namely, AMOEBA03 and AMOEBA14. How do I do that? 

Thanks
Koushik

**Comment by peastman** [comment]
The water model is included in `amoeba2013.xml` along with the rest of the force field, since everything was parametrized to be used together.  If you want to use different parameters for water, the simplest thing would be to make a copy of that file and modify it.

See https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/data/amoeba2013.xml#L1759-L1765, and for information about how force fields are defined, see http://docs.openmm.org/latest/userguide/application.html#creating-force-fields.

**Comment by k79-cyber** [comment]
I understand now. Thanks.

Koushik
