### ISSUE TITLE
TestReferenceAmoebaGeneralizedKirkwoodForce timeout

### ISSUE THREAD

**Issue by frank-stonybrook** [openmm/openmm#2749]
Dear OpenMM developers,

I did a quick search and seems that nobody mentioned this. Here are details:

- OpenMM version (Official release 7.4.0);

- Platform: IBM Power9;

Here are the test output:
```
Start 184: TestReferenceAmoebaGeneralizedKirkwoodForce
184/287 Test #184: TestReferenceAmoebaGeneralizedKirkwoodForce ....***Timeout 1500.12 sec

```

Best,
Cong

**Comment by peastman** [comment]
Could you try with the latest version of the code from the repository?  That test is passing on travis, so most likely it's a problem that has already been fixed.  If not, we need to figure out what's different on your computer.

**Comment by frank-stonybrook** [comment]
Same test with the latest repo passed the test very quickly on my machine (POWER9 cpu)! I am curious about the changes related to this test. Could you say a few words about it? Thanks

**Comment by peastman** [comment]
I don't know.  It's been a while since 7.4.0 was released and there have been a number of changes to related code since.  You could try checking out old revisions to identify exactly which one fixed it.  All I can definitely say is that it's been working ever since we got travis set up to run tests on PPC, but that was only a couple of months ago.

**Comment by frank-stonybrook** [comment]
Okay, Thanks!
