### ISSUE TITLE
XTC reporter / preservation of PBC

### ISSUE THREAD

**Issue by jadeshi** [openmm/openmm#2755]
Hey all,
I've been trying to write an XTC reporter for OpenMM simulations, but I've been running into the issue that the resulting xtc trajectory, when loaded into VMD or Pymol, does not seem to preserve the PBC for the solvent molecules. I've attached an example with alanine dipeptide in TIP3P water to show what I mean: the archive contains the python run script, the initial AMBER prmtop and inpcrd file generated from tleap, and the written xtc trajectory: [ala2_xtcreporter.tar.gz](https://github.com/openmm/openmm/files/4822417/ala2_xtcreporter.tar.gz)

Basically, the way I'm going about it is I'm first loading a dummy topology and coordinates using mdtraj, overwriting topology.xyz using the current simulation coordinates, saving this as an xtc, and then successively appending new xtc frames together to this one using the "cat" command. However, when I load this into VMD with the original AMBER prmtop file, it does not seem to be able to handle the PBC correctly, and the solvent molecules appear to just diffuse outwards endlessly. 

Wondering if someone could take a look and let me know what I'm doing wrong? Please excuse my stupidity if I'm missing something really obvious...

Thanks a lot!

**Comment by jchodera** [comment]
That's awesome that you're writing an `XTCReporter`! This could be very useful.

OpenMM does not re-image the molecules by default because this would destroy the ability to examine phenomena like diffusion constants. To ensure all the molecules end up imaged in the box, you should call `getState()` with the `enforcePeriodicBox=True` option. While this won't prevent diffusion of the macromolecule to the box edges, all molecules should at least be re-imaged into the simulation cell.

You might take a look at the `Reporter` classes implemented in [OpenMM](http://docs.openmm.org/latest/api-python/app.html#reporting-output) and [mdtraj](http://mdtraj.org/1.9.3/api/reporters.html) for more examples.

**Comment by jadeshi** [comment]
Ah, I see, thanks John! That seems to have done it.

**Comment by peastman** [comment]
That shouldn't be necessary.  If the 6th element of the tuple returned by `describeNextReport()` is `True`, that tells it to apply periodic boundary conditions.  No need to call `getState()` again (which is expensive).
