### ISSUE TITLE
Interesting NAMD NVIDIA blog

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2759]
I thought this might be of interest:
https://developer.nvidia.com/blog/delivering-up-to-9x-throughput-with-namd-v3-and-a100-gpu/

**Comment by peastman** [comment]
Basically they concluded that to get better performance, they needed to make it work more like OpenMM. :)  Run everything on the GPU instead of treating it as an accelerator for slow operations.  Only use a single GPU to eliminate communication overhead.  If your computer has multiple GPUs, run a separate simulation on each one, or possibly even more than one simulation on each one.

**Comment by jchodera** [comment]
Would we be interested in writing something like this for the NVIDIA blog?
