### ISSUE TITLE
Fail to parse CHARMM parameter files in latest master branch

### ISSUE THREAD

**Issue by HanatoK** [openmm/openmm#2773]
It seems in CHARMM parameter files the lines starting with `DONOR` will be considered as `ANGLES` by `charmmparameterset.py`.

This only happens in the latest master branch. In 7.4.2 everything is OK.

A test case can be found at https://github.com/HanatoK/Apoa1-Benchmark/blob/master/openMM/apoa1_nvt.py . Other parameter files are in https://github.com/HanatoK/Apoa1-Benchmark/blob/master/openMM/ as well.

Error messages:
```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/simtk/openmm/app/charmmparameterset.py", line 101, in _convert
    return type(data)
ValueError: could not convert string to float: 'OH2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./apoa1_nvt.py", line 23, in <module>
    param = CharmmParameterSet('par_all36_lipid.prm', 'par_all36m_prot.prm', 'top_all36_lipid.rtf', 'top_all36_prot.rtf', 'toppar_water_ions.prm')
  File "/usr/local/lib64/python3.8/site-packages/simtk/openmm/app/charmmparameterset.py", line 148, in __init__
    for par in pars: self.readParameterFile(par, permissive=permissive)
  File "/usr/local/lib64/python3.8/site-packages/simtk/openmm/app/charmmparameterset.py", line 325, in readParameterFile
    k = conv(words[2], float, 'bond force constant')
  File "/usr/local/lib64/python3.8/site-packages/simtk/openmm/app/charmmparameterset.py", line 103, in _convert
    raise CharmmFileError('Could not convert %s to %s' % (msg, type))
simtk.openmm.app.internal.charmm.exceptions.CharmmFileError: Could not convert bond force constant to <class 'float'>

```

**Comment by peastman** [comment]
@Olllom could I get your advice on how to fix this?  It was introduced as a side effect of #2596.

The problem is that toppar_water_ions.prm contains both residue definitions (`RESI` records) and parameters.  It looks for section headers to tell it what section it's currently parsing.  Prior to #2596 it expected the angles section to begin with the full word `ANGLES`.  But now it accepts anything that starts with `ANGL`, which includes a single `ANGLE` record inside a `RESI`.

It isn't clear to me from the documentation how this is supposed to be parsed.  A simple fix, at least for this file, is to require the line must contain only a single token to interpret it as a section header.  But I'm not certain if that's correct.

**Comment by peastman** [comment]
I've been debugging this further.  The problem seems to be related to the filename extension you used.  The original force field includes the file `toppar_water_ions.str`, but you renamed it to `toppar_water_ions.prm`.  If I just change the extension back, it loads correctly.  Was that an error, or is it supposed to work with either extension?

**Comment by HanatoK** [comment]
> I've been debugging this further. The problem seems to be related to the filename extension you used. The original force field includes the file `toppar_water_ions.str`, but you renamed it to `toppar_water_ions.prm`. If I just change the extension back, it loads correctly. Was that an error, or is it supposed to work with either extension?

Thanks! I remember that in the old version the .prm extension also worked. If changing the extension works then it should be a problem of the filename itself.
