### ISSUE TITLE
Removing custom external force in xml file

### ISSUE THREAD

**Issue by atbogetti** [openmm/openmm#2780]
Hello,  I would like to heat and equilibrate my system with restraints and then remove those restraints for production.  I do so with the following in a minimize_and_heat.py file:

`force = CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")`
`force.addGlobalParameter("k", 5.0*kilocalories_per_mole/angstroms**2)`
`force.addPerParticleParameter("x0")`
`force.addPerParticleParameter("y0")`
`force.addPerParticleParameter("z0")`
I add my particles...
`system.addForce(force)`

Then I save the simulation as an .xml file state with saveState and load that into my next equilibration step.  This equilibration step has the exact same force defined, so it works.  However, when I try to load in my equil.xml file (a saveState .xml file from my equilibration) into my production simulation, which does not have the force defined, I get the following error:

Traceback (most recent call last):
  File "prod.py", line 54, in <module>
    simulation.loadState("equil.xml")
  File "/PATH/apps/anaconda3/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 338, in loadState
    self.context.setState(mm.XmlSerializer.deserialize(xml))
  File "/PATH/apps/anaconda3/envs/openmm/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18307, in setState
    return _openmm.Context_setState(self, state)
Exception: Called setParameter() with invalid parameter name: k

How can I fix this?  When I save a checkpoint (as a .chk file) everything works fine, it's just the xml file that is causing the error.  I'd like to use the xml file throughout.

I have visualized the trajectory and verified that the force is working correctly as defined and when removed (using the .chk files, the only way that works) is properly removed.

Thanks.

**Comment by peastman** [comment]
States are flexible.  When you create them, you can specify what information you want it to contain.  `Simulation.saveState()` tries to include all possible information so as to restore the simulation to as close to where it was as possible.  That includes positions, velocities, and context parameters:

https://github.com/openmm/openmm/blob/ac5a8f7127656c1ca1679a8842dd93d64628699c/wrappers/python/simtk/openmm/app/simulation.py#L315

Because your custom force defines a global parameter, the state can't be loaded after you remove the force.  The state has a parameter that no longer exists.  The solution is to write out a State that doesn't include parameters.

```python
state = simulation.context.getState(getPositions=True, getVelocities=True)
with open('savedstate.xml', 'w') as output:
  output.write(XmlSerializer.serialize(state))
```

**Comment by atbogetti** [comment]
This worked for me.  Thank you so much!
