### ISSUE TITLE
Temporarily masking atom or molecule contributions to energies

### ISSUE THREAD

**Issue by EqualAPriori** [openmm/openmm#2792]
Hi all, I was wondering if there might be a simple way to mask particular atoms and molecules when calculating the system energy -- this would be useful for getting the energy changes for monte carlo calculations that involve, say, deleting a molecule, or perturbing the conformation of an internal segment of a polymer, say by configurational bias.  While molecule deletions could be done by creating a new topology and a new system, such a procedure seems much more cumbersome for incremental configurational bias energy calculations.

To be more concrete, if say I mask an atom (or atoms, or even residues) in a chain, I would would want to remove the bonding, angle, and torsion energies (as well as nonbonded interactions) of interactions that involve the masked atom(s).

Or would the easiest way be to manually get the bond, angle, torsion, non-bonded parameters and calculate just these components in code separate from OpenMM? However, one problem I foresee with this approach is the more complicated task of calculating the electrostatic interactions outside of OpenMM.

Thanks!

**Comment by jchodera** [comment]
Is the main goal here convenience of implementation or performance (this should be faster or comparable to standard energy or force computation)? There are a few things we could recommend depending on which regime you are in.

Also, which specific force types are you using?

**Comment by EqualAPriori** [comment]
Ease of implementation would probably be the first priority -- my understanding is that configurational bias moves are usually only used on relatively simple molecules and polymers, and I would want to do some exploration to test its feasibility for more complicated structures. If it is feasible, however, then we can think about higher-performance methods.

As for force fields, I've mostly been using GAFF, but for testing purposes will probably use common united atom force fields e.g. from OPLS or TRAPPE, so mostly lennard jones + electrostatics + standard bonded potentials.

Thanks!

**Comment by peastman** [comment]
Since you're doing MC, I assume you'll be doing this repeatedly with different sets of atoms?  If there was just one molecule you wanted to compute the energy with and without, that could be done very efficiently using a global parameter to turn it on or off.  But if you have a lot of molecules, and you might want to temporarily turn off any one of them, that wouldn't work.

Assuming I've understood correctly, it's probably easiest to do this by modifying the force parameters to set particular terms to zero.  For example, here's the code for a HarmonicBondForce.  Assume that `atoms` is a `set` containing the indices of atoms you want to remove, and `bond_k` is a list containing the spring constant for every bond.  You could then write

```python
for i in range(force.getNumBonds()):
  p1, p2, length, k = force.getBondParameters(i)
  exclude = (p1 in atoms or p2 in atoms)
  force.setBondParameters(i, p1, p2, length, 0 if exclude else bond_k[i])
force.updateParametersInContext(context)
```

You can do something similar for any other force.  For a NonbondedForce, you would set `charge` and `epsilon` to 0 (and be sure to loop over the exceptions as well as the particles).

**Comment by EqualAPriori** [comment]
Ah, that makes sense. In the interim I'll write a wrapper that stores the interaction terms and toggles them on/off depending on the atoms/residues that I want to isolate. I'll check back later if I need a faster implementation that doesn't require re-calculating energies of the entire system. 

Thanks!

**Comment by tristanic** [comment]
In ISOLDE I make fairly extensive use of switchable forces (for user-applied restraints and tugging), with the general form:

"select(step(enabled - 0.5),energy_function,0)"

where "enabled" is a per-particle or per-bond parameter with the value 1 (enabled) or 0 (disabled). Might be useful?
