### ISSUE TITLE
question about createSystem and finding matching residues

### ISSUE THREAD

**Issue by dacase** [openmm/openmm#2809]
[NB: low urgency here -- I got everything to work.  But I'm trying to learn more about openmm, and if there is a better way to define new residues.]

I edited `amoeba2013.xml` to add a new residue ("NO3").  Jay sent me the Amoeba parameters for this, and I have tried to follow how the "HOH" residue is defined.  My code is like this:
```
import simtk.openmm.app as app
pdb = app.PDBFile(opt.pdb)
ff = app.ForceField('amoeba2013_dac.xml')
system = ff.createSystem(pdb.topology, ...plus optional args)
```
All of the standard residues load fine, but I get this error when the NO3 residue in the pdb file is encountered:
```
ValueError: No template found for residue 414 (NO3).  The set of atoms matches NO3, but the bonds are different.
```
My question is this: How does createSystem() look for matching bonds?  Or, (generally) how does createSystem find bonds in the input PDB file, in order to try to find a match?  I find that if I add explicit `CONECT` records for NO3 residues, I can get a match and everything works OK.  But I'm confused about why CONECT records are not needed for other residues. And since it's a bit of a pain to add the CONECT lines, if there is a simple way to avoid that, it would be good to know.

...thx...dac

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template.  It discusses this in a fair amount of detail.  Here's the short answer: the PDB spec says that CONECT records should not be included for standard amino acids, nucleotides, and water.  That's why OpenMM fills in the bonds for them automatically.  All heterogens other than water need CONECT records or it won't know where the bonds go.

**Comment by dacase** [comment]
Got it, and thanks.  (I've spent too much time in Amber, where, once the residue names and atoms match, bonds are assumed to come from the library, not the pdb file.) And apologies for not seeing the FAQ answer.
