### ISSUE TITLE
A small number of constraints have extreme impact of CustomIntegrator performance

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2814]
The most recent batch of Folding@home free energy calculations has run into a surprising issue where the calculations are exceptionally slow. A bit of debugging has identified that a handful of restraints in the small molecule are responsible for this, where ligand-in-solvent goes from 230 ns/day down to 90 ns/day on a GTX 1080 Ti. (The same issues also manifest in the large complex simulation, but are harder to interactively debug there.)

Here is an attached ZIP file and a short benchmark script. While the CustomIntegrator is rather complex (for nonequilibrium cycling free energy calculations), commenting out the constraints for the solute (particles 0-50) takes the simulation from 90 ns/day -> 230 ns/day. 

This may be running into similar issues as observed earlier, where near-colinear constrained bonds can cause pathological problems for CCMA. This may occur frequently in alchemical calculations because old and new atoms are excluded from each other. 

Is it easy to establish if this is the case? If so, can we also support an alternative algorithm (e.g. SHAKE/RATTLE) that is slightly less efficient for normal dynamics but incredibly more efficient than CCMA for free energy calculations?
[ccma-issues.zip](https://github.com/openmm/openmm/files/5121621/ccma-issues.zip)

**Comment by jchodera** [comment]
In fact, all you have to do is comment out a _single_ constraint to see this effect (90 -> 230 ns/day)!
```XML
 <Constraint d=".1020056453864" p1="25" p2="50"/>
```

**Comment by jchodera** [comment]
Note that at the end of the `<Constraints>` block are two more constraints to atom 25:
```XML
               <Constraint d=".1094223427522" p1="25" p2="4052"/>
                <Constraint d=".1094223427522" p1="25" p2="4053"/>
```
It's likely the combination of all three constraints to atom 25 that is the problem.

As noted, this situation is very common in free energy calculations.

**Comment by peastman** [comment]
Those three constraints are the only ones in the whole system that require CCMA.  Everything else can be handled with SETTLE or SHAKE.  That makes a big difference, because SETTLE and SHAKE are each done with a single kernel invocation.  CCMA requires multiple kernels per iteration.  Even if it only has a tiny number of constraints, the launch overhead from all those kernels adds up.

This is made worse by an issue that I've pointed out several times: the custom integrators in openmmtools apply constraints much more often than they need to.  The integrator you have here applies position constraints three times and velocity constraints six(!) times in every time step  Are all of those really necessary?  If you can remove some of them, that will help a lot.

If you think this is likely to be a common situation (a large system with only one small cluster of constraints that need CCMA), we could consider creating an alternate implementation that runs in a single kernel.  It would have to be limited to a single thread block to allow synchronization, but if you only have a few constraints that wouldn't matter.

**Comment by jchodera** [comment]
> This is made worse by an issue that I've pointed out several times: the custom integrators in openmmtools apply constraints much more often than they need to. The integrator you have here applies position constraints three times and velocity constraints six(!) times in every time step Are all of those really necessary? If you can remove some of them, that will help a lot.

The first position and velocity constraints are only applied on the first step---they're in an "if" block. This is just to ensure that we can correctly measure work during the nonequilibrium protocol. 

On a GTX 2080, the unmodified integrator gives 62 ns/day with the third X-H constraint, or 200 ns/day without that one constraint. (Note I neglected to add a `context.getState()` after the initial `integrator.step(2)` warmup.) Commenting out the first pair of position/velocity constraints has no measurable impact on performance. So let's ignore this pair.

The `integrators.xml` per cycle runs two positions constraints (`computationType="3"`) and five velocity constraints (`computationType="4"`) during each cycle. The additional constraints are used to make sure we are accurately measuring the accumulation of protocol and shadow work while also producing constrained velocities and positions at the end of the integrator cycle.

While we may be able to skip some velocity constraint steps if we're not accumulating shadow work, I'm not actually sure if we _can_ dispense with the position constraints because we need constrained positions whenever we compute the force or energy. But let's say we refactored the integrator to measure the accumulation of protocol work elsewhere in the cycle when the positions are already constrained---that would get rid of one position constraint step. Commenting out the last position constraint step has no measurable impact. Additionally commenting out the last two velocity constraint steps only increases performance to 93 ns/day.

> If you think this is likely to be a common situation (a large system with only one small cluster of constraints that need CCMA), we could consider creating an alternate implementation that runs in a single kernel. It would have to be limited to a single thread block to allow synchronization, but if you only have a few constraints that wouldn't matter.

Considering we're burning most of the MD computing time in the entire world on this right now, this is definitely critical, both for Folding@home and for any OpenMM based free energy calculations in general. We could consider
* Coalescing things into a single kernel
* Using a different algorithm that doesn't run into pathologies when bonds are nearly colinear; wouldn't SHAKE or LINCS work?
* Improving the stability of CCMA to better handle nearly colinear constraints

**Comment by peastman** [comment]
> Using a different algorithm that doesn't run into pathologies when bonds are nearly colinear

Do you have any reason to think it's anything related to that?  I don't think it's any sort of pathologies.  It's just that you're launching a whole lot of extra kernels to deal with only three constraints.

**Comment by jchodera** [comment]
> Do you have any reason to think it's anything related to that? I don't think it's any sort of pathologies. It's just that you're launching a whole lot of extra kernels to deal with only three constraints.

We've had previous discussions about pathologically slow performance in perses calculations that appeared to be caused by nearly colinear bonds, but you're right that this may not be the primary issue. If I change the reference angle of these bonds to ensure they are different, it does not speed things up.

**Comment by jchodera** [comment]
Just so I understand here, is it that SHAKE can be used for an atom involved in a maximum of three constrained bonds? And our situation involves more than this? Just trying to better understand why CCMA is required here.

**Comment by peastman** [comment]
Exactly.  SHAKE is an inherently serial algorithm.  There's no way to parallelize a single constraint application.  But the common case of `constraints=HBonds` produces lots of tiny, independent clusters, so we can use a separate thread for each cluster.  The code only supports that very specific case though: a heavy atom with constraints to one to three hydrogens.

In contrast, CCMA can be efficiently parallelized, so that's what we use for arbitrary sets of constraints that don't meet one of our other special cases.  But it does require synchronizing across all threads at certain points, and on a GPU that means splitting it into multiple kernels.  That's what makes it slow, especially when only being used for a small number of constraints.

I'm suggesting adding another special case.  To synchronize across *all* threads we need multiple kernels, but if you only need to synchronize across the threads *in a single thread block* that can be done within a single kernel.  So we could have another version of CCMA that runs in a single kernel with a single thread block.  For moderate numbers of constraints (at least up to a few hundred, maybe larger) that should end up being faster.

**Comment by jchodera** [comment]
> Exactly. SHAKE is an inherently serial algorithm. There's no way to parallelize a single constraint application. But the common case of constraints=HBonds produces lots of tiny, independent clusters, so we can use a separate thread for each cluster. The code only supports that very specific case though: a heavy atom with constraints to one to three hydrogens.

Would adding an option to force OpenMM to continue to use SHAKE in a simple serial iteration over each constraint in the constraint cluster work here? It seems like this may still have better performance than forcing CCMA to be used for just a single constraint cluster, and my understanding is that this is how other codes work.

> I'm suggesting adding another special case. To synchronize across all threads we need multiple kernels, but if you only need to synchronize across the threads in a single thread block that can be done within a single kernel. So we could have another version of CCMA that runs in a single kernel with a single thread block. For moderate numbers of constraints (at least up to a few hundred, maybe larger) that should end up being faster.

Sounds awesome, but could this be overkill for what we need?

**Comment by peastman** [comment]
> Sounds awesome, but could this be overkill for what we need?

Possibly, but if we're adding another special case, let's make it as useful as possible.  It probably won't even be much more difficult to implement, since it can continue to use all the same data structures we currently build for CCMA.  All the code that analyzes the constraints can remain the same.  The only change to host side code will be to launch a different kernel.  Creating another version of SHAKE would mean a simpler GPU kernel but more changes to host code.

**Comment by jchodera** [comment]
Understood! It would be _incredibly_ useful if we could squeeze this into 7.5.0, given how critical this is to relative free energy calculations.

**Comment by peastman** [comment]
I'll see what I can do.
