### ISSUE TITLE
Constraining Angles and Bonds in xml force field files

### ISSUE THREAD

**Issue by nsherck** [openmm/openmm#2834]
Hello,

I am working on a project using the Trappe-UA force field, which in some cases requires constraining angles in addition to bonds. In our case we would like to make the benzene ring rigid.

(1) Is there a way to specify these constraints directly in the <Residues> section of the xml force field file (see snippet of xml code below for the definition of a polystyrene monomer residue)?

(2) Additionally, is there a simple way to constrain specific angles? This would be beyond manually specifying distance constraints, but more along the lines of being able to specify if the angle is constrained or not (i.e., True or False). 

Many thanks in advance, 
Nick 

    <Residue name="PSmid">
      <AllowPatch name="PpmS"/>
      <Atom name="C1" type="CH(sp3)"/>
      <Atom name="C2" type="CH2(sp3)"/>
      <Atom name="C3" type="C(aro)"/>
      <Atom name="C4" type="CH(aro)"/>
      <Atom name="C5" type="CH(aro)"/>
      <Atom name="C6" type="CH(aro)"/>
      <Atom name="C7" type="CH(aro)"/>
      <Atom name="C8" type="CH(aro)"/>
    
      <Bond atomName1="C1" atomName2="C2"/>
      <Bond atomName1="C1" atomName2="C3"/>
      <Bond atomName1="C3" atomName2="C4"/>
      <Bond atomName1="C4" atomName2="C5"/>
      <Bond atomName1="C5" atomName2="C6"/>
      <Bond atomName1="C6" atomName2="C7"/>
      <Bond atomName1="C7" atomName2="C8"/>
      <Bond atomName1="C8" atomName2="C3"/>
      
      <Constraint d="0.2424871131" atomName1="C3" atomName2="C5"/>
      <Constraint d="0.2424871131" atomName1="C4" atomName2="C6"/>
      <Constraint d="0.2424871131" atomName1="C5" atomName2="C7"/>
      <Constraint d="0.2424871131" atomName1="C6" atomName2="C8"/>
      <Constraint d="0.2424871131" atomName1="C3" atomName2="C5"/>
      <Constraint d="0.2424871131" atomName1="C8" atomName2="C4"/>
      
      <ExternalBond atomName="C1"/>
      <ExternalBond atomName="C2"/>
    </Residue>

**Comment by peastman** [comment]
Once you start constraining angles, things can quickly become complicated.  There are various situations that can lead to the constraint matrix becoming poorly conditioned or even singular.  That causes simulations to blow up.

The first thing to be careful of is not to overconstrain anything.  Suppose you want to make a methane molecule completely rigid.  It has five atoms, each with three degrees of freedom, so 15 degrees of freedom total.  It also contains four bonds and six angles.  The naive way to make it rigid would be to constrain all the bonds and angles.  If you do that, it leaves 15-4-6 = 5 degrees of freedom.  But that's too few!  A rigid body should have six degrees of freedom.  By doing that you overconstrain it, which produces a singular constraint matrix.  To make it work, you need to remove one constraint.

Another problematic situation is the one you suggested: constraining a planar group to be rigid.  Constraints are enforced by applying restoring forces along the constrained directions.  If the group is planar, that means all constraint forces necessarily act in the plane.  It's impossible for them to resist forces that are trying to move the atoms out of the plane.  Even if you have the right total number of constraints, motion within the plane is overconstrained and motion perpendicular to the plane is poorly constrained.

The solution to this problem is to add an extra non-interacting dummy atom out of the plane of the rest of the atoms, and add constraints between that atom and all the real atoms.

Handling situations like these is beyond the scope of what ForceField is designed for.  But it's easy to add the extra particles and constraints by hand, calling `addParticle()` and `addConstraint()` on the System.
