### ISSUE TITLE
Compiling openmm on a cluster

### ISSUE THREAD

**Issue by ncf0003** [openmm/openmm#2840]
Hey all,

I am try to compile openmm on my university's cluster, and after working with one of the members of the HPC team, he recommended I contact you. 

We successfully compile openmm, but when we go to run the tests, a seemingly random (to us) selection of the CUDA and OpenCL tests fail. I attached the log of the tests. From what we could tell, the CUDA tests were all failing due to "No compatible CUDA device is available".

We have CUDA version 10.0 and gcc version 7.5. 

Let me know anything else you might need tot figure out this problem.

Thanks!

Nick
[tests.log](https://github.com/openmm/openmm/files/5211320/tests.log)

**Comment by peastman** [comment]
I can make a guess.  Run `nvidia-smi`.  What mode does it list the GPU as being in?  If it's in "exclusive process" mode, that means only one context can be created on the GPU at a time, so any test that tries to create more than one context at the same time will fail with that error.

**Comment by ncf0003** [comment]
@peastman Thanks for the help! Yes, they are indeed in exclusive process mode. I'm going to guess that it is vital for using openmm with cuda that they are set to "default"? Just want to make sure I'm barking up the right tree in terms of solutions.

**Comment by peastman** [comment]
As long as you only create one context at a time, it's fine for them to be in exclusive mode.  Some of the test cases do create multiple contexts at once, so those tests fail in exclusive mode.

**Comment by Lnaden** [comment]
There is a possibility of a workaround, but based on the cluster nature of this setup, may not be feasible. 

You can load multiple contexts onto a single GPU in `exclusive` mode if you are able to launch the [NVIDA Multi-Process Service or MPS](https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf) daemon in your cluster job. It does allow the creation of multiple CUDA contexts on a single or MPI-connected cards even if they are `exclusive` mode.

Some caveats to that though:
* You have to be able to launch the daemon
* CUDA contexts only, no OpenCL
* There might be a performance hit. I tested this a couple years back, it was not noticeable for my small test systems
* Hard upper limit of 16 contexts per card instead of GPU-RAM limited (if I recall correctly)
* MPS will renumber your GPU's in CUDA_VISIBLE_DEVICES starting from index 0.
    e.g. If your node has 4 GPUs on it, and your scheduler gives you access to the card in slot 2 and 3, your `CUDA_VISIBLE_DEVICES` environment variable will be `2,3`, but turning on the MPS daemon then renumbers those and maps them to `CUDA_VISIBLE_DEVICES=0,1` even though outside of the MPS daemon they are still `2,3`. Its a subtle change, but can be confusing when doing debugging.

That is alot of caveats which all linchpin on your ability to even run the daemon in the first place on a cluster, but its something to look into and see if you can actually request MPS though your scheduler. I was able to at a previous HPC resource which is why I bring this up in the first place.

**Comment by ncf0003** [comment]
hank you both for the help. I only plan to create one context per node so I suppose this isn't an issue. However, I of course am having some other issues with installing. 

I'd like to use the python api to run openmm. My issue is installing it in the proper location and linking openmm to it. Since this is not my personal computer, I of course don't have access to /usr/local/ so made an install directory for openmm separate from the build directory by running `make install DESTDIR=../openmm_install/`. That seems fine. I believe was able to run one of the Hello's. 
However when I try to do something similar with the python api `make PythonInstall DESTDIR=../openmm_install/` I can't seem to access the openmm modules when I run python interactively or otherwise. Thanks for any suggestions!

**Comment by peastman** [comment]
`DESTDIR` is not a property used by the OpenMM build system.  The way you specify the install location is with `CMAKE_INSTALL_PREFIX` when running CMake.

**Comment by ncf0003** [comment]
Alright. I started over. My HPC person had me going down a route different from the directions you have posted for compiling. 

I now have everything installed in a single directory. However I noticed here:

error: could not create '/shared/software/intel/intelpython3/lib/python3.6/site-packages/simtk': Permission denied

the install is trying to add to the python install that I have loaded as a module but obviously no control over. Is there an environment variable or something I could set to access the packages when I need them? Did it actually install properly without that step?

Thanks again!

**Comment by Lnaden** [comment]
that looks like a permission problem when trying to install a new package into a shared/custer-wide Python instance. I'm don't think that's an OpenMM problem, more of a cluster-side problem for any Python package you would try to install. It would be very hard for us to debug on our end. Is it possible to use some other Python instance such as miniconda?

**Comment by ncf0003** [comment]
@Lnaden Definitely the issue and that was an excellent idea. I think that I have everything working now. I was able to complete the install and run the benchmark.py script in the examples directory. 

Thanks @Lnaden and @peastman for all the help!

**Comment by ncf0003** [comment]
Hey all.

Sorry to reopen but I'm actually having some issues running the benchmark.py script for the default time (60 s). I only ran it for 10 a couple days ago. I'm getting "Particle coordinate is nan" error which from what I can tell means that openmm is breaking for some reason. 

Should this be happening with the benchmark systems? I would assume they are properly setup so it made me worry as to if something is wrong with the install.

Thanks again!

**Comment by peastman** [comment]
Is that on ApoA1?  I occasionally get that too.  I think it's just that the starting conformation isn't well optimized.  I've been meaning to look into it.

I'm closing this because the original issue is resolved and this is unrelated to it.  Feel free to open another issue for it if you want (but don't feel you need to, because I'm going to look into it regardless).
