### ISSUE TITLE
Minimization on Amber system resets coordinates of water box

### ISSUE THREAD

**Issue by tuckerburgin** [openmm/openmm#2876]
I am attempting to perform a short minimization step on a system built and equilibrated previously in Amber 18. For some reason however, it seems that even though the model is loaded with the proper coordinates, the simulation.minimizeEnergy() step specifically is resetting the coordinates of my water molecules to the constraints of a small periodic box before beginning the simulation. Here's the code that reproduces the issue:

```python
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *

# Amber files
mutated_rst = 'data/one_frame.rst7'
mutated_top = 'data/my_top.prmtop'

# Load files in OpenMM and build Simulation object
openmm_top = AmberPrmtopFile(mutated_top)
openmm_sys = openmm_top.createSystem(constraints=None, nonbondedMethod=PME, nonbondedCutoff=0.8*nanometer)
openmm_rst = AmberInpcrdFile(mutated_rst)
integrator = LangevinIntegrator(300 * kelvin, 1 / picosecond, 0.002 * picoseconds)
simulation = Simulation(openmm_top.topology, openmm_sys, integrator)
simulation.context.setPositions(openmm_rst.positions)

# Produce PDB file to show that model has been created correctly
pdbfile.PDBFile.writeFile(openmm_top.topology, openmm_rst.positions, open('before_min.pdb', 'w'))

if openmm_rst.boxVectors is not None:   # problem persists without this block
    simulation.context.setPeriodicBoxVectors(*openmm_rst.boxVectors)

# Run minimization
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('min.pdb', 10))
simulation.reporters.append(StateDataReporter(sys.stdout, 1, step=True, potentialEnergy=True, temperature=True))
simulation.step(10)
```

Here are visualizations of the various models (the first two look very slightly different because VMD is explicitly modeling the H-H bond in these TIP3P waters in the first case but not the second, but the coordinates between the two are identical):

![201002_openmm_box](https://user-images.githubusercontent.com/23060814/94937611-ce277100-049d-11eb-8357-e0dd072ef472.png)

What's going on here and how can I make it stop?

**Comment by frank-stonybrook** [comment]
I doubt this might just be a visualization artifact: The OpenMM reporters automatically wrap up the system when write out the coordinates.  If you use **cpptraj** to reimagine your **one_frame.rst7**, you should get something similar. Try the following command in cpptraj:
`
autoimage origin
`

**Comment by Lnaden** [comment]
I agree with @frank-stonybrook. OpenMM translates all of the coordinates into the confined distances of a periodic box when it takes a step.

Now then, as to why this persists if you have the `if openmm_rst.boxVectors is not None:` line or not has to do with your `openmm_top.createSystem` call. Because you specified `nonbondedMethod=PME`, you are requesting a nonbonded method which needs a periodic box, so a box is applied whether you set the vectors or not. I don't remember what the defaults are (or if its implied from the topology file) or not.

**Comment by peastman** [comment]
Exactly.  By specifying `nonbondedMethod=PME` you tell it that your system is periodic.  The specific periodic box vectors are coming from the prmtop file.  If it didn't include any box vectors, `createSystem()` would throw an exception telling you that PME isn't a valid choice for a non-periodic system.

An unusual feature of Amber files is that it stores box vectors in both the prmtop and inpcrd files.  Since your prmtop has box vectors, it uses them.  If your inpcrd also had them, your script would tell it to use those vectors instead.

**Comment by tuckerburgin** [comment]
Ah, yes, you're both right. I hadn't realized that the PDBReporter option 'enforcePeriodicBox' is set to True by default. Setting it to False fixes the "issue."

Thanks both for your help, and thanks @Lnaden for answering followup question that I didn't even ask.
