### ISSUE TITLE
Can I call custom nonbonded force more than one time? 

### ISSUE THREAD

**Issue by LipikaBaidya** [openmm/openmm#2889]
My system is a polymer. Here two types of nonbonded force are present. For example, between particle (i, i+2) and (i,i+3) have energy function is (a/r)^6 . The interaction energy is with rest of particles i.e. (i,i+4),(i,i+5),(i,i+6),.........,(i,i+N) which has the form of LJ type interaction ,[(a/r)^12 - (a/r)^6]. So, to incorporate this two energy function, can I call custom nonbonded force two times?

**Comment by peastman** [comment]
You don't call a force.  You create it and add it to the System.  You can add as many forces as you want of whatever types you want, including multiple forces of the same class.  So yes, you can add multiple CustomNonbondedForce objects if you want.  But in your case, it sounds like one of them should actually be a CustomBondForce.  A bonded force is one that acts between specific sets of particles you enumerate in advance.  So what you want to do is

1. Create a CustomBondForce for the attractive potential, and call `addBond()` to add all the (i, i+2) and (i, i+3) pairs to it.
2. Create a CustomNonbondedForce for the LJ interaction and add all the particles to it.
3. Call `addExclusion()` on the CustomNonbondedForce for all the (i, i+1), (i, i+2), and (i, i+3) pairs.  That tells it not to compute those interactions, since you're handling them differently.

**Comment by LipikaBaidya** [comment]
No, there is no bonded force betetween i,i+2 and i,i+3. In my case, between i,i+2 and i,i+3 , there is replusive nonbonded force like excluded volume of the form (a/r)^6. Between i ans other particles its of LJ kind.
So,
Can i write it like this :
#for excluded volume interaction
Nonbonded_force1 = Openmm.CustomNonbondedForce('(a/r)**6')
Nonbonded_force1.addperparticle('a')
for i in range(N):
           Nonbonded_force1.addparticle(i)
for i in range(N):
         for j in range(i+4,N):
                  Nonbonded_force1.addExclusion(i,j)
#for LJ interaction
Nonbonded_force2 = Openmm.CustomNonbondedForce('(a/r)**12-(a/r)^6')
Nonbonded_force2.addperparticle('a')
for i in range(N):
           Nonbonded_force2.addparticle(i)
for i in range(N):
         for j in range(i+2,i+4): 
                     Nonbonded_force2.addExclusion(i,j)
system.addForce(Nonbonded_force1+Nonbonded_force2)

**Comment by peastman** [comment]
That is, by definition, a bonded force.  This is how OpenMM defines the terms.  A bonded force is one that is evaluated between specific sets of particles that are enumerated in advance.  A nonbonded force is computed between every particle and every other particle.
