### ISSUE TITLE
Potential enhancement: Add option to MonteCarloBarostat to not wrap coordinates into box

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2898]
Currently, the `MonteCarloBarostat` will wrap all positions into the main simulation box each time it attempts to resize the box.

When simulating protein-ligand or protein-protein systems, this can be inconvenient, since it requires expensive operations (like [`mdtraj.Trajectory.image_molecules()](http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html) to re-image and make complexes whole, and even this process is heuristic and not fool-proof. 

It would be useful to have an optional mode for `MonteCarloBarostat` to re-image the molecules back by applying the negative scaled displacement vector after the Monte Carlo scaling operation.

Alternatively, as a work-around, would adding dummy harmonic bonds (with zero spring constants) between pairs of molecules work for ensuring they are imaged together, or would this cause havoc with the barostat were they ever to dissociate?

**Comment by frank-stonybrook** [comment]
This is very interesting! 

> Currently, the MonteCarloBarostat will wrap all positions into the main simulation box each time it attempts to resize the box.

I have a dumb question. Looking at the `MonteCarloBarostat*.cpp` files, I didn't see this wrapping operation. The only place I saw is in `Context.cpp`. Could you point out where it is being performed? 

Second question, for simulating protein-ligand system, what will happen to the `MonterCarlosBarostat` if there is a 'bond' ( a form of restraint) between protein and ligand. Especially, when the ligand drifts out of the primary box.

**Comment by peastman** [comment]
If you add a bond between two molecules, then it will never scale the distance between them.  That's fine as long as they're stuck together, but if they separate and water molecules come between them, it will make the acceptance rate go down.

**Comment by frank-stonybrook** [comment]
> That's fine as long as they're stuck together, but if they separate and water molecules come between them, it will make the acceptance rate go down.

Thanks for sharing the insight @peastman. It's good to know that the volume adjustment will be affected, since I do have a system where the ligand is kept unbound through out the simulation and the water molecules definitely come between them. 
After skipping through the algorithm explanation [here](http://docs.openmm.org/latest/userguide/theory.html#montecarlobarostat), I am trying to understand where does the acceptance rate decreasing comes from.  Given the equation below, 
<img width="382" alt="Screen Shot 2020-10-23 at 14 46 58" src="https://user-images.githubusercontent.com/10855977/97042375-edff0180-153e-11eb-927b-cf214291d3f1.png">

I assume that the failure of scaling the intermolecular distance between ligand and protein can only affect <a href="https://www.codecogs.com/eqnedit.php?latex=\Delta{E}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Delta{E}" title="\Delta{E}" /></a>. But the nonbond interactions (except the one  involving the 'bonded' atom pair or maybe also 1-3, 1-4 pairs) will all properly evaluated according to the minimum image convention, right? I am confused about where this decreasing acceptance rate comes, could you elaborate more on it? Thanks!

**Comment by peastman** [comment]
If some distances are being scaled and others aren't, that effectively means molecules are moving with respect to each other.  That leads to more severe clashes and a larger increase in the energy.

**Comment by frank-stonybrook** [comment]
I don't want to hijack the discussion @jchodera set up here. We had some ligand-protein simulations that ligand will not be wrapped back but the 'bond' energy doesn't look abnormal. I have to take a further look and maybe open a separate issue. Thanks, again!

**Comment by jchodera** [comment]
@peastman: Isn't backward compatibility important here? Shouldn't the
option not to wrap be an optional argument sent to reproduce the previous
behavior by default?

Also, let's PLEASE learn from the 7.6.0 release and become disciplined
about compiling a detailed list of behavior changes with each PR so that we
can disseminate a detailed list of changes with each release. Our former
process does not work: we need to carefully document all bug fixes, new
features, and behavior changes as we go.

**Comment by peastman** [comment]
The former behavior was never documented, and was a frequent source of confusion.  Nothing in the documentation implied it should work that way, and there was no reason anyone would expect it to.  If we added an option to implement that behavior, no one would understand why it existed.  Sometimes, going to extreme lengths to [preserve exact backward compatibility](https://xkcd.com/1172/) is the wrong choice.

> Also, let's PLEASE learn from the 7.6.0 release and become disciplined
about compiling a detailed list of behavior changes with each PR so that we
can disseminate a detailed list of changes with each release.

I don't understand what you mean.  Github maintains a list of all merged PRs.  The PR describes exactly what behavior changed.  Based on that, it's trivial to put together a list.

**Comment by jchodera** [comment]
> The former behavior was never documented, and was a frequent source of confusion. Nothing in the documentation implied it should work that way, and there was no reason anyone would expect it to. If we added an option to implement that behavior, no one would understand why it existed. Sometimes, going to extreme lengths to preserve exact backward compatibility is the wrong choice.

Should this be a "bugfix" then? It should at least be documented under "Changed behaviors" or something.

> I don't understand what you mean. Github maintains a list of all merged PRs. The PR describes exactly what behavior changed. Based on that, it's trivial to put together a list.

THIS DID NOT WORK. This process failed miserably in the release 7.6.0. We even deleted a whole set of Amoeba*Forces from the API and didn't bother to even mention it in the release notes. WE NEED A DIFFERENT SYSTEM FOR PREPARING RELEASE NOTES BECAUSE OUR CURRENT SYSTEM IS BROKEN. I'm still finding reports of codes that were negatively impacted by the 7.6.0 release because of undocumented issues we simply failed to document.

Let's discuss this in https://github.com/openmm/openmm/issues/3232, but it is essential we start building a detailed changelog to be used in the release notes, noting bug fixes, new features, changed behaviors, and deprecated usage, and also compile a running changelog so users can understand when and where we changed behaviors (like this one). Otherwise we are just going to keep causing our users more pain with each release.

**Comment by Dann239** [comment]
@peastman i apologize if i'm mistaken, but aren't we still kind of wrapping coordinates here?

https://github.com/openmm/openmm/blob/b33a7a5a10fb864f9fa63f5f967f48bae340e205/platforms/common/src/CommonKernels.cpp#L7904-L7905

is this intentional? or is this a mistake?

thanks in advance

**Comment by peastman** [comment]
I believe you're right.  Those lines should be removed.  Thanks!

**Comment by peastman** [comment]
The fix is in #3490.
