### ISSUE TITLE
Nan for dU/dLambda with Soft-core LJ and mixed precision.

### ISSUE THREAD

**Issue by adw62** [openmm/openmm#2914]
Hello,

I want to calculate the gradient of a Lennard-Jones Soft-core potential with respect to a alchemical parameter lambda. To test this I have created a box of water where 10 of the waters have their oxygens represented with a `CustomNonbondedForce()`. I have borrowed the form of this `CustomNonbondedForce()` from OpenMMTools and it is a soft-core LJ controlled by the parameter `lambda`. This is the full script I'm using (Please see simplified script I have provided in a later comment): 

```python
from openmmtools.testsystems import PMEWaterBox
from simtk import openmm as mm
from simtk import unit
import copy


def get_sterics_energy_expressions():
    lambda_variable_name = 'lambda'
    sterics_mixing_rules = ('epsilon = sqrt(epsilon1*epsilon2);'  # Mixing rule for epsilon.
                            'sigma = 0.5*(sigma1 + sigma2);')  # Mixing rule for sigma.

    # Soft-core Lennard-Jones.
    exceptions_sterics_energy_expression = ('U_sterics;'
                                            'U_sterics = (({0})^softcore_a)*4*epsilon*x*(x-1.0);'
                                            'x = (sigma/reff_sterics)^6;'
                                            # Effective softcore distance for sterics.
                                            'reff_sterics = sigma*((softcore_alpha*(1.0-({0}))^softcore_b + (r/sigma)^softcore_c))^(1/softcore_c);') \
                                            .format(lambda_variable_name)

    return exceptions_sterics_energy_expression + sterics_mixing_rules

def build_alchemical_context(precision):
    # Get a test system from OpenMMTools and pull out its nonbonded force
    waterbox = PMEWaterBox()
    [system, positions] = [waterbox.system, waterbox.positions]
    for force_index, force in enumerate(system.getForces()):
        if isinstance(force, mm.NonbondedForce):
            nonbonded_force = force

    custom_LJ = mm.CustomNonbondedForce(get_sterics_energy_expressions())

    # Add per particle params to custom force
    custom_LJ.addPerParticleParameter("sigma")  # Lennard-Jones sigma
    custom_LJ.addPerParticleParameter("epsilon")  # Lennard-Jones epsilon

    # add all global params to custom force
    global_params = {'softcore_alpha': 0.5, 'softcore_a': 1, 'softcore_b': 1, 'softcore_c': 6, 'lambda': 1.0}
    for param, value in global_params.items():
        custom_LJ.addGlobalParameter(param, value)

    # Add param for derivative computation.
    custom_LJ.addEnergyParameterDerivative('lambda')

    # making some oxygens in the 3p waters alchemical
    alchemical_atoms = [i * 3 for i in range(10)]
    all_atoms = range(nonbonded_force.getNumParticles())
    non_alchemical_atoms = [x for x in all_atoms if x not in alchemical_atoms]

    for atom in all_atoms:
        q, sig, eps = nonbonded_force.getParticleParameters(atom)
        if atom in alchemical_atoms:
            # Turn off LJ for alchemical atoms in the nonbonded this will be computed by custom forces
            nonbonded_force.setParticleParameters(atom, q, 1.0, 0.0)

        # add all particles to custom force turned on
        custom_LJ.addParticle([sig, eps])

    # exception are not needed for physics here but must exist in CustomNonbondedForce
    for exception_index in range(nonbonded_force.getNumExceptions()):
        iatom, jatom, chargeprod, sig, eps = nonbonded_force.getExceptionParameters(exception_index)
        custom_LJ.addExclusion(iatom, jatom)

    # Set meta params of custom force to match nonbonded
    custom_LJ.setUseSwitchingFunction(nonbonded_force.getUseSwitchingFunction())
    custom_LJ.setCutoffDistance(nonbonded_force.getCutoffDistance())
    custom_LJ.setSwitchingDistance(nonbonded_force.getSwitchingDistance())
    custom_LJ.setUseLongRangeCorrection(nonbonded_force.getUseDispersionCorrection())
    custom_LJ.setNonbondedMethod(mm.CustomNonbondedForce.CutoffPeriodic)

    # Make forces for alchemical-alchemical (aa) and alchemical-non_alchemical (na) interactions
    aa_LJ = copy.deepcopy(custom_LJ)
    na_LJ = copy.deepcopy(custom_LJ)

    # restrict custom forces to there respective groups
    aa_LJ.addInteractionGroup(alchemical_atoms, alchemical_atoms)
    na_LJ.addInteractionGroup(non_alchemical_atoms, alchemical_atoms)

    system.addForce(aa_LJ)
    system.addForce(na_LJ)

    # Build intergrator, context and set positions
    integrator = mm.LangevinIntegrator(300 * unit.kelvin, 0.3 / unit.picosecond, 2.0 * unit.femtosecond)
    platform = mm.Platform.getPlatformByName('CUDA')
    properties = {'CudaPrecision': precision, 'CudaDeviceIndex': '0'}
    context = mm.Context(system, integrator, platform, properties)
    context.setPositions(positions)

    return context

if __name__ == '__main__':

    for precision in ['mixed', 'double']:

        #Load a system, make it alchemical and build a context
        context = build_alchemical_context(precision)

        print('### Precision', precision)
        print('Minimizing')
        mm.LocalEnergyMinimizer.minimize(context)

        lam_schedual = [1.0, 0.0]
        # Iterate over a lambda schedule
        for lam in lam_schedual:

            #Check values of potential around current lambda
            for param_val in [lam-0.001, lam, lam+0.001]:
                context.setParameter('lambda', param_val)
                print('Potential for lambda = {}:'.format(param_val),
                      context.getState(getEnergy=True).getPotentialEnergy().in_units_of(
                          unit.kilocalorie_per_mole))

            context.setParameter('lambda', lam)
            dEdlam = context.getState(getParameterDerivatives=True).getEnergyParameterDerivatives()
            for energy_derivatives in dEdlam:
                if energy_derivatives == 'lambda':
                    grad = dEdlam[energy_derivatives]*unit.kilojoule_per_mole
                    print('Lambda = {}, dU/dlam:'.format(lam), grad.in_units_of(unit.kilocalorie_per_mole))

```

The problem I'm having is that for mixed precision the value of the gradient calculated for Lambda = 0, 1 is nan. Using double precision I'm able to calculate the gradient without issue. As a check I'm printing out the gradient and the value of the potential for 'nearby' values of lambda and can see that for values of lambda < 0 and lambda > 1 the potential will also nan. This is my output:

```
### Precision mixed
Minimizing
Potential for lambda = 0.999: -5907.317541525722 kcal/mol
Potential for lambda = 1.0: -5907.070211430668 kcal/mol
Potential for lambda = 1.001: nan kcal/mol
Lambda = 1.0, dU/dlam: nan kcal/mol
Potential for lambda = -0.001: nan kcal/mol
Potential for lambda = 0.0: -5953.491719282205 kcal/mol
Potential for lambda = 0.001: -5953.5076332905255 kcal/mol
Lambda = 0.0, dU/dlam: nan kcal/mol
### Precision double
Minimizing
Potential for lambda = 0.999: -5907.480101524413 kcal/mol
Potential for lambda = 1.0: -5907.233187235826 kcal/mol
Potential for lambda = 1.001: nan kcal/mol
Lambda = 1.0, dU/dlam: 247.49095575758105 kcal/mol
Potential for lambda = -0.001: -5953.535559612313 kcal/mol
Potential for lambda = 0.0: -5953.551541672032 kcal/mol
Potential for lambda = 0.001: -5953.5674960409515 kcal/mol
Lambda = 0.0, dU/dlam: -15.968228527770806 kcal/mol
```

Is my problem here that I cannot calculate this gradient with mixed precision or is there another problem? Is there a form of the soft-core which would allow this derivative to be calculated in mixed precision? Any help would be greatly appreciated.

Thanks,
Alex

**Comment by Bio-Otto** [comment]
Maybe using ```
NonbondedForce.updateParametersInContext()
``` command can solve the problem.

**Comment by adw62** [comment]
Would you mind please giving some more detail on where you think this function should be called, it is not clear to me when you think I should use it?

**Comment by Lnaden** [comment]
It's a bit hard to tell what exactly is going on here due to the complexity of your system, however, there are a few things I think I see which might be causing the problems.

> ```
>    for atom in all_atoms:
>        q, sig, eps = nonbonded_force.getParticleParameters(atom)
>        if atom in alchemical_atoms:
>            # Turn off LJ for alchemical atoms in the nonbonded this will be computed by custom forces
>            nonbonded_force.setParticleParameters(atom, q, 1.0, 0.0)
>```
You are technically adding 2 additional `CustomNonbondedForce`s on top of the existing Nonbonded Force; but you are also mutating the normal `NonbondedForce` in a strange way. You set the partial charges here and then both sigma and epsilon to 1, instead of setting the `epsilon` to 0. I don't know what that will do to your system and the NaN's, but I can say it's going to cause weird interactions. 

> see that for values of lambda < 0 and lambda > 1 the potential will also nan

That softcore function isn't technically defined for lambda outside of the `[0, 1]` domain. I would not put much stock in values outside of that, especially for those `< 0`.

> Maybe using NonbondedForce.updateParametersInContext() command can solve the problem.

Because your parameters are `Global`, this function will not have any affect on this `Context`.

There might be some other oddities going on here, but I'm not convinced this is a mixed vs double problem yet. Can you simplify the system? Is this deterministic error or does it calculate correctly some times?

**Comment by adw62** [comment]
@Lnaden Thank for you comments, I agree the system is too complex please see the following where I have tried to simplify more:

```python
import numpy as np
from simtk.openmm import System, CustomNonbondedForce, LangevinIntegrator, Platform, Context
from simtk.unit import (dalton, nanometer, kilojoule_per_mole, kelvin, femtosecond, picosecond)


def get_sterics_energy_expressions():
    lambda_variable_name = 'lambda'
    sterics_mixing_rules = ('epsilon = sqrt(epsilon1*epsilon2);'  # Mixing rule for epsilon.
                            'sigma = 0.5*(sigma1 + sigma2);')  # Mixing rule for sigma.

    # Soft-core Lennard-Jones.
    exceptions_sterics_energy_expression = ('U_sterics;'
                                            'U_sterics = (({0})^softcore_a)*4*epsilon*x*(x-1.0);'
                                            'x = (sigma/reff_sterics)^6;'
                                            # Effective softcore distance for sterics.
                                            'reff_sterics = sigma*((softcore_alpha*(1.0-({0}))^softcore_b + (r/sigma)^softcore_c))^(1/softcore_c);') \
                                            .format(lambda_variable_name)

    return exceptions_sterics_energy_expression + sterics_mixing_rules

for precision in ['mixed', 'double']:

    print(precision)

    system = System()
    system.addParticle(1 * dalton)
    system.addParticle(1 * dalton)

    custom_LJ = CustomNonbondedForce(get_sterics_energy_expressions())
    custom_LJ.setNonbondedMethod(CustomNonbondedForce.NoCutoff)

    # Add per particle params to custom force
    custom_LJ.addPerParticleParameter("sigma")  # Lennard-Jones sigma
    custom_LJ.addPerParticleParameter("epsilon")  # Lennard-Jones epsilon

    # add all global params to custom force
    global_params = {'softcore_alpha': 0.5, 'softcore_a': 1, 'softcore_b': 1, 'softcore_c': 6, 'lambda': 1.0}
    for param, value in global_params.items():
        custom_LJ.addGlobalParameter(param, value)

    # Add param for derivative computation.
    custom_LJ.addEnergyParameterDerivative('lambda')

    custom_LJ.addParticle([1 * nanometer, 1 * kilojoule_per_mole])
    custom_LJ.addParticle([1 * nanometer, 1 * kilojoule_per_mole])
    system.addForce(custom_LJ)

    temperature = 300*kelvin
    timestep = 2. * femtosecond
    freq = 1/picosecond

    integ_eq = LangevinIntegrator(temperature, freq, timestep)
    platform = Platform.getPlatformByName('CUDA')
    properties = {'CudaPrecision': precision, 'CudaDeviceIndex': '0'}
    context = Context(system, integ_eq, platform, properties)

    positions = [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0]] * nanometer
    box_vectors = 5 * np.identity(3) * nanometer
    context.setPositions(positions)
    context.setPeriodicBoxVectors(*box_vectors)

    for lam in [1.0, 0.5, 0.0]:
        context.setParameter('lambda', lam)
        dEdlam = context.getState(getParameterDerivatives=True).getEnergyParameterDerivatives()
        for energy_derivatives in dEdlam:
            if energy_derivatives == 'lambda':
                grad = dEdlam[energy_derivatives]*kilojoule_per_mole
                print('Lambda = {}, dU/dlam:'.format(lam), grad)
```

> You set the partial charges here and then both sigma and epsilon to 1, instead of setting the epsilon to 0. I don't know what that will do to your system and the NaN's, but I can say it's going to cause weird interactions.

I thought I was setting epsilon to 0 here but in any case the revised script does not use this line

> That softcore function isn't technically defined for lambda outside of the [0, 1] domain. I would not put much stock in values outside of that, especially for those < 0.

> Because your parameters are Global, this function will not have any affect on this Context.

I agree with both these points. 

> Is this deterministic error or does it calculate correctly some times?

Deterministic as far as I can tell, I get the error on every run. My output for the revised script is:

```
mixed
Lambda = 1.0, dU/dlam: nan kJ/mol
Lambda = 0.5, dU/dlam: -0.2559991776943207 kJ/mol
Lambda = 0.0, dU/dlam: nan kJ/mol
double
Lambda = 1.0, dU/dlam: 2.0 kJ/mol
Lambda = 0.5, dU/dlam: -0.25599999999999956 kJ/mol
Lambda = 0.0, dU/dlam: -0.8888888888888894 kJ/mol
```

**Comment by peastman** [comment]
Here is what the automatic differentiation code produces for the derivative of energy with respect to lambda:

`((((4*((lambda)^(softcore_a)))*(sqrt((epsilon1)*(epsilon2))))*(((0.5*((sigma1)+(sigma2)))/((0.5*((sigma1)+(sigma2)))*((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(recip(softcore_c)))))^6))*((-6*(((0.5*((sigma1)+(sigma2)))/((0.5*((sigma1)+(sigma2)))*((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(recip(softcore_c)))))^5))*(((0.5*((sigma1)+(sigma2)))*((0.5*((sigma1)+(sigma2)))*((((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(-1+(recip(softcore_c))))/(softcore_c))*((softcore_alpha)*(-1*((softcore_b)*(((1)-(lambda))^(-1+(softcore_b)))))))))/(square((0.5*((sigma1)+(sigma2)))*((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(recip(softcore_c))))))))+((-1+(((0.5*((sigma1)+(sigma2)))/((0.5*((sigma1)+(sigma2)))*((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(recip(softcore_c)))))^6))*((((4*((lambda)^(softcore_a)))*(sqrt((epsilon1)*(epsilon2))))*((-6*(((0.5*((sigma1)+(sigma2)))/((0.5*((sigma1)+(sigma2)))*((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(recip(softcore_c)))))^5))*(((0.5*((sigma1)+(sigma2)))*((0.5*((sigma1)+(sigma2)))*((((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(-1+(recip(softcore_c))))/(softcore_c))*((softcore_alpha)*(-1*((softcore_b)*(((1)-(lambda))^(-1+(softcore_b)))))))))/(square((0.5*((sigma1)+(sigma2)))*((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(recip(softcore_c))))))))+((((0.5*((sigma1)+(sigma2)))/((0.5*((sigma1)+(sigma2)))*((((softcore_alpha)*(((1)-(lambda))^(softcore_b)))+(((r)/(0.5*((sigma1)+(sigma2))))^(softcore_c)))^(recip(softcore_c)))))^6)*((sqrt((epsilon1)*(epsilon2)))*(4*((softcore_a)*((lambda)^(-1+(softcore_a)))))))))`

Pretty horrifying, isn't it?  Because the expression contains so many variables, it's really hard to optimize.  (It also looks worse than it is because everything is completely expanded out.  Don't worry, it does common subexpression elimination when converting it to code.)  Unfortunately this contains various subexpressions that under the wrong circumstances evaluate to nan.  For example, `((1)-(lambda))^(-1+(softcore_b))`  When `lambda` and `softcore_b` are both 1, that becomes 0^0 = nan.

Rather than using global parameters for the constants, I suggest hardcoding them in the expression.  That is, add `softcore_alpha=0.5; softcore_a=1; softcore_b=1; softcore_c=6` to your expression.  That will let it optimize much more effectively.  For example, it will do the optimization `((1)-(lambda))^(-1+(softcore_b))` = `(1-lambda)^(-1+1)` = `(1-lambda)^0` = `1`.  With that change, the nans go away.

**Comment by adw62** [comment]
Yes that's a pretty scary expression, I can see why it was having trouble evaluating. Thank you for the help, the suggested change has fixed my problem.
