### ISSUE TITLE
windows - HelloArgon - no registered Platform called "CUDA"

### ISSUE THREAD

**Issue by biocodz** [openmm/openmm#2938]
Using OpenMM built from git sources on Windows with VS2019 and CUDA 10.1.
HelloArgon modified:
```
...
printf("Number of registered platforms: %d\n", OpenMM::Platform::getNumPlatforms());
std::vector<std::string> errl = OpenMM::Platform::getPluginLoadFailures();
for (int i = 0; i < errl.size(); ++i) printf("%s\n", errl[i].c_str()); // nothing
OpenMM::Context context(system, integrator, OpenMM::Platform::getPlatformByName("CUDA"));
...
```
The output:
```
Number of registered platforms: 1
EXCEPTION: There is no registered Platform called "CUDA"
```
The CUDA toolkit binaries are on the PATH.
`TestCudaAndersenThermostat` runs OK -> CUDA is OK apparently.

What do I do to make OpenMM to find/register CUDA?

Thank you

**Comment by peastman** [comment]
Since it only has one registered platform (reference), and doesn't report any errors loading plugins, this most likely means you didn't load plugins from the correct directory.  Right at the very beginning of `simulateArgon()` are the lines

```c++
    OpenMM::Platform::loadPluginsFromDirectory(
        OpenMM::Platform::getDefaultPluginsDirectory());
```

That's where it loads the plugins.  Since you built from source, `getDefaultPluginsDirectory()` probably isn't returning whatever directory you had it install the plugins into.  (That should be `<OpenMM install directory>\lib\plugins`.)  There are two easy ways to fix this.  One is to change the code to specify the correct directory.  The other is to set the environment variable `OPENMM_PLUGIN_DIR`, in which case `getDefaultPluginsDirectory()` will return whatever location it points to.

**Comment by biocodz** [comment]
Thanks a lot for the prompt response!
I guess `OpenMMCUDA.dll` is the right plugin.
Just pointed the debugger to  `OPENMM_PLUGIN_DIR=...\openmm\build\Debug\` and now seeing `Number of registered platforms: 3`...yeeha!
