### ISSUE TITLE
Recommended settings for LangevinMiddleIntegrator

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#2965]
I've been experimenting a bit with LangevinMiddleIntegrator and I'm not quite sure what settings to use.

The benchmark script seems to use this for the pme test:
```
method = app.PME
cutoff = 0.9*unit.nanometers
dt = 0.004*unit.picoseconds
constraints = app.HBonds
integ = mm.LangevinMiddleIntegrator(300*unit.kelvin, friction, dt)
```

and same for apoa1pme, except with:
```
hydrogenMass = 1.5*unit.amu
```

I tried the same settings (without hydrogenMass) in my system and 7 out of 9 replicas crashed in less than a million steps with "Particle position is NaN".  This is in a system which is stable long-term with LangevinIntegrator and 2fs steps (it's a medium-sized protein, amber14sb force field and tip3p water, nothing unusual).

Is LangevinMiddleIntegrator with 4fs steps really recommended for general use? How do I make it work in my system?  (also why use hydrogenMass=1.5 for apoa1 in the benchmark?)  

I definitely like the speedup, so would love to be able to use it :)

(openmm=7.5.0, cuda 10.1, v100 gpu)

**Comment by aizvorski** [comment]
P.S. Also just to confirm, LangevinMiddleIntegrator is the same thing as the earlier BAOABLangevinIntegrator from this repo or "BAOAB" / "VRORV" from Leimkuhler and Matthews 2015?

**Comment by peastman** [comment]
You probably want to use a little bit of hydrogen mass repartitioning.  In the benchmark script the ApoA1 benchmark was frequently crashing, and increasing the hydrogen mass fixed it.  I didn't do that with DHFR because it didn't seem to be necessary.  In OpenMM-Setup, the default is 1.5 amu.  That seems to be enough to get stability with 4 fs in most cases, while being small enough not to affect the dynamics much.

> P.S. Also just to confirm, LangevinMiddleIntegrator is the same thing as the earlier BAOABLangevinIntegrator from this repo or "BAOAB" / "VRORV" from Leimkuhler and Matthews 2015?

Almost.  It's a leapfrog version of the same discretization.  It turns out that the on-step velocities returned by BAOAB are a very poor representation of the thermal distribution, reflecting a temperature that's often about 15-20% too low.  The half-step velocities, on the other hand, are right on.  See https://pubs.acs.org/doi/abs/10.1021/acs.jpca.9b02771.

**Comment by aizvorski** [comment]
@peastman Thank you, I tested and looks like hydrogenMass=1.5 fixes this.  Also this system does have a small part that was parametrized in GAFF, not just a protein (sorry I should have checked more carefully which version I was running).  I'll do a few tests next week to see if there are similar issues without the GAFF part.
