### ISSUE TITLE
Rename python module?

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2997]
This question came up recently in #2991.  I've thought for a long time it would be nice if we could drop the `simtk` prefix from the Python modules.  It's only there for historical reasons, and it creates extra clutter.  `simtk.openmm` would become just `openmm.`   `simtk.openmm.app` would become `openmm.app`.  `simtk.unit` would become `openmm.unit`.

It would be essential to do this in a way that doesn't break compatibility with existing code.  I believe we could do that by keeping around the existing packages, but making them just be aliases for the new ones.  For example, `simtk.openmm` would contain an `__init__.py` file that reads

```python
from openmm import *
```

If we made this change, we could also update the module names for plugins that get installed separately.  `openmmtorch` could become `openmm.torch`, `openmmplumed` could become `openmm.plumed`, etc.

**Comment by proteneer** [comment]
This is a fantastic idea! Note that for ```simtk.unit``` there's actually a stand alone package in pypi https://pypi.org/project/simtk.unit/ that was initially maintained by @rmcgibbo.

We actually use the pypi package in some non-openmm projects as well and I was wondering if it was possible to keep that library decoupled still.

**Comment by jchodera** [comment]
Would love to hear thoughts from others on whether this is an opportunity to create a more Pythonic Python API that breaks free of legacy naming and other choices from the C++ API and harmonizes with modern efforts such as the [Open Force Field Initiative](http://openforcefield.org) standards, such as:
* PEP8 naming conventions
* Pythonic idioms (e.g. iterators)
* Modern unit systems that can check dimensionality (e.g. [pint](https://pint.readthedocs.io/en/stable/), [unyt](https://unyt.readthedocs.io/en/stable/))

**Comment by raimis** [comment]
@peastman, I agree!

The import names should be consistent with the package names.

`openmm` package provides:
```python
from openmm import *
```
`openmm-plumed` package provides:
```python
from openmm.plumed import *
```
and so on.

**Comment by peastman** [comment]
> Note that for simtk.unit there's actually a stand alone package in pypi https://pypi.org/project/simtk.unit/ that was initially maintained by @rmcgibbo.

It looks like that was last updated in 2014, so it's pretty far out of date.

> Would love to hear thoughts from others on whether this is an opportunity to create a more Pythonic Python API

I think that's its own issue.  Let's keep this one just to the package names.  Feel free to open a separate issue for other questions.

**Comment by mattwthompson** [comment]
Sounds like a great idea, while maintaining backwards compatibility (in both the core API and the units package) 

* Simpler and more consistent branding: I don't know what SimTK really is, as somebody who has only followed OpenMM for the past 2-3 years. I like the consistency and aesthetics of packages named `openmm-thing` with imports like `openmm.thing`, this is something we're doing at OpenFF and like so far. 
* Shorter imports: it's not overbearingly long, but every time I type ('simtk.`) it feels like something that could be done without

I'd be happy to chime in some of the other follow-on topics (other unit packages, in particular) in separate issues.

**Comment by giadefa** [comment]
yes, I would also like to remove simtk

**Comment by Lnaden** [comment]
I am all on board for the moving from the `simtk` namespace to just `openmm` namespace. It would make things cleaner and easier to understand I think for new people getting into OpenMM.

> `simtk.unit` would become `openmm.unit`

Yes please. 

> openmmtorch could become openmm.torch, openmmplumed could become openmm.plumed, etc.

My one caution here is we'll need to be careful of what exactly is imported at the `openmm` level. E.g. If someone is just looking to get the `units` submodule, we may not want to have them import all of OpenMM and its plugins as well. 

It would be nice to have the `simtk` namespace generate a `DeprecationWarning`, `ImportWarning` or something to let users know there is a unified namespace they can access.

**Comment by jaimergp** [comment]
+1!

I am not sure about plugins sharing a namespace. Maybe `openmm.plugins` if anything. 

The OFF team has gone through a `openforcefield` -> `openff.toolkit` namespace migration just now, so they might have some pointers and advice too.

**Comment by rmcgibbo** [comment]
Removing the `simtk` namespace sounds good to me, and I think ya'll are right to separate that from any other discussions about API organization or naming. I'm also happy to yank `simtk.unit` from pypi or transfer ownership of it on pypi to any of you; just ping me if you want that.

**Comment by peastman** [comment]
> My one caution here is we'll need to be careful of what exactly is imported at the openmm level. E.g. If someone is just looking to get the units submodule, we may not want to have them import all of OpenMM and its plugins as well.

Do you have any suggestions about that?  Loading a submodule necessarily loads the parent module.  So `import openmm.unit` would involve loading the `openmm` module, but not other submodules like `openmm.app` or `openmm.torch`.

> It would be nice to have the simtk namespace generate a DeprecationWarning

Good idea.

**Comment by swails** [comment]
> We actually use the pypi package in some non-openmm projects as well and I was wondering if it was possible to keep that library decoupled still.

FWIW, ParmEd packages `simtk.unit` as well so you could always pull it from there.  The approach taken there has the side-benefit of working correctly whether OpenMM is installed or not (that is, `parmed.unit.nanometer is simtk.unit.nanometer`) which makes cooperation between the packages seamless.

**Comment by jchodera** [comment]
@peastman @mattwthompson @j-wags : Let's open a new issue to discuss the units thing. It would be _immensely_ valuable (with no real downside) if we were able to transition to one of the better-supported unit-handling packages that can also handle dimensionality checking.

**Comment by peastman** [comment]
> one of the better-supported unit-handling packages that can also handle dimensionality checking.

You keep saying that, and I still have no clue what you mean by it.  OpenMM's units system does dimensionality checking.

```
>>> a = 1*nanometers
>>> a.value_in_unit(picoseconds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/unit/quantity.py", line 621, in value_in_unit
    val = self.in_units_of(unit)
  File "/Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/unit/quantity.py", line 657, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "nanometer" is not compatible with Unit "picosecond".
```

**Comment by swails** [comment]
Do you have an example where pint is clearly superior to simtk.unit (where the former works and the latter doesn't, or the former is correct and the latter isn't)?

I know OpenFF uses pint, and transitioning OpenMM to pint would eliminate that translation layer, but 
without examples it's hard to see the benefit (especially when openff settled on pint well after simtk.unit was adopted and mature). 

ParmEd bundles simtk.unit and integrates seamlessly with OpenMM because of it. Switching to pint will complicate several things. The transition will be painful for programs and libraries like ParmEd that need to support multiple versions of OpenMM around the transition point. And a lot of client code will need to be rewritten, or substantial effort would need to be invested to make pint fully (enough) api compatible with the current units package. Either way there is real cost, and I don't know that everyone agrees that the benefit justifies the cost. Specific examples would go a long way toward making that case.

**Comment by jchodera** [comment]
> Do you have an example where pint is clearly superior to simtk.unit (where the former works and the latter doesn't, or the former is correct and the latter isn't)?

Here's just one of many: Providing `Quantity` objects to OpenMM functions with incorrect dimensionality is a major class of user error for OpenMM. I and the members of my laboratory have repeatedly had this bite them, where OpenMM will happily consume quantities with incorrect dimensions and convert them into meaningless gibberish values (which are almost guaranteed to cause hard-to-spot scientific errors) without any warning whatsoever.

Both [pint](https://pint.readthedocs.io/en/stable/wrapping.html#:~:text=Checking%20dimensionality,dimensionality%20of%20the%20physical%20quantity) and [unyt](https://unyt.readthedocs.io/en/stable/usage.html#checking-units) provide dimensionality-checking capabilities (see links) that would completely eliminate this major class of user error.

> without examples it's hard to see the benefit (especially when openff settled on pint well after simtk.unit was adopted and mature).

`simtk.unit` is still immature, and still silently fails to do the right thing in a number of obvious cases. For example:
```python
>>> from simtk import unit
>>> import numpy as np
>>> x = unit.Quantity(np.ones([10,3]), unit.angstroms)
>>> x.sum(axis=1)
Quantity(value=array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]), unit=angstrom)
```
but
```python
>>> x.prod(axis=1)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```
As @rmcgibbo succinctly stated in https://github.com/openmm/openmm/issues/690, trying to patch `simtk.unit` to provide numpy compatibility is "a neverending black hole". We just don't have the right design. It's just not a mature package, and probably never will be due to design limitations.

`simtk.unit` is also incredibly slow. Converting to/from units is a major bottleneck in any code that uses the OpenMM classes as container objects.

And, as was stressed before, the overhead of maintaining converters between (immature) `simtk.unit` and (mature) packages like `pynt` and `unyt` is substantial, and needs to be present in every code that uses these mature packages.

`simtk.unit` was a great idea ten years ago, but now is the right time to pay for the technical debt accumulated by failing to keep up with modern mature unit-handling implementations.

**Comment by jchodera** [comment]
> ParmEd bundles simtk.unit and integrates seamlessly with OpenMM because of it. Switching to pint will complicate several things. The transition will be painful for programs and libraries like ParmEd that need to support multiple versions of OpenMM around the transition point. And a lot of client code will need to be rewritten, or substantial effort would need to be invested to make pint fully (enough) api compatible with the current units package. Either way there is real cost, and I don't know that everyone agrees that the benefit justifies the cost. Specific examples would go a long way toward making that case.

To make this easier, it would make sense to keep legacy `simtk.openmm` and `simtk.unit` compatibility throughout OpenMM 8, with deprecation warnings, but adopt a modern units system for the new `openmm.*` namespace methods.

**Comment by swails** [comment]
> Here's just one of many: Providing `Quantity` objects to OpenMM functions with incorrect dimensionality is a major class of user error for OpenMM.

This isn't simtk.unit's fault, this is a consequence of the Forces themselves not enforcing their dimensions -- they call `value_in_unit_system` instead of `value_in_unit`.  That is the problem that needs to be fixed here, and it would need to be fixed regardless of whether or not we switched packages (but once fixed for pint or unyt, would also be fixed for simtk.unit).

The problem would be substantially more difficult when it came to dealing with custom forces and integrators -- expected units would need to be inferred from the energy equation which strikes me as a very involved exercise to make rigorously correct.  `value_in_unit_system` is an imperfect, though convenient and largely helpful shortcut.

> As @rmcgibbo succinctly stated in #690, trying to patch `simtk.unit` to provide numpy compatibility is "a neverending black hole". We just don't have the right design.

The lack of numpy compatibility is a better argument (assuming, of course, that pint and unyt just "Do The Right Thing (TM)").  I have yet to encounter a situation where more complete (and correct) treatment of numpy ufuncs and vector methods would be beneficial to me, but it's not hard to envision a situation where it would be useful to others.

I'm not sure that OpenMM itself would directly benefit much from that.  Nor have I looked at all at how burdensome the pint<->simtk.unit translation layers that OpenFF and friends need to use to integrate with OpenMM while using pint internally really are.  That said, those translation layers are already *there*, so it strikes me that the primary beneficiaries of a move would be future projects, with the primary casualties would be existing projects and scripts.

> It's just not a mature package, and probably never will be due to design limitations.

At the risk of splitting hairs here, `simtk.unit` *is* mature.  It's been around for a long time and has required very few changes.  But it still actively receives some (like @peastman's recent improvement for numerical stability).  For very many use-cases, it is completely sufficient.  It "just works", and in my hands has worked as expected every time I've used it except one (`dalton` seems to have the wrong dimensionality and is incompatible with `gram` which seems wrong to me).

I'll accept it's not as feature rich, performant, or as well-designed as alternatives, but it is definitely not immature.

**Comment by peastman** [comment]
> Providing Quantity objects to OpenMM functions with incorrect dimensionality is a major class of user error for OpenMM.

This has nothing to do with the units classes.  It's just that it doesn't know what dimension a particular function is expecting.  You can tell it that in swigInputConfig.py.  For example,

https://github.com/openmm/openmm/blob/eff1f26e904dda804104eda4b423c1c4dea3d7ac/wrappers/python/src/swig_doxygen/swigInputConfig.py#L179

That tells it the value should be converted to bar, and if you provide a value that can't be converted it throws an exception:

```
>>> barostat.setDefaultPressure(1*nanometer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/openmm.py", line 6231, in setDefaultPressure
    pressure = pressure.value_in_unit(unit.bar)
  File "/Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/unit/quantity.py", line 621, in value_in_unit
    val = self.in_units_of(unit)
  File "/Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/unit/quantity.py", line 657, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "nanometer" is not compatible with Unit "bar".
```

No one has ever taken the time to go through and fill in the expected units for every argument of every method, but if you feel motivated to do it, that would be great.  Switching to a different units package wouldn't make any difference.  It still wouldn't magically know the expected units of every method.  Someone has to tell it that.

> We just don't have the right design. It's just not a mature package, and probably never will be due to design limitations.

I agree with @swails: that just isn't true.  It's a very mature package.  It's been incredibly stably and almost completely bug free for years.

What do you feel is the "right design"?

> simtk.unit is also incredibly slow. Converting to/from units is a major bottleneck in any code that uses the OpenMM classes as container objects.

You've made that claim on various occasions, but whenever someone provides a test case to demonstrate it, the bottleneck almost always ends up being somewhere else.  Can you provide a test case where OpenMM's units are substantially slower than the other packages?  It may turn out to be trivial to optimize, but without a concrete example I can't say more.

**Comment by jchodera** [comment]
Folks, I think this turned out to be more antagonistic that I had intended. I think `simtk.unit` has served us incredibly well and been an incredibly useful tool, but I think we should be able to take advantage of the numerous advantages offered by these more modern unit packages. We want to do this in a way that is mindful of the work it would take to migrate tools that use `simtk.unit`.

Let me first address some of the feedback, and then propose some alternatives.

> This has nothing to do with the units classes. It's just that it doesn't know what dimension a particular function is expecting. You can tell it that in swigInputConfig.py.

The issue of incompatible dimensionalities extends beyond just SWIG-wrapped functions, and into everything in our Python layer and everything built on top of OpenMM as well. Both pint and unyt provide decorators ([pint](https://pint.readthedocs.io/en/stable/wrapping.html#:~:text=Checking%20dimensionality,dimensionality%20of%20the%20physical%20quantity) and [unyt](https://unyt.readthedocs.io/en/stable/usage.html#checking-units)) that enable a very simple scheme for adding dimensionality-checking capabilities to all code.

Separately: If we aren't currently doing this for OpenMM SWIG-wrapped methods right now, we should probably add that!

> I agree with @swails: that just isn't true. It's a very mature package. It's been incredibly stably and almost completely bug free for years.

I think it's important to distinguish between "has stopped changing" and "has solved all the major issues". We've not yet managed to do that with `simtk.unit` with numpy compatibility (as evidenced by the `quantity.sum()` and `quantity.prod()` giving correct and incorrect results), provide dimensionality checking, and incompatibility with modern unit packages.

> What do you feel is the "right design"?

I don't have opinions on the architecture, but libraries like pint have been deployed and tested orders of magnitude more broadly than OpenMM, and it would seem that they have overcome of these limitations.

> You've made that claim on various occasions, but whenever someone provides a test case to demonstrate it, the bottleneck almost always ends up being somewhere else. Can you provide a test case where OpenMM's units are substantially slower than the other packages? It may turn out to be trivial to optimize, but without a concrete example I can't say more.

Here's the simplest demonstration of an issue we ran into, showing a 19x speed difference for what should otherwise be incredibly lightweight operations:
![image](https://user-images.githubusercontent.com/3656088/106421304-551b3480-6411-11eb-84a2-548bdacfbf88.png)

Because units are attached to returned quantities, this kind of overhead is often unavoidable with the current OpenMM Python API.

Now, I'm certainly not sure if other unit-handling packages are faster, or how to optimize them. but there are at least some limitations of the current system that it would be great to identify ways to address:
* Incompatibility with modern systems of pint and unyt. Instead of every OpenMM-based tool needing to engineer their own solution, we should see if we can address this at the OpenMM level.
* Incorrect results (e.g. with numpy computations) 
* Offering a way to avoid the overhead of unit-handling on input and output
* Ensuring dimensionality is checked when unit-bearing quantities are provided, and making it easy for apps built on top of OpenMM to do the same

**Comment by proteneer** [comment]
I agree with @jchodera thatmaking ```simtk.unit``` to be more numpy friendly is important. In my case, it would be even nicer if the package were compatible with jax as well! However, I'd rather we find ways to improve the existing ```simtk.unit``` package than to migrate to another less battle-tested (in our community) like pint, despite its very appealing webpage.

**Comment by jchodera** [comment]
@proteneer : Is there anything we could do to make it easier to adopt an OpenMM-like API to timemachine, or make it easier to interoperate between OpenMM and timemachine? Packages like timemachine are the kind of ML-enabled future we'd love to support, so any insight you had for how to make these worlds more interoperable would be welcomed!

**Comment by proteneer** [comment]
Possibly - but I think we should talk about this offline or in a separate timemachine issue so as to not derail this one.

**Comment by swails** [comment]
I don't think this has turned antagonistic, nor do I think anybody here has a purely emotional attachment to `simtk.units`.  The proposed change of unit systems is a profound change that will have a huge impact on the entire OpenMM ecosystem. 

Unless the unit system replacement is made fully API-compatible with simtk.unit, every existing tutorial, script, and library will break with "new" versions of OpenMM.  Employing a deprecation period is a likely significant engineering effort, since unit handling is too tightly coupled to OpenMM to assume you can easily support simtk.unit and pint simultaneously.  In particular, I'm strongly disputing the claim "(with no real downside)", and am still a little skeptical of describing the value as "immense".

> Both pint and unyt provide decorators ([pint](https://pint.readthedocs.io/en/stable/wrapping.html#:~:text=Checking%20dimensionality,dimensionality%20of%20the%20physical%20quantity) and [unyt](https://unyt.readthedocs.io/en/stable/usage.html#checking-units)) that enable a very simple scheme for adding dimensionality-checking capabilities to all code.

Such a decorator would be trivial to add to `simtk.unit`, especially compared to swapping unit systems.  The point is that `simtk.unit` handles dimensionality and detects incompatible dimensions with a ValueError.  Dimension checking doesn't come for free - the programmer needs to specify what dimensions to expect, which works equally well with simtk.unit as it does with pint and unyt.

> I think it's important to distinguish between "has stopped changing" and "has solved all the major issues".

Sure, but this isn't maturity.  Even if simtk.unit hasn't resolved all major issues as a general-purpose unit package, it has for handling units with OpenMM. Swapping units package would actually reduce our general maturity at first as we would know less about corner cases, general performance, gotchas, optimizations, etc. until our experience grew.  You could (justifiably) argue that the maturation process would be greatly aided by the general maturity of pint, but I think it's a mistake to consider only simtk.unit vs pint/unyt and ignore the overall context of the current situation.

> Here's the simplest demonstration of an issue we ran into, showing a 19x speed difference for what should otherwise be incredibly lightweight operations:

You're comparing simtk.unit vs. nothing, not simtk.unit vs pint or unyt.  There *are* optimizations you can make if you are willing to handle dimensional analysis yourself.  Assigning and resolving dimensions are not symmetric in cost:

```python
In [1]: import simtk.unit as u

In [2]: import random

In [3]: value = random.random()

In [4]: quantity = random.random() * u.nanometers

In [5]: %timeit value * u.nanometers
1.93 µs ± 26.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [6]: %timeit quantity.value_in_unit_system(u.md_unit_system)
7.93 µs ± 294 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [7]: %timeit quantity.value_in_unit(u.nanometers)
11.2 µs ± 577 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

`value_in_unit_system` and `value_in_unit` are anywhere from 4-6x slower than setting units.  While you can't prevent OpenMM from setting units in their functions, you *can* avoid the unit conversion step:

```python
In [1]: import simtk.unit as u

In [2]: import simtk.openmm as mm

In [3]: system = mm.System()

In [4]: system.addParticle(1 * u.dalton)
Out[4]: 0

In [5]: import random

In [6]: new_mass = random.random() * 10 * u.dalton

In [7]: %timeit system.setParticleMass(0, new_mass)
12.1 µs ± 287 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [8]: %timeit system.setParticleMass(0, new_mass._value)
810 ns ± 42.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

If you need a speedup, make sure you have the value expressed in the correct units already and just pass the value.  In other cases, there are very slow and much faster ways of doing things:

```python
# This is very slow
context.setPositions(
    [(x[j] * 2).value_in_unit(u.nanometers) for j in range(3)] for x in coordinates]
)

# This is very fast
context.setPositions(
    [x[j] * 2 for x in coordinates.value_in_unit(u.nanometers)]
)
```

But out of curiosity, I tried `pint`:

```python
In [1]: import random

In [2]: import pint

In [3]: value = random.random()

In [5]: from pint import UnitRegistry

In [6]: ureg = UnitRegistry()

In [18]: def test_pint(nparticles=1000, use_units=True):
    ...:     system = openmm.System()
    ...:     if use_units:
    ...:         for i in range(nparticles):
    ...:             mass = random.random() * 10 * ureg.dalton
    ...:             system.addParticle(mass.m_as(ureg.dalton))
    ...:     else:
    ...:         for i in range(nparticles):
    ...:             mass = random.random() * 10
    ...:             system.addParticle(mass)
    ...: 

In [19]: %timeit test_pint()
74.4 ms ± 1.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [20]: %timeit test_pint(use_units=False)
857 µs ± 29.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [21]: import simtk.unit as u
    ...: def test_simtk(nparticles=1000, use_units=True):
    ...:     system = openmm.System()
    ...:     if use_units:
    ...:         for i in range(nparticles):
    ...:             mass = random.random() * 10 * u.dalton
    ...:             system.addParticle(mass)
    ...:     else:
    ...:         for i in range(nparticles):
    ...:             mass = random.random() * 10
    ...:             system.addParticle(mass)
    ...: 

In [22]: %timeit test_simtk()
16.2 ms ± 358 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [24]: %timeit test_simtk(use_units=False)
971 µs ± 63.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

You complained about simtk.unit being slow, but `pint` is literally 5x slower than simtk.unit for exactly the same operation.  There's a very real possibility that the performance difference between simtk.unit and alternatives is profound, but in a way that favors simtk.unit.

>     * Incompatibility with modern systems of pint and unyt. Instead of every OpenMM-based tool needing to engineer their own solution, we should see if we can address this at the OpenMM level.

This is only true for OpenMM-based tools that chose pint or unyt.  ParmEd chose OpenMM's units and has no incompatibility to manage (at the cost of not having access to some of the nicer numpy features).  I'm not easily convinced that OpenMM needs to change simply because it will alleviate pain points caused by choices made by downstream projects (that, put bluntly, could have been avoided).

> Incorrect results (e.g. with numpy computations)

Incorrect results are bugs that get fixed.  numpy compatibility is a notable shortcoming, but as this conversation has progressed, numpy compatibility is emerging to me as only differentiating feature (pint seems to be explicit about dimensionality while openmm is implicit -- that is pint recognizes generic dimensions like length, time, mass, etc. while openmm builds unit relationships between these dimensions, but this seems of minor practical importance to me).

> Offering a way to avoid the overhead of unit-handling on input and output

simtk.unit already has that.  I actually view this as something we'd lose moving to pint or unyt (unless there's an equally easy way of accessing the raw value).  This is more a core Python app layer design choice (applying units everywhere) than a unit package property.

> Ensuring dimensionality is checked when unit-bearing quantities are provided, and making it easy for apps built on top of OpenMM to do the same

The same work needs to be done here for every unit package - @peastman pointed it out.  If an equivalent decorator of `ureg.wraps` is what you mean by "making it easy for apps to build on top of OpenMM", this is easier to add than swapping unit packages (and is, IMO, a very good suggestion).

---------

I'll conclude this treatise with a final caveat: I am assuming that replacing simtk.unit with pint will result in wide-ranging backwards-incompatibilities and that the vast majority of existing code will not work without at least some modification.  If my assumption is misplaced, and simtk.unit can effectively be replaced with a thin wrapper around a `pint.UnitRegistry` without breaking, that will obviously undercut the bulk of my arguments against changing and shift my attitude.  But the only way to really prove my assumptions wrong is to do the work knowing it may not be accepted if the cost is deemed too high for the benefit.

OTOH, I suspect that it may actually be easier to see how `pint` integrates so nicely with numpy and simply borrow what they've done there.

**Comment by jchodera** [comment]
I'll expand into the great points by @swails later, since I'm typing on my phone right now, but just wanted to clarify this point:

> Offering a way to avoid the overhead of unit-handling on input and output

This is indeed a Python API choice, where we currently offer the ability to accept arguments with or without simtk.unit.Quantity wrapping, but force the user to accept unit-bearing quantities in return, and the overhead that comes with them.

**Comment by peastman** [comment]
This is a great discussion, but could we move it to a new issue?  It has nothing to do with renaming `simtk.openmm`, and this issue is about to get closed when I merge #3000.

**Comment by peastman** [comment]
I'll open a new issue with a summary of the discussion so far.

**Comment by peastman** [comment]
> openmmtorch could become openmm.torch, openmmplumed could become openmm.plumed, etc.

I realized that if we do this, it will have a really annoying consequence.  Every time I type 'make PythonInstall' to install an updated version of OpenMM, it will delete all other subpackages that have been installed under `openmm`.  That would be a huge hassle in development.

**Comment by jchodera** [comment]
That doesn't have to happen! Tagging @j-wags and @simonboothroyd who can give more information about how they implemented this namespace change for the openff-toolkit.

**Comment by SimonBoothroyd** [comment]
> I realized that if we do this, it will have a really annoying consequence. Every time I type 'make PythonInstall' to install an updated version of OpenMM, it will delete all other subpackages that have been installed under openmm. That would be a huge hassle in development.

I think that will depend on how your are setting up the namespace packages and how you are doing the setup. 

The OpenFF stack uses the implicit namespaces introduced by [PEP 420](https://www.python.org/dev/peps/pep-0420/), and installation works fine using either `python setup.py ...` and `pip install .` without overwriting other installed sub-packages. There are some caveats here such as the other namespace packages must not have a top level `__init__.py` in the root `openmm` directory while all other subdirectories must include an `__init__.py`.

If the setup can be done by either of the stock install commands you should be fine, but if you are doing something more bespoke (which you might be due to building swig wrappers) then YMMV.

**Comment by jaimergp** [comment]
Can you have an non-root implicit namespace? For example, `openmm.plugins` is empty, and the plugins are populate directories under `openmm.plugins.X`:

```
openmm/ #  this is the package contained in this repo
openmm/plugins/  # this is empty by default
openmm/plugins/torch  # available via openmm-torch
openmm/plugins/plumed  # available via openmm-plumed
```

**Comment by peastman** [comment]
I just looked at PEP 420.  I'm not certain whether or not it can do what we want.

`openmm` is *not* a namespace package.  It has an `__init__.py` that does lots of initialization when the package is loaded.  It also contains subpackages like `openmm.app` that likewise are not namespace packages.

Now I want to have a separately installed package that goes in its own directory, *not* inside the `openmm` directory.  For example, it might be in a directory called `openmmtorch`, but we want to tell Python that the package name is actually `openmm.torch`.  Is that possible?

**Comment by jaimergp** [comment]
AFAIK import paths are linked to filesystem paths. So my immediate answer is _no_. 

But maybe other projects with this kind of behavior might offer alternatives, like [pytest plugins](https://docs.pytest.org/en/stable/writing_plugins.html).

Still, I think that `openmm.plugins` might be an implicit namespace, but I haven't checked.

**Comment by Lnaden** [comment]
If I understand correctly, you are suggesting a folder structure like:

```
.
├── openmm
│   └── __init__.py
└── openmmtorch
```

Then could you not just treat the `openmmtorch` directory like any other dependency like `numpy` in your `openmm/__init__.py` file by

```python
try:
    import openmmtorch as torch
except ImportError:
    pass
```

Then you would have `import openmm` also have access to `openmm.torch`?

**Comment by jaimergp** [comment]
Depending on the amount of plugins that might increase the import time unnecessarily (numbers needed), and it requires the registration to be done on `openmm` manually, so external contributors can't just sign up a plugin upon installation.

That said, it might be a good start for some official plugins and we can reassess more automated ways in the future, if needed.

**Comment by Lnaden** [comment]
Not sure if this helps. It might be possible to use the `entry_point` of "plugins" setup.py to expose the 3rd party package to OpenMM. Pytest does something like this, but I'm not quite sure it applies here: https://docs.pytest.org/en/stable/writing_plugins.html#making-your-plugin-installable-by-others

**Comment by peastman** [comment]
My understanding is that when you run `setup.py` to reinstall OpenMM, it will delete everything inside the `openmm` folder.  Is there a way I can have a package like `openmm.torch` or `openmm.plugins.torch` such that 1) it won't get deleted when reinstalling OpenMM, and 2) we don't need to have hardcoded support for it in OpenMM?  I tried to figure this out from PEP 420, but it's confusing.  They discuss the case of a top level namespace package, but I didn't see any mention of a namespace package nested inside a regular package.  They also seemed mainly concerned with the final result after your package has been installed, not with what happens during development when you're frequently removing and reinstalling packages.
