### ISSUE TITLE
Gromacs integration breaks with recent versions (>2018)

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm#3006]
The GitHub Actions CI is pinning `gromacs` as 2018.* because later versions made tests fail. This should be addressed in a PR where the build environments unpin the package and figure out what's going on (maybe just a "files are now in a different path" issue).

**Comment by peastman** [comment]
It seems Gromacs 2020 removed support for implicit solvent.  Here's what they say about it in the [release notes](https://manual.gromacs.org/documentation/2020/release-notes/2019/major/removed-functionality.html#implicit-solvent-support-removed):

> Since GROMACS-4.6, the SIMD and multi-threading support has been mostly broken. Since nobody wants to fix it, the feature has been removed. Old force field files with parameters for such simulations can still be read, but the values are ignored.

I'm not sure how we should handle this.  Since Gromacs no longer supports this feature, we could make a case for removing it from GromacsTopFile.  On the other hand, it still works fine as long as you have a copy of Gromacs 2018 or earlier installed.  I don't want to remove it if there are people still relying on it.  Perhaps we should mark it as deprecated and note that it might be removed in a future release?

**Comment by jchodera** [comment]
Can we support both versions, and include test branches with 2018 and 2020 versions of gromacs?

We can encapsulate the behavior in try...except clauses and try both in order?

**Comment by jchodera** [comment]
But adding a deprecation warning would also be good!

**Comment by peastman** [comment]
Supporting both is easy.  Mostly it's just a matter of the test cases.  The .top file \#includes amber99sb.ff/forcefield.itp.  In Gromacs 2018 and earlier, that file has the line `#include "gbsa.itp"`.  In Gromacs 2020 and later, it doesn't.  That's fine either way.  But if you ask for implicit solvent in the call to `createSystem()`, we expect GB parameters to have been loaded.  If your force fields came from 2018, they were.  If they came from 2020, they weren't and we throw an exception.

The longer term question though is whether we should remove the `implicitSolvent` argument from `createSystem()`, since Gromacs no longer supports implicit solvent.

**Comment by jchodera** [comment]
Thanks for the clear explanation!

Does this plan sound reasonable?
* Add a deprecation warning that we will remove this in the next release, since gromacs doesn't plan to support this going forward
* Try to support 2018 and 2020 for now, since our users may need both
* Add test branches for both
* If none of our users send us panicked notes, we consider extending support for the next release, and also ask them to lobby gromacs folks?

**Comment by peastman** [comment]
The deprecation notice has been there since 7.7, and no one has complained.  Shall I go ahead and remove the option for implicit solvent?
