### ISSUE TITLE
Update charges in every step

### ISSUE THREAD

**Issue by XiaojuanHu** [openmm/openmm#3008]
Hi, I want to update charges in every time step (maybe not in every step to save sources ). New values of charges are related to the distances between atoms, so we also need to get atomic positions in every step. Can we perform this with the code following? And, do we need to update the parameters of exception?  Thank you!

```
pdb = PDBFile('input.pdb')
forcefield = ForceField(force_file)
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=None)

integrator = VerletIntegrator(0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)

simulation.context.setPositions(pdb.positions)

simulation.minimizeEnergy()

for sp in range(steps):
	simulation.step(sp)
	
	# get position
	state = simulation.context.getState(getEnergy=True,getPositions=True) # getForces =True)
	position = state.getPositions()
	
	# get new charges
	new_charges = get_charge(position)
	
	# update new charges
	# load nonbondedforce
	forces = { force.__class__.__name__ : force for force in system.getForces() }
	nbforce = forces['NonbondedForce']
	
	for index in range(nbforce.getNumParticles()):
		
		# charge
		[charge, sigma, epsilon] = nbforce.getParticleParameters(index)
		nbforce.setParticleParameters(index, new_charges[index], sigma, epsilon)
		
	# set exceptions?
	for i in range(nbforce.getNumExceptions()):
		(p1, p2, q, sig, eps) = nbforce.getExceptionParameters(i)
		if q._value != 0.0:
			q_new = new_charges[p1] * new_charges[p2] * f14
			nbforce.setExceptionParameters(i, p1, p2, q_new, sig, eps)
	
	nbforce.updateParametersInContext(simulation.context)

simulation.step(20000)
```

**Comment by Lnaden** [comment]
Something like that will technically work. You can update the partial charges every step, and you would have to update the exception parameters as well. However, this would be an extremely slow simulation since `updateParametersInContext` is one of the more expensive functions you can call. I can't say for certain your code would work as is, but it looks okay at first pass.

There might be a better way to do this based on what your scientific needs are, but we'll need some more information first. I'm going to throw out some ideas here.
* Updating *all* partial charges based on position sounds like either a type of external force (e.g. magnetic field) or a type of reaction field based nonbonded (instead of PME),.
* If this is only on a small set of atoms who's partial charges need updated, it may be worth exploring some of the `Custom*Force`s to see if any of them can effectivley implement your equation.
* If the scaling on the electrostatics is all uniform, then there may be simpler ways to implement this.
* Depending on what you're doing, it may be possible to implement this as `CustomNonbondedForce` as a replacement to the normal `NonbondedForce`, or implemented as a second `CustomNonbondedForce` which effectively adjusts the potential and force acting on each particle.

**Comment by XiaojuanHu** [comment]
Thank you for the reply! I'm trying to implement a polarizable model CTPOL, which introduces charge transfer and polarization effect into classical FF. In this model, charges on ligand atoms (only consider N, O, and S) and cation (e.g. Ca2+) fluctuate depend on the distance between ligand atom and cation, r$_{L-Cation}$. So charge on ligand atoms is:
q_L=q0+q_trans=q0+(a_L*r$_{L-Cation}$+b_L)
charge on cation (e.g. Ca2+) is:
q_cation=2-sum(q_trans)
Two points make me feel difficult to use a CustomNonbondedForce:
1. Assume atom $i$ is one of the elements of N, O, and S, the electrostatic interaction between atom $i$ and $j$ does not only depend on the distance between $i$ and $j$ but also the distance between atom $i$ and cation.
2. To calculate the charge on cation, we need the total amount of charge transfer.

Besides this, we also want to add polarization energy. It needs to solve dipoles self consistently. I considered using AmoebaMultipoleForce, but CTPOL uses a different way to set cutoff distance. If we write a code to solve dipoles by ourselves, we'll need to update the dipole in each step by calling updateParametersInContext, which is expensive. Do I have any other choices?

**Comment by jchodera** [comment]
Shouldn't the position-dependence of the charges also contribute to the force? I worry these approaches will miss that contribution.

We've been thinking about ways to support position-dependent charges through machine learning framework plugins. Would adding a capability that allows for position-dependent charges to be described in a pytorch model do what you need? If so, we may be able to construct a custom force that enables you to define position, velocity, box, time, and global parameter dependent charges through a pytorch model, and correctly propagate the spatial gradient of the charges into the force.

Do you need PME electrostatics, or would you want to use some other electrostatics model?

**Comment by XiaojuanHu** [comment]
This is a simplified model. We neglect some contributions.

Position-dependent charges might be what I need. It would be good if we can define the position. While optimization is not needed in our model.

And yes, we need  PME electrostatics.

**Comment by peastman** [comment]
To do this efficiently, I think you're going to need to write a plugin.  NonbondedForce and CustomNonbondedForce implement pairwise interactions, but what you described is a many-body interaction, where the interaction between two atoms depends on the position of a third atom.  And it isn't even a straightforward three body interaction (which you might have been able to use CustomManyParticleForce for), because you need to iterate the calculation until it converges to find the self consistent solution.

You could, of course, implement this in Python like you originally suggested.  That would work, but it would be really slow.  To get good performance, you want to implement everything in CUDA so the whole calculation stays on the GPU.

Take a look at the [developer guide](http://docs.openmm.org/latest/developerguide/index.html).  It describes how to write a plugin.  If you're up for the challenge of doing that, we'll be happy to provide advice and guidance.

**Comment by jchodera** [comment]
@XiaojuanHu Did this address your question in appropriate detail? If so, can we close this issue?
