### ISSUE TITLE
Is it Possible to Calculate just Nonbonded energy for saving time?

### ISSUE THREAD

**Issue by Bio-Otto** [openmm/openmm#3031]
I wonder if it is possible to calculate only one energy group with Openmm? But I am not talking about calculating all energies and pulling only the nonbonded from the system, as in energy decomposition. I want to have only nonbonded calculations in the system (protein + water) directly. 

Thank you in advance for your help.

**Comment by Lnaden** [comment]
Can you elaborate your use case a bit more? I'm unsure as to exactly what you are looking for. I'm sure we can find a solution for what you're trying to do, but some more details would help.

My current understanding is you are looking to have only protein-water interactions computed in the Nonbonded Force so that the simulation propagates forward in faster wall clock? Ignoring the water-water and protein-protein nonbonded interactions?

The other interpretation I can glean here is you're plugging coordinates in from an external source and only need the protein-water nonbonded energy; not actually propagating the simulation in time.

**Comment by Bio-Otto** [comment]
What I really want to do is have the system set up on a single snapshot and then have it calculate only the nonbound energy for the atoms I have determined. For example, I want to give an equation with CustomNonbondedForce and just calculate it again. So I don't want to compute all force groups and choose just one. 

Thank you for your quick response.

**Comment by Lnaden** [comment]
You can set `addInteractionGroups` to a `CustomNonbondedForce` to isolate specific interactions between sets of atoms. How efficient it is depends on how you have defined the force expression. There was discussion about a very similar topic for speed purposes in #2698 which you may want to look at for ideas.

I'm not sure of a way to do what you're looking for if you are using the standard `NonbondedForce` without some form of plugin.

**Comment by Bio-Otto** [comment]
I think this might work for me. But it is stated that there is no change in speed. I want to try and see the approach here.

**Comment by Lnaden** [comment]
I think in their case they were trying to have all three interaction pairs all on at once: protein-water, protein-protein, and water-water. In that case, the interaction groups trying to emulate the fully-interacting system with no interaction groups will be slower. However, since you only want once of those three, it has the potential to work faster.

You can also experiment with modifying the energy expression to zero out certain interactions, see if that works faster. I'm not the most familiar with the internals of how zeroed interactions are optimized though.

**Comment by peastman** [comment]
Using interaction groups is potentially faster, because it doesn't have to compute as many interactions.  On the other hand, the algorithm is intrinsically less efficient, so that makes it slower.  How these two factors combine depends on how many interactions you're computing.  If it's only a small fraction of all interactions in the system, the interaction groups will end up being faster.  If you're computing a large fraction of them, it will probably end up being slower.

**Comment by Bio-Otto** [comment]
Your recommendations made a lot of sense. The system I want to set up will be less complex. It is also worth a try considering that Openmm is a very flexible tool.

**Comment by jchodera** [comment]
@Bio-Otto Did we address your question in sufficient detail? If so, can we close this issue?
