### ISSUE TITLE
Clarify CUDA minimum version

### ISSUE THREAD

**Issue by scal444** [openmm/openmm#3088]
I was browsing the OpenMM documentation (which is awesome, BTW), and I noticed what might be some conflicting descriptions of capabilities.

From my reading, it seems the oldest CUDA version packaged now is [series 9](https://github.com/openmm/openmm/blob/master/docs-source/usersguide/application.rst#installing-openmm).
In the developer doc, it's stated that the CUDA plugin works for [compute capability 1.2 and up](https://github.com/openmm/openmm/blob/master/docs-source/developerguide/developer.rst#accumulating-forces) whereas I believe if CUDA 9 is the minimum version, then the minimum cc is 3.0. This may be of interest to anyone hacking on the CUDA code, because it opens up a new API, such as [shuffle reductions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#warp-shuffle-functions). 

Unless of course minimum packaged CUDA version != minimum supported CUDA version, in which case it might be nice to know what the range of supported versions is (and to let users know that if they have an older GPU, they'd need to use an old openMM version or install from source).

**Comment by peastman** [comment]
The versions we have packages for are dictated by what conda-forge supports.  It doesn't mean the code won't work with earlier versions if you compile it yourself.  On the other hand, we don't test on very old CUDA versions.  So I don't know what the oldest version is that would actually work.  Until fairly recently we built packages going back to 7.5, and we haven't made any changes that I would expect to break compatibility, so that probably would still be fine.  Versions older than that, I just don't know.  They might work, but it has been a long time since we tested on them.

If the code compiles, and if the full test suite passes, it should be fine.  Do you need a particular version?

**Comment by scal444** [comment]
> Do you need a particular version?

Ah no, I was just browsing the codebase and was curious. Thanks for the explanation!

For more context, I'm working on Gromacs and was interested in seeing how other MD engines CUDA implementations were organized. Gromacs tends to be quite aggressive about requiring recent CUDA versions to be able to use the newest features.

**Comment by peastman** [comment]
We try to be more flexible about it.  OpenMM has the advantage that it compiles all its kernels at runtime, so it's easier to target exactly the features available in your GPU and CUDA version.

I'm going to close this issue, since I think all the questions have been answered.
