### ISSUE TITLE
High potential energies when using unwrapped coordinates via amber files

### ISSUE THREAD

**Issue by asilveirastx** [openmm/openmm#3102]
I am getting high initial potential energies when specifying unwrapped positions via amber files. The box is octahedral. These energies (in most cases) look good after minimizing.  FYI, I don't get these initial high energies when using the ParmEd amber parser. In addition, OpenMM 7.4.2 yields positive energies after minimizing when (1) using the nc file and (2) specifying rigidWater as False. OpenMM 7.5 works fine for both rigidWater True and False. The following script reproduces the issues. I've attached the input files. Thanks!
[input_files.tar.gz](https://github.com/openmm/openmm/files/6417061/input_files.tar.gz)

```
import simtk.openmm as mm
import simtk.openmm.app as app
from simtk.openmm import unit

prmtop = app.AmberPrmtopFile('solvated.prmtop')
netcdf = app.AmberInpcrdFile('solvated.nc')
inpcrd = app.AmberInpcrdFile('solvated.inpcrd')

for rigidWater in [True, False]:
    system = prmtop.createSystem(rigidWater=rigidWater, nonbondedMethod= app.PME, nonbondedCutoff=0.9*unit.nanometer )
    integrator = mm.CustomIntegrator(0)
    simulation = app.Simulation(prmtop.topology, system, integrator)
    simulation.context.setPositions(netcdf.positions)
    print(f'Potential energy with netcdf coords and rigidWater {rigidWater} is {simulation.context.getState(getEnergy=True).getPotentialEnergy()}')
    simulation.minimizeEnergy()
    print(f'Potential energy after minimizing is {simulation.context.getState(getEnergy=True).getPotentialEnergy()}')
    simulation.context.setPositions(inpcrd.positions)
    print(f'Potential energy with inpcrd coords and rigidWater {rigidWater}  is {simulation.context.getState(getEnergy=True).getPotentialEnergy()}')
    simulation.minimizeEnergy()
    print(f'Potential energy after minimizing is {simulation.context.getState(getEnergy=True).getPotentialEnergy()}')

**Comment by swails** [comment]
This sounds like the unit cell vectors aren't being set correctly.

With ParmEd, you can (and should) instantiate the AmberParm object with a coordinate filename.  If you do this, ParmEd will (properly) use the unit cell vectors defined in the coordinate file instead of the ones defined in the prmtop file.  If you've run an NpT simulation, the unit cell vectors in the prmtop file will be wrong when applied to coordinates from an NpT trajectory (like a restart at the end of the run).

However, in this code snippet you are instantiating the OpenMM `System` object using just the prmtop file, so it has no choice but to use the unit cell vectors from the prmtop file (which, again, might be wrong for the coordinates you're passing in).  This is one of the few places where OpenMM and ParmEd do things differently.

**Comment by peastman** [comment]
See the example at http://docs.openmm.org/latest/userguide/application.html#using-amber-files.  It shows how to set the box vectors from the inpcrd file.

**Comment by asilveirastx** [comment]
Thanks @peastman and @swails ! setting the box vectors from the coord files worked!
