### ISSUE TITLE
Adding fixed number of solvent molecules leads to NaNs for certain systems

### ISSUE THREAD

**Issue by schallerdavid** [openmm/openmm#3113]
Hello, 

we are currently interested in simulating multiple conformations of the same protein. Having the same number of solvent molecules in each system would be great, in our case we estimated 32000 would be a good number for all systems.

Although this seems to work for most conformations, there are few conformations for which we retrieve NaNs immediately after starting the simulation. Surprisingly, those systems just run fine when adding solvent via the padding parameter. 

I attached a small script and two PDB files to reproduce the error ([test_openmm.zip](https://github.com/openmm/openmm/files/6462222/test_openmm.zip)). The default behavior is to create a cubic water box with 1.5 nm padding. However, one can specify the number of solvent molecules to add via the -n argument.

Version:
OpenMM 7.5.0 via conda-forge

Steps to reproduce:
- unzip attachment
- change to directory
- activate conda environment
- run commands:
  - python test_openmm.py 0.pdb
  - python test_openmm.py 0.pdb -n 32000
  - python test_openmm.py 32.pdb
  - python test_openmm.py 32.pdb -n 32000

Expected behavior:
 - all simulations finish

Observed behavior:
 - system 32.pdb with 32000 solvent molecules leads no NaNs

Interestingly, increasing or decreasing the total number of added solvent molecules by 2000 does not result in NaNs.

Thanks for your help,
David

**Comment by AnthoniAlcaraz** [comment]
Hi,

I tested your system by curiosity. I got **Energy is NaN** with 32.pdb and 32000. 
I understand some molecules are closer because the initial energy is too repulsive:

`Minimizing energy ... `
`  initial : 2502208526542412.500 kcal/mol `
`   final : 2490130984066053.000 kcal/mol`
` Saving minimized system ...`

I checked modeller.py and I found this:
`        numAdded : int=None`
`            the total number of molecules (waters and ions) to add`
32000 is just waters, right? 

I got the padding value computed by OpenMM with this line:
`padding = 1.1*(numAdded/((len(pdbResidues)/pdbBoxSize[0]**3)*8))**(1.0/3.0)` 
**I got 5.435751468822078 with modeller.py.** 
Then I changed the padding value: 1.5 by ~5.43 and I ran your script. The output was:
`Minimizing energy ...`
`  initial : -1430874.675 kcal/mol`
` final : -2203550.105 kcal/mol`
`Saving minimized system ...`

After that I didn't get **Energy is NaN**

I hope it helps you.

**Comment by schallerdavid** [comment]
Thanks @AnthoniAlcaraz for the suggestion. This is an interesting workaround! It would still be great to investigate the origin of the NaNs, since it looks like some internal problem that might also affect other's simulations.

> I understand some molecules are closer because the initial energy is too repulsive:

Interestingly, the reported initial energy is super high and not getting negative during the minimization, but when looking at the solvated system, there are no severe atom clashes.

**Comment by AnthoniAlcaraz** [comment]
You are welcome @schallerdavid . 
I think it seems to be a bug. Since **padding** is computed with **numAdded** I didn't see a source of error, at least in modeller.py.

**Comment by schallerdavid** [comment]
We investigated this a little further with our use case of solvating 400 EGFR structures with the same number of solvent molecules which can be found in an [OSF project](https://osf.io/6b3jr/files/). Running short simulations (10 steps) for each system, we found that 32200 solvent molecules work fine for all structures but not 32000 or 32100 solvent molecules. If anyone runs into a similar problem just use this script ([test_openmm.zip](https://github.com/openmm/openmm/files/6489868/test_openmm.zip)) to find a number suiting all systems.

**Comment by jchodera** [comment]
This is super odd that this is so fragile. Hopefully we can take a look at this and figure out a way to make this more robust.

**Comment by peastman** [comment]
I think I understand what's going on.  When adding solvent, the first step is to tile a pre-equilibrated cube of water to cover the box.  Because it's pre-equilibrated, there are no clashes between water molecules in adjacent copies of the cube.

But usually that will be more water than you want, so we need to remove the excess water molecules.  If you specify a box size, it first removes any water outside the box.  That might leave clashes between molecules on opposite sides of the box, so it checks for any that are too close to each other and removes them.

If you instead specify a number of molecules, it instead selects the molecules that are furthest from the edge of the extended box (that is, an integral number of tiled copies of the pre-equilibrated cube).  If you ask for N molecules, it gives you the N molecules furthest from the edge.  Then it finds the range of coordinates spanned by those molecules and sets it as the box size.

This again creates the possibility of a severe clash between molecules on opposite sides of the box.  That's what's happening in your case.  This time we don't have the option of checking for clashes and removing molecules, because that would leave fewer molecules than the number you asked for.  The simplest solution would be to just add a little padding to the box width.  1 A would be enough to resolve most clashes.  The disadvantage would be that you would get a band of lower density at the edge of the box.  Hopefully a little equilibration with a barostat would fix that quickly.  We could try to do something more complicated, but I'm not sure it's worth it.

**Comment by schallerdavid** [comment]
Thanks for looking into this @peastman ,

this really makes sense. For us, this issue is not of high priority, since there are workarounds. We just did not expect this to happen, so maybe adding a note to the documentation would be good.

**Comment by peastman** [comment]
I think we should do *something* about this, even if it's just adding some padding.  You're probably not the only person who will encounter it!
