### ISSUE TITLE
OpenMM Cookbook

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#3140]
It would be useful to create a "cookbook" with short examples showing how to do lots of common things in OpenMM.  To get some initial ideas, I went through recent posts on the forum to find questions that would make good examples.  Here are some I have found so far.

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=13510&p=38760&start=0&view=
Examples of both constraining and restraining particle positions

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=13263&p=0&start=0&view=&sid=dc6fb179717ef6d823bd5c12cfa106a6
How to merge two PDB files into a single Topology

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=13103&p=0&start=0&view=&sid=a3efb4c058dc747e356c126978b41809
Applying a force to a dihedral

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10183&p=0&start=0&view=&sid=a3efb4c058dc747e356c126978b41809
Forcing an atom to follow a fixed trajectory

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=12877&p=0&start=0&view=&sid=e1178b3611d704a96a4171c692cdd5d1
Query the charge of each particle

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=12424&p=0&start=0&view=&sid=08110ce15a5b0d303ebedb21a8b7de6f
Change the pressure during a simulation

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=12340&p=0&start=0&view=&sid=bccda359d0e19ba0a784fbea68f2dab4
Applying constant forces to atoms

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=12112&p=0&start=0&view=&sid=bccda359d0e19ba0a784fbea68f2dab4
Query the energy contributions of individual Force objects

cc @Yoshanuikabundi

**Comment by ljmartin** [comment]
I'd like to contribute some examples to this, since I can remember being a newbie and needing such cookbook examples - now I've got a few demo scripts that do exactly these sort of things. If you have a preferred format - notebook, colab, self-contained scripts vs requiring input files, then I can write them up.

**Comment by Yoshanuikabundi** [comment]
That would be great! I think notebooks are probably the most convenient, that way we can choose whether to put them in colab or the documentation or just distribute them on GitHub later.

**Comment by peastman** [comment]
Thank you!  Does anyone know of examples of other projects that do this?  It would be good to look at them to see how other people have organized them.

**Comment by peastman** [comment]
Answering my own question:

https://scipy-cookbook.readthedocs.io/
https://biopython.org/wiki/Category:Cookbook
https://www.rdkit.org/docs/Cookbook.html
http://www.cookbook-r.com/

Using a notebook for each one seems to be standard.  The RDKit cookbook merges all of them into a single page.  The others have each entry as a separate page with an index to all of them.  I think I prefer the latter.

**Comment by jchodera** [comment]
More examples:
* [Tensorflow tutorials](https://www.tensorflow.org/tutorials) - really nice, thorough collection of examples with clear cut-and-paste fields and open-in-colab buttons
* [PyTorch tutorials](https://pytorch.org/tutorials) - similar to tensorflow
* [OpenEye Python Cookbook](https://docs.eyesopen.com/toolkits/cookbook/python/index.html)
* [QCArchive examples](https://qcarchive.molssi.org/examples/) - Jupyter notebooks with mybinder launch button
* [Open Force Field examples](https://open-forcefield-toolkit.readthedocs.io/en/0.9.2/examples.html) - GitHub repo with Jupyter notebooks and mybinder launch buttons

**Comment by peastman** [comment]
A cookbook is different from tutorials.  The goal of tutorials is to teach you to use the software.  Ideally they should form a sequence that a new user can go through in order, each one introducing new concepts and providing lots of explanation.  A cookbook is a reference.  Each entry should be concise and self-contained, giving precise instructions on how to do a particular thing.

**Comment by jchodera** [comment]
That doesn't mean we have to engineer completely different infrastructure for cookbooks and tutorials.

**Comment by peastman** [comment]
Agreed!  I was just thinking about how to present it to the user.

**Comment by ljmartin** [comment]
Here's an example to kick things off: https://gist.github.com/ljmartin/53c6b72fb1bf2150aece52ab4e121ce0
It would be nice if someone can check my work, particularly the minimum image distance calculation...

Some points:
- OpenMM sometimes avoids `numpy`, so I used `math` instead. Would you like to keep that convention here?
- Scripts here often use `from simtk import *` but I kept it to explicit module names. Not sure whether that makes life easier or not for new users
- I imagine there's a bit of code simplification or best practice to change

Happy to have another go, or turn it over to someone else to standardise it.
FYI Another library with really useful examples is https://docs.pymc.io/nb_examples/index.html . Since it's notebook format its ideal for presenting a bit of discussion along with the code.

**Comment by peastman** [comment]
> OpenMM sometimes avoids numpy, so I used math instead. Would you like to keep that convention here?

It's fine to use numpy in tutorials and cookbook entries.  We try to keep the number of required dependencies to an absolute minimum, but for teaching users how to do something, there's nothing wrong with using common libraries like numpy or matplotlib.  That said, there's also nothing wrong with using `math`!

> Scripts here often use from simtk import * but I kept it to explicit module names.

I think either one is fine.

**Comment by peastman** [comment]
I created a couple of entries for the first item on the list above (constraining and restraining particles).  Where do we want to keep them?  Presumably in a folder in the openmm-org repo?

https://gist.github.com/peastman/21facc27bed0ee2437a2011dbf67aab9

https://gist.github.com/peastman/ad8cda653242d731d75e18c836b2a3a5

**Comment by jchodera** [comment]
> Where do we want to keep them? Presumably in a folder in the openmm-org repo?

Great question! We'll need to sort out some infrastructure for this, ensuring that these recipes are also tested via CI (both on commit and nightly).

Would it make sense to have an `openmm-cookbook` repo that folks could check out separately, where we can have `openmm-org` render them into the webpage on build? The only difficulty is that we'd have to force an `openmm-org` build when the recipes are updated unless we just have the webpage rebuild nightly.

**Comment by jchodera** [comment]
> I created a couple of entries for the first item on the list above (constraining and restraining particles)

These are great! I have a few minor comments, but it will be much easier to add those comments inline once we open a PR.

**Comment by peastman** [comment]
> Would it make sense to have an openmm-cookbook repo that folks could check out separately

What would be the advantage over keeping them in the same repo?

**Comment by jchodera** [comment]
> What would be the advantage over keeping them in the same repo?

Users could check the cookbook out and work through the cookbook examples or copy-and-paste locally without ingesting a whole lot of irrelevant website stuff. We can also more easily automate testing of the examples via CI in a manner that is decoupled from website updates.

Perhaps this isn't really necessary if we provide a nice way to copy-and-paste from the website (and launch colab notebooks), and figure out an elegant way to separately recognize when CI should rebuild the website vs test the examples?

**Comment by peastman** [comment]
Whatever we do for this, we should do the same thing for the tutorials.  Currently they're in a folder in openmm-org.

**Comment by jchodera** [comment]
Agreed that these can share infrastructure and even the same repository!

**Comment by peastman** [comment]
@raimis any thoughts on the best way of handling this?  Would it add complexity if the tutorials and cookbook were in a separate repo from the website?

**Comment by jchodera** [comment]
What if we used the same build scheme and style that [pytorch uses](https://github.com/pytorch/tutorials) to present [these beautiful examples](https://pytorch.org/tutorials/)? See the README for how they do this.

**Comment by raimis** [comment]
> @raimis any thoughts on the best way of handling this? Would it add complexity if the tutorials and cookbook were in a separate repo from the website?

You can fetch the file of the tutorials and cookbook from any URL. The rendering is done in a browser.

**Comment by peastman** [comment]
I'd like to move forward with this.  For the moment, I suggest we just store the cookbook entries the same way we do the tutorials: a folder of notebooks in the openmm-org repository.  If we decide we want to move them somewhere else later, that's easy to do.

**Comment by raimis** [comment]
Do you want to write them in Markdown or as Jupyter notebooks?

**Comment by peastman** [comment]
Let's do notebooks for the moment.

**Comment by jchodera** [comment]
@Yoshanuikabundi : Any chance you'd be able to help with the infrastructure for this as well as the content?

**Comment by Yoshanuikabundi** [comment]
@jchodera Sure thing!

I've thought about this a lot. I think using the same infra for the cookbook and the templates is a clear win. 

Putting notebooks in a Git repo feels off to me. I'm not saying its bad, its just always bothered me that there isn't a better way:
- XML diffs are ugly
- Notebooks store a huge amount of data that the user doesn't need, some of which there might be potential privacy concerns around (eg, absolute file paths)
- It seems weird to store the output of code right next to the code. It's admittedly amazing for integration testing - re-execute the notebook and check that the output hasn't changed - but it's easy to get into trouble when code isn't deterministic, or when the user's environment doesn't match the developers, or when the codebase has changed and you have to re-execute every notebook. Usually we don't do this unless its a very deliberate choice - eg, we don't store the C or Fortran wrappers, or the Python Swig stuff, or the Doxygen XML - and it feels like a bad default to me.
- Developing notebooks that are going to be primarily read as static HTML is awkward. It usually involves loops of changing a cell in the notebook via the browser, and then re-executing the entire notebook to see the static HTML that's produced. You usually can't use the notebook's built in tools because the static HTML parser is always slightly different, and you often need to re-execute the entire notebook to ensure that the output is consistent, so you don't end up gaining much by using the usual notebook workflow. Instead, you just wind up using the browser instead of your fine-tuned VIM (or whatever) environment. Though the usual notebook workflow does start becoming useful again when the notebook is computationally expensive, which it could well be for OpenMM. But even then, it's easy enough to just have a 1000 step simulation for development and then increase it for publication.

So I'm very intrigued by the way PyTorch does things (though I'd use a different, bigger font... and some other colour-scheme... and clearer code highlighting... and space things out more...). It's like old school [literate programming](https://en.wikipedia.org/wiki/Literate_programming). I like the idea of writing a carefully annotated script and having it converted into a notebook automatically, rather than the other way around. 

I don't think writing rST or MD files with lots of code blocks is a good solution, coz then you still need to come up with an execution environment, though [myst-nb](https://myst-nb.readthedocs.io/en/latest/use/markdown.html) goes down this road. I also like the idea of users being able to download the notebooks they want without having to plumb the depths of GitHub. A disadvantage is that this means adding some Sphinxiness to the website. This might actually take some surgery. Does the website repo currently use any static site generator? It seems to just be the exact code you'd see if you went to the URL. Like a client-side SSG?

When I first read this thread, I thought the debate was between the openmm repo or a new one, not the website repo! The advantage of this is that it makes it easy to test the cookbook as a pre-requisite for release. It could even be tested on every PR, though this might be overkill, or on every push to Master, which is probably a better balance. But if we don't want to do that, I think the website repo is fine if we provide an easy way to download the notebooks from the website. 

A separate repo might make more sense if we want to run tests with the openmm repo CI machinery, and would also let us cleanly separate out the new Sphinx site we'd need if we went with sphinx-gallery.

That's a lot of text with no real conclusion, so I guess my first preference would be to run a combined cookbook/tutorials site with sphinx-gallery in its own repo, which can then write itself (after compilation) to the openmm-org repo, and can be called in CI from openmm.

**Comment by peastman** [comment]
To offer the other side of it, notebooks are a "boring technology" in the best sense: well established, very widely used, well supported.  Everyone is used to working with them.  We can be pretty sure they'll still be around and still supported five or ten years from now.

> Developing notebooks that are going to be primarily read as static HTML is awkward. It usually involves loops of changing a cell in the notebook via the browser, and then re-executing the entire notebook to see the static HTML that's produced.

Creating notebooks is fast and easy because you *don't* need to rerun the whole notebook.  You can make changes and rerun individual cells.  At the very end you need to do a complete run and check that the static output is correct, but that's a small part of creating a tutorial.  Most of the work is in writing the text, and writing and testing the code.  A notebook makes that fast.  Compare that to the tool used by the PyTorch examples, which is just a single Python script.  If you make any change to the text or code, however small, you need to regenerate the whole thing and rerun all the code to see the effect.

> Notebooks store a huge amount of data that the user doesn't need, some of which there might be potential privacy concerns around (eg, absolute file paths)

When do they do that?  I searched all the notebooks I've created so far in https://github.com/openmm/openmm-org/pull/66 and didn't find any absolute file paths.

**Comment by Yoshanuikabundi** [comment]
I also like boring technology. But sphinx-gallery is [not exactly exciting](https://github.com/sphinx-gallery/sphinx-gallery#who-uses-sphinx-gallery).

>Creating notebooks is fast and easy because you don't need to rerun the whole notebook....

If the whole script runs in less than a second this is really a non-issue, but I admit this is likely not the case for OpenMM. Although having fast-running tutorials and examples is probably something to strive for. I've definitely had the experience where re-running individual cells has burned me before, but its not a huge issue. I mentioned it more to suggest that development ease is not a foregone win for notebooks.

There's also the point that how we develop stuff and how we distribute stuff doesn't have to match. We could develop in notebooks and convert to scripts for commit or vice versa pretty easily, and in either case the intention is for users to be able to download them as notebooks. Don't even have to do it the same way for every example. So I don't think development ease should play into this decision as much as diffability or data redundancy concerns should.

> When do they do that?

Hmm, I might be confusing myself, I remember having to remove absolute paths from notebooks but it might have been in output cells.

**Comment by peastman** [comment]
For the cookbook I'm trying to keep all the code reasonably fast, less than a minute to execute the whole notebook on a laptop.  With tutorials that sometimes won't be possible.  If you're demonstrating how to run a simulation and analyze results, you need to run it long enough for the results to converge.  We should expect tutorials could sometimes take minutes to hours to fully run.

**Comment by raimis** [comment]
In general the idea and implementation are good.

Comments:
- The repo shouldn't contain notebooks by itself, but rather a list of notebook URLs and fetch them when building the website. It makes more sent to keep tutorials and cookbooks in the code repos, so it is more likely they are updated when the code changes.
- The rest machinery could be in a separate repo. Potentially, we can use this not only for cookbooks, but for the tutorials too, so the name could be more generic (e.g. `openmm-notebooks`).
- Regarding the integration with https://openmm.org, it could be the same like with the documentation: a separate website, which linked from https://openmm.org (https://openmm.org/documentation).
- An installer with global list of decencies (`openmm-cookbook/colab/construct.yaml`) will be problematic for the plugins. For example, OpenMM-Torch and OpenMM-Tensorflow need PyTorch and Tensorflow respectively, which will make the installer >1 GB. I think, it is better to build the environment for Colab directly from a Conda environment file. So each notebook can have a different file. Mamba is resolving dependencies pretty fast, so the custom installers not longer have significant speed advantage.

**Comment by Yoshanuikabundi** [comment]
Thanks!

 I think if we're keeping the notebooks in the code repo, we might as well keep the machinery there too. That way it lives with and can be deployed and versioned with the other documentation. I'll keep them separate for now while I iterate on them and we can merge them in later.

 The installer is already >1gb, coz it has Cuda, but it's a good point that we should support notebooks with different dependencies. I didn't start with this because it means each notebook needs its own metadata, which is an extra level of complexity that I wanted to see if I could avoid. The reason for the custom installer was because the kernel has to restart during the installation, and I wanted to keep all the setup commands in the one notebook cell. However, the !wget commands seem to work even though they're after the restart, so I'll try fitting `mamba` in there too!

**Comment by peastman** [comment]
@Yoshanuikabundi what still needs to be done to get the cookbook online?  If it's close to ready, and if you can describe the remaining task, I can try to finish it up.

**Comment by peastman** [comment]
We really need to get something online.  I've made several attempts to contact @Yoshanuikabundi to find out what I need to do to finish up his experimental website, but I haven't heard anything from him.  In the mean time, I'm inclined to just create a page on wiki with links to the notebooks.  I can do that very quickly, and it will be much better than nothing.  Then we can take our time in figuring out something nicer.

**Comment by jchodera** [comment]
As far as I can tell, everything actually works, so we can even just add a link to point to https://openmm.github.io/openmm-cookbook/dev/index.html right now if we wanted to have it go live right away.

**Comment by jchodera** [comment]
In fact, the current GitHub actions push to the `dev/` path, but it looks like the [GitHub Actions already contain a branch for handling `release` deployments](https://github.com/openmm/openmm-cookbook/blob/main/.github/workflows/gh-pages.yml#L71) to github pages for when we cut a release!

**Comment by peastman** [comment]
It seems possible.  I wish we could just get confirmation from @Yoshanuikabundi about what state he left the code in.  Are you in touch with him?  He hasn't replied to my emails.

**Comment by jchodera** [comment]
I've tried him on Slack, but there's a significant time difference---will let you know what he says.

From what I can see, this is fully functional and ready to go, but may require some additional tweaking and potentially additional content.

The [GitHub Actions nightlies](https://github.com/openmm/openmm-cookbook/actions) stopped running 24 days ago, presumably because the last push was some time ago and it thinks the repo is inactive. Once you try pushing some cleanup changes, it should be clear whether things are working as intended.

Let's run with it, and I can hop in and help (or get someone else to help) if we run into trouble?

**Comment by Yoshanuikabundi** [comment]
Hi all, sorry I've been difficult to contact. The cookbook is basically ready to go but could use a bit of polishing. In particular:

- Individual notebooks need thumbnail images
- The github actions need testing (particularly cutting a release)
- The details of the deployment need finalising (giving the GH pages a better URL or moving the deployment to S3)
- Theming and notebook organisation should be checked/finalised
- Additional content can be added at any time

I've described the update/release strategy we came up with on the cookbook repo readme, and the actions are written to support that:

- The cookbook is tested against OpenMM's `master` branch in [`ci-nightly.yml`](https://github.com/openmm/openmm-cookbook/blob/main/.github/workflows/ci-nightly.yml) (once/day)
- The cookbook's is tested against the latest OpenMM release (or technically whatever is in [environment.yml](https://github.com/openmm/openmm-cookbook/blob/main/environment.yml)) in [`ci-main.yml`](https://github.com/openmm/openmm-cookbook/blob/main/.github/workflows/ci-main.yml) (once/day or in PRs or pushes to main)
- The [`gh-pages.yml`](https://github.com/openmm/openmm-cookbook/blob/main/.github/workflows/gh-pages.yml) workflow deploys the cookbook on pushes to main, PRs, and releases (of the cookbook)
- Cookbook releases have to be cut manually, which involves merging in any `next` branch and pinning the appropriate OpenMM release in `environment.yml`. This could be automated in an action in the OpenMM repo if desired

> The [GitHub Actions nightlies](https://github.com/openmm/openmm-cookbook/actions) stopped running 24 days ago, presumably because the last push was some time ago and it thinks the repo is inactive.

Yep, that's right. The [workflow](https://github.com/openmm/openmm-cookbook/actions/workflows/ci-main.yml) [pages](https://github.com/openmm/openmm-cookbook/actions/workflows/ci-nightly.yml) state this explicitly and have a button to start them up again.

**Comment by peastman** [comment]
Thanks!  That sounds like it should work well.  I'll go ahead and add a link to it from the website, since it's already usable.  Then I can look into the remaining issues, but they sound like they're all much lower priority.

**Comment by peastman** [comment]
I just tried to make some changes in https://github.com/openmm/openmm-cookbook/pull/2, but it failed to deploy them:

```
Pushing deploy directory to gh-pages branch on openmm/openmm-cookbook repo
  /usr/bin/git push ***github.com/openmm/openmm-cookbook.git gh-pages
  remote: Permission to openmm/openmm-cookbook.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/openmm/openmm-cookbook.git/': The requested URL returned error: 403
```

Anyone have an idea what the fix is?

**Comment by jchodera** [comment]
From the [docs for that GitHub action](https://github.com/crazy-max/ghaction-github-pages#environment-variables), it looks like it uses a GitHub secret. Secrets are not substituted in PRs made from forks---you should use branches instead.

**Comment by peastman** [comment]
Thanks!  That fixed it.

**Comment by peastman** [comment]
I think we can call this done!  The website now has a link to the cookbook.  I also verified that I can add a new entry and everything gets updated correctly.

**Comment by jchodera** [comment]
@peastman: You appear to have linked to the `dev` version of the cookbook, rather than a specific deployed release. Is this what you intended to do? 

Would it make more sense to cut a release of the cookbook with examples that are paired with a specific OpenMM release? I forget how we had discussed this should work earlier.

**Comment by jchodera** [comment]
I've also tweeted about these:
https://twitter.com/openmm_toolkit/status/1491866763956346880

**Comment by peastman** [comment]
The link is just to https://openmm.github.io/openmm-cookbook.  But when you load that URL, it redirects to https://openmm.github.io/openmm-cookbook/dev/index.html.  It has something to do with how the repository is configured.

**Comment by jchodera** [comment]
Looks like the cookbook is proving to be wildly popular:
![image](https://user-images.githubusercontent.com/3656088/153653125-e9e935cc-6fed-424d-83a5-d293777bb1e2.png)
