### ISSUE TITLE
Question about scaling parameters and implementation multipole electrostatic potential in AMOEBA plugin

### ISSUE THREAD

**Issue by blues0024** [openmm/openmm#3168]
Hi everyone. While I'm reading 'AmoebaReferenceMultipoleForce.cpp' code in AMOEBA plugin, there was something I couldn't understand, so I'm inquiring through this channel.

About the previous AMOEBA paper and #2063, there are 2 scaling factor handling the interaction between permanent moments and induced dipoles, `dScale` & `pScale`. I understood as `dScale` is related with 'polarization group' and `pScale` is related with 'topology'. Through the whole code in 'AmoebaReferenceMultipoleForce.cpp', the other two terms called `_fixedMultipoleField` and `_inducedDipole` accompany another term with `Polar` suffix. (i.e. `_fixedMultipoleFieldPolar`) The two terms are scaled with `dScale` (w/o `Polar` suffix) or `pScale` (w/ `Polar` suffix) respectively. So I've understood as the two polarization terms are calculated contemporary.

However, in the function named `calculteElectrostaticPairIxn`, especially from the line number 1242 (and for PME case, 6520), `eUIndCoef` terms are scaled by `pScale` and `eUinpCoef` terms are scaled by `dScale`. `eUIndCoef` terms are calculated from `_inducedDipole` and `eUInpCoef` terms are calculated from `_inducedDipolePolar`, respectively. As far as I understand, the two terms seem like crossed. If I was wrong, please someone tell me why the scaling factors are multiplied to the other term.

Thank you :D

![image](https://user-images.githubusercontent.com/79687451/124439284-34864a80-ddb4-11eb-9e73-50b12b4e2dcf.png)

![image](https://user-images.githubusercontent.com/79687451/124439208-1882a900-ddb4-11eb-8899-4a3567f1ecf0.png)

![image](https://user-images.githubusercontent.com/79687451/124439154-07d23300-ddb4-11eb-8a03-746b1f74ef53.png)

**Comment by peastman** [comment]
The code is correct, but there isn't a simple answer for why it's correct.  That's just how the math works out.  The duplicate "polar" dipoles are a quirk of AMOEBA.  It groups atoms into "polarization groups".  For some parts of the calculation it ignores interactions between atoms in the same polarization group, and for other parts it includes them.  Originally AMOEBA was just designed for calculating energies, and this didn't add any significant cost or complexity.  Then people started trying to run dynamics with it, and realized that for computing forces it added a lot of complexity, since it ended up forcing you to compute and carry around two different dipoles for each atom, one that used the polarization groups and one that didn't.

**Comment by blues0024** [comment]
Thank you for your comment. So, you mean the induced dipoles with polarization groups are scaled by "pScale", which scaled originally electrostatic field not duplicated as polar, in the force calculation step, and vice versa right?

**Comment by peastman** [comment]
I don't remember the exact details, but dscale and pscale are both used to scale individual interactions when computing the induced dipoles.  Each will be between 0 (when the atoms are closely bonded to each other) and 1 (when they're separated by many bonds or are in different molecules).

**Comment by blues0024** [comment]
@peastman Thanks :) !!
