### ISSUE TITLE
Disuflide bond potential issue in OpenMM app

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3179]
@peastman: I just noticed this [openmm patch](https://github.com/deepmind/alphafold/blob/main/docker/openmm.patch) in the recent GitHub release of the [DeepMind AlphaFold2 code](https://github.com/deepmind/alphafold). Seems like the patch prevents a potential bug where more than one disulfide bond can be assigned to a Cys `SG` atom.

Perhaps we should see if this needs to be incorporated as a bugfix?

**Comment by peastman** [comment]
Yes, that does look useful.  @augustinzidek is it ok if we adopt your fix directly?  We would need permission to use it under the MIT license, since that's what the OpenMM Python layer uses.

And I'm very glad to see it's released.  I'm sure I'm not the only person who has been eagerly waiting for it!

**Comment by jchodera** [comment]
Tagging @Augustin-Zidek (since @augustinzidek appears to be a typo)!

**Comment by peastman** [comment]
Oops, sorry about that!

**Comment by Augustin-Zidek** [comment]
Sorry for the late reply. We are happy with the patch being included in OpenMM.

Note however, that our code is licensed under Apache 2.0, so that applies also to the patch as well. If that is compatible with OpenMM's license then feel free to apply the patch. If not, I am happy to send a separate PR to OpenMM with the patch which we would license under CC0.

**Comment by peastman** [comment]
Thanks!  A separate PR would be great.  The OpenMM Python code uses the MIT license, so one way or another we need permission to distribute the patch under those terms (which CC0 would do).

**Comment by Augustin-Zidek** [comment]
Hello, I sent a PR: https://github.com/openmm/openmm/pull/3203 with this patch.

**Comment by jchodera** [comment]
Thanks so much @Augustin-Zidek!

**Comment by peastman** [comment]
Fixed by #3203.
