### ISSUE TITLE
What is the difference between `setIncludeDirectSpace` and `setReciprocalForceGroup` ?

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#3279]
I noticed that a new method `getIncludeDirectSpace()` gets introduced into the latest OpenMM. Could you elaborate a bit about the difference between the following two code snippets ? From the documentation, it seems both will use only the reciprocal part of the nonbonded interactions. Is there a performance advantage to choose one over the other?
```
nbforce = NonbondedForce()
nbforce.setIncludeDirectSpace(False)
```
```
nbforce = NonbondedForce()
nbforce.setReciprocalForceGroup(1)
integrator.setIntegrationForceGroups({0})
context.getState(getEnergies=True, groups={0})
```

**Comment by Lnaden** [comment]
The idea behind your snippets would produce the same result. If your `getState` had `... groups={1})`, the results would be the same energy result since you would be getting the Reciprocal Space in both cases. 

As written, the first snippet gives reciprocal space energy and propagates time based only on the reciprocal space part of the nonbonded force, the second gives direct space energy and propagates time only on the direct space part of the nonbonded force. If you wanted to use the reciprocal part only for each example, you'd need to set `integrator.setIntegrationForceGroups({1})`.

The use case for each method one is a different.

The `setIncludeDirectSpace` would let you fully disable the direct space computation and replace it with something else you may be interested in, such as a `CustomNonbondedForce` which may represent the direct space differently (such as short range alchemical methods).

The `setReciprocalForceGroup` method puts the computation of the Reciprocal Space calculation into a different force group so you could split out the evaluation from each part of the nonbonded term and get their results separately. 

In your second snippet, time propagation would only use the direct space part of the nonbonded force, but you could still access the reciprocal energy by `context.getState(getEnergies=True, groups={1})`.

You could also mix both methods to access different use case. Say you want to replace the direct space computation with a localized reaction field-like potential, but want to use PME long range-based interactions (setting aside the validity of this for example purposes). What you could do is set `nbforce.setIncludeDirectSpace(False)` so you can still get the reciprocal space, and then write a `CustumNonbondedForce` with a cutoff to implement the direct space with this pseudo-reaction-field. Finally set each one to its own force group and propagate the integrator with all forces. In analysis, you can then access the value of each force through the `getState(getEnergies=True, groups={X})` replacing `X` with the force group each force is in. 

As for the cost advantage of using one or the other: I can't say exactly. Off the top of my head, i would say both examples in theory would run at the same speed (assuming `integrator.setIntegrationForceGroups({1})`) since they both are doing integration only over the reciprocal part and the actual energy evaluation doesn't happen during propagation. However, the implementation of each feature may give slightly different speeds.

**Comment by peastman** [comment]
You're correct that both features can be used to implement the same behavior.  It's really just a question of what is most convenient for your own code.  The particular use case that led us to add the feature was in Perses, where they wanted to use a soft-core interaction with PME.  That meant using a CustomNonbondedForce for direct space and a NonbondedForce for reciprocal space.  They could have done that with force groups, but then they would have needed to modify every place in their code that queried energies to specify the correct groups.  Being able to completely disable direct space, not just move it into a different group, saved a lot of annoying bookkeeping.

**Comment by z-gong** [comment]
Thank you for your elaboration !
