### ISSUE TITLE
Exception raised when creating exception with zero sigma and epsilon

### ISSUE THREAD

**Issue by mattwthompson** [openmm/openmm#3325]
Thanks for packaging betas - it's a huge help to be able to test against upstream changes without needing to build locally.

One of the additions in https://github.com/openmm/openmm/pull/3286 was a requirement that sigma values in exceptions must be non-negative. Forbidding negative sigma makes sense as that's non-physical. But there are some cases in which programmatically generating exceptions can hit the case of sigma being zero (along with epsilon also being zero). Five-site water models are one example; it's hard to imagine what a sigma should be for the interactions that have zero epsilon, so a zero sigma can sneak in and not cause too much trouble.

The exception is raised [here](https://github.com/openmm/openmm/blob/7.7.0beta/openmmapi/src/NonbondedForceImpl.cpp#L96-L97) and is new since version 7.6. More or less I'm proposing that it still throws on negative sigma but only throws on zero sigma if epsilon in non-zero. This could (and maybe should) be handled downstream, moving that logic to where we add virtual sites and their interactions to the force object. But it could also be a small patch directly in OpenMM. What do you think?

**Comment by jchodera** [comment]
I believe we had attempted to exclude setting `sigma` to zero because this can cause NaNs or instability when running simulations. 

In principle, we could only throw an exception for `sigma`=0 if `epsilon` != 0, and if `sigma=epsilon=0`, internally set `sigma` to a small value to prevent instabilities, but the problem with this would be that retrieving the system would result in modified values of the parameters, which would violate the "principle of least surprise".

**Comment by z-gong** [comment]
Isn't it an overkill to introduce these checks for the _correctness_ of force field parameters ?

I can understand that temperature or friction in an integrator must be non-negative because they are physically positive quantities.
However, it's not the case for the force field. A potential function is not necessarily constructed following solid physics. For MD simulation, any differentiable function should be considered as valid. For MC, we don't even have to use a  differentiable function.

A negative `k` in HaromicBondForce can be used to push two particles away. Even for the angle in `HarmonicAngleForce`, someone may try to use an equilibrated angle larger than `pi` to make sure a linear structure. These hacks are quite common for non-biological simulations.

I believe that it is the user's responsibility to make sure he inputs _the correct value following his need_.

**Comment by jchodera** [comment]
It's still possible to do all of what you describe with `Custom*Force` classes. The goal here is to make it hard to do the wrong thing by eliminating the potential for simple mistakes, like unit conversion errors. OpenMM also provides a way to avoid units altogether if you "know what you're doing", but these checks should catch a variety of common errors.

**Comment by peastman** [comment]
I had also thought in the past we ran into numerical problems caused by sigma being zero.  But looking at the code, I can't figure out how that would happen.  Sigma only appears in the numerator, never the denominator, so it shouldn't be a problem if it's zero.

I already had to remove the check for negative k in HarmonicBondForce, because it turned out AMOEBA used that for the Urey-Bradley term on water molecules.  I could remove the one on HarmonicAngleForce as well.

**Comment by mattwthompson** [comment]
> I believe we had attempted to exclude setting sigma to zero because this can cause NaNs or instability when running simulations.

FWIW, this is currently allowed; it doesn't happen often and does not cause (obvious) issues in the minimal cases in which we encounter it. Not having encountered these instabilities, I can only speak to my use case of excluding intramolecular particle interactions between virtual sites that have no vdW interactions, only a partial charge.

**Comment by j-wags** [comment]
>> Even for the angle in HarmonicAngleForce, someone may try to use an equilibrated angle larger than pi to make sure a linear structure.

>  I could remove the one on HarmonicAngleForce as well.

I was thinking about this last night - An angle over 180 would lead to a discontinuous derivative, which may not play nicely with integrators/energy conservation (though this is handwavey - I'm not an expert in that area). I wonder if this is a behavior question - "Should the built-in `HarmonicAngleForce` class guarantee continuous derivatives/compatibility with some family of simulation methods?"

**Comment by peastman** [comment]
That seems to me like a good argument for not allowing it.  If something will cause problems, it's reasonable to make people jump through a few hoops to do it.  But if it doesn't cause problems, we should allow it even if there's no obvious physical meaning.  So negative force constants are OK, but angles greater than 180 degrees are not.
