### ISSUE TITLE
Is there a Lepton function to check for NaN in CustomIntegrator?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#333]
Is there some way I can use Lepton functions to check if energies have gone `NaN` in `CustomIntegrator`?

**Comment by jchodera** [comment]
Reopening this to check if I have the best way to detect `nan` in a GHMC `CustomIntegrator`.

I'm using the following code block to add a GHMC step to my `CustomIntegrator` subclass:
```python
    def addGHMCStep(self):
        """
        Add a GHMC step.
        """
        self.hasStatistics = True

        self.addComputePerDof("sigma", "sqrt(kT/m)")

        #
        # Velocity randomization
        #
        self.addComputePerDof("v", "sqrt(b)*v + sqrt(1-b)*sigma*gaussian")
        self.addConstrainVelocities()

        #
        # Metropolized symplectic step.
        #
        self.addConstrainPositions()
        self.addConstrainVelocities()

        self.addComputeSum("ke", "0.5*m*v*v")
        self.addComputeGlobal("Eold", "ke + energy")
        self.addComputePerDof("xold", "x")
        self.addComputePerDof("vold", "v")
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
        self.addComputePerDof("x", "x + v*dt")
        self.addComputePerDof("x1", "x")
        self.addConstrainPositions()
        self.addComputePerDof("v", "v + 0.5*dt*f/m + (x-x1)/dt")
        self.addConstrainVelocities()
        self.addComputeSum("ke", "0.5*m*v*v")
        self.addComputeGlobal("Enew", "ke + energy")
        self.addComputeGlobal("accept", "step(exp(-(Enew-Eold)/kT) - uniform)")
        self.beginIfBlock("accept != 1")
        self.addComputePerDof("x", "xold")
        self.addComputePerDof("v", "-vold")
        self.endBlock()

        #
        # Velocity randomization
        #
        self.addComputePerDof("v", "sqrt(b)*v + sqrt(1-b)*sigma*gaussian")
        self.addConstrainVelocities()

        #
        # Accumulate statistics.
        #
        self.addComputeGlobal("naccept", "naccept + accept")
        self.addComputeGlobal("ntrials", "ntrials + 1")
```
The important code is this, which checks whether the move was accepted and is *supposed* to reject the move if the energy has become `nan`:
```python
        self.addComputeSum("ke", "0.5*m*v*v")
        self.addComputeGlobal("Enew", "ke + energy")
        self.addComputeGlobal("accept", "step(exp(-(Enew-Eold)/kT) - uniform)")
        self.beginIfBlock("accept != 1")
        self.addComputePerDof("x", "xold")
        self.addComputePerDof("v", "-vold")
        self.endBlock()
```
Oddly enough, I'm seeing some cases where `Enew` appears to be finite, but `x` ends up `nan` after this process (using both `CPU` and `CUDA` platforms). Adding an additional `addComputeSum('xsum_new', 'x')` can also catch that the positions `x` have become `nan`, but the energy remains finite.

I'm trying to come up with a minimal test example---unfortunately not easy, since I'm not certain what characteristics of the failing cases are important---but I'm a bit baffled how this could even happen. Anyone have any ideas?

**Comment by Lnaden** [comment]
Knowing you are doing alchemical transformations, I have personally seen `NaN`s get thrown when a not fully decoupled point-charge hydrogen (e.g. TIP3P, -OH groups in many force fields) approach a non-alchemical atom (or vice-versa). The hydrogen can approach the other charged atom much closer since its not properly shielded by the bonded partially decoupled Lennard-Jones atoms. The force shoots up and the numerical error from finite time step integration accumulates too fast, causing the particle positions to go to `NaN`. 

If you are doing simultaneous electrostatic + LJ decoupling in your GHMC process, you can get this effect. 

Here is a link to a video where I have a mostly decoupled OH group and a fully coupled ring. 
https://www.dropbox.com/s/oaietw6lelxu2qd/HelicopterOH.mpg?dl=0
If you frame the video forward, you see the hydrogen wiggle close, then go flying. The ring also deforms which I'm sure causes the bonded terms to explode in a cascade of bad. You are having something similar happen, but I can't be sure.

**Comment by peastman** [comment]
The code looks reasonable to me.  Here's how the step function is implemented:

```C++
return (args[0] >= 0.0 ? 1.0 : 0.0);
```

So if the argument is nan, that should evaluate to 0.  And I'm really baffled how you could have a position that's nan, yet have the energy evaluate to something finite.  I could sort of imagine something strange going on with that on the GPU, but for the CPU platform that really shouldn't happen.
