### ISSUE TITLE
TestCudaCompiler - sh: this does not exist

### ISSUE THREAD

**Issue by ca-taylor** [openmm/openmm#3373]
I built OpenMM 7.6.0 on RHEL 7.7 with CUDA 11.0.207.  The host compiler is gcc/9.3.0 and the OpenMPI is 4.0.4.   All seemed to go well and when I ran "make tests", 296 of 297 tests passed.   The only test that fails is "TestCudaCompiler".    

Even after looking at the source code for "TestCudaCompiler", I'm a bit perplexed.   This seems to have something to do with CudaTempDirectory but I've tried setting TMPDIR and it makes no difference.   It is also not clear why it is spitting out the name of a "log" file with the "this does not exist" exception message.   

I've also checked the setting of OPENMM_CUDA_COMPILER and it is correct and the compiler can be successfully instantiated.

> [chasman@c0803a-s23 build]$ ./TestCudaCompiler 
> sh: this does not exist/openmmTempKernel0x1bc55f0_117700.log: No such file or directory
> exception: Error launching CUDA compiler: 256

Has anyone seen this before?   Any idea where I'm going wrong and what I might do to avoid this?

**Comment by peastman** [comment]
You need to unset `OPENMM_CUDA_COMPILER` before running it.

A bit of background: OpenMM can compile CUDA kernels in two different ways, either with the runtime compiler library (nvrtc) or by invoking the standalone `nvcc` compiler.  Usually it defaults to nvrtc, but if you specifically request a particular compiler, such as by setting `OPENMM_CUDA_COMPILER`, it uses that instead.  TestCudaCompiler is specifically meant to test using nvrtc.  To make absolutely sure nvcc doesn't get used instead, and also to make sure it doesn't just reuse a previously compiled kernel (either of which could hide a problem invoking nvrtc), it sets the path to your temp directory to "this does not exist".  That ensures that trying to invoke nvcc will fail.

That's what's happening here.  You specifically asked it to use a standalone compiler.  That fails because it can't access the nonexistant temp directory.

**Comment by ca-taylor** [comment]
Yes, unsetting OPENMM_CUDA_COMPILER fixes the problem.   Thank you.

**Comment by peastman** [comment]
Great!  That test is kind of confusing.
