### ISSUE TITLE
Question: adjacency based alchemical reaction in OpenMM?

### ISSUE THREAD

**Issue by orioncohen** [openmm/openmm#3381]
Is there any tooling for performing an alchemical adjacency based reaction in OpenMM?

I would like to polymerize a polymer network from monomers. Ideally the tooling would be compatible with the Sage force field.

I am interested in something that acts like the [LAMMPS fix bond/react command](https://docs.lammps.org/fix_bond_react.html).

If this doesn't currently exist, how difficult would it be to implement an alchemical reaction based on some distance cutoff?

Thank you!

**Comment by jchodera** [comment]
OpenMM doesn't currently have this capability, but it certainly wouldn't be difficult to code something like this up in OpenMM yourself:
1. Construct an initial Topology for your monomers and geometry (e.g. with [PackMol](http://m3g.iqm.unicamp.br/packmol/))
2. Parameterize it with `openmmforcefields`
3. Run some dynamics
4. Assess which bonds (if any) should be created, and generate a new OpenMM Topology object representing the post-reaction system
5. Parameterize it with `openmmforcefields`
6. Map atomic coordinates to new Topology
7. Repeat steps 3-6 as desired
 
However, the [OpenFF Sage force fields](https://openforcefield.org/force-fields/force-fields/) are only practical for small molecules right now, since the AM1-BCC charging calculation becomes very slow for large molecules. (This should be addressed in upcoming releases that will move to graph net based charge models.)

**Comment by orioncohen** [comment]
Thanks for the quick response @jchodera!

Would that be possible to do entirely through the python API or would it require using C++?

**Comment by jchodera** [comment]
> Would that be possible to do entirely through the python API or would it require using C++?

Definitely easiest to do through Python!

**Comment by orioncohen** [comment]
Awesome. Thanks for the advice. I'll give that a try. Closing this now.
