### ISSUE TITLE
Data source for atomic masses

### ISSUE THREAD

**Issue by mattwthompson** [openmm/openmm#3434]
Hi OpenMM developers,

I'm curious if there's a data source for the values of elemental masses used in `openmm.app.element`. I could not find anything documented in the source code or docs, nor in the git history ([blame](https://github.com/openmm/openmm/blame/master/wrappers/python/openmm/app/element.py) / [mega-commit](https://github.com/openmm/openmm/commit/ccc0ba85e2b1964d048d7047661c414f421dd563)). I did some digging and found pretty good consistency with [IUPAC reports](https://www.ciaaw.org/publications.htm) sometime between 2001 and 2009, which makes sense given the history of the project.

Some element packages report [_slightly_](https://github.com/openforcefield/openff-toolkit/issues/1178) different values. While the sixth significant digit in the mass of a carbon atom probably matters for nobody, it would be nice to have note where the specific values came from. Note that I'm strictly asking about element masses, i.e. if a carbon's mass if 12.011 vs. 12.01078 vs. something else, Things like CODATA definitions of units, unit packages for the Python module, etc. are out of scope for what I'm getting after here.

**Comment by peastman** [comment]
No idea.  That file was created a long time ago by someone who hasn't been involved in the project for years.  If he didn't document the source, I don't know what it was.

Keep in mind that elemental masses are always a bit arbitrary.  They represent an average mass, not the mass of a single atom.  1 amu is defined as exactly 1/12 the mass of a 12C atom.  The mass of carbon is listed as slightly higher than 12 because about 1% of carbon atoms are 13C instead of 12C.  But that's just an average figure.  The ratio won't be exactly the same in every sample.  So "the mass of carbon" isn't a well defined physical quantity with a precise value.

**Comment by jchodera** [comment]
Yeah, it totally doesn't make sense to use average elemental masses (instead of true masses of a single isotope) because almost no properties of interest are linear in the these masses.
