### ISSUE TITLE
Should nonbonded exceptions apply cutoffs?

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#3467]
When computing nonbonded exceptions, we always include them at full strength regardless of the cutoff distance.  For PME that's obviously the correct thing to do.  All interactions are supposed to be included regardless of distance.  But for CutoffNonPeriodic and CutoffPeriodic it seems inconsistent.  Should we apply the cutoff to them?  This would change existing results, which is a little scary to do.  But I can't think of any good argument for why cutoffs shouldn't be applied.

**Comment by swails** [comment]
They're not subject to the cutoff in Amber either. Not sure about gromacs, but I strongly suspect charmm doesn't subject them to the cutoff either. 

A final observation I'll make is that you have often recommended a custom bond force as an implementation of non bonded exception parameters (as a workaround for custom nonbonded forces only supporting exclusions rather than exceptions). Those implementations do not obey a cutoff either. 

I can't think of a scenario in practice where a user would hit this condition and expect to get anything meaningful out of the model. Since either choice is almost certain to lead to garbage results, I'd personally opt to keep the garbage we have right now. 

Besides, the lepton parser supports enough special functions that an enterprising user that _wants_ the other flavor of nonsense can work around the limitation in a straightforward manner.

So until we have a compelling reason to change the behavior, I vote we keep it as-is.

**Comment by peastman** [comment]
I think Amber only supports sharp cutoffs, not reaction field?  That's the case where it makes a difference, since the interaction strength is reduced even for distances shorter than the cutoff.  I'm not sure what either Gromacs or CHARMM does in that case.

**Comment by swails** [comment]
Amber supports at least a shifting function, maybe a switch as well.

But to me, more importantly most force fields are parametrized by fitting the torsion potential to reconstruct what the 1-4 nonbonded interactions fail to capture.  So in a practical sense the exception interactions are as much a part of the torsion potential as they are part of nonbonded interactions.  There's a strong argument to make that scaling them in a reaction field would break the force field.

**Comment by peastman** [comment]
Fair enough.  I'll close this then.  Thanks for your insight!

**Comment by peastman** [comment]
I added documentation in #3470 to clarify this point.
