### ISSUE TITLE
truncated octahedron from LEaP

### ISSUE THREAD

**Issue by rpavlovicz** [openmm/openmm#3507]
Hi,

I have been preparing my systems in the LEaP module of AmberTools and have noticed that simulations setup with a truncated octahedron (solvateoct) solvent box are being treated as rectangular boxes in my OpenMM simulations. This creates imaging issues during processing as well as likely applying some unwanted forces on the system during equilibration. 

Is there a way to have OpenMM work with the input files I've generated with AmberTools?

Thanks for your help!

**Comment by peastman** [comment]
It's actually the same thing.  It turns out that a truncated octahedron is exactly equivalent to a triclinic box with a particular set of vectors, and that in turn is exactly equivalent to a rectangular box with offsets between periodic copies.  [This paper](https://onlinelibrary.wiley.com/doi/abs/10.1002/%28SICI%291096-987X%2819971130%2918%3A15%3C1930%3A%3AAID-JCC8%3E3.0.CO%3B2-P) describes how it works.

Try calling `getPeriodicBoxVectors()` on the Topology.  If the box truly is rectangular, each vector will have only a single nonzero element.  If additional elements are nonzero, that means it's triclinic.

**Comment by rpavlovicz** [comment]
Hey Peter,

Here's the prmtop.topology.getPeriodicBoxVectors():

`(Vec3(x=10.412634, y=0.0, z=0.0), Vec3(x=-3.4708777199444643, y=9.817125580899386, z=0.0), Vec3(x=-3.4708777199444643, y=-4.908562196362206, z=8.501880488197477)) nm`

And here's what the system looks like out of LEaP (a truncated octahedron):

<img width="602" alt="Screen Shot 2022-03-08 at 2 17 10 PM" src="https://user-images.githubusercontent.com/8700070/157335351-a7b9252b-680f-4d3c-8330-3326e26bd471.png">

and what it looks like after 5000 equilibration steps (a rectangular box):

<img width="604" alt="Screen Shot 2022-03-08 at 2 17 30 PM" src="https://user-images.githubusercontent.com/8700070/157335464-3f2bd117-7a4b-439d-8ab1-9641025838b0.png">

In my OpenMM script, the AmberPrmtop is used to create the system and simulation objects:

```
prmtop = AmberPrmtopFile('system.prmtop')

system = prmtop.createSystem(nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff, rigidWater=rigidWater, constraints=constraints, ewaldErrorTolerance=ewaldErrorTolerance, hydrogenMass=hydrogenMass)

simulation = Simulation(prmtop.topology, system, integrator, platform, platformProperties)
```

Am I missing a step?

**Comment by peastman** [comment]
I think everything is fine.  Notice that the box vectors contain off-diagonal nonzero elements.  That's how you know it's triclinic.  The visualization looks different, but that's just because it's being wrapped differently.  It really is completely equivalent.  The paper I linked explains all of it.

**Comment by rpavlovicz** [comment]
Thanks for taking a look and the reassurance, Peter.

I only noticed that my water box was changing apparent shape when I was having trouble imaging some of my trajectories with cpptraj, where I get this message:

```
Warning: Trajectory box type is 'Rhombohedral' but topology box type is 'Truncated octahedron'.
Warning: Setting topology box information from trajectory. 
```

I guess I'll take my issue over to the cpptraj repo :)

**Comment by rpavlovicz** [comment]
Just got help from @drroe on the cpptraj repo. It appears cpptraj is expecting a different unit cell format when reading a DCD file, which leads to the imaging problems I was having. In case anyone stumbles upon this, the solution to correctly image a system with cpptraj that was setup with `solvateoct` via LEaP in an OpenMM simulation using DCD output is to use the `ucell` command when loading your trajectory in cpptraj:

`trajin trajectory.dcd 1 last ucell`

Here's more detail from @drroe about the expected unit cell format for cpptraj when reading a DCD file:

> The problem appears to be in how OpenMM is writing unit cell information to DCD files. As you probably know, DCD is the binary charmm trajectory format. In charmm versions < 22, unit cell information was stored as X-aligned with 3x lengths and 3x angles (A, B, C, alpha, beta, gamma). From version 22 and up however, charmm stores the symmetric shape matrix (upper-right + diagonal, so still 6 elements). It seems that although OpenMM writes DCD trajectories with the version bit set to >= 22, it is still storing X-aligned unit cell values.
> 
> The good news is that you can work around this in cpptraj by telling it to assume the X-aligned unit cell values are stored via the ucell keyword for the trajin command

**Comment by peastman** [comment]
Thanks!  We should fix that.  @drroe is there a spec for the right way to store the information?

**Comment by drroe** [comment]
> Thanks! We should fix that. @drroe is there a spec for the right way to store the information?

Unfortunately nothing written down (at least not that I could ever find). I only figured it out by delving into the CHARMM source code (so. much. fun.). There's a paper describing the symmetric shape matrix but I'm having trouble remembering it now - I'll post an update if I think of it.

Check out the source code for cpptraj's DCD reader/writer here: https://github.com/Amber-MD/cpptraj/blob/10562263434a62d9ef04115585c2d004bad5b9c8/src/Traj_CharmmDcd.cpp

In particular the `Traj_CharmmDcd::ReadBox()` and `Traj_CharmmDcd::readFrame()` functions. The logic for assigning the unit cell from shape matrix is in https://github.com/Amber-MD/cpptraj/blob/10562263434a62d9ef04115585c2d004bad5b9c8/src/Box.cpp in the `Box::CalcXyzAbgFromShape()` function. The Box class also has the logic for going the other way. Sorry the code is all a little messy, let me know if anything is unclear or if I can help in any way.

**Comment by peastman** [comment]
I've been looking through various DCD readers and writers to figure out the best way of fixing this.  First there's the [one in MDTraj](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/dcd/src/dcdplugin.c), which looks like it was probably originally adapted from NAMD.  It writes exactly the same format as OpenMM: the version number is reported as 24, and it writes box lengths and angles.  When reading files, it always interprets the values as box lengths and angles as well, regardless of the version number.

Then there's the [one in ChimeraX](https://github.com/RBVI/ChimeraX/blob/872021d21ca596585dd464121527c882accbb473/src/bundles/md_crds/src/dcd/MDToolsMarch97/md_DCD.py).  Unfortunately it just ignores box information, so it isn't useful in figuring out what to do (or alternatively, it just doesn't matter since anything will work equally well).

[This one](http://prody.csb.pitt.edu/_modules/prody/trajectory/dcdfile.html) is from a program I'm not familiar with called ProDy.  Its behavior is the same as MDTraj: write angles and assume the values it reads are angles, regardless of version number.

 Of course I'd really like to see what CHARMM does, but I don't have access to the source code.

Given these behaviors, perhaps the best solution is to continue writing angles but report the version number as 0 rather than 24?  If I understand correctly (which I'm not confident of!), that indicates a file written by NAMD rather than CHARMM.  But the other codes I looked at also write 24 while reporting angles.

**Comment by drroe** [comment]
So in CHARMM, there is code like this in the trajectory read routines (this is from `dynamc/cvio.F90`):
```Fortran
     IF(QCRYS .AND. XDIM > 0) THEN
        IF (ICNTRL(20) < 22) THEN
           !     for version numbers  <  22 we have XUCELL data in XTLABC.
           xucell(1:6) = xtlabc(1:6)
           CALL XTLAXS(XTLABC,XUCELL)
        ENDIF
     ENDIF
```
where `XTLAXS` is a subroutine that converts unit cell parameters (a,b,c,alpha,beta,gamma) to the symmetric shape matrix (located in `image/crystal.F90`).

> Of course I'd really like to see what CHARMM does, but I don't have access to the source code.

There is a free version of charmm (https://charmm.chemistry.harvard.edu/charmm_lite.php) but if that's a pain just email me directly and I can get you the necessary files.

**Comment by drroe** [comment]
> Given these behaviors, perhaps the best solution is to continue writing angles but report the version number as 0 rather than 24?

CPPTRAJ sets the version to 21 if writing the X-aligned unit cell parameters (since that was the last version of charmm to write unit cell params) and 35 otherwise, which seems to work ok. The read routines assume shape matrix if version >= 22, unit cell params otherwise (like charmm itself).

**Comment by peastman** [comment]
> CPPTRAJ sets the version to 21 if writing the X-aligned unit cell parameters

That sounds like a good strategy.  It should produce files that are read correctly by all the programs I've looked at.  I'll do that.
