### ISSUE TITLE
Using Modeller addSolvent with Gromacs input files

### ISSUE THREAD

**Issue by djhuggins** [openmm/openmm#3566]
Hello,

I have Gromacs input structure and toplogy files (.gro and .top) for a molecule. I would like to solvate the molecule in OpenMM. I usually use Modeller's addSolvent function to achieve this when using PDB/XML input files.

With Gromacs there is a problem that I do not have molecule parameters available as an XML file to feed into ForceField and thus addSolvent will not run, complaining about the missing residue template.

Are there alternatives to addSolvent I should consider or any other ways to provide ForceField with the parameters it needs?

Thanks very much,

Dave

**Comment by peastman** [comment]
What sorts of molecules are in your system?  Are they all found in standard force fields?  `addSolvent()` needs the force field to determine charges and atomic radii.

**Comment by djhuggins** [comment]
Hi there,

Thanks. Thats the problem. The molecules are not found in standard force fields. This is for an absolute binding free energy calculations benchmark set from Bayer:

https://github.com/bayer-science-for-a-better-life/abfe-benchmark

The inputs are all Gromacs files.

Cheers,

Dave

**Comment by peastman** [comment]
In order to use `addSolvent()`, you need a ForceField that can parametrize the Topology.  It doesn't have to be the one you'll actually use for the real simulation, just something that provides reasonable parameters for use in building the water box.  [These instructions](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#small-molecule-parameters) describe how to register a template generator for a small molecule.

What's the larger workflow this is part of?  Once you create the water box, what do you plan to do with it?  I assume you eventually want to do calculations of some sort with it, and at that point you'll need to parametrize it anyway.

**Comment by djhuggins** [comment]
Thanks. This is for alchemical calculations. For benchmarking/comparison purposes, all the parameters used in the simulation must be those from the Gromacs file.

**Comment by peastman** [comment]
But you're adding more molecules to the Topology.  The Gromacs file only provides parameters for what's in the Gromacs file.  If you want to create a System based on what's in the file, then you have to stick with exactly what's in the file, nothing else.

**Comment by djhuggins** [comment]
Ok thanks. I will have to ask for pre-solvated systems or use another piece of software.

**Comment by peastman** [comment]
You should be able to use the [gmx solvate](https://manual.gromacs.org/documentation/2018/onlinehelp/gmx-solvate.html) command to add water to the Gromacs file.  Then you can load the file into OpenMM.

**Comment by peastman** [comment]
Closing this, since the question has been answered.
