### ISSUE TITLE
modeller delete all the bonds

### ISSUE THREAD

**Issue by cyrushu** [openmm/openmm#3609]
Dear developer,

The model delete api delete all the bonds.
The 4 chains contains:
chain0: protein, chain1: ligand, chain2: water, chain3: ions

```python
In [14]: import openmm;openmm.__version__
Out[14]: '7.7'

In [1]: from openmm.app import PDBxFile
   ...: from openmm.app import Modeller
   ...: import copy
   ...:
   ...: pdb = PDBxFile('./solv.pdbx')
   ...: top =  copy.deepcopy(pdb.topology)

In [2]: top
Out[2]: <Topology; 4 chains, 16113 residues, 54938 atoms, 39468 bonds>

In [3]: to_delete= []
   ...: for chain in top.chains():
   ...:      if chain.index>1:
   ...:          to_delete.append(chain)
   ...:

In [4]: model = Modeller(top,pdb.positions)

In [5]: model.delete
Out[5]: <bound method Modeller.delete of <openmm.app.modeller.Modeller object at 0x7f50cfc4c490>>

In [6]: model.delete(to_delete)

In [7]: model.topology
Out[7]: <Topology; 2 chains, 533 residues, 8320 atoms, 0 bonds>

In [8]: list(model.topology.bonds())
Out[8]: []


```

**Comment by peastman** [comment]
Can you post your input file?

**Comment by cyrushu** [comment]
please rename it into solv.pdbx
[solv.txt](https://github.com/openmm/openmm/files/8731269/solv.txt)

**Comment by peastman** [comment]
The problem is caused by your call to `deepcopy()`.  The Topology contains a list of atoms, and also a list of bonds that consist of two atoms.  `deepcopy()` separately makes deep copies of those containers and everything they contain.  As a result, each bond lists two Atom objects that are not actually present in the Topology's list of atoms.

If you call `copy()` instead of `deepcopy()` it works correctly.  Or you can just omit copying altogether.  There's no need for it, since Modeller never modifies the existing Topology.  It just creates new ones.

**Comment by cyrushu** [comment]
> The problem is caused by your call to `deepcopy()`. The Topology contains a list of atoms, and also a list of bonds that consist of two atoms. `deepcopy()` separately makes deep copies of those containers and everything they contain. As a result, each bond lists two Atom objects that are not actually present in the Topology's list of atoms.
> 
> If you call `copy()` instead of `deepcopy()` it works correctly. Or you can just omit copying altogether. There's no need for it, since Modeller never modifies the existing Topology. It just creates new ones.

wow! Thank you for your reply and nice project like openmm series.
