### ISSUE TITLE
Simulated tempering in the isothermal-isobaric ensemble

### ISSUE THREAD

**Issue by SHervoe-Hansen** [openmm/openmm#3612]
Hi OpenMM-devs,

I am attempting to run simulated tempering in the isothermal-isobaric ensemble, however upon inspection of the code it appears to me it only works in the canonical ensemble or non-MC volume regulated simulations?

I was wondering, could one run with a Monte Carlo barostat by addition of the following code?
```python
# Select the initial temperature.

self.currentTemperature = 0
self.simulation.integrator.setTemperature(self.temperatures[self.currentTemperature])
for force in self.simulation.system.getForces():
    if force.getName() == 'MonteCarloBarostat':
        force.setDefaultTemperature(self.temperatures[self.currentTemperature])
```
and
```python
# Select this temperature.
self._hasMadeTransition = True
self.currentTemperature = j
self.simulation.integrator.setTemperature(self.temperatures[j])
for force in self.simulation.system.getForces():
    if force.getName() == 'MonteCarloBarostat':
        force.setDefaultTemperature(self.temperatures[self.currentTemperature])
```
Looking forward hearing from you and hoping to get even more hands-on with OpenMM in the future.

**Comment by peastman** [comment]
Good point.  Yes, you're right it should change the barostat temperature as well.  Changing the default temperature on the barostat won't affect an existing simulation though.  Instead you need to change the parameter on the context.  You can do it like this.

```python
for param in self.simulation.context.getParameters():
    if 'MonteCarloTemperature' in param:
        self.simulation.context.setParameter(param, self.temperatures[self.currentTemperature])
```

That should cover all the barostat classes, since they have parameter names like "AnisotropicMonteCarloTemperature", "MembraneMonteCarloTemperature", etc.  A PR would be welcome!

**Comment by SHervoe-Hansen** [comment]
Thank you for the rapid reply and help. I will look into making a PR as soon as possible.
