### ISSUE TITLE
Full nonbonded interactions in NPT ensemble 

### ISSUE THREAD

**Issue by moeenmeigooni** [openmm/openmm#3623]
I am trying to set up a simulation of a small solvated peptide system of around 5000 atoms. I want to use the combination of:
(1) full nonbonded interactions using NoCutoff
(2) pressure control using MonteCarloBarostat
However, OpenMM does not allow me to use both (1) and (2) at the same time. Consider the excerpt below:
```python
...
psf.setBox(boxX*nanometer, boxY*nanometer, boxZ*nanometer)
system = psf.createSystem(params, nonbondedMethod=NoCutoff, constraints=HBonds)
system.setDefaultPeriodicBoxVectors(*psf.boxVectors)
system.addForce(MonteCarloBarostat(1*atmosphere, 300*kelvin))
...
```

Declaring a Simulation with the above System results in the following error:
```
simtk.openmm.OpenMMException: A barostat cannot be used with a non-periodic system
```

Oddly, my system is being recognized as non-periodic, but only if I add the barostat. If I remove the line that adds the barostat, the Simulation has no problem being initialized and recognized as periodic. 
```python
...
psf.setBox(boxX*nanometer, boxY*nanometer, boxZ*nanometer)
system = psf.createSystem(params, nonbondedMethod=NoCutoff, constraints=HBonds)
system.setDefaultPeriodicBoxVectors(*psf.boxVectors)
#system.addForce(MonteCarloBarostat(1*atmosphere, 300*kelvin))
...
``` 
Declaring a Simulation with the above System throws no errors. The resulting dcd trajectory shows NVT behavior with fixed box dimensions and molecules crossing the periodic boundary. 

Why would adding a barostat cause the system to be recognized as non-periodic when the same system with no barostat is recognized as periodic? At first I thought maybe ```nonbondedMethod = NoCutoff``` assumes the system is non-periodic and thus does not support periodic boundary conditions. However, since omitting the line that adds the barostat results in periodic boundary conditions with a constant volume, this appears to not be the case. Similarly, if I keep the barostat, but instead use ```CutoffPeriodic``` or ```PME``` as my nonbondedMethod, the Simulation has no problem initializing and running NPT. There seems to be a problem specifically with the combination of NoCutoff and MonteCarloBarostat.

Is there any theoretical reason why NoCutoff should not be used in pressure-controlled periodic systems? This seems like an ordinary setup for small systems so I feel like I'm missing something crucial or obvious. I say ordinary because I think it's fair to expect full nonbonded calculations to be faster for very small systems (such as mine) compared to other methods like PME whose performance scaling is better suited to large systems.

**Comment by peastman** [comment]
Instead of approaching it from the algorithm, start from the physical system you want to simulate.  Each nonbonded method is an approximation to a particular physical system.

There are two main types of physical systems people simulate:

- Vacuum simulations.  There is a single isolated copy of the system.
- Bulk simulations.  The system repeats periodically throughout space to represent an infinite system.

`NoCutoff` and `CutoffNonPeriodic` are used for the first type.  `NoCutoff` computes it exactly, while `CutoffNonPeriodic` tries to approximate it at lower computational cost.  There are no periodic boundary conditions, because that's not the physical system they're designed to simulate.

The other methods all represent an infinite repeating system.  `CutoffPeriodic` approximates it while using a cutoff.  `PME` approximates it much more accurately by computing the full set of Coulomb interactions with all the infinite periodic copies.  `LJPME` is still more accurate by computing all the infinite Van der Waals interactions as well.

What is the physical system you want to simulate?

**Comment by moeenmeigooni** [comment]
The system I want to simulate is a polypeptide in water in its zwitterionic form. I am specifically interested in the interactions between the oppositely charged termini, so I don't want their electrostatic interactions to be approximated in any way. Therefore I do not want to use any nonbonded method with a cutoff or correction that might influence the sensitive long-range Coulombic interaction between the termini.  I cannot use the reaction field method because that method assumes the net charge of the set of particles within the cutoff to be neutral, which is not the case for this system because the two termini can be separated by a distance larger than the nonbonded cutoff, and no counter-ions are present. If I use Ewald or PME, there is no net force between these charged groups if their separation is exactly half the box length because of the regular spacing of the infinite lattice, so I'd have to use an extremely large water box to prevent this, which is also undesirable.

I get that different nonbonded methods are designed for different physical systems, so I should choose the nonbonded method that has been designed for the type of physical system I want to simulate. My question is deeper than just 'which nonbonded method should I use for my system'. Rather, why is it considered fundamentally improper to compute nonbonded forces as I've described (N^2 interactions applied between periodic images)? What assumptions am I breaking? I was looking for an answer beyond the tautology of "that is not what it was designed for". Since my question is really about the theory of molecular simulation rather than something specific to OpenMM, I suppose I should just read the early literature on molecular simulation methods instead of continuing here.

**Comment by peastman** [comment]
Questions about theory are welcome.  It's part of what we're here for! :)

> I am specifically interested in the interactions between the oppositely charged termini, so I don't want their electrostatic interactions to be approximated in any way.

That's the case PME is designed for.

> there is no net force between these charged groups if their separation is exactly half the box length because of the regular spacing of the infinite lattice, so I'd have to use an extremely large water box to prevent this, which is also undesirable.

That's inherent in using a periodic system to approximate a non-periodic one.  Really you want to simulate a huge box of solvent, but that would be far too expensive.  Instead you simulate a smaller one with periodic boundary conditions.  For a lot of purposes it works well, but you do have to watch out for artifacts coming from the periodicity.  Very roughly speaking, to avoid artifacts you need the width of the box to be larger than the length scale of whatever physical effects you're studying.  I don't know of any way to get around that requirement.

> why is it considered fundamentally improper to compute nonbonded forces as I've described (N^2 interactions applied between periodic images)?

If I've understood correctly, your suggestion is that each atom should only interact with the nearest periodic copy of each other atom, but that interaction should be computed at full strength, not reduced with distance like in reaction field?  Consider what would happen when two atoms are separated by almost exactly half the box width.  Because Coulomb interactions decay slowly with distance, and because you don't want to use a huge box, the force will still be significant at that point.  Each atom feels a force pointing away from the other.  Than one of them moves by a tiny amount so a different periodic copy becomes the nearest one.  The force abruptly changes and points in a different direction.  You've created a discontinuity where an infinitesimal displacement leads to a large change in force.  This is a problem for two reasons.

1. It will break lots of numerical algorithms.  Integrators are based on the assumption that forces are continuous, so this will lead to large errors.  It also won't come anywhere close to conserving energy, which breaks most sampling algorithms.
2. It isn't an approximation to any physical system.  Whatever it is you're trying to model, this calculation would not be a meaningful representation of it.  Real physical systems don't involve forces that undergo large discontinuous changes at arbitrary separations.

**Comment by moeenmeigooni** [comment]
Thank you for the thorough explanation! I think I'm finally starting to make sense of this. 

I think part of my confusion comes from how the motivations for using PME and other nonbonded methods are usually presented. Consider this excerpt from the introduction of the 1991 JCP paper "Peptides in ionic solutions: A comparison of the Ewald and switching function techniques" by Smith and Pettit:

>Truncation of the electrostatic interactions is usually necessary to reduce the computational requirements from a problem which scales as the square of the number of particles to one which scales linearly with particle number. In modern simulation studies there are at least four main techniques used to treat long-ranged electrostatic interactions. These are: (i) simple truncation, where interactions beyond a certain specified distance are neglected, (ii) the shifted potential, which shifts the Coulombic interaction forcing it to be zero at some specified distance, (iii) the switching function, which modifies the normal coulombic potential by forcing it to smoothly approach zero over some specified distance, typically. 1-4 A, and (iv) the Ewald technique, which uses the periodicity of the system, via lattice sums, to truncate the electrostatic interactions at very large distances (of the order of many box lengths). 

Here (and often elsewhere) the modification of long-range electrostatics is presented as a means of addressing the scaling problem, rather than as a fundamental necessity for periodic systems. I figured that for small systems, it would be preferable to compute N^2 nonbonded interactions between nearest periodic copies at full strength, because that would be more 'accurate'. It never quite clicked for me until your explanation that _any_ nonbonded force in a periodic system must be modified at distances approaching half the box length. Thinking of it in terms of physical systems helps tremendously; that periodic boundary conditions are not just a trick to reduce the amount of water you need, but that the dynamics you observe in such a system are actually representative of an infinitely repeating system. 

I suppose I will just have to add more water :). Thanks again for your feedback.
