### ISSUE TITLE
Modifying the PME calculations for smeared charges

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3676]
Hello!

Instead of using point charges, I would like to use smeared charges, or ions with radial Gaussian charge distributions.

I came across an implementation by [Eslami, Khani, and Muller-Plathe](https://pubs.acs.org/doi/full/10.1021/acs.jctc.9b00174) that has a very similar form to the particle mesh Ewald (PME) summation that is currently being used by OpenMM, except with a slightly different "direct" term since the Coulomb potential with smeared charges does not diverge as r -> 0 and is finite.

I found the implementation for the PME calculation for `NonbondedForce` in `ReferenceLJCoulombIxn::calculateEwaldIxn` (lines 190-524 of `openmm/platforms/reference/src/SimTKReference/ReferenceLJCoulombIxn.cpp`). If I only needed to change the "direct" term, what would be the best way to do so? I may still need the default Coulomb potential in the future, but I did not find any easy ways to implement what I want using `CustomNonbondedForce` since it doesn't support PME (naturally). In LAMMPS, I would simply create a new potential, but it doesn't seem so straightforward here.

Thanks in advance for any pointers/suggestions.

**Comment by peastman** [comment]
It's possible to do that.  The trick is to use NonbondedForce for the reciprocal space calculation and CustomNonbondedForce for the direct space calculation.  Just call [setIncludeDirectSpace(False)](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.NonbondedForce.html#openmm.openmm.NonbondedForce.setIncludeDirectSpace) on the NonbondedForce.

Remember that this removes LJ as well as Coulomb, so you'll need to compute that in your CustomNonbondedForce as well.  Or you could use a second NonbondedForce just for it, setting all charges to 0.  Likewise, it prevents any exceptions added to the NonbondedForce from being computed, since those are in direct space.

**Comment by bbye98** [comment]
Brilliant solution. I do not need the Lennard-Jones potential, just the electrostatic interactions, so this is perfect.

Is the error function (`erf`) available in the `CustomNonbondedForce` implementation?

**Comment by peastman** [comment]
Correct, but it requires the NonbondedForce and CustomNonbondedForce to have identical sets of excluded interactions.  That's because it uses a single neighbor list for both of them.  Of course, the exclusions (or rather, exceptions) added to the NonbondedForce won't affect anything since you never compute the direct space part.

It's also important to understand how exceptions interact with PME.  It can be a bit confusing.

- Interactions beyond the cutoff distance are computed entirely by the reciprocal space term.  Ones closer than the cutoff are a mix of direct space and reciprocal space.  Both contribute significantly.
- It's easy to omit exceptions or exclusions from the direct space term, but it's impossible to omit them from the reciprocal space term.  They always get included (based on standard charges, not the alternate charge products specified in the exception) whether you want them or not.
- Therefore we need to subtract that part back off in direct space.  NonbondedForce does this automatically when computing its direct space term.  For each exception, it computes the energy with the modified parameters minus `erf(alpha*r)` times the energy with standard charges to remove the part that was incorrectly included in reciprocal space.

Since you're going to be computing direct space yourself, if you have any nonbonded exceptions that involve nonstandard charges you'll need to include that correction.  [Here is the code](https://github.com/openmm/openmm/blob/1dac981a63300a2a53a7925f570995914f7163ed/platforms/reference/src/SimTKReference/ReferenceLJCoulombIxn.cpp#L469-L498) that computes that correction in the Reference platform.

**Comment by bbye98** [comment]
Thanks for the explanation.

I plan on pairing the smeared Coulomb potential with a Gaussian potential for the excluded volume interactions (of course, with the Gaussian potential being stronger than the Coulomb potential at short ranges so particles don't collapse into each other as r -> 0).

In a bulk system, this should be straightforward to implement, When I tried doing so, the performance dropped from ~350 ns/day (LJ + Coul) to less than 30 ns/day (Gauss + smeared Coul). Any tricks to speed up the run/optimize the `NonbondedForce`s?

    def pair_gauss_mass(cutoff: float, A: float) -> openmm.CustomNonbondedForce:

    """
    Implements the Gaussian potential for particles with smeared masses.

    Arguments:
        cutoff:         System cutoff. Reference unit: nm.
        A:              Interaction strength.
                        Reference unit: nm^-3 * kJ / mol.
    
    Return:
        gauss:          openmm.NonbondedForce.
    """
    
    cutoff_nd = cutoff / unit.nanometer
    gauss = openmm.CustomNonbondedForce(
        f"step({cutoff_nd} - r) * (alpha * (exp(-beta * r ^ 2) - exp(-beta * {cutoff_nd} ^ 2)));"
        f"alpha = A * (beta / {np.pi}) ^ (3 / 2);"
        "beta = 3 / (2 * sigma ^ 2);"
        "sigma = sqrt(sigma1 ^ 2 + sigma2 ^ 2);"
    )
    gauss.addGlobalParameter("A", A)
    gauss.addPerParticleParameter("sigma")
    gauss.setCutoffDistance(cutoff)
    gauss.setNonbondedMethod(openmm.CustomNonbondedForce.CutoffPeriodic)
    return gauss

    def pair_gauss_charge(
        cutoff: float, eps: unit.Quantity, lB: unit.Quantity,
        alpha: unit.Quantity, dims: unit.Quantity, tol: float = 1e-5
    ) -> openmm.NonbondedForce:

    """
    Implements the Gaussian potential for particles with smeared
    charges.

    Arguments:
        cutoff:         System cutoff. Reference unit: nm.
        eps:            Thermal energy. Reference unit: kJ / mol.
        lB:             Bjerrum length. Reference unit: nm.
        alpha:          Ewald summation coefficient.
                        Reference unit: nm^-1.
        dims:           System dimensions. Reference unit: nm.
        tol:            Error tolerance for Ewald summation.
                        Defaults to 1e-5.
    
    Returns:
        direct:         NonbondedForce for real-space sums.
        recip:          NonbondedForce for reciprocal-space sums.
    """
    
    alpha = alpha.in_units_of(unit.nanometer ** -1)

    direct = openmm.CustomNonbondedForce(
        "lBkBT * z1 * z2 * (erf(alpha_ij * r) - erf(ewaldCoeff * r)) / r;"
        f"alpha_ij = sqrt({np.pi} / (a1 ^ 2 + a2 ^ 2)) / 2;"
    )
    direct.addGlobalParameter("ewaldCoeff", alpha)
    direct.addGlobalParameter("lBkBT", (lB * eps).in_units_of(unit.nanometer * unit.kilojoule_per_mole))
    direct.addPerParticleParameter("a")
    direct.addPerParticleParameter("z")
    direct.setCutoffDistance(cutoff)
    direct.setNonbondedMethod(openmm.CustomNonbondedForce.CutoffPeriodic)
    
    n_mesh = np.ceil(2 * alpha * dims / (3 * tol ** (1 / 5)))
    recip = openmm.NonbondedForce()
    recip.setCutoffDistance(cutoff)
    recip.setIncludeDirectSpace(False)
    recip.setPMEParameters(alpha, *n_mesh)
    recip.setNonbondedMethod(openmm.NonbondedForce.PME)

    return direct, recip

**Comment by peastman** [comment]
Which platform are you using?  On CUDA and OpenCL CustomNonbondedForce should have similar speed to NonbondedForce (assuming the interaction you compute has similar cost), but for CPU it's a lot slower.  OpenMM 8.0 improves it though.

Assuming you're running on a GPU, we need to figure out what makes your force so expensive.  Try removing each of the two forces to find out how expensive each is, then try removing pieces of each one to find the most expensive parts.  The calls to `erf()` are a likely candidate.  They get computed by the GPU's special functions unit, which has much lower throughput than most other calculations.

**Comment by bbye98** [comment]
That is correct--I am using the CUDA platform on a RTX 3080 Ti / RTX 3090. Let me try removing the forces one-by-one and see what performance change I get. I will report back shortly.

**Comment by bbye98** [comment]
Hello! Sorry for the late response.

Here are my findings on my RTX 3090 running OpenMM 7.7 via WSL2 (just for testing purposes):

WCA: 495 ns/day
WCA + Coulomb: 252 ns/day
WCA + smeared Coulomb: 24.7 ns/day
Gaussian: 487 ns/day
Gaussian + Coul: (not possible due to divergence as r -> 0)
Gaussian + smeared Coulomb: 24.7 ns/day

So it looks like the slowdown is definitely caused by my implementation of the smeared Coulomb potential. Is there anything obviously wrong with my implementation in `pair_gauss_charge()` above? Would it be better to evaluate the Coulomb potential part (factor in front of erf functions) normally instead of `lBkBT * z1 * z2` (Bjerrum length * thermal energy per mole * charge numbers)? Am I choosing `n_mesh` correctly (I used the formula in the theory section of the OpenMM user guide)?

Or is implementing a custom kernel the only way to get performance similar to the regular Ewald summation?

Thanks in advance for any advice/feedback!

**Comment by peastman** [comment]
What are the actual values of `alpha` and `n_mesh`?  The formula in the user guide assumes you're also choosing `alpha` in the way it specifies.  If you're using a different value, that formula might lead to a mesh that's much larger than you need.

Also, what are the cutoff distance and box size?

**Comment by bbye98** [comment]
This is subject to change, but currently I'm using:

```
cutoff =2.061140461006964 nm
dims = [6.29, 6.18342138, 12.63185917] nm
alpha =5.529327076391912 nm^-1
tol = 1e-5
n_mesh = np.ceil(2 * alpha * dims / (3 * tol ** (1 / 5))) = [232, 228, 466]
```

 Is this far off from default implementation? I tried to set up a `NonbondedForce` normally by setting the tolerance, but calling `getPMEParameters()` on it returned zeros.

**Comment by peastman** [comment]
That's a huge grid.  Here's a script to show the parameters OpenMM chooses by default for that box size and cutoff, along with different tolerances.

```python
from openmm import *
system = System()
system.addParticle(1.0)
system.setDefaultPeriodicBoxVectors(Vec3(6.29, 0, 0), Vec3(0, 6.18342138, 0), Vec3(0, 0, 12.63185917))
nb = NonbondedForce()
nb.addParticle(1.0, 1, 1)
nb.setCutoffDistance(2.061140461006964)
nb.setNonbondedMethod(NonbondedForce.PME)
system.addForce(nb)
for tol in [5e-4, 2e-4, 1e-4, 5e-5, 2e-5, 1e-5]:
    nb.setEwaldErrorTolerance(tol)
    integrator = VerletIntegrator(0.001)
    context = Context(system, integrator, Platform.getPlatformByName('Reference'))
    print(tol, nb.getPMEParametersInContext(context))
```

Here is the output.

```
0.0005 [1.2751488482228122, 25, 25, 50]
0.0002 [1.35708830885305, 32, 31, 63]
0.0001 [1.4159263383955132, 38, 37, 76]
5e-05 [1.4724150615565634, 45, 44, 90]
2e-05 [1.5439204015752517, 57, 56, 114]
1e-05 [1.5958849971526081, 67, 66, 135]
```

However you probably don't really want such a large cutoff.  A shorter cutoff will probably be faster.  Reducing it to 1 nm gives this output.

```
0.0005 [2.628260884878466, 51, 50, 102]
0.0002 [2.797149622536537, 65, 64, 130]
0.0001 [2.918423065872431, 78, 76, 156]
5e-05 [3.0348542587702925, 93, 91, 186]
2e-05 [3.182236808260871, 117, 115, 234]
1e-05 [3.2893431387452243, 138, 136, 278]
```

Also consider that the default tolerance of 5e-4 is accurate enough for most purposes, and 5e-5 is very high accuracy.  In fact, unless you use double precision, asking for a tolerance less than 5e-5 will likely make the actual accuracy go down rather than up due to increased numerical error.

**Comment by peastman** [comment]
Is there a good reason not to use OpenMM's calculation for alpha?

The recommended way to use it is to choose the tolerance based on your application's accuracy requirements.  You can then adjust the cutoff to optimize speed, letting it automatically select alpha and grid size.

**Comment by bbye98** [comment]
Perhaps I'm a little misguided on how the Ewald summation works.

From my understanding, the Ewald summation calculates the normal Coulomb potential in three parts: (1) direct/real energy (before cutoff), (2) reciprocal energy (after cutoff), and (3) self-energy. Parts 1 and 3 are calculated in real space, while part 2 is calculated in reciprocal space using Fourier transforms. Here, the parameter `alpha` simply controls whether the error is lower/higher in part 1 or part 2, and `alpha` is selected such that the actual error is around or lower than the desired error.

Now, in the smeared charge case, the real energy has a different from with the `erf(alpha_ij * r_ij) - erf(alpha * r_ij)` factor, where `alpha_ij` depends on the particle sizes. I am under the impression that, here, `alpha` does not actually control the error since the real energy form is completely different (e.g., if reciprocal energy error increase (resp. decrease), real/direct energy may not necessarily decrease (resp. increase); **is this true?**).

Generally, papers recommended that `alpha >> alpha_ij` ([J. Chem. Theory Comput. 2014, 10, 12, 5513–5519](https://pubs.acs.org/doi/10.1021/ct5009069), [J. Chem. Theory Comput. 2019, 15, 7, 4197–4207
](https://pubs.acs.org/doi/10.1021/acs.jctc.9b00174)). There's no hard guideline on what `alpha` should be, but since `alpha_ij` is determined by my particle sizes, there is a change `alpha` is close to or less than `alpha_ij`, which would significantly affect the error.

Perhaps I'm completely wrong about the error--maybe letting OpenMM choose `alpha` based on the cutoff/Ewald relative tolerance and my setting the `alpha_ij` will be sufficient for what I plan to do. I would love this to be the case since it would simplify the implementation quite a bit.

**Comment by peastman** [comment]
> and alpha is selected such that the actual error is around or lower than the desired error.

It's a little more complicated.  The direct space error is determined by the cutoff and alpha.  If you fix one, you can make it arbitrarily accurate by adjusting the other.  The reciprocal space error is determined by the grid size and alpha.  Again you can fix one and adjust the other to make it arbitrarily accurate.  So we have three parameters (cutoff, grid size, alpha) that we adjust to determine two values (accuracy of direct space and reciprocal space).  We have an extra degree of freedom we can set however we want.  In practice, you want to adjust it to optimize speed.

OpenMM treats the cutoff distance as being the free parameter.  Given a value chosen by the user, it sets the grid spacing and alpha to achieve the desired accuracy.

> I am under the impression that, here, alpha does not actually control the error since the real energy form is completely different

I'm not familiar with this model, but it looks to me like you're adding two terms: the standard term that depends on `alpha`, and a separate term with a different physical meaning that depends on `alpha_ij`.  If so then `alpha` does still control accuracy, but only of the standard term.  The other one represents a different physical effect and doesn't depend on `alpha`.  I'm not sure what the reason is for recommending `alpha >> alpha_ij`.  I would think the relevant requirement would be `alpha_ij*r_c > 1` so the interaction becomes negligible at the cutoff.  But there might be other reasons I'm not aware of.

**Comment by bbye98** [comment]
This makes complete sense, and I can't believe I didn't realize this earlier.

You're absolutely right--the real/direct term in the normal Ewald/PPPM/PME is actually `(Coulomb potential) * (1 - erf(alpha * r_ij))`. Basically, the only change here is that the `1` was replaced with `erf(alpha_ij * r_ij)`, so the `alpha` parameter still controls the error in the `erf(alpha * r_ij)` term but not the `erf(alpha_ij * r_ij)` term, just like how it didn't control the error of the `1` term in the original formulation since it didn't depend on `alpha`. 

That's why LAMMPS allows the user to pick `alpha_ij` and only specify an error tolerance for the PPPM solver (instead of also specifying `alpha`/`g_ewald` and number of mesh points), and the same process is used to pick an appropriate `alpha`/`g_ewald` for the PPPM solver despite the real/direct part being different.

In this case, it looks like the implementation really is simple, and the OpenMM performance is **significantly** higher than the CPU-only implementation of the same potential. It really does blow my mind how you considered the possibility of the user swapping out the real/direct part with the `setIncludeDirectSpace(False)` implementation.

Just to be safe, I think I will test with two oppositely charged ions in a *very* large box and see if the interaction potential matches/comes close to the analytical value.

Once again, I really appreciate your time and thank you so much!

**Comment by peastman** [comment]
Glad that works.  By the way, notice that `erf(alpha_ij*r) - erf(alpha*r) = erfc(alpha*r) - erfc(alpha_ij*r)`.  The equations make a little more sense if you think of it that way.  It's just keeping the standard term `erfc(alpha*r)` unchanged, and adding in a separate term with a different value for alpha.
