### ISSUE TITLE
Inconsistent temperature and energy drift with Verlet dynamics for triethylamine simulations

### ISSUE THREAD

**Issue by kstreu** [openmm/openmm#3689]
When I continue a previous simulation that was using Langevin dynamics (at 300K) and then pass it to Verlet integrator for NVE dynamics (particle velocities set to 300K), the system is having problems maintaining temperature, and I observe energy drift.

In **example1.zip** I include an example of my system, code, and output. The system is a small molecule solvated in triethylamine and I am using a 2 fs timestep, double precision, and PME with default error tolerance. For this system using Verlet dynamics, I observe total energy change by approximately 40 kJ/mol per nanosecond of simulation time. I also observe an initial temperature drop by approximately 10 K when I move my system from NVT → NVE.

Here are some of the things I’ve tried:
- reducing the timestep down to 0.5 fs
- reducing the nonbonded error tolerance down to 5e-6
- changing the nonbonded method from PME to Ewald
- adding switchDistance=0.9*nanometer
- reducing the constraint tolerance down to 1e-7
- reducing minimization energy tolerance (down to 0.1 kcal/mol)
- running on a CPU platform

I found that reducing the constraint tolerance to 1e-7 was the most effective at maintaining temperature and energy, but the energy is still consistently drifting. Specifically, I observe a 60 kJ/mol drop in energy over 20 ns. I also still observe the initial 10 K temperature drop, but then the temperature is maintained at 290 K. (I include my code and output for this simulation in **example2.zip**)

**Are there any additional things I could try that will help maintain temperature through the integrator switch and minimize energy drift for my system with Verlet dynamics?**

[example1.zip](https://github.com/openmm/openmm/files/9073290/example1.zip)
[example2.zip](https://github.com/openmm/openmm/files/9073291/example2.zip)

**Comment by peastman** [comment]
The difference may be coming from on-step versus half-step velocities.  Computing an effective temperature based on velocities turns out to be surprisingly complicated and subtle.  In the case of LangevinMiddleIntegrator, the positions are drawn from the correct Boltzmann distribution for the specified temperature.  And if you compute an effective temperature based on the half-step velocities, it averages to the correct value.  But if you instead compute it from the on-step velocities, you get a lower temperature.  To be honest, I don't completely understand the reasons.  And certainly there could be strange things that happen when switching between integrators, especially to one with a different step size.

> Separately, I was able to minimize the energy drift to under 0.1 kJ/mol/ns by combining the reduced constraint tolerance with the switching function and a lower timestep.

Glad to hear it!
