### ISSUE TITLE
Optimizing the runtime on a system of proteins

### ISSUE THREAD

**Issue by razvanmarinescu** [openmm/openmm#3695]
Hi everyone,

I'm trying to optimize the code for openMM to run as fast as possible on a system of 4 proteins (a dimer of dimers): https://www.rcsb.org/structure/2g33.

The system has 9266 atoms, uses implicit solvent (GBn2), 2fs timestep, and runs on 1 GPU (Nvidia A4000). See below the setup: 
```
pdb = PDBFile('bstate.pdb')
psf = CharmmPsfFile('bstate.psf')

params = CharmmParameterSet('toppar_c36_jul21/top_all36_prot.rtf', 'toppar_c36_jul21/par_all36m_prot.prm')

system = psf.createSystem(params, nonbondedMethod=NoCutoff, nonbondedCutoff=1*nanometer
, constraints=HBonds, implicitSolvent=GBn2)

integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)

platform = Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '%s' % 1} # implicit solvent doesn't support more than 1 GPU
simulation = Simulation(psf.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)

simulation.loadState('parent.xml')
simulation.reporters.append(DCDReporter('seg.dcd', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True, speed=True))
simulation.step(25000)
```

I packaged my code, so you can run it easily with these commands (requires openmm installed):
```
git clone https://github.com/razvanmarinescu/openmm_test.git
cd openmm_test
python run_md.py
```

The output should be something like this:
```
Number of atoms: 9266
#"Step","Potential Energy (kJ/mole)","Temperature (K)","Speed (ns/day)"
1000,-27012.52734375,300.59369305510904,0
2000,-27264.291015625,298.26243258040313,54.8
3000,-27147.15234375,303.1054522940317,54.1
4000,-27407.64453125,299.08015484042755,54.1
5000,-27418.265625,308.7059997280709,54.1
...
```

On my hardware (1x NVIDIA A4000), I'm getting **54ns/day**. However, I need to reach much faster simulation times, as I'm trying to understand protein interactions that happen over much longer timescales.  How can I speed it up? 

For example, when I run the gbsa benchmark (also with implicit solvent) from openMM, which has a system of similar size (2489 atoms), I get **1,976.79ns/day**!! 

These are the commands I used for the gbsa benchmark, and the output:
```
git clone https://github.com/openmm/openmm.git
cd openmm/examples
python benchmark.py --test gbsa --seconds 10 --platform CUDA


Platform: CUDA
Precision: single
Test: gbsa
Ensemble: NVT
Step Size: 4 fs
number of atoms 2489
Integrated 54881 steps in 9.59481 seconds
1976.79 ns/day
```

Can you help me optimize the code? What makes the gbsa system run so much faster, and how can I reach similar speeds in my system? Some ideas: increasing the timestep to 4fs, removing/changing the constraints, running a faster force field, ... What are my options? Happy to receive either comments here, or even pull requests on github.

**Comment by razvanmarinescu** [comment]
A few more details. The 2g33 protein has 4 chains, which I re-packed with PACKMOL, to study how they bind together. The original un-hydrogenated system had a total of 4658 atoms. I used psfgen to predict the missing hydrogens, which added the rest of the atoms up to 9266.

Is it also better to do the packing and hydrogen prediction with openMM?

**Comment by peastman** [comment]
The biggest difference is that the GBSA benchmark uses a 2 nm cutoff.  GB tends to require a longer cutoff than explicit solvent, but 2 nm should be enough to give fairly accurate results.  That will make it a lot faster.

Of course, it's also a smaller system.  2489 atoms is much faster than 9266.  When using a cutoff, the execution time is roughly proportional to the number of atoms, but without a cutoff it's proportional to the square of the number of atoms.

Use LangevinMiddleIntegrator instead of LangevinIntegrator.  It uses a better discretization.  Combined with a small amount of hydrogen mass repartitioning (specify `hydrogenMass=1.5*amu` as an argument to `createSystem()`), it lets you double the step size to 4 fs without loss of accuracy.

The benchmark uses OBC2 which is a bit faster than GBn2, though possibly also a bit less accurate.

Try these settings:

```python
system = psf.createSystem(params, nonbondedMethod=CutoffNonPeriodic, nonbondedCutoff=2*nanometer, constraints=HBonds, implicitSolvent=GBn2, hydrogenMass=1.5*amu)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
```

**Comment by peastman** [comment]
I'm not surprised about the heavy hydrogens.  That used to be a more useful setting when we were otherwise stuck with a 2 fs time step.  Now that we have LangevinMiddleIntegrator that allows 4 fs, there's rarely a reason to use it.

I would be hesitant to use a 1 nm cutoff with GB.  That's short enough that a lot of interactions aren't fully screened, leading to a significant discontinuity where they jump to 0.  It will also cause some of the Born radii to be underestimated.

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen if I missed something.
