### ISSUE TITLE
Time out error when the cutoff distance is small.

### ISSUE THREAD

**Issue by SophiaRuan** [openmm/openmm#3712]
Hi all,

@rkingsbury
I tried to set the `cutoff = 1 `in the `input/system.xml `to make it smaller than half of the periodic box size, but the simulation got stuck and reported a time-out issue. But when I set the `cutoff = 3`, it worked out.
A hypothesis for this is that a small cutoff may cause the computation burden to be too high. But this is opposite to my understanding that a smaller cutoff should mean the simulation has to iterate over fewer neighbors to calculate the forces. Does anyone know what happens here?

This is where I changed the cutoff distance:
<img width="550" alt="Screen Shot 2022-07-25 at 18 08 19" src="https://user-images.githubusercontent.com/67963337/180900826-5237763b-9f6c-4882-b902-a467a1e7fc56.png">

This is the time-out report: 
<img width="471" alt="Brun Job step aborted Waiting up to 32 seconds for job step to finish" src="https://user-images.githubusercontent.com/67963337/180900590-42e1d5ee-cd79-4d43-88c8-5117e9138c29.png">

**Comment by peastman** [comment]
When using PME, there generally is an optimal cutoff distance that makes it fastest.  Shorter or longer than that is slower.  But in most cases the optimum is around 1 nm.  I suspect the real problem is something different.

What program are you running?  The message about "job step aborted" is not something that OpenMM produces.  Do you know where it's coming from?

**Comment by SophiaRuan** [comment]
> 
I'm using [pymatgen.io.openmm](https://github.com/orionarcher/pymatgen-io-openmm), where the OpenMM is incorporated as a Pymatgen add-on package. Recently, my colleagues @[rkingsbury](https://github.com/rkingsbury) @[orionarcher](https://github.com/orionarcher) and I found that there's a [unit inconsistency](https://github.com/orionarcher/pymatgen-io-openmm/pull/6) between `get_box(angstrom) `and `cutoff(nm)` and `nonbondedCutoff = min(10, box_size // 2)`. That caused the cutoff distance may be calculated as 10 nm (100 Angstroms) which should actually be 10 Angstroms or 1 nm. So before we revise this part, we want to change the cutoff distance manually to run the simulation.

I'm using the supercomputer to do long-time simulations with the input set generated by pymatgen.io.openmm. The error came from a job that I submitted. It took too long to run the simulation and there was no output.

**Comment by rkingsbury** [comment]
Just to expand a bit on @SophiaRuan's comments - we have been running OpenMM on GPUs (on the NERSC Perlmutter system); the timeout error is a symptom rather than the direct cause of the problem we're asking about (sorry for any confusion).

We've run a few different systems comprising water, ions, and in some cases small organic molecules, with both 100% SAGE and a mixture of SAGE and the built-in tip3p-fb water and ion parameters. For my part, my box size is typically around 30-40 Ang on a side. I initially set the `nonbondedcutoff` at 10 thinking it was in Angstrom, and got a periodic box size error. We then saw in [the documentation](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) that the cutoff is in nm, so I reduced the value to 1.

With the lower cutoff, the simulation just gets stuck. There's no error, and also no output to either the terminal or to the designated output files. The job will just sit there for hours (hence the timeout error @SophiaRuan posted).  Based on @SophiaRuan further testing, we think that in the case of a cutoff of 1, the simulation is just _extremely_ slow. We can get the same systems to run (slowly) at a cutoff of ~3, but a that point we're in danger of tripping another box size error.

I suppose one solution is just to increase our whole system size such that a cutoff of 5-10 is appropriate, but that seems like an inefficient workaround. We'd appreciate any additional insight about why this may be happening.

**Comment by rkingsbury** [comment]
After further investigation, I believe we've traced this problem to an issue with our setup code that was causing the particle positions to be initialized in the wrong units, effectively creating a MUCH larger box than we intended. @SophiaRuan after you confirm, I think we can close this.
