### ISSUE TITLE
Increase collision frequency to speed-up protein interactions

### ISSUE THREAD

**Issue by razvanmarinescu** [openmm/openmm#3727]
I'm trying to increase the collision frequency of the atoms, in order to speed-up protein interactions. By collision frequency, I mean simulating a medium with viscosity much lower than water (e.g. much closer to air or gases). 

I searched through openMM, and AndersenThermostat seems to be the only option to change the collision frequency of the particles. Is there any way I can do it through my current setup, which uses LangevinMiddleIntegrator? Also, if I use an Andersen thermostat, do I need to switch to Verlet Integrator? 

Here's what I have right now:
```
forcefield = ForceField('amber/protein.ff14SB.xml', 'implicit/gbn2.xml')

dt = 0.004*picoseconds
constraints = HBonds
hydrogenMass = 1.5*amu

system = forcefield.createSystem(pdb.topology, nonbondedMethod=CutoffNonPeriodic,
      nonbondedCutoff=2*nanometer, constraints=constraints, hydrogenMass=hydrogenMass)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, dt)
simulation = Simulation(pdb.topology, system, integrator, platform, properties)
```

In particular, I run GB implicit solvent, and have hydrogen mass repartitioning enabled. Thanks.

**Comment by peastman** [comment]
The relevant parameter for LangevinMiddleIntegrator is the friction coefficient, which you have specified as 1/ps.  The friction coefficient of water is 91/ps, so you're already simulating a much less viscous medium than water.  Note that increasing the collision frequency makes it more viscous, not less.

**Comment by razvanmarinescu** [comment]
Oh, gotcha. Can I go below 1/ps? What is the lower limit?

I've googled for references online for the friction coefficient (& collision coefficient) of water and other substances, but couldn't find anything useful. Do these parameters have another name they go by? I even googled your value of 91/ps. Do you have a reference table (with common liquids/gases)?

**Comment by peastman** [comment]
Think of the friction coefficient as setting the time constant over which the thermostat works.  A friction coefficient `c` means it takes time `1/c` to exchange significant energy between the system and the heat bath.  There's no lower limit, but the less friction you have, the less effective the thermostat becomes.  This can lead to slower sampling.  This is all related to [the fluctuation-dissipation theorem](https://peastman.github.io/statmech/friction.html).

When simulating explicit solvent you don't want to add extra friction.  The solvent molecules already provide all the friction you want.  So you set a very low value for the thermostat's friction, just enough to maintain the temperature.  1/ps tends to be a good value in that case.  When using implicit solvent, the thermostat becomes the only source of friction.  If you want realistic dynamics, you should set a larger friction coefficient that reflects the environment you want to simulate, such as 91/ps for water.  But often you don't care about dynamics, just sampling.  In that case, it's better to use a low value like 1/ps, since it allows much faster sampling.  Extra friction would just slow it down.  It's unrealistic in the sense that things happen faster than they would in real water, but for your purposes that's a good thing.

**Comment by razvanmarinescu** [comment]
That is a great explanation, thank you Peter! In this case I'll leave it to 1/ps.

**Comment by razvanmarinescu** [comment]
Also, thanks for linking the book chapter, I'll read through it.
