### ISSUE TITLE
How to extract force acting on an ion from interactions with diffrent atom groups ?

### ISSUE THREAD

**Issue by Panda-DaLong** [openmm/openmm#3746]
Hi,

There are ions, waters, a channel and a lipid membrane in the system. When an ion passing across the channel, I want to compute the mean force acting on the ion from interactions with diffrent atom groups, such as channel atoms, or lipid membrane atoms.

How to divide the forces acting on the ion atom from interactions with diffrent predefined atom groups?

Looking for reply!

**Comment by jeff231li** [comment]
Hi @Panda-DaLong, I think you would need to create multiple `NonbondedForce` or `CustomNonbondedForce` that separates the different interactions then add them to your `System`. Make sure you set the `forceGroup` to different numbers so you can call them later. You can then extract the forces by calling the `context.getState` function given the current positions and box vectors. With the example below, `forceGroup` number 2 is the force object describing the interaction between the channel and ion only and number 3 is between the lipid and ion.

```python
simulation.context.setPeriodicBoxVectors(*box_vectors)
simulation.context.setPositions(positions)

force_by_channel = simulation.context.getState(getForces=True, groups={2}).getForces()
force_by_lipid = simulation.context.getState(getForces=True, groups={3}).getForces()
```

I hope this helps.

**Comment by peastman** [comment]
There are a few ways of doing this, depending on the details of your simulation.

- What force field are you using?  (If it's a polarizable force field like AMOEBA, that makes things a lot more complicated.)
- Is it a monatomic ion, so we're only concerned about nonbonded forces?
- How often will you want to do this analysis?  Every time step, or only occasionally?
- How large are the groups of atoms you want to compute the interaction with, and how many are there?
- Is there anything else unusual about your system that might complicate things (extra custom forces, alchemical transformations, etc.)?

**Comment by Panda-DaLong** [comment]
@peastman Thanks for reply!
There are more details about the simulation as following:
1.  CHARMM36 force filed (fixed charge model)
2.  it's a monoatom ion, potasium or sodium ion
3.  about per 10 or 100 time step
4.  about 10000 (ten thousands) atoms in a group
5.  restraint on the target ion by a CustomExternalForce, or constrain on the target ion by setting zero mass

**Comment by Panda-DaLong** [comment]
@jeff231li Thanks for reply!
I have a question as following:
The forces between the target ion and the channel(or lipid, water, the other ions) are defined by CHARMM36 force filed.
How to add these forces into multiple NonbondedForce or CustomNonbondedForce?

**Comment by jeff231li** [comment]
@Panda-DaLong The snippet below shows **one way** to do this. The first step is to extract the `NonbondedForce` object from `system` and turn off all intramolecular interactions (since it's not relevant here for the force acting on the ion). Copy the object with `deepcopy`, and then you will need to set the parameters of lipid and solvent atoms  to zero (atom indices stored in the list `lipid_and_solvent_atoms`). Finally, you simply add this force back to the `system`.

```python
# Create system
system = psffile.createSystem(...)

# Get the `NonbondedForce` object
total_nonbonded = [force for force in system.getForces() if isintance(force, NonbondedForce)][0]

# Set all exception parameters to zero - since we don't care about intramolecular interactions
for i_exception in range(total_nonbonded):
    atom_i, atom_j, chargeprod, sigma, epsilon = total_nonbonded.getExceptionParameters(i_exception)
    total_nonbonded.setExceptionParameters(i_exception, atom_i, atom_j, 0.0, sigma, 0.0)

# Copy `NonbondedForce`
from copy import deepcopy
nonbonded_ion_and_channel = deepcopy(total_nonbonded)
nonbonded_ion_and_channel.setForceGroup(2)  # useful later when calling `getState`

# Turn off "q" and "epsilon" for lipids and solvents (water+bulk ions)
for atom in lipid_and_solvent_atoms:
    charge, sigma, epsilon = nonbonded_ion_and_channel.setParticleParameters(atom, 0.0,)
    nonbonded_ion_and_channel.setParticleParameters(atom, 0.0, sigma, 0.0)

# Add force to System
system.addForce(nonbonded_ion_and_channel)
```

**Comment by peastman** [comment]
Since you only need to compute it every 10 or 100 steps, a faster way of doing it would be to leave the existing NonbondedForce alone (it still computes all interactions), then add a new NonbondedForce that computes only the interactions with the specific group (as shown above).  That means it's duplicating interactions that are also computed by the main NonbondedForce.  So call `setIntegrationForceGroups()` on the integrator to tell it to ignore the extra forces you added.  They won't apply forces to the particles and they won't contribute to the potential energy.  But you can query them whenever you want using the `groups` argument to `getState()`.  The advantage of doing it this way is that on ordinary time steps, it only has to evaluate one NonbondedForce instead of several.

**Comment by Panda-DaLong** [comment]
@jeff231li @peastman 
I understand it now. Thank you for so great guidance!

**Comment by Panda-DaLong** [comment]
I have a new question for help.

I want to choose the water in channel as a group and compute their force with target ion.
The problem is that the water in channel will change in md simulation.
I just know the way to choose the water atoms in channel by analyze trajectory after md simulation.

How to choose the water atoms in channel and change 'NonbondedForce' in md simulation?

**Comment by peastman** [comment]
In the example code above, the NonbondedForce determines which atoms to compute forces with by assigning real parameters to those atoms and zero charge and epsilon to all other atoms.  To change it, you reassign the parameters.  Call `setParticleParameters()` on the NonbondedForce to set the new parameter values, then call `updateParametersInContext()` on it to copy them over to the Context for your simulation.

**Comment by Panda-DaLong** [comment]
I got it and I will have a try.
Thanks so much!
