### ISSUE TITLE
Reporting a custom property that uses information from system

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3747]
I am trying to calculate and report a quantity that involves the masses of each atom, positions, forces, and velocities. I am going off of the ForceReporter example in the documentation (http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html). However, I have been having trouble figuring out how to get the masses of each atom (information from the System.getParticleMass) inside the reporter object so that I may calculate the desired quantity. I am also curious as to how I could get information from the topology file into the reporter object to calculate the desired quantity. Thank you for any advice.

**Comment by peastman** [comment]
You can get the System with `simulation.context.getSystem()` and the Topology with `simulation.topology`.

**Comment by kong1-731** [comment]
Oh thank you! Also if the calculation requires this information for atoms from neighboring sub-domains, would the easiest way to do this be to translate the positions by the periodic box vectors? And then the velocities/forces etc would remain the same without changing the sign for the virtual particle in the surrounding copies of the box?

**Comment by peastman** [comment]
By "sub-domains", you mean periodic copies?  Yes, their positions are constructed by adding box vectors.  And velocities and forces are the same for all periodic copies.

If you have virtual sites, be careful about how you interpret the forces on them.  Their positions don't get integrated.  So although it does return a force on each virtual site, that force doesn't affect how it moves.

**Comment by kong1-731** [comment]
Thank you! I keep running into an error getting the particle mass in the reporter that I am not sure how to get past.
Using the following code keeps generating the error: 
`TypeError: Quantity.__float__ returned non-float (type Quantity)`

```
mass = simulation.context.getSystem().getParticleMass(1)
self._out.write('%g\n' % (mass))
```

```
mass = simulation.context.getSystem().getParticleMass(1)
product = float(mass)*float(velocities[idx][0])*float(velocities[idx][0])
```

**Comment by peastman** [comment]
String formatting with `%g` expects something that can be cast to a float.  `mass` is a quantity with units.  Try this.

```python
mass = mass.value_in_unit(amu)
```

That will give you a float.

**Comment by kong1-731** [comment]
I see. Thank you! My other issue that I have not been able to figure out is that the report outputs information per atom to a file but does not do so if I try to output information that is not per atom (similar to the StateDataReporter).

The following code does not output anything to forces.txt, but it does if I replace the self.out line with 
```
#for idx, f in enumerate(forces):
            #self._out.write('%g %g %g\n' % (f[0], positions[idx][1], velocities[idx][2]))
```


Code that does not output anything to output file forces.txt:
```
simulation.reporters.append(ForceReporter('forces.txt', 1000))

class ForceReporter(object):
    def __init__(self, file, reportInterval):
        self._out = open(file, 'w')
        self._reportInterval = reportInterval

    def __del__(self):
        self._out.close()

    def describeNextReport(self, simulation):
        steps = self._reportInterval - simulation.currentStep%self._reportInterval
        return (steps, False, False, True, False, None)

    def report(self, simulation, state):

        system = simulation.context.getSystem()
        mass = system.getParticleMass(1).value_in_unit(dalton)
        self._out.write('%g' % (mass))

```

**Comment by peastman** [comment]
Python buffers output.  It will get written once enough output has collected.  Or you can call `self._out.flush()` to make it get written immediately.

**Comment by kong1-731** [comment]
I see! Thank you

**Comment by peastman** [comment]
Closing this since the question has been answered.  Feel free to reopen it if it still isn't working.

**Comment by kong1-731** [comment]
I am wondering if it is possible to access information from the state reporter a timestep before the current timestep in order to calculate certain properties or if it is instead necessary to do the calculation offline with the output reporter txt file.

**Comment by peastman** [comment]
Your reporter would need to implement that itself.  Ask to be called two timesteps in a row.  On the first call, record the information you need but don't report anything.  On the next call, compute the quantity you want to report by using the information you saved in the previous call.

**Comment by kong1-731** [comment]
Thank you. I am still trying to figure out how to implement this. When I ask to call the reporter two timesteps in a row, would I do that inside the reporter?

Just for an example based on the force reporter in the advanced simulation examples,

```
class ForceReporter(object):
    def __init__(self, file, reportInterval):
        self._out = open(file, 'w')
        self._reportInterval = reportInterval

    def __del__(self):
        self._out.close()

    def describeNextReport(self, simulation):
        steps = self._reportInterval - simulation.currentStep%self._reportInterval
        return (steps, False, False, True, False, None)

    def report(self, simulation, state):
        forces_prev = state.getForces().value_in_unit(kilojoules/mole/nanometer)
        simulation.step(1)
        forces_new = simulation.context.getState.getForces().value_in_unit(kilojoules/mole/nanometer)
        self._out.write('%g %g %g\n' % (forces_prev[0][0]*forces_new[0][0]))

```

Within the openmm_run.py script:
`simulation.reporters.append(ForceReporter('forces.txt', 100))`

In this example would I end up getting the product of the forces on the first atom from step 100 and 101, 200 and 201, etc.?

**Comment by peastman** [comment]
You don't want to call `step()` inside `report()`.  That will cause lots of confusion and problems.

You control when the reporter gets called using the first value returned by `describeNextReport()`.  Suppose you want to generate a report every 100 steps, and the report needs values that were saved in the previous step.  Then `describeNextReport()` should return 99 instead of 100.  When `report()` gets called it will save the information you need but not generate any output.  `describeNextReport()` should then return 1 to indicate it should be called again on the next step.  That's when you'll generate the output.

The code could look something like this.

```python
def __init__(...)
    ...
    self.saved_data = None

def describeNextReport(self, simulation):
    if self.saved_data is None:
        steps = self._reportInterval - simulation.currentStep%self._reportInterval - 1
    else:
        steps = 1
    ...

def report(self, simulation, state):
    if self.saved_data is None:
        self.saved_data = ...
    else:
        ...
        self.saved_data = None
```

**Comment by kong1-731** [comment]
Thank you so much! The sample code has been very helpful to me. I am wondering if it is possible to obtain the current temperature of the simulation inside a custom reporter in order to calculate a quantity from it.

**Comment by peastman** [comment]
"Temperature" can mean two different things.  First there's the temperature of the heat bath the system is coupled to.  That's a fixed property of the thermostat.  For example, if you're using a LangevinMiddleIntegrator to control temperature you call `getTemperature()` on it.

Second, you can define an "instantaneous" temperature as `(2*ke)/(kB*dof)` where `ke` is the current kinetic energy, `kB` is Boltzmann's constant, and `dof` is the number of degrees of freedom in the system.  Take a look at StateDataReporter, which can compute this.  There are subtleties involved in computing the number of degrees of freedom, and also because Drude integrators need to implement the calculation in a different way.  Here is how it computes the degrees of freedom:

https://github.com/openmm/openmm/blob/a056d5a3754e193105409afa12c9f0c9a2d972a2/wrappers/python/openmm/app/statedatareporter.py#L301-L313

And then it computes the temperature like this:

https://github.com/openmm/openmm/blob/a056d5a3754e193105409afa12c9f0c9a2d972a2/wrappers/python/openmm/app/statedatareporter.py#L250-L255
