### ISSUE TITLE
Virtual sites in diatomic molecules

### ISSUE THREAD

**Issue by UnWaDo** [openmm/openmm#3766]
Hello!

As far as I understood from [documentation](http://docs.openmm.org/7.6.0/userguide/application/05_creating_ffs.html), virtual sites can be implemented with their position set by local coordinates. However in case of diatomic molecules (HHal, Hal<sub>2</sub>) there is a problem that there is not enough atoms to select three reference particles. Is there some other way to set virtual sites coordinates in this case?

**Comment by peastman** [comment]
Where do you want to position the virtual site?

There are several VirtualSite classes that use different rules for positioning it.  TwoParticleAverageSite only depends on two particles.  It can place the virtual site at a position along the axis of the two particles.  If you want to place it at any point off the axis, you'll need three particles since two don't give enough information to define the position.

**Comment by UnWaDo** [comment]
Yes, now when I read about `TwoParticleAverageSite` class I found, that it is what I need, thank you!

Is it possible to add links to descriptions of these classes to documentation?
