### ISSUE TITLE
Title section determination error with CHARMM parameter files when NDON and NACC are filled

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3792]
Hi.

I'm trying droplet simulation with CHARMM parameter files.

However, water molecules in a system dissipates away in very short time, which is far different from the result of simulation performed with espaloma forcefield.

Since the hydrogen bond donor and acceptor sections of psf file were blank, I filled in those section, but an error occured.

Also, there was no interaction between H2O, sodium ion, and chloride during the smulation.

```Traceback (most recent call last):
  File "/home/compu/temp/parameters/droplet_CHARMM2.py", line 13, in <module>
    psf = CharmmPsfFile(f'{name1}.psf')
  File "/home/compu/anaconda3/envs/openmmvenv/lib/python3.7/site-packages/openmm/app/charmmpsffile.py", line 73, in newfunc
    return func(*args, **kwargs)
  File "/home/compu/anaconda3/envs/openmmvenv/lib/python3.7/site-packages/openmm/app/charmmpsffile.py", line 209, in __init__
    sec, ptr, data = CharmmPsfFile._parse_psf_section(psf)
  File "/home/compu/anaconda3/envs/openmmvenv/lib/python3.7/site-packages/openmm/app/charmmpsffile.py", line 566, in _parse_psf_section
    raise CharmmPSFError('Could not determine section title')
openmm.app.internal.charmm.exceptions.CharmmPSFError: Could not determine section title

Process finished with exit code 1
```

How can I run the simulation without such problem?

The following is the corresponding files for simulation.
[Desktop.zip](https://github.com/openmm/openmm/files/9640724/Desktop.zip)

The only difference of two psf files is whether NDON and NACC sections are filled or not

**Comment by peastman** [comment]
You seem to be describing several different issues.  Let me take them one at a time.

When simulating a water droplet, you need a restraint potential to keep them from diffusing away.  Something like what's described [here](http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#applying-an-external-force-to-particles-a-spherical-container).  That's because the average lifetime of hydrogen bonds in water is very short, less than 1 ps.  The waters on the surface of the droplet will constantly be breaking off, and if there's nothing to contain them, they'll just diffuse away.

Second, you mentioned the donor and acceptor sections in the PSF file.  Modern CHARMM force fields don't include an explicit term for hydrogen bonds, so those sections are normally empty.  If CHARMM has generated a PSF file for you, *do not* modify that file by hand unless you're absolutely sure you know what you're doing!  You're much more likely to break it.

Finally, you said there's no interaction between the water and ions.  What did you mean by that?  What leads you to believe there's no interaction?

**Comment by OkKakao** [comment]
1. What I simulating is a nanodroplet that is diffusing away, but that would give me some insight if I try simulation with spherical potential.

2. I generated psf file with ParmEd, but angle, dihedral, improper diheral terms were not defined. That's why I manually added such terms, since it's trivial that such terms for CB7 and water molecule are required.
Of course I'm not sure about what I'm doing because I'm just a newbie for MD simuation, but I had to do it because of the lack of time...

3. I already tried several simulations with Espaloma. The droplet is maintained its strucure even though there was no potential. Also, Na and Cl ions were remained in the droplet during the simulation. 
However, when it comes to CHARMM parmeter applied simulation, water droplet and ions dissipates way too faster than espaloma, which breaks the structure of droplet.
That's why I thought that there is no interaction.

Anyway, I'll try it again with potetial well. thanks for your help!

P.S. Does amber14/tip3p.xml file in openmm contains NBFIX parameters for monovalent ions?

**Comment by OkKakao** [comment]
> You seem to be describing several different issues. Let me take them one at a time.
> 
> When simulating a water droplet, you need a restraint potential to keep them from diffusing away. Something like what's described [here](http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#applying-an-external-force-to-particles-a-spherical-container). That's because the average lifetime of hydrogen bonds in water is very short, less than 1 ps. The waters on the surface of the droplet will constantly be breaking off, and if there's nothing to contain them, they'll just diffuse away.
> 
> Second, you mentioned the donor and acceptor sections in the PSF file. Modern CHARMM force fields don't include an explicit term for hydrogen bonds, so those sections are normally empty. If CHARMM has generated a PSF file for you, _do not_ modify that file by hand unless you're absolutely sure you know what you're doing! You're much more likely to break it.
> 
> Finally, you said there's no interaction between the water and ions. What did you mean by that? What leads you to believe there's no interaction?

1. What I simulating is a nanodroplet that is diffusing away, but that would give me some insight if I try simulation with spherical potential.

2. I generated psf file with ParmEd, but angle, dihedral, improper diheral terms were not defined. That's why I manually added such terms, since it's trivial that such terms for CB7 and water molecule are required.
Of course I'm not sure about what I'm doing because I'm just a newbie for MD simuation, but I had to do it because of the lack of time...

3. I already tried several simulations with AMBER14/tip3p.xml. The droplet maintained its strucure even though there was no potential. Also, Na and Cl ions were remained in the droplet during the simulation. 
However, when it comes to CHARMM tip3p.str applied simulation, water droplet and ions dissipates way too faster than espaloma, which breaks the structure of droplet.
That's why I thought that there is no interaction.

Anyway, I'll try it again with potetial well. thanks for your help!

P.S. Does amber14/tip3p.xml file in openmm contains NBFIX parameters for monovalent ions?

**Comment by OkKakao** [comment]
> > I generated psf file with ParmEd, but angle, dihedral, improper diheral terms were not defined.
> 
> ParmEd should accurately convert whatever inputs you give it. What input files are you giving to ParmEd, and where did you get them from?

I got the orginal file from one of my senior.

The pdb file contains gaussian optimized coordinations.

And I modified the file with maestro, since the center of mass of the molecule was (0, 0, 0), I moved it to (20, 20, 20).

The followings are my ParmEd code, input and output files.

```
import parmed as pmd

structure = pmd.load_file('parameters/cb7(4).pdb')
structure.save('parameters/tested.psf')
```
[pdb_and_psf.zip](https://github.com/openmm/openmm/files/9653153/pdb_and_psf.zip)


> > P.S. Does amber14/tip3p.xml file in openmm contains NBFIX parameters for monovalent ions?
> 
> Amber doesn't use NBFIX.

Then maybe the different behavior of the solvent molecules could be attributable to this difference...?

**Comment by peastman** [comment]
PDB is a format for structures only.  It contains coordinates for the atoms and limited chemical information (elements, bonds), but no information about how they should be simulated.  There are no force field parameters or any kind of information about what force field to use.

PSF is for parametrized structures, ones that have had force field information assigned.  It contains information that's specific to a force field: atom types, angles, dihedrals, etc.

You load a PDB, which has no force field information, and immediately save it to a PSF.  That's why your PSF is missing lots of information.

Try using CHARMM-GUI to parametrize your model.  The PSF it creates should be much more complete.

**Comment by OkKakao** [comment]
> PDB is a format for structures only. It contains coordinates for the atoms and limited chemical information (elements, bonds), but no information about how they should be simulated. There are no force field parameters or any kind of information about what force field to use.
> 
> PSF is for parametrized structures, ones that have had force field information assigned. It contains information that's specific to a force field: atom types, angles, dihedrals, etc.
> 
> You load a PDB, which has no force field information, and immediately save it to a PSF. That's why your PSF is missing lots of information.
> 
> Try using CHARMM-GUI to parametrize your model. The PSF it creates should be much more complete.

Thank you for helping me!

I think that have to study a lot more...
