### ISSUE TITLE
Setting box vectors in prmtop topology doesn't change box vectors in resultant system

### ISSUE THREAD

**Issue by proteins247** [openmm/openmm#3802]
I understand that prmtop files have periodic box vectors, but because coordinates and box sizes change during NPT simulation, when creating a simulation, you should update the box size.

Hence the example in the tutorial: http://docs.openmm.org/latest/userguide/application/02_running_sims.html#using-amber-files

```
prmtop = AmberPrmtopFile('input.prmtop')
inpcrd = AmberInpcrdFile('input.inpcrd')
system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
```

In my situation, I generated a prmtop after solvating my system in tLeap. The box vectors in the prmtop correspond to the equilibrated system. After equilibration, the box vectors shrunk. I used openmm to equilibrate, and saved my coordinates into a PDB file (which has box vectors).

To my surprise, if I try to update the prmtop.topology object with the new box vectors, the resultant simulation context that I generate from my prmtop.topology doesn't reflect the new box vectors:

```
In [1]: import openmm.app as app

In [2]: prmtop = app.AmberPrmtopFile("TOPOLOGY.prmtop")

In [3]: prmtop.topology.getPeriodicBoxVectors()
Out[3]: Quantity(value=(Vec3(x=6.358086650000001, y=0.0, z=0.0), Vec3(x=0.0, y=6.309765850000001, z=0.0), Vec3(x=0.0, y=0.0, z=6.33810575)), unit=nanometer)

In [4]: prmtop.topology.getUnitCellDimensions()
Out[4]: Quantity(value=Vec3(x=6.358086650000001, y=6.309765850000001, z=6.33810575), unit=nanometer)

In [5]: pdbfile = app.PDBFile("EQUILIBRATED.pdb")

In [6]: pdbfile.topology.getPeriodicBoxVectors()
Out[6]: Quantity(value=(Vec3(x=5.8425, y=0.0, z=0.0), Vec3(x=0.0, y=5.798100000000001, z=0.0), Vec3(x=0.0, y=0.0, z=5.8241000000000005)), unit=nanometer)

In [7]: prmtop.topology.setPeriodicBoxVectors(pdbfile.topology.getPeriodicBoxVectors())

In [8]: prmtop.topology.getPeriodicBoxVectors()
Out[8]: Quantity(value=(Vec3(x=5.8425, y=0.0, z=0.0), Vec3(x=0.0, y=5.798100000000001, z=0.0), Vec3(x=0.0, y=0.0, z=5.8241000000000005)), unit=nanometer)

In [9]: prmtop.topology.getUnitCellDimensions()
Out[9]: Quantity(value=Vec3(x=5.8425, y=5.798100000000001, z=5.8241000000000005), unit=nanometer)

In [10]: system = prmtop.createSystem()

In [11]: import openmm.unit as unit

In [12]: import openmm as mm

In [13]: simulation = app.Simulation(prmtop.topology, system, mm.LangevinMiddleIntegrator(300 * unit.kelvin, 1 / unit.picosecond, 0.002 * unit.picosecond))

In [14]: simulation.context.getState().getPeriodicBoxVectors()
Out[14]: Quantity(value=[Vec3(x=6.358086650000001, y=0.0, z=0.0), Vec3(x=0.0, y=6.309765850000001, z=0.0), Vec3(x=0.0, y=0.0, z=6.33810575)], unit=nanometer)
```

I suppose this is because the underlying C++ object doesn't see the changes to the box size? 

I also had a minor question. Why does `Context.setPeriodicBoxVectors` take 3 vectors as arguments whereas `Topology.setPeriodicBoxVectors` take a single argument? Some application versus library layer difference?

**Comment by peastman** [comment]
You should treat the Topology you get from AmberPrmtopFile as immutable.  It creates a Topology as a convenience for you, because you'll need it when you create a Simulation.  But it also stores lots of information internally.  If you modify the Topology it created, that means it's now out of sync with the AmberPrmtopFile that created it.  That doesn't modify any of the internal fields in the AmberPrmtopFile.

> Why does Context.setPeriodicBoxVectors take 3 vectors as arguments whereas Topology.setPeriodicBoxVectors take a single argument? Some application versus library layer difference?

Exactly.  Context is a C++ class that has wrappers generated automatically.  Topology is a Python class.  Making it take three separate vectors would be more consist with Context, but making it take a single list of vectors is more consistent with the return value of `getPeriodicBoxVectors()`.

**Comment by proteins247** [comment]
Thanks for the fast reply and explanation! Is it similar with PDBFile.topology? I'd suspect modifications to that will be reflected in the resultant system?

**Comment by peastman** [comment]
PDBFile doesn't have a `createSystem()` method, so that case is a little different.  A prmtop file describes a completely parametrized system with all the force field parameters, so you can create a System from it directly.  A PDB file only contains topology information, no parameters.  You need to use a ForceField to parametrize it.  `ForceField.createSystem()` takes a Topology as input.  It doesn't know where that Topology came from.
