### ISSUE TITLE
Question about boundary of BiasVariable class

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#3805]
I meet a question when I try to use openmm to conduct the Metadynamics simulation. I notice that the min and max argument of `__init__` method of `BiasVariable` has a notification that:

> If it should ever go above this, the bias force will be set to 0.

I get two questions:
1. The bias force represents the energy of Force object or the force acting on the particle
2. If the force acting on the particles is set to 0, the enhanced sampling will fail if the variable goes beyond the range. This will frequently happen if I choose a steric variable like radius to the origin point. How to prevent this happen

Thanks

**Comment by peastman** [comment]
> The bias force represents the energy of Force object or the force acting on the particle

It creates a CustomCVForce whose energy is just the value of a tabulated function:

https://github.com/openmm/openmm/blob/cf824381f13a88402b0f676fb7e910c8693f9a9a/wrappers/python/openmm/app/metadynamics.py#L129

If any CV (that is, the value of any argument to the tabulated function) goes outside its defined range, then the value of the tabulated function (the energy) and its derivative (the force) are both zero.

> If the force acting on the particles is set to 0, the enhanced sampling will fail if the variable goes beyond the range.

Correct.  It will only apply a bias force over the range that you specify.  Usually that isn't a problem, because you know what range your CV is expected to vary over.  Do you have a situation where that isn't true, where you truly have no idea what values the CV will take?  Can you describe it?

**Comment by zhenyuwei99** [comment]
Hi Peter. Thanks for your explanation
> It creates a CustomCVForce whose energy is just the value of a tabulated function
`self._force = mm.CustomCVForce('table(%s)' % ', '.join(varNames)) `
That makes things clear.

> where you truly have no idea what values the CV will take? Can you describe it?

I think the main difficulty I met is the question about the coordinate wrap and unwrap. Suppose I use the coordinate of one axis of a specific particle. What is the specific range of the coordinate?
- The [0, 1] pbc length
- The [-0.5, 0.5] pbc length
- Or it's an unwrapped coordinate with no range as I see there is an `enforcePeriodicBox` keyword in `context.getState` method

**Comment by zhenyuwei99** [comment]
Meanwhile, I also have the question about the `gridWidth` argument in the `BiasVariable`:

> gridWidth (int (optional)) – the number of grid points to use when tabulating the bias function. If this is omitted, a reasonable value is chosen automatically.

I am curious about the strategy for choosing a reasonable value and the influence of different values. I think it is related to the `biasWidth` argument?

**Comment by peastman** [comment]
Coordinates are unbounded.  They can take on any value.  Periodic boundary conditions are applied to *displacements between particles*, not to individual particle positions.  See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic for more discussion of this point.

The position of a single particle is not typically useful as a CV for metadynamics.  It might be useful if you happen to be applying an external force that binds the system to a particular point in space.  But most systems are translationally invariant.  Applying metadynamics to the position of a single particle will just increase sampling of the global translation of the whole system, which is arbitrary and physically meaningless.  Instead, you want to increase sampling of *internal* degrees of freedom of the system, such as the distance between two particles.

> I am curious about the strategy for choosing a reasonable value and the influence of different values.

Here is how it chooses it:

https://github.com/openmm/openmm/blob/488859110959e77f2d81e927a488ef59b11ed5d3/wrappers/python/openmm/app/metadynamics.py#L303-L306

Since it approximates a Gaussian with discrete points on a grid, you want enough points to represent it fairly accurately.  Five grid points over a single standard deviation is accurate enough for most purposes.

**Comment by zhenyuwei99** [comment]
Great! 
I think this could fix the position questions by setting the variable as:
`peridoicdistance(0, 0, z, 0, 0, 0)`
And that indeed the distance between z and the origin. That would make the sampling meaningful.
Thanks a lot for your explanation

**Comment by peastman** [comment]
Glad to help!  Can we close this issue, or are there still parts that need to be addressed?

**Comment by zhenyuwei99** [comment]
I have one more question about the `biasFactor` argument. I am wondering whether the definition is (ΔT + T) / T as openmm will throw an error when I set this to 1.
And should I do the energy conversion for the data I get from `Metadynamics.getFreeEnergy` method?
Best,

**Comment by peastman** [comment]
If you set `biasFactor` to 1, that will lead to a divide by zero, which will lead to nans.

>  And should I do the energy conversion for the data I get from Metadynamics.getFreeEnergy method?

The value it returns is the actual free energy.  What conversion are you referring to?

**Comment by zhenyuwei99** [comment]
But when I try to plot the free energy at the beginning. I found the sampled area has positive energy, while the unsampled area kept 0. Maybe we missing the negative sign?

**Comment by peastman** [comment]
The value stored in the file is not the same as what's returned by `getFreeEnergy()`.  If you want the free energy, use the latter.

**Comment by zhenyuwei99** [comment]
Great. I will try. As I found the result within the same sample steps is different when I set the bias factor to different values. On my occasion, when I set the bias factor to a higher value, the free energy also increases.

I will recheck this result by using `getFreeEnergy` method.

I am also wondering if is there any suggestion for checking the convergence. Maybe I should check the difference between the result get from `getFreeEnergy` and see the difference?

Best

**Comment by peastman** [comment]
The question of how to check convergence [came up recently](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=14962&p=0&start=0&view=&sid=3acaebbdd1dd2d22a2a5e52535c1de2d) on the forum.  There's some advice there that might be helpful.

**Comment by zhenyuwei99** [comment]
Cool!
> If a state is visited only once during the simulation, its free energy is unlikely to be converged.

I think this means metadynamics converged when all points (in the collective variable space) are well sampled (based on the visiting counts). In this case, I am wondering if there is any method to get the histogram of visiting events to check this.

**Comment by peastman** [comment]
The metadynamics class itself doesn't log the values of the CVs, though that could potentially be a useful feature to add.  You can do it yourself by periodically calling `getCollectiveVariableValues()` on the CustomCVForce and recording them somewhere.

**Comment by zhenyuwei99** [comment]
Great. I think I have no more questions. Thanks a lot!
