### ISSUE TITLE
How to re-start a simulation from a checkpoint / saved state?

### ISSUE THREAD

**Issue by noahharrison64** [openmm/openmm#3810]
Hi,
I've been having issues restarting a saved simulation. I am running a protocol close to the one defined in this issue I raised 
#3782 
I have run 5ns of production run and have saved both the .state and .chk file. I have also saved the final frame coordinates as a PDB. Now, I am trying to re-start the simulation from this final position, however my jupyter session has lost all it's variables and so I need to re-create simulation / system instances etc. 
So, I re-ran the following code:

```
pdb = PDBFile(file=((workDir/'final_frame.pdb').as_posix()))
forcefield = ForceField('amber99sb.xml', 'tip3p.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME,
    nonbondedCutoff=1.0*nanometers, constraints=app.HBonds, rigidWater=True,
    ewaldErrorTolerance=0.0005)
posres_sys = add_backbone_posres(system, pdb.positions, pdb.topology.atoms(), 100)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
integrator.setConstraintTolerance(0.00001)
simulation = Simulation(pdb.topology, posres_sys, integrator)
simulation.reporters.append(
    StateDataReporter(
        stdout,
        10000,
        step=True,
        potentialEnergy=True,
        temperature=True,
        volume=True,
        density=True
    )
)

## I added the barostat that I had added in my initial 5ns run, following NVT equilibration
barostat = posres_sys.addForce(MonteCarloBarostat(1*atmosphere, 300*kelvin))
simulation.context.reinitialize(True)

## Load the checkpoint file (tried the same with loadState, same end result)
simulation.loadCheckpoint((workDir/'final.chk').as_posix())

mdsteps = 10000000
simulation.reporters.append(
    DCDReporter((workDir/f'1ns_traj_step_1.dcd').as_posix(), 1000))

simulation.step(int(mdsteps))
```

I then get the following error:

`OpenMMException: Particle coordinate is nan
`

The initial 5ns simulation ran fine, so I'm not sure why I'm getting this error. I imagine it's because i'm not restarting the simulation correctly. Any clues here would be greatly appreciated.

Thanks
Noah

**Comment by peastman** [comment]
If everything is really set up the same, it ought to continue exactly where it left off.  The nan suggests something must be different.

Are you certain your new System really is identical to the original one?  To be absolutely sure, it can be useful to save the System to a file and reload it, rather than trying to recreate it and risk having some difference in the parameters you specify.  See [this description](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html) of how to do that.

One thing that looks suspicious to me is the call to `add_backbone_posres()`.  I don't know for sure what it does, but I notice you pass in the positions loaded from `final_frame.pdb`.  Is it creating a different set of restraints than what you had in the original System?

Does the nan appear immediately (on the very first step), or does it take a while?

**Comment by noahharrison64** [comment]
Hi Peter,

Your comment about parsing final_frame.pdb solved the issue for me. I thought that I could re-start the simulation by using a PDB snapshot from the simulation (had assumed that all the atoms would be the same indices etc, just different xyz coords). I switched back to the original pre-simulation PDB (post using modeller to add solvent) and this did the trick. But thanks for pointing out the use of .xml files to save the system and reload, that'll be incredibly helpful.

Thanks,
Noah
