### ISSUE TITLE
large differences in force evaluation on `CPU` vs `CUDA` in omm7.7.0 with `CustomNonbondedForce` and `CustomBondForce``

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm#3833]
I've run into a problem re: evaluating forces on the same system/positions with the only difference being the `platform` used in the `Context` object using openmm `'7.7.0.dev-130124a'`.  

```
import os
import openmm
from openmm import unit
import numpy as np
import copy
platform = openmm.Platform.getPlatformByName( 'CPU' )
platform_props = {}

def deserialize(xml_filename):
    from openmm.openmm import XmlSerializer
    with open(xml_filename, 'r') as infile:
    xml_readable = infile.read()
    xml_deserialized = XmlSerializer.deserialize(xml_readable)
    return xml_deserialized

hybrid_system = deserialize("al.system.xml")
hybrid_state = deserialize("al.state.xml")
hybrid_positions = hybrid_state.getPositions(asNumpy=True)
hybr_int = openmm.LangevinMiddleIntegrator(300., 1., 0.002)
hybr_context = openmm.Context(hybrid_system, hybr_int, platform, platform_props)
hybr_context.setPositions(hybrid_positions)

_f = hybr_context.getState(getForces=True).getForces(asNumpy=True)
print(_f[:10])
```
gives me:
```
[[  91.11087616   57.04925416  -81.07370234]
 [ 137.80879187  247.79933001  -35.7503945 ]
 [ [233.0759479](tel:2330759479)   -37.40567909  -32.19216563]
 [ 191.99240829 -284.26214029   17.59930326]
 [-219.07344156 -273.49173954   93.95247016]
 [-306.31406207   38.56226566   46.11279947]
 [-172.2341995   268.97887959   61.77254522]
 [   3.0890086    48.64809207  -74.81144387]
 [ -68.33635951  139.06797349    8.67958372]
 [ 252.03212037  -97.57452139 -448.26307938]] kJ/(nm mol)
```

whereas changing the platform to `CUDA` gives 
```
[[ 3.68638127e-01  5.38285211e-01 -1.61782864e-01]
 [ 2.14748365e+09  2.14748365e+09 -2.14748365e+09]
 [-7.75927086e-01 -2.55322443e-01  2.34322803e-01]
 [ 2.14748365e+09  2.14748365e+09 -2.14748365e+09]
 [-4.20965662e-01 -6.24276246e-01  2.21717329e-01]
 [-1.21868251e-01 -6.53445749e-01  1.41251166e-01]
 [-2.14748365e+09  2.14748365e+09 -2.14748365e+09]
 [ 2.14748365e+09 -2.14748365e+09 -2.14748365e+09]
 [-2.14748365e+09  2.14748365e+09  2.14748365e+09]
 [-2.14748365e+09  2.14748365e+09  2.14748364e+09]] kJ/(nm mol)
```
for refernce, i am using `cudatoolkit==11.7.0`. Also, it appears that both force objects (`CustomNonbondedForce` and `CustomBondForce`) both have offending forces if I print the forces by force group.

the corresponding state and system xmls are attached
[al.tar.gz](https://github.com/openmm/openmm/files/9924693/al.tar.gz)

is this a known problem that i am missing from somewhere/is there a fix?

**Comment by dominicrufa** [comment]
update, it turns out that removing the `CustomNonbondedForce` (i.e. only running energy evaluation on the `CustomBondForce`) also causes this inconsistency.

**Comment by peastman** [comment]
This has been an interesting one to track down!  You're getting nans in the calculation.  The problem comes from this part of the expression: `(1-lam_sub)^softcore_b`.  When it takes the derivative to get the force, that produces a subexpression of the form `softcore_b*(1-lam_sub)^(softcore_b-1)`.  For some interactions, `1-lam_sub` and `softcore_b-1` are both zero, so it evaluates to `0^0 = nan`.

But wait a minute!  Why is that calculation being left in?  It gets multiplied by the derivative of `1-lam_sub`, which is always zero.  But because of the particular way the expression is written, the derivative is evaluated by an expression of the form `select(..., 0, 0)`.  It doesn't know to strip that out, so you end up with `0*nan = nan`.

I need to make the expression optimizer a little smarter, so it will know to completely remove that calculation.
