### ISSUE TITLE
Running OpenMM inside Singularity container

### ISSUE THREAD

**Issue by asiomchen** [openmm/openmm#3852]
I'm trying to create conda environment inside Singularity to run ligand-protein simulation on HPC cluster, script runs smoothly in local conda env, but inside a container it gives an error, when trying to add ligand to Modeller object, like it lacking permissions to write or something:

```python
Traceback (most recent call last):
  File "/home/anton/sing/simulateComplex.py", line 87, in <module>
    modeller.add(ligand_mol.to_topology().to_openmm(), ligand_mol.conformers[0])
  File "/opt/conda/envs/md/lib/python3.9/site-packages/openmm/app/modeller.py", line 132, in add
    newPositions.append(deepcopy(addPositions[atom.index]))
  File "/opt/conda/envs/md/lib/python3.9/site-packages/openmm/unit/quantity.py", line 773, in append
    raise TypeError("Cannot append item without units into list with units")
TypeError: Cannot append item without units into list with units
``` 
conda yml file:
```yml
name: md
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - openmm
  - openmmforcefields
  - plotly
  - pdbfixer
```
Singularity recipe:
```txt
Bootstrap: docker

From: continuumio/miniconda3

%files
    environment.yml

%post
    /opt/conda/bin/conda env create -f environment.yml

%runscript
    exec /opt/conda/envs/md/bin/"$@"
```

Where this issue may come from?

**Comment by pablo-arantes** [comment]
Hi all, 

I'm having the same issues. It's weird because it was working fine, and I didn't change anything in the code.

`TypeError                                 Traceback (most recent call last)
[<ipython-input-18-afb954b267c9>](https://localhost:8080/#) in <module>
    117 # Add the ligand
    118 # Under the hood, this line uses the OpenFF Toolkit to generate new parameters for the ligand
--> 119 modeller.add(ligand_topology.to_openmm(), ligand.conformers[0]*unit.nanometers)
    120 
    121 modeller.addHydrogens(omm_forcefield, pH=float(pH))

1 frames
[/usr/local/lib/python3.8/site-packages/openmm/unit/quantity.py](https://localhost:8080/#) in append(self, item)
    771             return self._value.append(item)
    772         else:
--> 773             raise TypeError("Cannot append item without units into list with units")
    774     def extend(self, rhs):
    775         self._value.extend(rhs.value_in_unit(self.unit))

TypeError: Cannot append item without units into list with units`

Can you please help me address this issue? 

Thank you.

Pablo

**Comment by peastman** [comment]
OpenFF Toolkit has its own units package.  I think you're probably mixing up the two, passing an object with OpenFF units to a routine that expects one with OpenMM units.

**Comment by pablo-arantes** [comment]
Hi @peastman,

Thank you for your help. It's working fine now. You are right I was trying to pass an object with with OpenFF units to a routine that expects one with OpenMM units.

I fixed with the following line:

> from openff.units.openmm import to_openmm, from_openmm

> ligand_positions = ligand.conformers[0]
ligand_topology = ligand.to_topology()
modeller.add(ligand_topology.to_openmm(), to_openmm(ligand_positions))

Thank you so much.

Best,

Pablo
