### ISSUE TITLE
Confusion in improper torsion of the CustomTorsionForce.

### ISSUE THREAD

**Issue by wayuer19** [openmm/openmm#3908]
Hi,

I'm trying to add a improper torsion into the force field xml file using CustomTorsionForce. As described in the Document, "An improper torsion involves a central atom and three others that are bonded to it: atoms 2, 3, and 4 are all bonded to atom 1. " So in my xml file (hyres_ff.xml in attached files), it is:
`    <CustomTorsionForce energy="k*(theta-theta0)^2">
        <PerTorsionParameter name="k"/>
        <PerTorsionParameter name="theta0"/>
        <Improper type1="NH1" type2="" type3="" type4="H" theta0="0.0000" k="188.2800"/>
        ......
    </CustomTorsionForce>`
the first atomtype is the type of the central atom.
   But, when I check the xml file (system.xml in attached files) obtained through XmlSerializer, it looks like:
`                 <Force energy="k*(theta-theta0)^2" forceGroup="0" name="CustomTorsionForce" type="CustomTorsionForce" usesPeriodic="0" version="3">
                         <PerTorsionParameters>
                                 <Parameter name="k"/>
                                 <Parameter name="theta0"/>
                         </PerTorsionParameters>
                         <GlobalParameters/>
                         <EnergyParameterDerivatives/>
                         <Torsions>
                                 <Torsion p1="1" p2="5" p3="3" p4="4" param1="188.28" param2="0"/>
`
I think these four atoms are in a wrong sequence, but I am not clear what the problem is. Any suggestion?
Thanks!
version: 7.7
OS: Ubuntu 20.10
![example](https://user-images.githubusercontent.com/24451788/212436667-e856058a-1199-4306-bc0e-4f03658580a5.jpg)
[files.zip](https://github.com/openmm/openmm/files/10416046/files.zip)

**Comment by peastman** [comment]
Improper torsions are confusing.  Different force fields define them in different ways, and they often use lots of wildcards (as you did).  So we have to separate two issues: selecting the parameters for a torsion, and selecting the order to list the atoms in.  When it says the central atom is listed first, that's just for the purpose of assigning parameters.  It then has to select an order for the atoms.

The `<CustomTorsionForce>` tag allows an optional `ordering` attribute that can take on four different values: `"default"`, `"amber"`, `"charmm"`, and `"smirnoff"`.  Different options use different strange, arbitrary rules for selecting an order to try to match the behavior of particular programs.  With `"default"` (which you're getting, since you didn't specify an order), the central atom ends up as the third atom.

By the way, atoms are numbered starting from 0, not 1.  To match them up, subtract 1 from all the numbers in your image.

**Comment by wayuer19** [comment]
> The <CustomTorsionForce> tag allows an optional ordering attribute that can take on four different values: "default", "amber", "charmm", and "smirnoff". Different options use different strange, arbitrary rules for selecting an order to try to match the behavior of particular programs. With "default" (which you're getting, since you didn't specify an order), the central atom ends up as the third atom.
So, if I chose different value or `ordering`, should I change the order of four atoms in `<Improper type1="NH1" type2="" type3="" type4="H" theta0="0.0000" k="188.2800"/>` according to different ways? Or the value of `ordering` is only related to the atom order in the output xml file?
Actually, I just added different `ordering` in the <CustomTorsionForce> tag, no difference was found in the output xml file.

> By the way, atoms are numbered starting from 0, not 1. To match them up, subtract 1 from all the numbers in your image.
Yes, I did.

**Comment by peastman** [comment]
The way you listed the atoms in the `<Improper>` tag is fine.  Just be aware that when your custom force gets evaluated, the central atom will be the third one in the sequence used to define the angle.
