### ISSUE TITLE
Setting atomic forces at each time step from python API

### ISSUE THREAD

**Issue by dpadula85** [openmm/openmm#3949]
Hello,

I would need, at each step of the MD, to read forces and velocities (which I accomplished from `context.getState()`) to process them, modify them both, and have the simulation proceed with modified forces and velocities after my computations.

I see that there are ways to update velocities (`context.setVelocities()`), but I don't really understand if it is possible to overwrite forces for the simulation to go on?

I see from [Issue 1179](https://github.com/openmm/openmm/issues/1179) that there is a way to add an external force, but I would like to replace the current forces. If there is no simple way, then I guess I could add the opposite of the current forces plus the forces I want to apply, but I wanted to ask to you before doing anything stupid.

Thanks in advance for the help.

P.S.: I should do all this in the python code because I don't know C++ to write a plugin to do what I want.

**Comment by dpadula85** [comment]
Hi @Lnaden,

sure, I didn't want to go too much into detail,  I'll try to be short.
I would like to use OpenMM as the classical nuclear dynamics driver in a semiclassical Tully Surface Hopping scheme for aggregate systems, described [here](https://aip.scitation.org/doi/10.1063/1.4960144) (see eqs. 20-21 for nuclear gradients, section IIIF for a more detailed description, and Fig. 3 for a scheme).
So at each MD step I should solve an electronic problem and evaluate new forces, to be fed to the classical nuclear dynamics integrator.

I did not implement anything yet, just trying to figure out whether OpenMM is the right classical MD engine to do it. Do you think this is achievable?

**Comment by Lnaden** [comment]
I don't think you need to extract the forces, modify them, and then update forces with what you showed. Without really understanding what's going on in the paper here, I can present some options for what you're trying to do in OpenMM. Others can comment as well.

Near as I can tell, you need standard MD + some external calculations for nuclear gradient for `i != j` particles, then that goes into a velocity rescaling algorithm after performing a Monte Carlo move.

It sounds like you need the standard array of forces (Bond, angle, torsion, nonbonded, etc.), and then 
* a [Custom Nonbonded Force](http://docs.openmm.org/development/api-python/generated/openmm.openmm.CustomNonbondedForce.html) to handle the pairwise interaction computation where you'll want to find a way to negate the particle i-i self-interaction
* A second [Force Group](https://docs.openmm.org/development/api-python/generated/openmm.openmm.Force.html) for your custom force so the side calculations don't impact the dynamics of the non-custom forces.
* Possibly a [Custom Integrator](https://docs.openmm.org/development/api-python/generated/openmm.openmm.CustomIntegrator.html) which can read specific force groups to then update integrator steps.
* Optional multiple Systems (set of defined forces and particles) and Contexts (implemented and deployed System+Integrator) so when you do the Monte Carlo move you can copy coordinates and velocities without having to initialize a Context each time.

All of these things together is probably overkill and overly-complicated for what you need, but these are some of the tools available to you. I also suggest looking into [OpenMMTools](https://openmmtools.readthedocs.io/en/stable/) which is an auxiliary Python library separate from OpenMM which has many of those above features implemented which you can use as example or whole as needed. 

In general, you don't want to go back to the Python API level to do calculations every time step and then push changes back to the `Context` (on-metal implementation of the simulation) as this can be a very slow process going over various buses, so the more you can implement in the `Context` through `Force`s in the `System` and `Integrator`, the better.

I know this isn't the most directly helpful since I don't understand exactly what you're needing based on the paper, but hopefully this gives you ideas. Anyone else is also welcome to provide ideas if they have any.

**Comment by peastman** [comment]
@dpadula85 did the above answer your question?  Is it ok to close this?

**Comment by dpadula85** [comment]
@peastman Hi, yes, it can be closed. Thanks!
