### ISSUE TITLE
Pressure tensor calculation every 50 timesteps

### ISSUE THREAD

**Issue by Alexandrina-Chen** [openmm/openmm#3972]
Dear all,

I am trying to calculate the surface tension of a vacuum-liquid-vacuum system of ionic liquids using pressure tensor at every 50 timesteps, which is a high frequency. To do a polarizable model, I am using the `DrudeLengivenIntegrator`.

I have looked through several related issues, like #1989 and #3647 . It seems that one solution is to use the second formula in https://docs.lammps.org/compute_pressure.html. My intuition is at `every 50 timesteps`, (1) use `Context.getState(getVelocities=True, getForces=True,getPositions=True)` to obtain the velocity components, force components, and position components of each atom; (2) calculate the pressure tensor and surface tension; (3) print out them; (4) iterate the simulation to the next 50 timesteps. Considering the high frequency I need the position/force/velocity components, I prefer to calculate the surface tension on-the-fly, instead of storing the information and doing some post-processing because it will spend tons of storage space.

But my first concern about this method is that as mentioned in #3647 the second comment "The contribution of the total force on a given atom i from each of the other atoms j is not kept track of in OpenMM, so the formula you are referring to cannot be applied here.". This comment is different from my understanding of `getState()`. I am wondering if `Context.getState(getVelocities=True, getForces=True,getPositions=True).getForces(asNumpy=True)` will give me the **actual total force component** acting on each atom on the timestep when I call the function, which is crucial.

My second concern is that, as mentioned in #1989 the last second comment, `getState()` is a relatively expensive operation. And a `CustomIntegrator` may serve as a better choice. However, I haven't written a complicated integrator like the `DrudeLengivenIntegrator`. I believe it is easy to implement the pressure tensor calculation as a `CustomIntegrator`, but not the Drude part. It would be better if I had any other choice to avoid this. Or, is that possible to implement a second integrator (the `CustomIntegrator` of pressure tensor calculation) into the main integrator (the `DrudeLengivenIntegrator`) without rewriting the main integrator? I know it sounds stupid, but just curious.

Another solution is, as mentioned in #3647 , to do finite-difference estimates of the energy derivative with respect to box size. However, I don't think it is an easy task to do the estimation on-the-fly for an MD simulation. Besides, this method will only give the configurational energy part of the pressure tensor, I still need to calculate the kinetic part, which goes back to the first solution. Therefore, this solution is not so attractive to me.

Currently, I am testing my intuition as described in the second paragraph to see how it will affect the speed. But considering the concerns I have, I am quite curious if there is a better choice for me to do the pressure tensor calculation at a high frequency on-the-fly. Any suggestion will be appreciated! Thank you in advance.

**Comment by z-gong** [comment]
The atomic virial for a periodic system is quite complicated. The LAMMPS formula you cited makes use of ghost atoms ($N^\prime$), which do not exist in OpenMM.

The finite difference method might be more feasible. I have written such a [pressure reporter](https://github.com/z-gong/mstk/blob/130caecbc84b776cf995a0936260efa0f223e99a/mstk/ommhelper/reporter/statedatareporter.py#L470). In my experience, evaluating pressure tensor per 50 steps could degrade the MD performance by around 50 %.

The kinetic part can be easily evaluated from the ideal gas formula. The real issue is the contribution of the constraints to the viral. In the reporter, I approximate its contribution by treating each constrained group as a rigid body and removing its virial from the kinetic part.

**Comment by Alexandrina-Chen** [comment]
@z-gong Thanks! This really helps. 

I am new to openMM and I didn't realize that the energy perturbation can be evaluated in such a simple way, which makes me feel that it is difficult to use the finite difference method. In my system, there is no constraints, therefore the kinetic part doesn't worry me. 

But again, thank you so much for your pressure reporter. Such an useful tool!

**Comment by sef43** [comment]
Hi @z-gong thank you for providing this answer and code! This question about how to calculate pressure in OpenMM simulations turns up quite often, and your code is a nice example on how to use the finite difference method for calculating it. Would you be interested in including it as a code example in the OpenMM cookbook: https://github.com/openmm/openmm-cookbook, rendered here: https://openmm.github.io/openmm-cookbook/latest/index.html ?

We would welcome a pull request, or If you like I can create the example, with attribution to you?

**Comment by z-gong** [comment]
Hi @sef43. Sorry for the late reply. I just realized that a force push has broken the link in the previous comment. Now it's fixed.
Please feel free to include this code snippet in the Cookbook.

However, be careful about systems that contain constraints. Because the constraints' contribution to virial cannot be evaluated by scaling up the box and positions, I choose to treat the constrained atoms as a rigid body during the pressure evaluation. This trick seems to work well: the calculated pressure and density agree with the simulations performed with LAMMPS. But for all of my simulations, I only constrain hydrogen-related bonds. I have never tried to constrain all bonds, so I'm not sure if the trick is still valid.

**Comment by ShinyEgg-pku** [comment]
> The atomic virial for a periodic system is quite complicated. The LAMMPS formula you cited makes use of ghost atoms ( N ′ ), which do not exist in OpenMM.
> 
> The finite difference method might be more feasible. I have written such a [pressure reporter](https://github.com/z-gong/mstk/blob/master/mstk/ommhelper/reporter/statedatareporter.py#L470). In my experience, evaluating pressure tensor per 50 steps could degrade the MD performance by around 50 %.
> 
> The kinetic part can be easily evaluated from the ideal gas formula. The real issue is the contribution of the constraints to the viral. In the reporter, I approximate its contribution by treating each constrained group as a rigid body and removing its virial from the kinetic part.

@z-gong  Hi! Your pressure reporter is very useful. But I noticed that only diagonal elements pxx, pyy, and pzz were calculated. Can I use the same method in the code to calculate non diagonal elements pxy, pxz, and pyz?

**Comment by z-gong** [comment]
> [@z-gong](https://github.com/z-gong) Hi! Your pressure reporter is very useful. But I noticed that only diagonal elements pxx, pyy, and pzz were calculated. Can I use the same method in the code to calculate non diagonal elements pxy, pxz, and pyz?

Hi @ShinyEgg-pku , I'm not familiar with the calculation of off-diagonal pressures, but I feel that it's more complicated than diagonal ones. For the kinetic part, you can calculate it with $\frac{1}{V} \sum mv_\alpha v_\beta$. But I don't know how to consider the contribution of constraints. For the virial part, you can apply a perturbation to the off-diagonal elements of the box vectors and calculate the energy difference.

For an amorphous system, the kinetic part can be safely ignored. Only the virial contribution need to be calculated with finite difference method. But for a non-amorphous system, the kinetic part and constraints could be more complicated.

In any case, I suggest you compare your results with the values from other simulation packages that can calculate full pressure tensor.

By the way, what's your purpose of calculating the off-diagonal pressures? If you are planing to calculate viscosity, I would recommend the periodic perturbation method (https://aip.scitation.org/doi/abs/10.1063/1.1421362), which is more efficient and accurate than Green-Kubo method. I have implemented this method in an OpenMM plugin (https://github.com/z-gong/openmm-velocityVerlet?tab=readme-ov-file#periodic-perturbation-method)

**Comment by peastman** [comment]
@z-gong I'm working on implementing proper pressure reporting from within OpenMM.  I'm looking at your reporter, and I'm confused about this line:

```python
p_kinetic *= len(self._constrained_groups) * 3 / self._dof
```

I don't think you want to be scaling it like that?  The LAMMPS documentation defines the pressure calculation as

$P = \frac{NkT}{V} + \frac{1}{Vd} \sum_i r_i \cdot f_i$

The second term, they point out, is just $-\frac{dU}{dV}$, which we compute directly from a finite difference.  The first term depends only on the temperature and volume, not the kinetic energy.  However, *on average* we expect the kinetic energy to be $3NkT/2$.  Substituting that in, the first term becomes $\frac{2\<ke\>}{3V}$.  In your reporter you replace the average kinetic energy with the instantaneous kinetic energy.  That's not the same thing, but it should average out to the same.  However, when computed that way, the number of degrees of freedom no longer comes into the calculation.  You're really just calculating kinetic energy per volume.  So I don't think it's correct to scale it by the number of degrees of freedom?  If there are constraints, they'll already have been accounted for by their effect in reducing the kinetic energy.

**Comment by z-gong** [comment]
>  $P = \frac{N k T}{V} + \frac{1}{Vd} ∑_i r_i ⋅ f_i $

In this formula, the $T$ is instantaneous temperature. We can see it from the LAMMPS implementation 
https://github.com/lammps/lammps/blob/8defe0e7981d2fef26de959c9d876d350dba77d9/src/compute_pressure.cpp#L256
```
    if (keflag)
      scalar = (temperature->dof * boltz * temperature->scalar +
                virial[0] + virial[1] + virial[2]) / 3.0 * inv_volume * nktv2p;
```
https://github.com/lammps/lammps/blob/8defe0e7981d2fef26de959c9d876d350dba77d9/src/compute_temp.cpp#L90
```
    for (int i = 0; i < nlocal; i++)
      if (mask[i] & groupbit)
        t += (v[i][0] * v[i][0] + v[i][1] * v[i][1] + v[i][2] * v[i][2]) * mass[type[i]];
  }

  MPI_Allreduce(&t, &scalar, 1, MPI_DOUBLE, MPI_SUM, world);
```

> ```p_kinetic *= len(self._constrained_groups) * 3 / self._dof```
However, when computed that way, the number of degrees of freedom no longer comes into the calculation. You're really just calculating kinetic energy per volume. So I don't think it's correct to scale it by the number of degrees of freedom? If there are constraints, they'll already have been accounted for by their effect in reducing the kinetic energy.

The pressure can be calculated at different levels, commonly at atomic or molecular level. The definition of kinectic pressure and virial pressure changes at different levels.
- At atomic level (this is how LAMMPS calculates pressure), all the inter-atomic forces (including constraints) will contribute to virial. The contribution of constraints must be explicitly calculated, which is not possible in OpenMM.
- At molecular level, the contribution of constraints to virial is zero, along with other intra-molecular forces like bonds, angles. The kinetic pressure only comes from the translational motion of molecules. The rotational and vibrational motions have no contribution to kinetic pressure.
- In my implementation, the pressure is calculated at the level of constrained groups. At this level, constraints will be the only intra- force that has no contribution to virial. For the kinetic pressure, only the translational motion of constrained groups should be considered. That's why the kinetic pressure is scaled by `len(self._constrained_groups) * 3 / self._dof`

**Comment by peastman** [comment]
My point is that the constraints have already been taken into account.  A constrained degree of freedom has no kinetic energy.  The kinetic energy is already proportional to the number of non-constrained degrees of freedom.

**Comment by peastman** [comment]
I'm trying to test your `_compute_pressure()` function on a box of water.  Here's my test code.

```python
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
modeller = Modeller(Topology(), []*nanometers)
modeller.addSolvent(forcefield, boxSize=(3.0, 3.0, 3.0)*nanometers)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME, nonbondedCutoff=0.9*nanometer)
system.addForce(MonteCarloBarostat(1.0*bar, 300*kelvin))
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy()
simulation.step(5000)
for i in range(10000):
    simulation.step(10)
    print(_compute_pressure(simulation.context, simulation.context.getState(positions=True, energy=True)))
```

Here's what a bit of the output looks like.

```
439.611829486895
-172.64800766793246
-312.8026752306964
821.4184991644497
789.5788843528378
```

The numbers are enormous and all over the place.  Do they average out to the correct value (1.0)?  I can't really say.  Even after averaging 10,000 of them, the fluctuations are on the order of about +/- 20, far too large to get an accurate estimate.  I would need to average about 100 million pressure measurements to get the fluctuations low enough to test whether the average is correct.

Am I doing something wrong?  Is there a better way of testing it?

**Comment by z-gong** [comment]
> My point is that the constraints have already been taken into account. A constrained degree of freedom has no kinetic energy. The kinetic energy is already proportional to the number of non-constrained degrees of freedom.

For a system containing 1000 rigid water molecules, there are 3000 translational DOF and 3000 rotational DOF contributing to kinetic energy. Of them, only the 3000 translational DOF contribute to pressure. That's where the scaling comes from.

> The numbers are enormous and all over the place.

This is expected. Instantaneous pressure fluctuates a lot. What matters is the distribution.

>  Even after averaging 10,000 of them, the fluctuations are on the order of about +/- 20, far too large to get an accurate estimate.

Indeed, there's something missing in the formula. I forgot to consider the effect of COM removal. The correct formula should be
```
p_kinetic *= (len(self._constrained_groups) * 3 - 3) / self._dof
```
Using the new formula, I ran simulation of a box containing 1000 OPC3 water molecules for  400 ps and recorded the pressure every 0.04 ps. Here is the time evolution of the pressure from OpenMM and LAMMPS
<img src="https://github.com/user-attachments/assets/c668aab2-3f50-4eb9-b422-a1f36c4a625b" width=60%>
<img src="https://github.com/user-attachments/assets/9d07e6f6-0d5a-4119-8e76-44c6bf628442" width=60%>

Here is the distribution of the pressure
<img src="https://github.com/user-attachments/assets/e59383c4-dd7f-4d3d-aa5d-51161dc4c8ec" width=60%>
<img src="https://github.com/user-attachments/assets/794c55ec-c720-4f7a-a2c6-d7de9f5116f9" width=60%>

If the kinetic pressure is not scaled by `(len(self._constrained_groups) * 3 - 3) / self._dof`, the calculated average pressure will be 1400 bar.

**Comment by z-gong** [comment]
Another test was conducted using 1000 OPC3 water molecules in a cubic box with a fixed length of 3.109 nm. NVT simulations were performed to eliminate barostat effects.

Here is the cumulative average of pressure. Even after nanoseconds of simulation, the average pressure continues to fluctuate by tens of bars.
<img src="https://github.com/user-attachments/assets/ef3a9d8e-083e-4d3f-bc78-7d9a7e1c4675" width="60%"/>

**Comment by peastman** [comment]
Actually, I think the problem was that I didn't equilibrate long enough.  The results are better if I make sure the volume has stabilized before collecting any data.

I've been reading more about this, and I think I understand the calculation better now.  The molecular virial is defined in terms of whole molecules rather than atoms.  The kinetic energy term in the expression for pressure is $NkT/V$, where $N$ is the number of molecules, regardless of whether they're rigid, partly constrained, or fully flexible.  [Some sources](https://www.sciencedirect.com/science/article/abs/pii/S0927025619307293?via%3Dihub) define $T$ to be the temperature of the heat bath, while [others](https://www.researchgate.net/publication/233807916_Constant_pressure-constant_temperature_molecular_dynamics_A_correct_constrained_NPT_ensemble_using_the_molecular_virial?__cf_chl_tk=65h6MHDu5lwlOd4y.9qrpWIIBcqeG1hsqTkcfuSz_ws-1743704710-1.0.1.1-pnFrZEX4WEpsmcPzar6B_w8RVe7t8ukjAtiuaNai5Wk) take it to be the instantaneous molecular temperature calculated as $\frac{1}{3k} \sum_i m_i |v_i|^2$ where the sum is over molecules, $m$ is the mass of the molecule, and $v$ is its center of mass velocity.

You're doing something slightly different.  You take the total kinetic energy, which includes center of mass translations, center of mass rotations, and internal motions, and scale it based on the number of degrees of freedom.  That works as long as 1) the bodies are completely rigid (which you assume but I can't assume in the general purpose implementation), and 2) the average kinetic energy is the same for translational and rotational degrees of freedom (which should be the case as long as there are no constraints imposed on the center of mass translations or rotations of molecules).

So how should we calculate the pressure for the general case?  We could either sum over molecules to add up their center of mass momentum, or use the heat bath temperature instead of the instantaneous temperature.  In most cases they should give the same average pressure, but there are exceptions when degrees of freedom are constrained.  For example, if a particle is immobilized by making it massless, that will reduce the instantaneous temperature but not the heat bath temperature.

I *believe* the most correct thing to do is to make the calculation consistent with how the barostat determines pressure.  Here is where MonteCarloBarostat computes the acceptance probability:

https://github.com/openmm/openmm/blob/1ece5c285ce4bf90ce84ffe2000c41f978d82c09/openmmapi/src/MonteCarloBarostatImpl.cpp#L89-L90

It computes it based on the heat bath temperature and the total number of molecules, so I believe the pressure calculation should do the same.

**Comment by z-gong** [comment]
> You take the total kinetic energy, which includes center of mass translations, center of mass rotations, and internal motions, and scale it based on the number of degrees of freedom.

I chose to **approximate** the kinectic contribution by scaling DOF for performance reasons. I was reusing data that had already been calculated. The more rigorous way is to explictly calculate the kinectic energies of COM translations.

>  That works as long as 1) the bodies are completely rigid (which you assume but I can't assume in the general purpose implementation), and 2) the average kinetic energy is the same for translational and rotational degrees of freedom (which should be the case as long as there are no constraints imposed on the center of mass translations or rotations of molecules).

1) It doesn't assume the bodies to be rigid. The separation of total kinectic energy into COM translation and internal motion relative to the COM holds for any system, regardless of how molecules are defined (whether via constraints, flexible bonds or even arbitrarily selected atoms).
2) You are right, I didn't consider the condition where COM translations is constrained.

However, my calculation does have a flaw. Even though the equipartition theorem ensures that different DOF have the same **averaged temperature**, it does not guarantee that the **instantaneous kinetic energy** will be the same.

> I believe the most correct thing to do is to make the calculation consistent with how the barostat determines pressure. It computes it based on the heat bath temperature and the total number of molecules, so I believe the pressure calculation should do the same.

I disagree. Barostat defines ensemble averaged pressure. But in the reporter, we are calculating instantaneous pressure. Additionally, there are cases where no heat bath is used (e.g., in NVE simulations).

**Comment by peastman** [comment]
My standard for correctness is that if you run a NPT simulation specifying a particular pressure, and then average the instantaneous pressure over the whole simulation, it should come out to the value you specified.  If you define temperature differently in the barostat and in the pressure calculation, there will inevitably be situations where the two are systematically different.

**Comment by peastman** [comment]
I have the beginnings of an implementation of this in #4881.  Feedback on it would be very appreciated!

**Comment by peastman** [comment]
I suppose the counter argument is that there are cases where they really should be different.  For example, a system consisting entirely of non-interacting, immobile particles.  That would be an absurd thing to simulate, but it's still well defined.  Clearly the pressure of that system should always be zero, regardless of the heat bath temperature.
