### ISSUE TITLE
ImportError when create system

### ISSUE THREAD

**Issue by slweng0321** [openmm/openmm#3974]
Dear all,
I try to create system with the Amber input rst7 and parm7 file via the following script:
system = fus.createSystem(nonbondedMethod=PME,
                               nonbondedCutoff=1.0*nanometer, constraints=app.HBonds,
                               hydrogenMass=1.5*amu,
)

I receive the error:
Traceback (most recent call last):
  File "//openmm.py", line 29, in <module>
    system = fus.createSystem(nonbondedMethod=PME,
  File "//amber22/lib/python3.9/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
    raise ImportError('You must have at least OpenMM 6.3 installed')
ImportError: You must have at least OpenMM 6.3 installed

I used Platform.getOpenMMVersion() to check OpenMM version and it is 7.6.
How can I fix this problem? Thanks for any help.

**Comment by peastman** [comment]
It looks like you're using the file reader from ParmEd rather than the one from OpenMM.  See http://docs.openmm.org/latest/userguide/application/02_running_sims.html#using-amber-files for how to use the OpenMM readers.  If you have a reason for needing to use the ParmEd one instead, you should report this at https://github.com/ParmEd/ParmEd.

**Comment by slweng0321** [comment]
Thanks I will ask at ParmEd
