### ISSUE TITLE
are the latest API docs up to date?

### ISSUE THREAD

**Issue by sef43** [openmm/openmm#3985]
have the `http://docs.openmm.org/latest/api-python` been updated for OpenMM 8.0 release?

If I look here:
http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomNonbondedForce.html#openmm.openmm.CustomNonbondedForce
I would expect to see mention of `addComputedValue` which was added in 8.0, but I don't see it 
I can see it in the development docs:
http://docs.openmm.org/development/api-python/generated/openmm.openmm.CustomNonbondedForce.html#openmm.openmm.CustomNonbondedForce

**Comment by peastman** [comment]
Are the docs still being hosted on the pandelab AWS account, or did we move them somewhere else?  I tried to log into that account, but it now has two factor authentication set up and sends a message to someone's phone.

**Comment by peastman** [comment]
@jchodera I think you're the only person who has access to it now?

**Comment by jchodera** [comment]
Apologies for the delay---I missed the original ping.

After a bit of investigation, here is what I have been able to determine:
* I own the `openmm.org` domain, which is managed via GoDaddy.
* `docs.openmm.org` is a CNAME entry that points to `docs.openmm.org.s3-website-us-west-1.amazonaws.com.`, which then immediately redirects to https://openmm.org/documentation
* The [`docs-openmm-org` S3 bucket](https://s3.console.aws.amazon.com/s3/buckets/docs-openmm-org) in `us-east-1` is in my personal AWS account, but this is a different region. However, S3 bucket names are globally unique across all regions, so maybe this does not matter. The contents in the bucket have not been updated since 22 Oct 2020.
* The `index.html` in the S3 `docs-openmm-org` bucket contains only the content:
```html
<head>
<meta http-equiv="refresh" content="0; url=http://openmm.org/documentation.html" />
</head>
```
The links there point to specific URLs, such as http://docs.openmm.org/latest/api-python/, that I believe could resolve to specific objects within this S3 bucket.
* The development docs are set up to deploy automatically by the GitHub actions CI workflow via [this code](https://github.com/openmm/openmm/blob/master/.github/workflows/CI.yml#L648-L659) into a `development/` folder when code is merged into `master`. `docs-openmm-org` is set up to enable pushes by an `openmm-org-ci` IAM user. We have GitHub secrets credentials set for access key and secret access key, but the S3 bucket name is _also_ a secret that we cannot check. Assuming we have configured this correctly for `docs-openmm-org` and the `openmm-org-ci` IAM user credentials, I see the S3 bucket contains a `development/` folder, but its contents have not been updated since 22 Oct 2020. I notice the [`AWS_REGION`](https://github.com/openmm/openmm/blob/master/.github/workflows/CI.yml#L657) is incorrect if it is intended to go to my `us-east-1` bucket `docs-openmm-org`.
* The `openmm-org-ci` IAM user was last active 22 Oct 2020.
* I don't see an action to build and deploy docs for releases. Is this supposed to be a manual part of our release checklist?

Questions for you:
* Have we updated the OpenMM docs since 22 Oct 2020? If so, how?
* Is my `us-east-1` region `docs-openmm-org` bucket the actual S3 bucket serving the docs?
* Do you want me to try to reset the http://github.com/openmm/openmm repo Actions secrets for the `openmm-org-ci` account credentials and the `docs-openmm-org` bucket? If so, you will want to correct the region to `us-east-1` in GitHub Actions and test whether the development docs successfully push to http://docs.openmm.org/development/api-python/ and friends. I can also check if the account is actively being used.
* How do you want to carry out release documentation pushes to the bucket?
* It would help if we could consolidate this information in documentation of our release process. Could you help with this?

**Comment by peastman** [comment]
> I don't see an action to build and deploy docs for releases. Is this supposed to be a manual part of our release checklist?

That's how we've done it in the past.  See https://github.com/openmm/openmm/wiki/Uploading-documentation.

> Have we updated the OpenMM docs since 22 Oct 2020? If so, how?

Yes.  OpenMM 7.7 was released in Dec. 2021, and the documentation includes new features added in that release, for example [MonteCarloFlexibleBarostat](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.MonteCarloFlexibleBarostat.html#openmm.openmm.MonteCarloFlexibleBarostat).  It would have been done by copying `development` over to `7.7.0` and `latest`.  I've always done it through the web interface, since I couldn't get the command line client working.

> I see the S3 bucket contains a development/ folder, but its contents have not been updated since 22 Oct 2020.

That's not the correct one then.  The development documentation is currently up to date.  For example, [here](http://docs.openmm.org/development/api-python/generated/openmm.app.topology.Topology.html#openmm.app.topology.Topology.bonds) you can see a change that was just made last month in #3968.

In the past I've updated the documentation by logging in to the pandelabaws account.  My vague recollection is that you took over ownership of that account?

**Comment by peastman** [comment]
The correct documentation for 8.0 should now be online.
