### ISSUE TITLE
LRC not converging in CustomNonbondedForce

### ISSUE THREAD

**Issue by aehogan** [openmm/openmm#4047]
Hi,

My custom force's LRC is not converging and openmm is crashing for linux and macos running openmm 8.0.0 however the same code works on linux running 7.7.0 and windows (in a pycharm/conda/cuda env) running 8.0.0

A minimal example is attached.

Thanks,
Adam

[main.zip](https://github.com/openmm/openmm/files/11325591/main.zip)

**Comment by peastman** [comment]
When it tries to integrate the expression to infinity, it gets NaNs due to the expression being numerically unstable.  Consider the term `expbr * ttdamp10Sum`, for example.  As r increases, `expbr` shrinks as exp(-r) while `ttdamp10Sum` grows as r^10.  Eventually they both exceed the range that can be represented in floating point and the product turns into 0*infinity = NaN.

A possible solution would be to wrap those terms in `select(expbr, ..., 0)`.  That will ensure that if `expbr` saturates to zero, the product becomes exactly zero.

Your expression is more complicated than it needs to be.  Writing out repeated products like this is not a good idea:

```
        "br10 = br5*br5;"
        "br9 = br5*br4;"
        "br8 = br4*br4;"
        "br7 = br4*br3;"
        "br6 = br3*br3;"
        "br5 = br3*br2;"
        "br4 = br2*br2;"
        "br3 = br2*br;"
        "br2 = br*br;"
```

Instead, just write whatever power you need where you need it, e.g. `br^10`.  It's really good at optimizing expressions of that sort and computing them efficiently.  By writing out a long series of products, you get in the way of the optimizer and usually get slower performance.

**Comment by aehogan** [comment]
Thanks for the advice!
