### ISSUE TITLE
Nose Hoover Friction Coefficient/Debugging the Step Function

### ISSUE THREAD

**Issue by wlai0611** [openmm/openmm#4100]
Good Evening,
    I hope you are well.  Would it be possible to show me how to access the friction coefficient in each step of the Nose Hoover Integrator?  I am referring to the friction coefficient, $\xi$ in Equation 5 of [Hoover's 1986 paper in which he modified Nose's thermostat](https://williamhoover.info/Scans1980s/1986-4.pdf#page=3).  The friction coefficient, $\xi$ is time dependent and I was hoping to access it at every timestep.  Also would it be possible to access the derivative of $\xi$, $\frac{d\xi}{dt}$ at each time step?

I have built OpenMM from source and tried to step into the OpenMM::NoseHooverIntegrator::step function at each timestep but I cannot go any deeper than the shared library libOpenMM.so.8.0.  Is there a way to expose the implementation of NoseHooverIntegrator's step function so I can see how the velocities are updated at each timestep?  Thank you very much for any guidance you can provide.

Sincerely
Walter

**Comment by peastman** [comment]
You'll need to compile with debug symbols if you want to be able to step into it with a debugger.  In CMake, set `CMAKE_BUILD_TYPE` to `Debug`.  Or you can just add debugging code to print the information you want.

I'm not familiar with the details of the algorithm, and it won't exactly match that paper since NoseHooverIntegrator uses [Nose-Hoover chains](https://www2.stat.duke.edu/~scs/Projects/REMD/NoseHooverChains1992.pdf).  The reference plaform is the simplest to work with.  I believe the code you're looking for is in this routine:

https://github.com/openmm/openmm/blob/13ff4482ec5eb5acdd74d8ff233483b6319c6086/platforms/reference/src/SimTKReference/ReferenceNoseHooverChain.cpp#L53-L95

**Comment by wlai0611** [comment]
Thank you so much for the reply.  I redid the CMAKE and I am able to step into the function OpenMM::NoseHooverIntegrator::step. 
I was also interested in taking another step into the functions "updateContextState()" and "calcForcesAndEnergy" which are called in the step() function.  However, when I take a further step, I am again reaching libOpenMM.so.8.0 and cannot examine or modify the code in that file.  

If I added debug code such as print statements to the Reference file, you provided, will those print statements be hit during execution?  I am using CUDA platform, do you recommend switching to Reference platform then, adding print statements to that SIMTKReferenceFile?

**Comment by peastman** [comment]
Yes, you need to recompile after making any change to the code.

**Comment by wlai0611** [comment]
Thank you so much for answering my questions.  I just wanted to know, if I made a modification to https://github.com/openmm/openmm/blob/master/platforms/common/src/kernels/noseHooverIntegrator.cc, in order for my changes to take effect, should I go to the kernel folder and run make noseHooverIntegrator.cc or am I running make on the wrong file?

**Comment by peastman** [comment]
You need to recompile the project by typing `make install` from your build folder.  See [the manual](http://docs.openmm.org/latest/userguide/library/02_compiling.html) for instructions on compiling.

**Comment by wlai0611** [comment]
Thank you so much!  I am able to modify the source code and run.  I will close this issue.  I greatly appreciate your quick and clear responses.
