### ISSUE TITLE
Stop supporting nvcc for compilation?

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#4105]
When the CUDA platform was first created, it compiled kernels by writing the source code to a temporary file, invoking nvcc to compile it, and loading in the file with the result.  That was the only way to do it.  Eventually NVIDIA introduced the nvrtc runtime compiler, which provided a cleaner way of doing it.  But we still needed to support older CUDA versions without nvrtc, so I structured it as a plugin.  With new CUDA versions, the plugin would be loaded and used to compile kernels.  With older CUDA versions, the plugin wouldn't load since it couldn't link to libnvrtc and it would continue to use the old method with nvcc.

We have long since dropped support for CUDA versions without nvrtc.  Is it time to simplify the mechanism, get rid of the plugin, have the main CUDA plugin link to libnvrtc directly, and make that into the only mechanism used to compile kernels?  It would simplify the code and eliminate a potential source of errors.

**Comment by jchodera** [comment]
Which CUDA versions does OpenMM currently support? 

It sounds like this would not restrict the range of supported CUDA versions further, so I don't see a downside if there isn't a significant performance difference between `nvcc` and `libnvrtc` (which are presumably using the same compiler infrastructure anyway).

Are there any implications for Folding@home core versions of OpenMM, where we rely on a single compiled executable to run on the broadest possible swath of recent GPUs?

**Comment by peastman** [comment]
> Which CUDA versions does OpenMM currently support?

I think the earliest one for conda-forge builds is either 10.2 or 11.0.  For comparison, nvrtc was introduced somewhere around 5.0.

> Are there any implications for Folding@home core versions of OpenMM

Not that I know of.

**Comment by tristanic** [comment]
I think that makes a lot of sense, but it would be important to ensure that the correct version of nvrtc and its associated redistributables are automatically installed and kept available, rather than relying on the user to maintain an exactly-matching minor version of CUDA for the purpose. Looks like that should be a whole lot easier than it used to be: https://pypi.org/project/nvidia-cuda-nvrtc-cu11/. Ridiculously bare-bones (literally just the header and compiled libraries plus empty `__init__.py` files), but makes it easy enough to find them on a given system.
```
pip install nvidia-cuda-nvrtc-cu11
```

```
import os
from nvidia.cuda_nvrtc import bin as nvrtc_bin
from nvidia.cuda.nvrtc import include
nvrtc_libdir = os.path.dirname(nvrtc_bin.__file__)
nvrtc_include = os.path.dirname(include.__file__)
``` 

There's also a `nvidia-cuda-nvrtc-cu12` package (which would be nice right about now, since the latest Nvidia display drivers have dropped backward compatibility with CUDA 11).

**Comment by peastman** [comment]
If you've installed the toolkit by any standard mechanism, you should have a correct version automatically.  This is no different from cufft.  They're both included in the toolkit.  If you somehow link to libraries pulled from different toolkit versions you're going to get problems.

**Comment by peastman** [comment]
Contrast that with nvcc, which is invoked as a command line, so it's very easy to end up in situations where you link to one toolkit version but run nvcc from a different version.
