### ISSUE TITLE
simulation using gromacs files blows up in openmm but not gromacs

### ISSUE THREAD

**Issue by rowanwalker96** [openmm/openmm#4209]
Hi there,

I am trying to run a simulation in openmm starting from gromacs .gro and .top files. If I begin dynamics with gromacs I have no problems whatsoever but if I use openmm the system instantly blows up with particle coordinate is NaN. Any immediate ideas on why this might be the case?

Here are the files needed to reproduce the behaviour:
[example_files.zip](https://github.com/openmm/openmm/files/12476886/example_files.zip)

The system of interest is a 30mer dA ssdna solvated in a truncated octahedral box parametrised with the des-amber forcefield and which uses the tip4pd water model. Systems of dT and rU prepared in exactly the same way seem to run fine in openmm which may offer a clue.

**Comment by peastman** [comment]
The first thing I notice about your script is that you add a CustomExternalForce which is meant to apply harmonic position restraints.  But it doesn't, because you add it after the Simulation has already been created.  Once you do that, any further changes to the System won't be seen by the existing Simulation unless you call `reinitialize()`.  You either need to reinitialize it, or just wait until after the force has been added to create the Simulation.

When I run the script I get this error:

```
openmm.OpenMMException: The System has two constraints between the same atoms.  This will produce a singular constraint matrix.
```

Since the script doesn't explicitly add any constraints, this is presumably a bug in the reader.  I suspect it was just introduced recently in #4188.  I'll investigate.

**Comment by peastman** [comment]
It happens because the file contains both `[ bonds ]` and `[ settles ]` for the same atoms.  Is that supposed to work?

As I understand it, the standard Gromacs water files include one or the other.  A single file includes both versions, and uses the `FLEXIBLE` macro to choose which to include.  The OpenMM reader defines that macro to get the version with bonds rather than constraints.  Then based on the `constraints` and `rigidWater` options passed to `createSystem()`, it may replace them with constraints.

Possibly when adding constraints based on those options, it should check whether there's already a constraint between the two particles, and only add a new constraint if there isn't already one?

**Comment by rowanwalker96** [comment]
adding the [bonds] in tip4pd.itp was just to work around #4188 , I wouldn't usually have both [bonds] and [settles], I was still using version 8.0 without the fix, I have removed [bonds] in the new files below to demonstrate the actual problem I was having: a system which runs fine in gromacs but blows up for openmm
[example.zip](https://github.com/openmm/openmm/files/12479359/example.zip)

**Comment by peastman** [comment]
It looks to me like your input file is messed up.  A few pieces of the molecule are translated way away from the rest.  Here is what VMD shows when I open em.gro.

![em](https://github.com/openmm/openmm/assets/4379786/d7d33891-1dcf-4438-a92b-700942ad923c)

When I load it into OpenMM, it produces some bonds with enormous energies.

**Comment by rowanwalker96** [comment]
I think that's just the periodic boundaries of the truncated octahedral box. 

In any case, here is an example where my molecule is centered in a rectangular box, minimisation is successful with gromacs but not openmm. Dynamics also appears fine with gromacs but blows up with openmm. I don't think the issue is the tip4pd water as I've been running simulations with it for other cases.

[example.zip](https://github.com/openmm/openmm/files/12487820/example.zip)

If I obtain the potential energy say of em.gro with gromacs and openmm with the same cutoff I get -3249626 kj/mol and --3399875 kj/mol for gromacs and openmm respectively. Can such a difference be expected?

What would you recommend I look at to find the source of the problem? Many thanks!

**Comment by peastman** [comment]
> I think that's just the periodic boundaries of the truncated octahedral box.

You can't break up a molecule like that.  See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic) for a discussion of periodic boundary conditions.

> I get -3249626 kj/mol and --3399875 kj/mol for gromacs and openmm respectively. 

You're looking at the energy after minimization.  The energy before minimization is -1717179 kJ/mol.  The minimizer doesn't guarantee which local minimum it will find, so it's expected that the minimizers in OpenMM and Gromacs will end up in different ones.  You should compare the energies they compute for the same coordinates.

On a different subject, do you really need to be writing frames to the trajectory every 50 steps?  On my computer, it spends almost all its time writing to disk and hardly any time running the simulation.  If I increase the interval for DCDReporter to 10000, the simulation speed increases from 9.7 ns/day to 116 ns/day.

**Comment by rowanwalker96** [comment]
> You can't break up a molecule like that. See [the FAQ]

ok thanks I'll have a look

> You should compare the energies they compute for the same coordinates.

Yes sorry for not being clear that's what I did, I compared the energies of the gromacs minmised coordinates em.gro in both gromacs and openmm and that was the difference

> On a different subject, do you really need to be writing frames to the trajectory every 50 steps? 

That was just for debugging purposes. So does the simulation actually run for you then? I can't even reach 50 steps before getting the particle coordinate is NaN error.

**Comment by peastman** [comment]
I ran it for over 20,000 steps without problem.  That's using the most recent development code.  I haven't tried 8.0.  There've been a number of changes to GromacsTopFile since then.

> I compared the energies of the gromacs minmised coordinates em.gro

There's no em.gro file, just SYSTEM.gro.

**Comment by rowanwalker96** [comment]
ok thanks, what's the best way to install the development code?

the em.gro file was in the gromacs_run folder, it's ok

**Comment by peastman** [comment]
Check out the code with `git clone https://github.com/openmm/openmm.git`.  Then follow the directions in http://docs.openmm.org/latest/userguide/library/02_compiling.html on how to compile from source.

**Comment by rowanwalker96** [comment]
development code seems to work, not quite sure why just yet, but thanks for your help
