### ISSUE TITLE
Saving trajectory without wrapping

### ISSUE THREAD

**Issue by CheggQuery** [openmm/openmm#4254]
I am running a Brownian dynamics simulation (openmm.BrownianIntegrator(300 kelvin, 91/ps, 2 fs)) for a protein in the presence of ions. I want to calculate the dynamic properties like the translational diffusion coefficient. For calculating the dynamic properties we need unwrapped trajectories. Therefore, I used dcdreporters as simulation.reporters.append(app.DCDReporter('traj.dcd',2 fs,enforcePeriodicBox=False)).

However, after running 2 microseconds, there is only 45 angstrom translation in the center of mass of the protein. Is it enough to write only enforcePeriodicBox=False in the dcdreporter to turn off pbc wrapping?

**Comment by peastman** [comment]
It's easy to tell whether it's getting wrapped: just watch a movie of the trajectory and look for a sudden jump in the position of the protein, where it moves from one side of the box to the other.

Is there a reason you chose Brownian dynamics?  It doesn't give very realistic diffusion properties.  Langevin dynamics should be more realistic.

Does your simulation use implicit or explicit solvent?  You specify friction of 91/ps, which is the experimental friction coefficient of water.  That's a reasonable choice for implicit solvent, but if you have explicit solvent it's much too high, because you already have friction from the actual water molecules.

You have your DCDReporter saving a frame after every step.  Is that really what you want?  It will spend almost all its time writing to disk, and hardly any time actually simulating.  Usually people write frames much less frequently, perhaps every 1000 steps or even less.

Be sure your system doesn't include a CMMotionRemover, since that will interfere with the diffusion rate.  If you create it with a ForceField, specifiy `removeCMMotion=False` in your call to `createSystem()`.

**Comment by CheggQuery** [comment]
> It's easy to tell whether it's getting wrapped: just watch a movie of the trajectory and look for a sudden jump in the position of the protein, where it moves from one side of the box to the other.

I can only observe 45 angstrom translation in the center of mass of the protein after running 2 microseconds. Is it enough?

> Is there a reason you chose Brownian dynamics? It doesn't give very realistic diffusion properties. Langevin dynamics should be more realistic.

I want to calculate dynamic properties as mentioned earlier. Therefore I need to use Brownian dynamics simulation.

> Does your simulation use implicit or explicit solvent? You specify friction of 91/ps, which is the experimental friction coefficient of water. That's a reasonable choice for implicit solvent, but if you have explicit solvent it's much too high, because you already have friction from the actual water molecules.

I am running a coarse-grained implicit solvent simulation.

> You have your DCDReporter saving a frame after every step. Is that really what you want? It will spend almost all its time writing to disk, and hardly any time actually simulating. Usually people write frames much less frequently, perhaps every 1000 steps or even less.

I am saving after 10000 steps.

> Be sure your system doesn't include a CMMotionRemover, since that will interfere with the diffusion rate. If you create it with a ForceField, specifiy removeCMMotion=False in your call to createSystem().

I am creating the system with these commands:
system = mm.System()
system.setDefaultPeriodicBoxVectors([box,0,0], [0,box,0], [0,0,box])

Will it interfere with the diffusion rate?

**Comment by peastman** [comment]
> I can only observe 45 angstrom translation in the center of mass of the protein after running 2 microseconds. Is it enough?

But you never see any sudden jumps?  Then it's not being wrapped.

> I want to calculate dynamic properties as mentioned earlier. Therefore I need to use Brownian dynamics simulation.

If you want accurate dynamics you should use Langevin dynamics.  Brownian dynamics is an approximation to Langevin dynamics.  It is never more accurate.  If the assumptions behind the approximation are not valid for your system, it may be less accurate.

**Comment by CheggQuery** [comment]
> But you never see any sudden jumps? Then it's not being wrapped.

No i did not see any sudden jump. Do I need to mention anything in the script to set unwrapping?

**Comment by RaulPPelaez** [comment]
See the documentation for this component:
http://docs.openmm.org/latest/api-python/generated/openmm.app.dcdreporter.DCDReporter.html
Probably a good idea to leave it as False explicitly, even if just for code clarity. In addition to this, checkout the removeCMMotion flag Peter mentioned.

When computing things like the mean squared displacement (I assume you are computing it since you mentioned diffusion coefficients) you can make sure no unwanted warps are taking place by adding a simple guard to your code, if the displacement of an object (e.g protein) from one snapshot to the next is larger than half the box size you should print an error.

> However, after running 2 microseconds, there is only 45 angstrom translation in the center of mass of the protein

Note that the average displacement of the CoM in a Brownian simulation is 0, this particular metric does not tell you anything useful, it is basically a random number. The mean squared displacement however, and thus the diff coeff, should scale inversely with the size of the protein:
https://en.wikipedia.org/wiki/Mean_squared_displacement

As Peter mentioned, Brownian Dynamics are not enough to recover the Stokes-Einstein equation, as it neglects hydrodynamic interactions https://en.wikipedia.org/wiki/Einstein_relation_(kinetic_theory)
The diffusion coefficient of your protein in BD will simply scale with the number of atoms in the protein, regardless of the shape of it. In BD a sphere of N atoms will have the same Diff coeff as, for instance, a disk with N atoms.

There are (expensive) ways to reintroduce hydrodynamics in BD, but with OpemMM the most straight-forward way is Langevin dynamics, which is as cheap as BD. With it, the MSD will eventually show a linear regime in time and its slope will give you a diffusion coefficient that correctly captures the Stokes-Einstein equation.

**Comment by CheggQuery** [comment]
> See the documentation for this component:
http://docs.openmm.org/latest/api-python/generated/openmm.app.dcdreporter.DCDReporter.html
Probably a good idea to leave it as False explicitly, even if just for code clarity. In addition to this, checkout the removeCMMotion flag Peter mentioned.

I am already using enforceBox=False to avoid wrapping. I have created the system using the commands below:
```
system = mm.System()
system.setDefaultPeriodicBoxVectors([box,0,0], [0,box,0], [0,0,box])
```
which does not contain any option for setting CMMotionremover=False. I am not even using anything related to CMMotionremover.

> When computing things like the mean squared displacement (I assume you are computing it since you mentioned diffusion coefficients) you can make sure no unwanted warps are taking place by adding a simple guard to your code, if the displacement of an object (e.g protein) from one snapshot to the next is larger than half the box size you should print an error.

Even after running my coarse-grained simulation for 2 microseconds, protein did not go out of the simulation box. However, the ions are out of the simulation box.

> Note that the average displacement of the CoM in a Brownian simulation is 0, this particular metric does not tell you anything useful, it is basically a random number. The mean squared displacement however, and thus the diff coeff, should scale inversely with the size of the protein:
> As Peter mentioned, Brownian Dynamics are not enough to recover the Stokes-Einstein equation, as it neglects hydrodynamic interactions https://en.wikipedia.org/wiki/Einstein_relation_(kinetic_theory)
> The diffusion coefficient of your protein in BD will simply scale with the number of atoms in the protein, regardless of the shape of it. In BD a sphere of N atoms will have the same Diff coeff as, for instance, a disk with N atoms.
> There are (expensive) ways to reintroduce hydrodynamics in BD, but with OpemMM the most straight-forward way is Langevin dynamics, which is as cheap as BD. With it, the MSD will eventually show a linear regime in time and its slope will give you a diffusion coefficient that correctly captures the Stokes-Einstein equation.

Langevin dynamics simulation is associated with low friction coefficient. Therefore, I choose Brownian dynamics with high friction to mimic actual water friction. I am hoping that the BrownianIntegrator in openmm used the equation of motion similar to the equation present in equation S8 in this paper (https://www.pnas.org/action/downloadSupplement?doi=10.1073%2Fpnas.1019500108&file=pnas.1019500108_SI.pdf). 

In my openmm  script, I am using these below commands:
```
pdb = app.PDBFile("position.pdb")
positions = pdb.positions
system = mm.System()
system.setDefaultPeriodicBoxVectors([box,0,0], [0,box,0], [0,0,box])
for i in range(n):
    system.addParticle(mass)
system.addForce(Custom_Bond_Force_fene)
system.addForce(NonbondedForce_PME)
system.addForce(CustomNonbondedForce_LJ)
system.addForce(CustomBondForce_Excluded_Volume)
platform = mm.Platform.getPlatformByName('CUDA')
properties = {'Precision': 'double'}
integratorLD = mm.BrownianIntegrator(T,fric_coef,timeStep)
simulation = app.Simulation(pdb.topology,system,integratorLD,platform,properties)
simulation.reporters.append(app.DCDReporter('traj.dcd',timeint,enforcePeriodicBox=False))
simulation.step(100000000)
```

I have not shown the expression explicitly for the forces. For CustomBondForce_Excluded_Volume, I am using NonbondedForce.CutoffPeriodic as nonbonded method.  Although I can see the ions are moving out of the simulation box with time, but the protein is always within the box. Can you please let me know what should I modify to save the unwrap trajectories?

**Comment by peastman** [comment]
> Langevin dynamics simulation is associated with low friction coefficient.

You can use any friction coefficient you want with either one.  Langevin dynamics simulates according to the Langevin equation:

$m \frac{d \mathbf{v}}{dt} = \mathbf{f} - \gamma m \mathbf{v} + \mathbf{R}$

where $\gamma$ is the friction coefficient and $\mathbf{R}$ is a random force.

Brownian dynamics assumes the left side of the equation is small enough we can ignore it.  That leads to a simpler equation:

$\mathbf{v} = \frac{\mathbf{f}}{\gamma m} + \mathbf{R}$

This is strictly an approximation to the Langevin equation.  It is never more accurate, and may be less accurate.

> Can you please let me know what should I modify to save the unwrap trajectories?

You're already doing it.

**Comment by peastman** [comment]
Is this still an issue, or have all your questions been answered?

**Comment by CheggQuery** [comment]
But still I don't see much shift in the com of protein. I am confused
whether it is saving the unwrapped coordinates or not?

**Comment by peastman** [comment]
They are not wrapped.
