### ISSUE TITLE
The format of the PDB file created by PDBFile.writeFile() is not correct.

### ISSUE THREAD

**Issue by KingOfChuXuan** [openmm/openmm#4307]
Hi! I want to save a conformation of the tip4p water model as a PDB file. However, I think the format is not correct.
Here is what I got:
![截图 2023-11-13 17-27-04](https://github.com/openmm/openmm/assets/146178267/1aa194ed-05e2-467d-81e3-61e22ab5f49d)
Obviously, the symbol "M" is in the wrong column, and 'EP' should be replaced by 'M'.
A similar result can be obtained by the following code:
```
from openmm import *
from openmm.app import *
from openmm.unit import *
pdb = PDBFile('tip4pew.pdb')
PDBFile.writeFile(pdb.topology, pdb.positions)
```
I wonder how to fix it?
Thank you for your reply!

**Comment by peastman** [comment]
See the [PDB spec](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#HETATM).  The atom name goes in columns 13-16.  If you count, you'll see the M is in column 13.  It might be better to center it within the field, but any reader should be able to handle it.

Columns 77-78 are supposed to contain the element symbol.  But in this case, there is no element, because the HETATM record corresponds to a virtual site, not a physical atom.  Since the spec doesn't consider that possibility, anything you put there in that case is necessarily non-standard.  By default we put "EP" for "extra particle".  You can tell it to put something different with the `extraParticleIdentifier` argument.

**Comment by KingOfChuXuan** [comment]
Oh, yes, thank you for your reply.


> However, I think the format is not correct.

I do get an Exception, and I thought the error was caused by the format, but in fact it should be attributed to the wrong PBC stored by PDBReporter. While I run a simulation in an NPT ensemble, the PBC box will change. 
However, the code for PDBReporter's 'report' method
```
    def report(self, simulation, state):
        """Generate a report.

        Parameters
        ----------
        simulation : Simulation
            The Simulation to generate a report for
        state : State
            The current state of the simulation
        """
        if self._atomSubset is not None:
            if self._subsetTopology is None:
                self._createSubsetTopology(simulation.topology)

            topology = self._subsetTopology

            #PDBFile will convert to angstroms so do it here first instead
            positions = state.getPositions().value_in_unit(angstroms) 
            positions = [positions[i] for i in self._atomSubset]

        else:
            topology = simulation.topology
            positions = state.getPositions()

        if self._nextModel == 0:
            PDBFile.writeHeader(topology, self._out)
            self._topology = topology
            self._nextModel += 1
        PDBFile.writeModel(topology, positions, self._out, self._nextModel)
        self._nextModel += 1
        if hasattr(self._out, 'flush') and callable(self._out.flush):
            self._out.flush()
```
seems that it doesn't change the PBC while saving.
So is it better to add `topology.setPeriodicBoxVectors(state.getPeriodicBoxVectors())` before `PDBFile.writeModel(topology, positions, self._out, self._nextModel)`?

**Comment by peastman** [comment]
That's a limitation of the PDB format.  It can't store different box vectors for different frames.  It only allows a single set of box vectors, which go in the header of the file.  That's why it writes the ones from the topology.

Other formats like DCD and XTC do have the ability to write different box vectors for each frame.

**Comment by KingOfChuXuan** [comment]
> It can't store different box vectors for different frames.

Oh! I get it. Thank you for your reply!
