### ISSUE TITLE
connection box vectors and volume

### ISSUE THREAD

**Issue by SchroedingersLion** [openmm/openmm#4318]
Hi everyone,

is it true that the box vectors when doing NPT sampling will always stay fixed whereas the actual volume changes? Because I just printed two PDB files at different points during NPT sampling, and I was confused to see that the box vectors were the same in the two files.

Does that mean that .pdb files are useless when trying to store an NPT-equilibrated system?

Regards

**Comment by peastman** [comment]
The PDB writer takes the box vectors from the topology, not the state.  That's because PDB format doesn't have the ability to store different box vectors for different frames.

This question seems to be coming up a lot lately.  See also #4307 for example.  Possibly we should change it to take the box vectors from the state when possible.  But that's only possible when writing a single frame, not a trajectory.

For writing trajectories, formats like DCD and XTC are much better choices.  They can store different box vectors for each frame.

**Comment by SchroedingersLion** [comment]
Thanks Peter, that explains it. 

My actual use-case is as follows (off-topic): I want to load an equilibrated system and do a few experiments for different hydrogen masses. I thought about storing the equilibrated system as an .xml file and then load my system using that, but I was not sure how to easily adjust the hydrogen masses for an existing system. It seems to be much easier when creating a system from a forcefield and a .pdb via `forcefield.createSystem` and then setting the `hydrogenMass` parameter. What would you recommend?

**Comment by peastman** [comment]
What about storing the coordinates and box vectors in a serialized State object with `simulation.saveState()`?  Another of the problems with PDB is that it has very limited precision for storing coordinates.  The State will record them to full precision, along with the box vectors, velocities, and any other parameters that may be relevant.

**Comment by SchroedingersLion** [comment]
Yes, I think that's the better option. Thank you!
