### ISSUE TITLE
Create Vec3 using default constructor from python API

### ISSUE THREAD

**Issue by hmacdope** [openmm/openmm#4333]
Currently calling `Vec3()` with no arguments from python API fails, whereas the C++ API has the overloaded constructor Where `Vec3()` is equivalent to `Vec3(0.0, 0.0, 0.0)`. 

Perhaps we could expose the default constructor at the python layer for consistency?

**Comment by hmacdope** [comment]
Would this be useful @peastman?

**Comment by peastman** [comment]
Sounds reasonable!  Note that the Python Vec3 class isn't actually a wrapper around the C++ Vec3 class.  It's good to keep the API as close as possible, though.

**Comment by peastman** [comment]
I remember now why I didn't do this in the first place.  C++ allows overloading.  We can have two constructors, one with no arguments and one with three arguments.  Python doesn't.  We're limited to a single constructor with a single set of arguments.

We could approximate the same thing with default arguments: `x=0.0, y=0.0, z=0.0`.  That would give the intended behavior for the 0 and 3 argument cases.  But it would also accept other things that it probably shouldn't.  If you passed two arguments, it would interpret them as the x and y components and set z to 0, whereas what it probably means is that you made a mistake and left off one of the arguments you intended to pass.

Another option is to just list the arguments as `*args`, then throw an exception if the number of arguments isn't 0 or 3.  That's a less friendly API that leads to more confusing documentation and breaks things like static code checkers.

That's why I decided the best option overall was to require three arguments.

**Comment by hmacdope** [comment]
That's totally fine :) python overloading is a pain. I'll close.
