### ISSUE TITLE
It takes too much time on forcefield.createSystem

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4379]
Hi

I'm trying to simulate water box system with carbon nanotube (CNT)

But it starts not to proceed at ```forcefield.createSystem(pdb.topology, nonbondedMethod=PME)```

Here's my input files and code.
 
input: [Desktop.zip](https://github.com/openmm/openmm/files/13820008/Desktop.zip)

```
from openmm.app import *
from openmm import *
from openmm.unit import *

topology.Topology.loadBondDefinitions("carbon_only.xml") # It seems not working
pdb = PDBFile('54_Cl.pdb')
forcefield = ForceField('charmm_polar_2019.xml', "carbon_only.xml")

# I had to insert this part since loadBondDefinitions does not work.
# Adding bonds to topology manually

for i in atoms:
    if i.name == 'C1':
        start_idx = i.index
with open("CNT_54_Cl_bond.txt", 'r') as f:
    for text in f.readlines():
        a, b = map(int, text.split())
        pdb.topology.addBond(atoms[a + start_idx], atoms[b + start_idx])

platform = Platform.getPlatformByName('CUDA')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME) # It stucks here
```

I'm pretty sure that the problem is due to the CNT residue, since it worked well without it.

But what did I missed?

**Comment by OkKakao** [comment]
[CNT_54_Cl_bond.txt](https://github.com/openmm/openmm/files/13820286/CNT_54_Cl_bond.txt)

I forgot to upload this file.

**Comment by peastman** [comment]
> topology.Topology.loadBondDefinitions("carbon_only.xml") # It seems not working

`loadBondDefinitions()` doesn't take a force field.  See [this file](https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/residues.xml) for the expected format.

As for why it's taking so long, it's trying to match atoms in the PDB file to ones in the force field's template.  That requires solving a graph isomorphism problem.  In the worst case, the time to solve it can scale exponentially in the number of atoms.  Usually this isn't a problem, because most residues are small.  An amino acid only has around 20 atoms.  Your nanotube has 256 atoms, making it far more expensive.

There also are ways we can reduce the number of possibilities it needs to consider.  We can first filter atoms by element.  A carbon in the PDB file won't match a hydrogen in the template, so we don't need to consider it.  But every atom in your residue has the same element, so that doesn't help us.  We also can filter by the number of bonds.  A carbon that forms three bonds clearly won't match a carbon that forms four bonds, so we don't need to consider it either.  But almost every atom in your residue has the same number of bonds, so that doesn't help us either.  We're stuck considering an exponential number of ways to match up a large number of atoms.

So what can you do about this?  Treat the nanotube as a polymer.  That's really what it is: a small repeating unit, with many copies stacked end to end.  In the PDB file, split it up into one residue for each copy of the repeating unit.  In the force field, define the template to include only a single copy of the repeating unit.  (You'll probably also need a separate template for the ends, since they're different.)  That will make matching very fast.  It also will let you build nanotubes of any length without needing to change the force field.

**Comment by RobertArbon** [comment]
Not a question - just adding my experience for other people to read here. 

I had a similar problem with the SmirnoffGenerator from openff: 

```python

from openmm import app, VerletIntegrator, CustomExternalForce, LangevinMiddleIntegrator, XmlSerializer
from openmm.unit import nanometer, kilojoules_per_mole, picoseconds, kelvin
from openmmforcefields.generators import SMIRNOFFTemplateGenerator
from openff.toolkit import Molecule

...

ligand = Molecule('ligand.sdf')
pdb = app.PDBFile(pdb_file)

forcefield = app.ForceField(
    "amber/protein.ff14SB.xml",
    "amber/tip3p_standard.xml",
)
smirnoff = SMIRNOFFTemplateGenerator(forcefield="openff-2.1.0", molecules=ligand)
forcefield.registerTemplateGenerator(smirnoff.generator)
print('creating System')
system = forcefield.createSystem(pdb.topology, 
                                 nonbondedMethod=app.PME,
                                 nonbondedCutoff=cutoff_nm*nanometer, 
                                 constraints=app.HBonds)
```

On a Mac M3 this would take several minutes.  On a Google VM / Debian with 8 CPUs this would hang, apparently indefinitely.  

I ended up creating the system on my M3 as an XML and copying over the the VM.

**Comment by peastman** [comment]
That's an unrelated issue, and not a bug.  The OpenFF force field uses AM1-BCC to compute partial charges.  That's a slow method that can take a while.
