### ISSUE TITLE
performance of CustomAngleForce

### ISSUE THREAD

**Issue by wayuer19** [openmm/openmm#4383]
Hi,

I'm trying to replace the harmonic angle potential created from Charmm files, V = k*(theta-theta0)^2, with a custom angle force following
```
for force in system.getForces():
    if force.getName() == "HarmonicAngleForce":
        hmangle = force

ReB = CustomAngleForce("kt*(theta-theta0)^2/(sin(theta)^2);")
ReB.addPerAngleParameter("theta0")
ReB.addPerAngleParameter("kt")
for angle_idx in range(hmangle.getNumAngles()):
    ang = hmangle.getAngleParameters(angle_idx)
    ReB.addAngle(ang[0], ang[1], ang[2], [ang[3], ang[4]])
system.addForce(ReB)
system.removeForce(hmangle.getForceGroup())
```

It worked as expected, but run much slower, almost 50% down. As a test, for 1000000 steps, I got the time cost of 46.692s with custom angle force, while 26.730s before.

Do you have any suggestions?

**Comment by jchodera** [comment]
Thanks for opening an issue into this! 

This _shouldn't_ slow things down for most systems since nonbonded interactions generally dominate, but I suppose it's possible this might be slower if you're using the CPU platform and vacuum systems.

This may not be the root cause, but I spotted a bug in your script. This line uses the force group number of the `hmangle` force rather than the index of the `HarmonicAngleForce` object within the `System` object:
```python
system.removeForce(hmangle.getForceGroup())
```
If you've separately set the force groups to correspond to the force index within `System`, that would not make a difference. But if not, you can modify your script to use the force index when deleting the `HarmonicAngleForce`:
```python
# Get harmonic angle force and force index
for force_index, force in system.getForces():
    if force.getName() == "HarmonicAngleForce":
        hmangle = force
        harmonic_force_index = force_index # index of Force within System
        break

ReB = CustomAngleForce("kt*(theta-theta0)^2/(sin(theta)^2);")
ReB.addPerAngleParameter("theta0")
ReB.addPerAngleParameter("kt")
for angle_idx in range(hmangle.getNumAngles()):
    ang = hmangle.getAngleParameters(angle_idx)
    ReB.addAngle(ang[0], ang[1], ang[2], [ang[3], ang[4]])
system.addForce(ReB)
# Remove the HarmonicAngleForce
system.removeForce(harmonic_force_index)
```
Note also that the OpenMM functional form for [`HarmonicAngleForce`](uide/theory/02_standard_forces.html#harmonicangleforce) includes a factor of `1/2` that you may want to account for in your modified function.

**Comment by peastman** [comment]
I agree, this should have minimal effect on speed.  Can you post a complete example (script and input files) to reproduce the behavior?

Which platform are you using?

**Comment by wayuer19** [comment]
Really appricate for your reply and suggestion. I made an mistake as @jchodera said, where a wrong force was removed. They got similar performance when using force index to remove the force.

Thank you so much!
