### ISSUE TITLE
How to use geometric combination rules?

### ISSUE THREAD

**Issue by KingOfChuXuan** [openmm/openmm#4384]
Hi there!

I’m using the OPLS force field to perform a molecular dynamics simulation of an organic system. The system requires geometric combination rules instead of Lorentz-Berthelot combination rules. I wonder how to make the NonBondedForce use geometric combination rules. Thank you for your reply!

**Comment by peastman** [comment]
NonbondedForce doesn't support alternate combining rules, so instead you need to use a CustomNonbondedForce.  You can still use NonbondedForce for the Coulomb interactions and for the exceptions, since they don't depend on the combining rule.

Set epsilon to 0 for every particle, so the NonbondedForce won't compute LJ interactions.  Then add a CustomNonbondedForce to compute just the LJ interactions using the combining rule of your choice.

**Comment by KingOfChuXuan** [comment]
I get it, thank you for your reply!
