### ISSUE TITLE
breaking/reforming bonds in OpenMM

### ISSUE THREAD

**Issue by ramansbach** [openmm/openmm#4403]
Hi,

I'm hoping to use OpenMM to do a simulation of disulfide cross-linked polymers and I'm trying to figure out if there would be an efficient way to implement forming and breaking bonds in OpenMM as part of a MonteCarlo step (MC I think could be done with the OpenMMtools plugin).  I think the bonds would be forming/breaking around every 50 timesteps.  Is this a possibility?  Is there an approach you would suggest to try implementing something like this?

Thanks so much!

**Comment by peastman** [comment]
There are a few possible ways of doing it.  Can you describe more about the system you want to simulate?

- How large is it (total number of atoms)?
- Are there just a few possible bonds that can be formed or broken, or can any monomer potentially bond to any other (very large number of possible bonds)?
- What happens when a bond forms or breaks?  For example, does it involve adding or removing hydrogens?  Do nonbonded parameters change?  Does it affect only the atoms directly involved in the bond, or does it cause charge rearrangements that affect a larger area?

**Comment by ramansbach** [comment]
Absolutely!  Thanks for your response.

I'm trying to model mucins, which are large polymers with, unfortunately, quite a number of disulfide cross-links.  The initial model I am trying to get to work is from a MSc thesis (was originally done with LAMMPs, but I was hoping to do with OpenMM).  It consists of 80,000 coarse-grained beads divided into molecules of 40 beads each for a total of 2000 molecules.  In each molecule there are two beads that can form disulfide cross-links with any other bead of the same type, so there are 4000 total beads capable of breaking/forming bonds with one another (a lot of total possible bonds, but the bonds can only reasonably form within a small cutoff distance so presumably one would realistically only check the neighbor-list or similar).

Each bond would only affect the S-S beads and the only change would be whether there's an additional covalent/spring-type bond hooking them together or not.  The nonbonded parameters don't change.

The bonds are formed/broken based on a straightforward Markov Chain Monte Carlo procedure, checked every 20 timesteps.

**Comment by peastman** [comment]
Got it, thanks for the explanation.  Short answer: it's easy to do, but may be challenging to make it fast enough.

I assume you're using a HarmonicBondForce or CustomBondForce to represent the bonds?  If you change the set of bonds, you need to reinitialize the context for it to see the changes.  That's very expensive, basically the same cost as creating a new context from scratch.  If all you're doing is changing the parameters of bonds, you can instead use `updateParametersInContext()`, which is much faster.  But it can't change which particles are connected by a bond.  If you only had a small list of pairs that could potentially be bonded, you could add bonds for all of them and turn them on or off by setting the force constant to 0.  But with millions of possible bonds, that would be very inefficient.

It might be better to instead treat the bonds as a nonbonded force.  Use a CustomNonbondedForce.  Add two per-particle parameters to it.  The first is just the index of the particle (0, 1, 2, ...).  The second is the index of the particle it's bonded to, or -1 if it isn't bonded.  The energy expression would be `select(delta(index1-bonded2), ..., 0)` where the ... is the energy expression for a bond.  If the first particle's index equals the second particle's bonded partner index, it will evaluate the bond energy.  Otherwise, the energy will be 0.

This effectively evaluates all possible bonds, which is inefficient in its own way, but since there's a cutoff it shouldn't be too bad.  It might also help performance if you call `addInteractionGroup()` to restrict it to only considering the 4000 particles that are capable of forming bonds (but test both ways to see whether it's actually faster or not).

So that's part of it.  To break or form bonds you call `setParticleParameters()` to change the `bonded` parameters of the particles involved, then finish with `updateParametersInContext()` to copy the changes over to the context.  That's still a somewhat slow operation, but much faster than reinitializing the whole context.  Doing it every 50 steps shouldn't be bad.

The second half of the problem is implementing your Monte Carlo algorithm.  Depending on what it involves (does a step require looking at all possible pairs that could form bonds?), that could be very slow, especially if implemented in Python.  MDTraj has a `compute_neighbors()` function that might be helpful.  It's implemented in C++, so it's reasonably fast.

There's an alternative to all of this if you really want the best possible performance: write a plugin to implement your algorithm.  You could create a special purpose force to compute exactly the forces you want and nothing else.  You could implement the Monte Carlo algorithm to run on the GPU.  That is, however, much more work.
