### ISSUE TITLE
Applying different drag coefficients to different particles

### ISSUE THREAD

**Issue by eweiner** [openmm/openmm#4442]
I am working on simulating electrolytes in explicit and implicit solvent. For the explicit solvent simulations, things are great and I get diffusion values I expect and just use Langevin dynamics as a thermostat. However, when I want to make measurements with implicit solvent, I find that I can't set a different value of the drag coefficient for different ion species. I have looked into both making a custom external force and making a custom integrator. The custom external force runs into issues as it requires velocity information and it just isn't really natural to represent the forces in terms of potential energy functions of particle position. The custom integrator approach runs into trouble because I am having trouble setting per DOF parameters that rely on different constants for different kinds of particles. Any advice would be appreciated, and in the long term it seems like adding the option to have different friction coefficients for different species in the Langevin integrator could be helpful?

**Comment by peastman** [comment]
Take a look at [NoseHooverIntegrator](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.NoseHooverIntegrator.html#openmm.openmm.NoseHooverIntegrator.addSubsystemThermostat).  It supports coupling different parts of the system to different thermostats.  Use the constructor that takes only a step size.  Call `addSubsystemThermostat()` for each set of particles.  You can pass an empty list for `thermostatedPairs`, which isn't relevant to you.

Another option if you prefer Langevin dynamics is to use a [CustomIntegrator](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomIntegrator.html).  The API documentation shows how to create an integrator that is identical LangevinMiddleIntegrator:

```python
integrator = CustomIntegrator(dt)
integrator.addGlobalVariable("a", exp(-friction*dt))
integrator.addGlobalVariable("b", sqrt(1-exp(-2*friction*dt)))
integrator.addGlobalVariable("kT", kB*temperature)
integrator.addPerDofVariable("x1", 0)
integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v + dt*f/m")
integrator.addConstrainVelocities()
integrator.addComputePerDof("x", "x + 0.5*dt*v")
integrator.addComputePerDof("v", "a*v + b*sqrt(kT/m)*gaussian")
integrator.addComputePerDof("x", "x + 0.5*dt*v")
integrator.addComputePerDof("x1", "x")
integrator.addConstrainPositions()
integrator.addComputePerDof("v", "v + (x-x1)/dt")
```

You can change `a` and `b` to be per-DOF variables instead of global variables, and set them correctly for each particle's friction coefficient.

Having a similar capability in the standard Langevin integrator would be useful, but right now NoseHooverIntegrator is the only standard integrator that supports it.

**Comment by peastman** [comment]
You assign it as a per-DOF variable.  That's similar to per-particle, except it has three values for each particle (x, y, and z components).  You can set all three to the same value.

**Comment by peastman** [comment]
By calling `setPerDofVariable()`.  Set it to one value for the sodiums and a different value for the chlorines.

**Comment by eweiner** [comment]
Got it, the types in the setPerDofVariable statement were tripping me up but I got there in the end. Thanks so much for your help!
