### ISSUE TITLE
Adding an uniform velocity to set of particles

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#4486]
Hi,

I would like to simulate the flow across the ion that is fixed in the aqueous solution. My problem is I need to give an additional velocity (constant) to water molecules in each step. Should I implement a custom integrator to achieve this? 

Meanwhile I am also thinking about the thermostat. If I add an additional velocity, I want the temperature to be calculated and maintained based on the origin velocity without the additional one. How can I do this?

Many thanks!

**Comment by peastman** [comment]
I don't quite understand.  Are you saying you want the water to move at a constant velocity?  Or that you want it to accelerate at a constant rate?  Or something different?

**Comment by zhenyuwei99** [comment]
Yes! I hope to move at a constant velocity for selected particles

**Comment by peastman** [comment]
I don't think what you've implemented there is physically consistent.  You can allow the integrator to control the motion of the particle.  Or you can skip integrating it and instead move it along a fixed, predefined path.  Instead of doing either of those, you have a "velocity" that is not the time derivative of the position.  What does that mean?

As a better defined alternative, what about letting the integrator update the particle position and velocity in the normal way, but adding a harmonic restraining force that binds the particle to a point in space that moves at a constant velocity?

> But this has very large temperature shift (around 80 K).

You aren't integrating a conservative system.  You add energy to it at every time step.  That will raise the temperature.

> Meanwhile, it can not modify velocity on a single axis (1/3 of DoFs)

If you make `v_add` a per-DOF variable, you can choose exactly which axes of which particles you want to modify.

**Comment by zhenyuwei99** [comment]
> As a better defined alternative, what about letting the integrator update the particle position and velocity in the normal way, but adding a harmonic restraining force that binds the particle to a point in space that moves at a constant velocity?

Yeah, I think that is a good idea and I will try it!

> If you make v_add a per-DOF variable, you can choose exactly which axes of which particles you want to modify.

That's  mean using the `addPerDofVariable` and `setPerDofVariable`. 

Thank you very much! Let me have a quick try! I will close the issue if I have no more questions.
