### ISSUE TITLE
AMOEBA pitorsion API

### ISSUE THREAD

**Issue by selimsami** [openmm/openmm#4499]
Hi,

AmoebaPiTorsionForce API seems to be missing? Or is there a way to access this?

Additionally, can I simply add AMOEBA-type forces to my non-Amoeba FF as I like? Or are there any restrictions?

Thanks!

**Comment by peastman** [comment]
Pi torsions are implemented with a CustomCompoundBondForce:

https://github.com/openmm/openmm/blob/b32720cc3eae99b98968f5560ac6ff728714f49e/wrappers/python/openmm/app/forcefield.py#L4061-L4076

Technically speaking, you're free to add AMOEBA energy terms to other force fields.  Just make sure you know what you're doing, since force fields are parametrized as a whole.  Combining terms from different force fields won't give accurate results without refitting the parameters.

**Comment by selimsami** [comment]
Ah that worked great.
Yes, definitely planning to re-parameterize.
Thanks!
