### ISSUE TITLE
How can I manipulate epsilon of the atoms to turn off LJ force during the simualtion?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4511]
Hi

I'm trying to simulate droplet and alkali halide cluster for the calculation of potential of mean force.

I have to turn off the electrostatic force and LJ force when moving the cluster , since water molecules sticks to the cluster.

I noticed that there is getParticleParameter and setParticleParameter functions can modify the parameters related to those forces, so I decided to set epsilon and charge to zero.

However, the epsilon values of the system were already zero.

Here's one example.

```
[Quantity(value=1.7163853282605033, unit=elementary charge), Quantity(value=1.0, unit=nanometer), Quantity(value=0.0, unit=kilojoule/mole)]
```

I'm currently using charmm_polar_2019.xml for the forcefield

What should I do to eliminate LJ force?

**Comment by peastman** [comment]
That will work to set the charge.  After you modify all the particles, call `updateParametersInContext()` to copy the changes over.  Otherwise the existing context won't see any changes you make.

The CHARMM polar force field uses a CustomNonbondedForce to implement LJ interactions, since it has NBFIX terms and NonbondedForce doesn't support them.  It defines a per-particle parameter called `type` which is an integer atom type.  It uses the types of two interacting particles to look up the coefficients of the $r^{-6}$ and $r^{-12}$ terms in a pair of tabulated functions.  To turn off the LJ interactions, set those functions to contain all zeros and call `updateParametersInContext()`.

**Comment by OkKakao** [comment]
> That looks right. I take it your system has twice as many particles as your topology?

The reference does not contain drude particles.

The particles that I interested in include drude particles, so I doubled it.

I have one more question.

When I calculate force on an atom, does the force applied to drude particle have to be taken into account?

**Comment by peastman** [comment]
Instead of `ref.topology.getNumAtoms() * 2`, it's probably better to write `system.getNumParticles()`.  It's clearer and avoids chances for mistakes.

A Drude particle is just a particle.  It moves according to the forces applied to it, just like any other.  There's a restraining force connecting it to the parent particle, so the two can never get too far apart.

**Comment by OkKakao** [comment]
> Instead of `ref.topology.getNumAtoms() * 2`, it's probably better to write `system.getNumParticles()`. It's clearer and avoids chances for mistakes.
> 
> A Drude particle is just a particle. It moves according to the forces applied to it, just like any other. There's a restraining force connecting it to the parent particle, so the two can never get too far apart.

Iodide atom consists of Iodine atom and drude particle when using polarizable forcefield.

Then, what is the force applied to iodide?

1. Sum of the force applied to drude particle and iodine
2. Force applied to iodine atom only

**Comment by peastman** [comment]
The two particles together represent the atom, so the force on the atom is the sum of the forces on the two particles.

**Comment by OkKakao** [comment]
> The two particles together represent the atom, so the force on the atom is the sum of the forces on the two particles.

Thank ypu for helping me!
