### ISSUE TITLE
Mixed NonbondedForce with PME and CustomNonbondedForce with CutoffPeriodic, got error openmm.OpenMMException: All Forces must have identical exceptions

### ISSUE THREAD

**Issue by smliu1997** [openmm/openmm#4573]
Hi, 

So I want to define an electrostatic potential that supports Ewald sum or PME, and a custom nonbonded force with special functional form and cutoff in a periodic system. However, I got error "openmm.OpenMMException: All Forces must have identical exceptions". I know NonbondedForce supports exception and I set exceptions, but CustomNonbondedForce does not have this setting. So I wonder if it is possible to mix NonbondedForce with PME and CustomNonbondedForce with CutoffPeriodic? If so, how to do this and avoid such error? Or if there is other workaround to get equivalent effects? Thank you so much!

**Comment by peastman** [comment]
For CustomNonbondedForce, use `addExclusion()`.

As far as the nonbonded kernel is concerned, they both mean the same thing: to skip particular interactions.  It creates a single neighbor list that is shared between all nonbonded forces, which is why they need to skip the same interactions.  NonbondedForce calls them "exceptions" because it also gives you the option of computing the interaction with different parameters, which is done in a different kernel.

**Comment by smliu1997** [comment]
Thank you for the detailed explanation! Yes, in my case I want to rescale and exclude particular pairs so I use addException in NonbondedForce. 

One thing I want to confirm is, if I want to rescale pair a1 and a2 in NonbondedForce with addException, even if this pair is rescaled rather than excluded, I have to exclude this pair in CustomNonbondedForce, is my understanding correct?

**Comment by peastman** [comment]
Correct.  The exceptions are computed in a separate kernel and are effectively a bonded force.  It can do that, since it knows what the form of the interaction is.  For a CustomNonbondedForce, the equivalent would be to exclude them and then use a CustomBondForce to compute the altered energies for them.

**Comment by smliu1997** [comment]
I see, thank you so much for your help!
