### ISSUE TITLE
Applying flat-bottom potential restraints

### ISSUE THREAD

**Issue by barmoral** [openmm/openmm#4581]
**Summary of the issue:**
Having trouble applying flat bottom potential constraints only to ions along the z-axis direction. Documentation not very clear.

**Context:**
- I have performed a calculation in gromacs applying flat-bottom potentials, but would like for it to work in OpenMM as well. 
- I have written a [code/notebook](https://github.com/barmoral/OpenMM_SPW/blob/main/SPW_MD.ipynb) that minimizes, equilibrates, and does a production run of my system using OpenMM without constraints. I have not been able to add constraints that work. Here is my github repository ["SPW_openMM"](https://github.com/barmoral/OpenMM_SPW) for reference.

**Attachment:**
I am attaching a figure to visually represent how I would like the flat-bottom potentials to work.
![FBP_rep_lq](https://github.com/openmm/openmm/assets/103068766/0a2a80a8-cd2e-496c-a940-d77a973297c8)

**Flat-bottom Potential equation:** 
- k = 4184 kJ/mol/nm^(2)
- r = 2.4 nm (the distance from reference position, which should be z = 7.2 nm )

**Comment by peastman** [comment]
[This example](http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#applying-an-external-force-to-particles-a-spherical-container) in the manual is almost exactly what you want.  The only difference is that it applies a spherical potential based on all three coordinates.  You want it to depend only on z.  Something like this.

```python
force = CustomExternalForce('4184*max(0, r-2.4)^2; r=abs(z-7.2)')
```

**Comment by barmoral** [comment]
Hello, unfortunately this has not worked for me. Attached is a screenshot of the code cells I applied to create the restraints, and the animated gif of how my ions are looking afterwards. It is not obvious to me what I'm doing wrong. The complete code is still available in the link I posted with the first issue comment. 


![Screenshot from 2024-07-15 18-33-47](https://github.com/user-attachments/assets/d912fce6-6761-405c-8bd7-0898abdfde75)
![test_fbps](https://github.com/user-attachments/assets/80412185-304b-4403-a916-a3c465799ef0)

**Comment by peastman** [comment]
Can you explain what I should be seeing in the animation, and in what way it doesn't work?  Does the width of the black rectangle represent the restrained area (4.8 nm)?  I'm a bit confused, because I see particles jumping back and forth as if you were applying periodic boundary conditions, but the restraint you applied seems to be intended for a nonperiodic system.

**Comment by barmoral** [comment]
The black rectangle is my full box, I just deleted the waters to make the problem clearer. I now attach animations of what I would expect to be seeing but I'm not getting. I'll double check my PBC settings to see if that fixes the problem, but would appreciate any other guidance.

![sim_working_full](https://github.com/user-attachments/assets/73ba3bfc-9740-4b7e-a835-731b22ae05d9)
![sim_working_ions](https://github.com/user-attachments/assets/449d5d4f-7ee3-457f-bbc3-6313b5d05698)

**Comment by peastman** [comment]
If I understand correctly, the vertical axis on your image is the direction in which the restraint is supposed to be applied?  And you expected the particles to be limited to a band in that direction, rather than filling the whole box?

Try putting the restraint force in its own force group.  For example,

```python
fb_force.setForceGroup(1)
```

Now you can query its forces and energy separately to see if they're what you expect.  For example,

```python
state = context.getState(getForces=True, getEnergy=True, groups={1})
forces = state.getForces()
```

You can check if the forces on atoms are what you expect them to be.  See https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Analyzing%20Energy%20Contributions.html for more information.

**Comment by barmoral** [comment]
I found the problem. I was visualizing my pdb and dcd files usng Ovito, which seems to have trouble reading these trajectory files (with ions at least...). The code is working fine and the simulation is running as expected when visualized in VMD and pymol. 
Thank you so much for the help!

 
![openmmspw](https://github.com/user-attachments/assets/96646060-590d-4152-aaa7-67a4342549db)
