### ISSUE TITLE
OpenMM H5MDReporter?

### ISSUE THREAD

**Issue by hmacdope** [openmm/openmm#4583]
Would there be interest in an H5MD reporter for OpenMM? Simple but effective format based on HDF5. 

It is well documented (https://www.nongnu.org/h5md/index.html, https://www.sciencedirect.com/science/article/abs/pii/S0010465514000447), used in several packages (LAMMPS, HOOMD, others) and supported by MDAnalysis.

It is also slated to be the next major format for GROMACS, replacing XTC/TNG (https://gitlab.com/gromacs/gromacs/-/issues/5016) and to be the dominant format for the MDDB project (https://gitlab.com/groups/gromacs/-/epics/5, https://mddbr.eu/). 

I would be happy to write the Reporter, but just thought I would canvas interest first (particularly from @peastman). It should be pretty easy with PyH5MD (https://github.com/pdebuyl/pyh5md).

**Comment by peastman** [comment]
I hadn't encountered that format before.  What are the advantages?  That is, when would we advise someone to use it instead of one of the existing formats?

**Comment by hmacdope** [comment]
There are a few advantages (as I see it). 

* Based on HDF5 format and fully extensible, you can store almost any data inside the H5MD file without breaking compliance. This allows you to store inputs, parameters and arbitrary reported data inside the file. This can make an H5MD file almost completely self describing, including with super fun applications like storing custom forcefields, free energy calculation parameters, etc etc.   Most other formats do not allow arbitrary data storage.
* Based on HDF5 means high performance IO available and validated (in multiple languages), as well as ongoing community support for the format basics. Other formats like XTC and TNG, due to being developed within a specific package can come and go (we saw this with TNG). 
* Tunable compression, supporting any HDF5 compatible compression scheme,  meaning data resolution and size can be tuned for the requirements of the problem at hand. With DCD or XTC one must choose between either very large full precision coordinate files, or very lossy but compact XTC storage (somewhat tuneable). 
* Flexible storage of multiple groups of particle dependant data. You can store any one of coordinates, forces and velocities at any timestep. With DCD you can do the same (only at full precision), but XTC does not allow storage of forces or velocities alongside coordinates. 
*  Self plug but HDF5 based formats are stream-able and shard-able, including over remote storage. MDAnalysis is doing [some work ](https://github.com/Becksteinlab/zarrtraj)in this space to enable remote streaming of trajectory files. 

Let me know your thoughts. :smile:

**Comment by peastman** [comment]
Those are theoretical advantages.  But in practice, when would we tell a user, "You should save your trajectory in this new format because it will work better than using any of the other formats?"

- A reporter in OpenMM isn't going to write arbitrary extensible data.  It will just save the same information about the trajectory that the other formats do.  So that isn't an advantage.
- DCD and XTC are not going to go away.  They're widely used and supported by all major analysis programs.  So that isn't an advantage.
- I can't imagine many users actually trying to fine tune the compression level, and I would advise them against it.  XTC is accurate enough for most purposes.  If someone has any doubt about whether it's accurate enough, my advice to them would be to save in full precision rather than risk finding afterward they didn't save enough precision.  So that isn't an advantage.
- A reporter in OpenMM isn't going to save different data at each timestep.  It will save exactly the same data at every timestep.  So that isn't an advantage.
- Other formats are also easily streamable and shardable.  So that isn't an advantage.

An analysis program needs to read all major formats to be sure people will be able to load their data, wherever it comes from.  A simulation engine only needs to write one format, as long as it's one that's widely supported by downstream tools.  Anything beyond that needs to have clear benefits to users to justify the extra code that needs to be maintained and, in this case, the need to introduce more dependencies.

**Comment by hmacdope** [comment]
That all makes a lot of sense! No worries, happy to shelve this.
