### ISSUE TITLE
Combining CustomNonbondedForce and CustomExternalForce gives wrong potential energy on OpenCL/CUDA

### ISSUE THREAD

**Issue by PhilippHoellmer** [openmm/openmm#4611]
Hi everyone,

I was combining a `CustomNonbonbdedForce` for a generalized Lennard-Jones potential with a `CustomExternalForce` for shifted Lennard-Jones walls in OpenMM 8.1.1. When I ran my code for a system of N=500 particles, I noticed that there is a huge difference (~300 kJ/mol) between the potential energy reported on the OpenCL platform and the CPU/Reference platforms.

Some interesting things that I learned already during debugging:
- The wrong potential comes from the `CustomExternalForce`. However, when I remove the `CustomNonbondedForce`, suddenly all platforms agree even though the `CustomExternalForce` is still computed.
- The disagreement appears to be influenced by the choice of the nonbonded cutoff method in the `CustomNonbondedForce`. OpenCL gives a wrong result for `CutoffPeriodic`, but the correct result for `CutoffNonPeriodic`.
- I observed the same issue on a CUDA platform on a Linux based machine.

I attached a smaller test Python script (in a zip file) that reproduces the issue on my Apple Silicon Mac for a single particle. It tests both nonbonded cutoff methods and the different platforms.  I get the following output (note that for this single particle, the third potential energy is 2.49 vs. 2.43 everywhere else and the force is also different) :
```
Results for cutoff 2 and platform Reference
2.4390506119428026 kJ/mol
[Vec3(x=0.27234126467738745, y=0.27234126467738745, z=0.27234126467738745)] kJ/(nm mol)
Results for cutoff 2 and platform CPU
2.4390506119428026 kJ/mol
[Vec3(x=0.27234126467738745, y=0.27234126467738745, z=0.27234126467738745)] kJ/(nm mol)
Results for cutoff 2 and platform OpenCL
2.4943385124206543 kJ/mol
[Vec3(x=0.0, y=0.0, z=0.0)] kJ/(nm mol)
Results for cutoff 1 and platform Reference
2.4390506119428026 kJ/mol
[Vec3(x=0.27234126467738745, y=0.27234126467738745, z=0.27234126467738745)] kJ/(nm mol)
Results for cutoff 1 and platform CPU
2.4390506119428026 kJ/mol
[Vec3(x=0.27234126467738745, y=0.27234126467738745, z=0.27234126467738745)] kJ/(nm mol)
Results for cutoff 1 and platform OpenCL
2.4390501976013184 kJ/mol
[Vec3(x=0.27234122157096863, y=0.27234122157096863, z=0.27234122157096863)] kJ/(nm mol)
```

If one removes the line `system.addForce(lennard_jones_force)`, suddenly all forces and potential energies agree.

[test.py.zip](https://github.com/user-attachments/files/16465641/test.py.zip)

**Comment by peastman** [comment]
Strange, I'm not seeing that.  Also running on an ARM Mac:

```
Results for cutoff 2 and platform Reference
2.4390506119428026 kJ/mol
[Vec3(x=0.27234126467738745, y=0.27234126467738745, z=0.27234126467738745)] kJ/(nm mol)
Results for cutoff 2 and platform CPU
2.4390506119428026 kJ/mol
[Vec3(x=0.27234126467738745, y=0.27234126467738745, z=0.27234126467738745)] kJ/(nm mol)
Results for cutoff 2 and platform OpenCL
2.4390501976013184 kJ/mol
[Vec3(x=0.27234122157096863, y=0.27234122157096863, z=0.27234122157096863)] kJ/(nm mol)
```

OpenCL agrees with the other platforms.

Though I don't think it's related, can you try upgrading to 8.1.2?  Just to be absolutely sure that isn't the difference.

**Comment by PhilippHoellmer** [comment]
Thanks for your quick reply.

I noticed that I sent the test file where I commented out `system.addForce(lennard_jones_force)` in line 69. In this case, the results agree for the different platforms. When I put that line back in, the results start to disagree.

What happens for you if you put line 69 back in?

I also tried upgrading to 8.1.2 and the disagreeing result in OpenCL is still there. I'm installing OpenMM with conda by the way, and `python -m openmm.testInstallation` says that everything is working fine.

**Comment by peastman** [comment]
Adding that line in I now get a difference.  I'll investigate.

**Comment by peastman** [comment]
It comes from the handling of periodic boundary conditions, which turns out to be a really complicated subject.  When you simulate a periodic system, the OpenCL and CUDA platforms internally translate all molecules into a single periodic box (coordinates between 0 and box_width).  That's done to maintain accuracy, since they're working in single precision.

When you add a CustomNonbondedForce and set its nonbonded method to CutoffPeriodic, you're telling OpenMM that you're simulating a periodic system.  For example, it causes `system.usesPeriodicBoundaryConditions()` to return true.  Positions are only defined up to a translation by box vectors.  You set the coordinates to -3.29629, but internally they're stored as 96.7037.

But then you also add a CustomExternalForce that depends on the absolute coordinates, including which box they're in.  Those coordinates give different results.

In the expression for your CustomExternalForce, replace `abs(x)` with `periodicdistance(x, 0, 0, 0, 0, 0)`.  That's the same thing (the absolute distance from the origin along the x axis), except taking periodic boundary conditions into account.

**Comment by PhilippHoellmer** [comment]
I see, that makes perfect sense. And I just realized that I vaguely remember reading about that in the documentation of the `CustomExternalForce`.  Thank you so much for clearing this up! I'll close this issue now.
