### ISSUE TITLE
System creation failure for deprotonated lysine

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#462]
OpenMM fails to build the System for some unconventional amino acids.

```
pdb = PDBFile(sys.argv[1])
ff = ForceField('amber99sb.xml', 'tip3p.xml')
system = ff.createSystem(pdb.topology)

Traceback (most recent call last):
  File "../HIP/min.py", line 31, in <module>
    system = ff.createSystem(pdb.topology)
  File "/home/leeping/local/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 333, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (ACE).  The set of atoms matches ACE, but the bonds are different.  Perhaps the chain is missing a terminal group?
```

The PDB in question is here: https://www.dropbox.com/s/j75p39mrplwhe4p/ace-LYN-nme.pdb

The same error occurs for protonated aspartic acid (ASH) and glutamic acid (GLH), as well as deprotonated cysteine (CYM).

**Comment by jchodera** [comment]
It seems like this might still need some sort of fix, such as the addition of standard bond perception for deprotonated lysine.  Maybe this can be marked `bug`?

**Comment by Astrovicis** [comment]
This is happening quite often for me. Eagerly awaiting a solution 😉

**Comment by jchodera** [comment]
@Astrovicis : Which force field(s) are you attempting to use, out of curiosity?

**Comment by jchodera** [comment]
It looks like `amber14/protein.ff14SB.xml` supports [deprotonated lysine (LYN)](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/data/amber14/protein.ff14SB.xml#L631-L675), but the [`residues.xml`](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/data/residues.xml) lacks a definition for this amino acid variant.

@peastman: What do you think about adding these protonation state variants to `residues.xml`? The PDB standard says that `CONECT` records are ["only mandatory for HET groups (excluding water) and for other bonds not specified in the standard residue connectivity table"](https://www.wwpdb.org/documentation/file-format-content/format33/sect10.html). Since the [definition of HET residues](http://www.wwpdb.org/documentation/file-format-content/format33/sect4.html) is vague, it could be interpreted as suggesting that standard amino acid variants / protonation states should be considered as not requiring `CONECT` residues.

@Astrovicis : As a workaround, you can add `CONECT` records to your PDB file.

**Comment by peastman** [comment]
What name does the residue have in the PDB file?  If it has the standard name LYS, the PDB loader should handle it correctly even if one atom is missing.  If the force field then has an appropriate template, it should work.  On the other hand, if you've given it a nonstandard name, there's no way the PDB loader can know what it's supposed to be.

> Since the definition of HET residues is vague, it could be interpreted as suggesting that standard amino acid variants / protonation states should be considered as not requiring CONECT residues.

The definition is pretty clear.  The chemical component dictionary defines exactly what atoms are expected to be present in each standard residue.  Missing atoms are tolerated, but the addition of any atom not present in the standard residue definition is not allowed.

**Comment by jchodera** [comment]
> The definition is pretty clear. The chemical component dictionary defines exactly what atoms are expected to be present in each standard residue. Missing atoms are tolerated, but the addition of any atom not present in the standard residue definition is not allowed.


That's not quite correct. The chemical component dictionary for [`HIS`](http://ligand-expo.rcsb.org/pyapps/ldHandler.py?formid=cc-index-search&target=his&operation=ccid), for example, includes [atom names](http://ligand-expo.rcsb.org/pyapps/ldHandler.py?formid=cc-index-search&target=his&operation=ccid) for both delta and epsilon protons and the C-terminal carboxylic acid hydrogen, but it does not include a third amino terminal proton needed if HIS were to appear at the N-terminus of a protein. And yet, despite this, [we include this third amino-terminal proton in `residues.xml`](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/data/residues.xml#L508).

**Comment by jchodera** [comment]
But @peastman has a good point: Replacing nonstandard amino acid names (`LYN`) with standard ones (`LYS`) in your PDB file will allow examples like [this](https://github.com/openmm/openmm/issues/462#issue-34239541) to work!
