### ISSUE TITLE
isopeptide patch

### ISSUE THREAD

**Issue by samcphee** [openmm/openmm#4702]
I am trying make an isopeptide bond between an N-terminal Gly and Glu side chain in the protein.ff14SB.xml forcefield. I added the following to the xml file based on the examples in documentation for disulfide and nter:

```
 <Patches>
    <Patch name="isopeptide" residues="2">
	  <RemoveAtom name="1:H2"/>
	  <RemoveAtom name="1:H3"/>
	  <RemoveAtom name="2:OE2"/>
	  <RemoveBond atomName1="1:N" atomName2="1:H2"/>
	  <RemoveBond atomName1="1:N" atomName2="1:H3"/>
	  <RemoveBond atomName1="2:CD" atomName2="2:OE2"/>
	  <AddBond atomName1="1:N" atomName2="2:CD"/>
	  <ApplyToResidue name="1:GLY"/>
	  <ApplyToResidue name="2:GLU"/>
    </Patch>
  </Patches>
```

I also tried the above with NGLY, but I still get the same failure at the add hydrogen step, using a state from the 1pp5.pdb, which has a conect between atoms.

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

pdb = PDBFile("1pp5_0001.pdb")
# Specify the forcefield
forcefield = ForceField('amber14-all.xml', 'protein.ff14SBi.xml', 'amber14/tip3pfb.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.deleteWater()
residues=modeller.addHydrogens(forcefield)
```

ValueError: No template found for residue 1 (GLY).  The set of atoms matches NGLY, but the bonds are different.  Perhaps the chain is missing a terminal group?

Am I implementing the patch correctly? 

(Alternative suggestions are also welcome if this isn't the best way to accomplish this.)

**Comment by peastman** [comment]
Can you post your PDB file?

**Comment by samcphee** [comment]
> Can you post your PDB file?

https://www.dropbox.com/scl/fi/nkz3x5qx5j1geulm3bh0m/1pp5_0001.pdb?rlkey=s1n2q4we6u0rxxxk74jxhvmfo&st=efu9mq2b&dl=0

Thank you.

**Comment by peastman** [comment]
There are a few different problems.

`addHydrogens()` doesn't use the ForceField in deciding what hydrogens to add.  It adds them according to the standard rules, then uses the ForceField to energy minimize them and select good positions.  Since GLY1 is an N-terminal residue, it adds the standard hydrogens expected in an N-terminal residue: three hydrogens on the nitrogen.  That doesn't match your template.

You need to prevent it from adding them.  OpenMM 8.2 has a new feature that you can use the `variants` argument to tell it exactly what hydrogens to add:

```python
variants = [None]*pdb.topology.getNumResidues()
variants[0] = [('HA2', 'CA'), ('HA3', 'CA'), ('H', 'N')]
residues=modeller.addHydrogens(forcefield, variants=variants)
```

We just posted a release candidate of 8.2.  See https://github.com/openmm/openmm/issues/4659#issuecomment-2434177337 for instructions on installing it.

The next problem is with the definition of the patch.  You tell it to base it on the GLY template:

```xml
<ApplyToResidue name="1:GLY"/>
```

But then you tell it to remove the H2 and H3 atoms from the template.  If you look at the GLY template, you'll see it doesn't have H2 or H3 atoms.  So the patch is invalid and can't be applied.

Probably you meant to base it on NGLY instead?  But you don't really need a patch for that residue.  If you take NGLY, remove the two extra hydrogens, and add a bond connecting the nitrogen to another residue, you end up with the standard GLY template.  It will never even try to use the patch, because it already succeeds in matching that residue to a template.  And that's fine.  You aren't changing any atom types, so let it match the standard GLY template.  All you need is a single-residue patch (or a template) for the GLU.

One other problem is with GLY21.  It's a C-terminal residue, but it's missing the OXT atom.  It won't match any template.

**Comment by samcphee** [comment]
> There are a few different problems.
> 
> `addHydrogens()` doesn't use the ForceField in deciding what hydrogens to add. It adds them according to the standard rules, then uses the ForceField to energy minimize them and select good positions. Since GLY1 is an N-terminal residue, it adds the standard hydrogens expected in an N-terminal residue: three hydrogens on the nitrogen. That doesn't match your template.
> 
> You need to prevent it from adding them. OpenMM 8.2 has a new feature that you can use the `variants` argument to tell it exactly what hydrogens to add:
> 
> ```python
> variants = [None]*pdb.topology.getNumResidues()
> variants[0] = [('HA2', 'CA'), ('HA3', 'CA'), ('H', 'N')]
> residues=modeller.addHydrogens(forcefield, variants=variants)
> ```
> 
> We just posted a release candidate of 8.2. See [#4659 (comment)](https://github.com/openmm/openmm/issues/4659#issuecomment-2434177337) for instructions on installing it.
> 
> The next problem is with the definition of the patch. You tell it to base it on the GLY template:
> 
> ```
> <ApplyToResidue name="1:GLY"/>
> ```
> 
> But then you tell it to remove the H2 and H3 atoms from the template. If you look at the GLY template, you'll see it doesn't have H2 or H3 atoms. So the patch is invalid and can't be applied.
> 
> Probably you meant to base it on NGLY instead? But you don't really need a patch for that residue. If you take NGLY, remove the two extra hydrogens, and add a bond connecting the nitrogen to another residue, you end up with the standard GLY template. It will never even try to use the patch, because it already succeeds in matching that residue to a template. And that's fine. You aren't changing any atom types, so let it match the standard GLY template. All you need is a single-residue patch (or a template) for the GLU.
> 
> One other problem is with GLY21. It's a C-terminal residue, but it's missing the OXT atom. It won't match any template.

Excellent - thank you I got the patch working!

**Comment by peastman** [comment]
Great!  Is it ok to close this issue?

**Comment by samcphee** [comment]
Yes, I appreciate your help with this.
