### ISSUE TITLE
Offsets performance question

### ISSUE THREAD

**Issue by WillGPoole** [openmm/openmm#4737]
Hey I was having a go at implementing my ideas using offset parameters thanks to #4732. In doing so I've noticed something with the performance of Offsets - I cant work out whether it's expected or not. 

I have set up 4 systems (2741 atoms):
1) Vanilla system, everything via `NonbondedForce`
2) Vanilla system with Offsets with `chargeScale`, `sigmaScale`, and `epsilonScale` all equal to 0 
3) A softcored LJ via `CustomNonbondedForce` and PME electrostatics in the original `NonbondedForce`
4) Softcored LJ, PME electrostatics with offsets in original `NonbondedForce` with `chargeScale`, `sigmaScale`, `epsilonScale` all equal to 0 

When adding offsets, it is for 13 atoms.

I then ran 750,000 steps of MD on GPU (RTX 3090) and these are the timings (they are fairly consistent between repeats): 
1) 87 s
2) 90 s
3) 84 s
4) 105 s

The difference between  1 and 2 makes sense, a mere 3s for offsets seems fine (although I have a suggestion below). 

Splitting the forces into a `CustomNonbondedForce` and `NonbondedForce` seems to actually gain a small amount of time (3 and 1)

Now the strange one is the difference between 4 and 3. If it was 3 seconds between 1 and 2, I'd expect similar for 3 and 4 but it has ended up 20 seconds slower. 

For this test case, I have kept all three Scales in the offsets as zero. For me, in a larger system, I envision having some atoms with the scales=0 and some with the scales as `-charge, 0, 0`, and this will change dynamically, hence #4732. One performance improvement could be to ignore offsets where all three of the scales=0. That should make 2 and 1 identical when all offsets are zero. 

Data for 3,750,000 steps (seconds):
1) 441 2) 453 3) 420 4) 528 

I've attached a zip folder with a notebook for this one as it is a bit chunky. 

 
[MWE_offsets.zip](https://github.com/user-attachments/files/17894480/MWE_offsets.zip)

Thanks again.

**Comment by peastman** [comment]
If I specify `{'DisablePmeStream':'true'}` when creating the Simulation, the effect goes away.  Not that you want to do that: it becomes slower in all cases.  But the pattern is much simpler.  Adding offsets slows it down by a little bit, using the softcore force slows it down by a larger amount, and there's no interaction between them.

I think something along these lines is happening.  The softcore force is more expensive to compute than the standard LJ force, so that slows it down.  But it can mask the effect because it's doing work on two different streams in parallel (one for direct space, one for reciprocal space).  Even though more work gets done in total, it gets parallelized effectively in a way that leads to very little change in total time.

When you add offsets, that requires extra synchronization between the two streams.  It needs to make sure the charges have all been computed before the PME stream can start on charge spreading.  It can no longer hide the extra work as effectively, leading to a larger increase in total time.

**Comment by WillGPoole** [comment]
Ah interesting and makes sense. Realistically I guess this is just the price to pay for the added flexibility. Am I right in thinking that the offsets are calculated at each force evaluation then? Is there something in being able to calculate the offset once and then using that until they are changed? I think I might have gone full circle here and just described `perParticleParameters`..! 

In any case, the speed up using a global parameter versus `updateParametersinContext` is still significant once you pass a certain number of calls. Or in otherwords if you only need to `updateParametersinContext` a few times then that is faster, but if you need to do it a lot more, then the extra time taken to calculate the Offsets is negligible in comparison. 

Happy to close this if you are. Thanks for your help again.

**Comment by peastman** [comment]
Correct, the calculation is run at every step even if the global parameter hasn't changed.  That's done because it calculates the Ewald self energy at the same time it's calculating the charges.
