### ISSUE TITLE
Benchmark large systems

### ISSUE THREAD

**Issue by ChayaSt** [openmm/openmm#753]
I'm running a simulation with ~300,000 atoms so I bench-marked the speed across 3 NVDIA GTX Titan GPUs. Here are the results. 

https://github.com/choderalab/gpcr-simulation/blob/master/beta2_2rh1/Weinstein/ddm/benchmark/Titan_benchmark.png

**Comment by jchodera** [comment]
@ChayaSt: Can you re-post those files?

**Comment by ChayaSt** [comment]
The files now live here:
https://github.com/choderalab/gpcr-simulation/tree/master/Weinstein/bdm/benchmark

However, the repository is private. I can give @peastman access.

**Comment by peastman** [comment]
I still can't access it.

**Comment by ChayaSt** [comment]
Here it is. I gave you access (it's a private repository)

https://github.com/ChayaSt/Benchmark_OMM

**Comment by jchodera** [comment]
Sorry about this, @peastman!  I think @ChayaSt has given you access now.

We unfortunately can't make those structures public because we did not generate them ourselves, though we are working on generating some initial simulation models ourselves that will be public.

**Comment by peastman** [comment]
Where do these imports come from?

```Python
# ParmEd Imports
from chemistry.charmm.openmmloader import (OpenMMCharmmPsfFile as CharmmPsfFile,
OpenMMCharmmCrdFile as CharmmCrdFile)
from chemistry.charmm.parameters import CharmmParameterSet
from chemistry.amber.openmmreporters import (
AmberStateDataReporter as AKMAStateDataReporter)
```

Contrary to the comment, those aren't part of ParmEd.  Its top level module is called "parmed", and as far as I can tell it doesn't contain any module called "chemistry" anywhere.

**Comment by jchodera** [comment]
Those are from an earlier version of ParmEd, when @swails had called the top-level import `chemistry`.  Now I think you need to change these to `parmed.chemistry`.

**Comment by peastman** [comment]
No such module.  And while there is a `parmed.charmm` module, it doesn't contain anything called `openmmloader`.  Likewise, there's a `parmed.amber` module, but it doesn't contain anything called `openmmreporters`.

**Comment by swails** [comment]
That was part of a large reorganization.  The `openmmloader` module is gone now.  `openmmreporters` is `parmed.openmm.reporters`.  And you change `chemistry` to `parmed`, not `parmed.chemistry`.

Here are the needed changes:

```Python
from parmed.charmm import CharmmPsfFile, CharmmCrdFile
from parmed.charmm.parameters import CharmmParameterSet
from parmed.openmm.reporters import StateDataReporter
```

**Comment by peastman** [comment]
Thanks!  That works.

Having made that change, it now fails with the following error:

```
Traceback (most recent call last):
  File "benchmark.py", line 23, in <module>
    twoRH1_crds = app.PDBFile('../pdb_files/2RH1_ddm_equal_output.pdb')
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/app/pdbfile.py", line 82, in __init__
    pdb = PdbStructure(inputfile, load_all_models=True)
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/app/internal/pdbstructure.py", line 146, in __init__
    self._load(input_stream)
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/app/internal/pdbstructure.py", line 183, in _load
    self._periodic_box_vectors = computePeriodicBoxVectors(a_length, b_length, c_length, alpha, beta, gamma)
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/app/internal/unitcell.py", line 77, in computePeriodicBoxVectors
    c = c - b*round(c[1]/b[1])
ZeroDivisionError: float division by zero
```

And looking at the PDB file it's loading, sure enough I see

```
CRYST1    0.000    0.000    0.000  90.00  90.00  90.00 P 1           1 
```

which is clearly not correct.  For the moment I'll try just deleting that line from the PDB, since it looks like the script computes its own box size anyway.

**Comment by jchodera** [comment]
Sorry about that!  I don't think @ChayaSt has touched these files in a long time.

**Comment by peastman** [comment]
The next error I got stock on was that CharmmPsfFile no longer has a`setBox()` method.  After a fair amount of experimenting, I figured out the correct replacement was

```Python
from simtk.openmm.app.internal.unitcell import computeLengthsAndAngles
box = computeLengthsAndAngles((mm.Vec3((max_crds[0]-min_crds[0]).value_in_unit(u.nanometers), 0, 0),
                               mm.Vec3(0, (max_crds[1]-min_crds[1]).value_in_unit(u.nanometers), 0),
                               mm.Vec3(0, 0, (max_crds[2]-min_crds[2]).value_in_unit(u.nanometers)))
)
twoRH1_solv.box = (box[0]*10, box[1]*10, box[2]*10, box[3]*180/math.pi, box[4]*180/math.pi, box[5]*180/math.pi)
```

But now I get yet another error:

```
Traceback (most recent call last):
  File "benchmark.py", line 79, in <module>
    sim.context.loadCheckpoint(f.read())
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/openmm.py", line 15917, in loadCheckpoint
    return _openmm.Context_loadCheckpoint(self, *args)
Exception: Checkpoint was created with a different version of OpenMM
```

Is the checkpoint actually needed?  Can I skip that and just run from the coordinates in the PDB file?

**Comment by jchodera** [comment]
> Is the checkpoint actually needed? Can I skip that and just run from the coordinates in the PDB file?

I'm not sure, but maybe it's worth a try?

@ChayaSt: Can you chime in here?

**Comment by peastman** [comment]
I managed to get it running.  Here's one easy way to speed it up a little bit: decrease the cutoff from 1 nm to 0.9 nm.  On my computer, that increased the speed from 4.83 to 5.26 ns/day.  Going to 0.85 nm speeds it up even a little bit more, to 5.4 ns/day.

This system has about 12.2 times as many atoms as DHFR, so if the performance scaled exactly linearly, we'd expect DHFR to get about 64 ns/day.  In fact it's closer to twice that.  Of course, the PME reciprocal calculation actually scales as n*log(n), so we don't expect it to be quite linear, but it should be pretty close.  Also, you're using mixed precision rather than single.  That will slow it down a little bit, but not a lot.

I suspect most of the difference comes from the fact that your system contains a large amount of lipids.  Those tend to be slower to simulate.  Our nonbonded algorithm depends on atoms that are close together in sequence also being close together in space.  For proteins, that's naturally true because they're so tightly packed.  For water, we can make it true by reordering the molecules.  But lipids are a problem.  They have long chains that stick out roughly in a straight line.  That makes the blocks of consecutive atoms less compact, so we end up having to evaluate more interactions.

**Comment by ChayaSt** [comment]
Thanks!

Sorry about that. I haven't touched these scripts since I posted them.

In addition to it being slow, it also doesn't scale linearly when I run it on 3 GPUs. 

https://github.com/ChayaSt/Benchmark_OMM/blob/master/benchmark/Titan_benchmark.png

**Comment by jchodera** [comment]
We certainly can't expect it to scale linearly with the number of GPUs,
especially on a standard PCIe3 bus without multi-way SLI.  Forthcoming
NVIDIA cards I think are supposed to have better ability to directly access
memory on other cards, so there can be potential scalability improvements
in the future.

Mostly, we were hoping that some observations might help us tune things for
this system or inspire future speedups.  The Nonbonded algorithm
observation isn't something I had previously appreciated!

**Comment by peastman** [comment]
I'm hoping to improve the scaling on multiple GPUs a little bit more.  One thing that's critical, though, is that all the GPUs be able to communicate through peer-to-peer.  That depends on the design of your PCIe bus, and doing it with more than two GPUs is usually only possible on high end motherboards.
