### ISSUE TITLE
Maximum run time and EXIT file trigger

### ISSUE THREAD

**Issue by OndrejMarsalek** [openmm/openmm#769]
I would like to add to the Python Simulation object the ability to save a checkpoint and exit if either a specified run time is reached or a specific file exists in the working directory (which can be used as a trigger for a clean exit, usually named EXIT). Do people have existing solutions that can be added to the repository? If not, I would like to offer my own implementation using a Reporter that performs the check and sets a flag in Simulation that breaks the main loop.

**Comment by swails** [comment]
This can be particularly useful when running via schedulers.  I'd like to propose an alternative to the reporter idea though.  The current `Simulation.step` effectively does this in pseudocode(.py):

```Python
for step in range(numSteps//10):
    integrator.step(10)
```

It seems that what you want is a while loop rather than a for loop:

```Python
while condition:
    integrator.step(10)
```

To me, this could be a `step_until` method on the `Simulation` object that may look something like this:

```Python
class Simulation(object):
    ... code

    def step(numSteps):
        ... code

    def step_until(conditional, step_size=10):
        while conditional():
            integrator.step(step_size)
            ... do reporter stuff
```

Of course, you could always subclass `Simulation` and implement it yourself for the time being, but it would be an interesting feature to discuss.  This way, the conditional could be anything -- a time-based criteria, the existence of a file, the progress of a different process you have an open socket with, user-input, ... etc.

You could of course do this with a Reporter if you were satisfied with giving reporters the ability to modify the `Simulation` object, but that behavior seems a bit counterintuitive to me.

**Comment by peastman** [comment]
This was partly addressed by adding Simulation.runForClockTime().

**Comment by OndrejMarsalek** [comment]
That looks nice. Do you think that adding a check for the existence of an EXIT file would be reasonable, or is it a potential performance issue? I think it would be enough to check only as often as reporters run (which likely perform I/O anyway), not every 10 steps like for ctrl-c.

A simple

```
if os.path.exists('EXIT'):
    os.remove('EXIT')
    return
```

somewhere close to the loop with 10-step blocks should be enough. There could also be a keword argument `fn_exit` defaulting to `None`, i.e. do not check.

**Comment by jchodera** [comment]
Couldn't you add your own `ExitFileWatcher` reporter that does this?

**Comment by swails** [comment]
> Couldn't you add your own ExitFileWatcher reporter that does this?

Awkwardly.  That reporter would need to raise an exception that you would have to catch.  That's the only way to *force* `Simulation.step` or `Simulation.runForClockTime` to end.

**Comment by swails** [comment]
> That looks nice. Do you think that adding a check for the existence of an EXIT file would be reasonable, or is it a potential performance issue? I think it would be enough to check only as often as reporters run (which likely perform I/O anyway), not every 10 steps like for ctrl-c.
> 
> A simple
> 
```
> if os.path.exists('EXIT'):
>     os.remove('EXIT')
>     return
```
> somewhere close to the loop with 10-step blocks should be enough. There could also be a keword argument fn_exit defaulting to None, i.e. do not check.

Ehh...  This seems super error-prone.  This file becomes visible to *all* processes (which means if you have two simulations you've accidentally set up to look for the same EXIT file, then the behavior becomes a race condition unless you take out the `os.remove` statement).  And it comes with all of the problems of a filesystem (symlinks, permissions, collisions, ... etc.)

It would be better to have some kind of per-process control (perhaps using sockets or signals).  In fact, you can implement this directly using signals, and commandeer one of the signals (like `SIGUSR1` or `SIGUSR2`) to do this for you.  Then send that signal to your process (not sure exactly how this would be done, but I'm sure Google could fill you in) externally somehow (basically, anything you would use to create the exit file, use that to send the process a signal instead).

I'd personally rather not see this kind of functionality added to OpenMM since it seems a bit awkward and unreliable, but you can always use @jchodera's suggestion and create an `ExitFileWatcher` that uses some kind of exception subclass for control flow.

**Comment by OndrejMarsalek** [comment]
I am not particularly attached to the mechanism. I just found it useful in other programs and thought I could use it in OpenMM as well. Of course if you run multiple simulations in the same directory, this is a potential problem. I think the keyword here is *optional* - if you don't specify an exit file name, nothing happens.

The signal mechanism is certainly another possibility, although it is usually more convenient to touch a file than to send a signal.

In any case, I have no strong preference for having this, so if nobody else does, either, I would be happy to close the ticket. The maximum run time is already in and that is no doubt a more important feature.

**Comment by swails** [comment]
What about @jchodera's suggestion?  That way you could implement whatever you want.  It could look something like this:

```Python
# exitreporter.py
import os
class StopSimulation(Exception):
    """ Exception raised in order to stop simulation """
    pass

class ExitFileReporter(object):
    """ Exits a Simulation by raising StopSimulation if an exit file exists """
    def __init__(self, filename, reportInterval, checkpointFile):
        self.filename = filename
        self.reportInterval = reportInterval
        self.checkpointFile = checkpointFile

    def describeNextReport(self, simulation):
        steps_left = simulation.currentStep % self.reportInterval
        steps = self.reportInterval = steps_left
        return (steps, False, False, False, False)

    def report(self, simulation, state):
        if os.path.exists(self.filename):
            # Remove exit file? Sounds like possible race condition; check for permissions?
            os.unlink(self.filename)
            with open(self.checkpointFile, 'wb') as f:
                f.write(simulation.context.createCheckpoint())
            raise StopSimulation()

    def finalize(self):
        """ Nothing to do, except maybe remove the exit file? """
        pass
```

Then all you have to do is something like this:

```Python
import exitreporter

# Set up your OpenMM simulation here

simulation.reporters.append(exitreporter.ExitFileReporter('EXIT', 1000, 'checkpoint'))

try:
    simulation.runForClockTime(8760) # Set run time for 1 year
except exitreporter.StopSimulation:
    # Checkpoint will already have been written by the reporter
    do_whatever_you_want()
```

**Comment by swails** [comment]
The signal approach can also be done externally from OpenMM proper.  I think the following should work, though it is untested:

```Python
from simtk.unit import *
from simtk.openmm import *
from simtk.openmm.app import *

# Set up your simulation, but don't start it yet

import signal

def exit_signal_handler(signum, stack_frame):
    global simulation, checkpointFile
    with open(checkpointFile, 'wb') as f:
        f.write(simulation.context.createCheckpoint())

signal.signal(signal.SIGUSR1, exit_signal_handler)

# Now run your simulation for ... idk, 1 year?
simulation.runForClockTime(1*year)
```

Then, instead of `touch EXIT`, use the command `kill -s USR1 <process>` (you can get `<process>` via `ps -edf | grep <scriptname>` or any other convenient method; like `top`, perhaps).  It's a little more work than using the exit file (since you need to figure out the process number, although that's not hard if you send the process to the background; see below).  But it does give you much finer-grained control over the exit behavior of individual running scripts.


As a demonstration, I wrote the following Python script:

```Python
# busywaiter.py

import signal, time

def handler(signum, stack):
    print('Caught signal! Doing whatever I want...')

signal.signal(signal.SIGUSR1, handler)

while True:
    time.sleep(1)

print('Careful though! This is not run! You need to do everything in handler')
```

Then I run it (in the background), and send `SIGUSR1` to it:

```
swails@batman ~ $ python busywaiter.py &
[2] 22922  # <<--- This is the PID!
swails@batman ~ $ kill -s USR1 22922
Caught signal! Doing whatever I want...
```

**Comment by jchodera** [comment]
Cool!
