### ISSUE TITLE
List of currently supported GPUs?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#849]
Do we maintain a list of "currently supported GPUs" where OpenMM is known to run correctly on?

**Comment by peastman** [comment]
We have never intentionally dropped support for a GPU.  New features may sometimes require newer hardware, but old features should continue to work on any hardware they used to work on.  If they don't that's a bug.

A separate question is what hardware we actually test on, since there have been many dozens (maybe hundreds?) of GPUs released over the past 7 years or so.  Obviously we can only test on a handful of them, and mostly only fairly recent ones.  So while in theory the OpenCL platform should still work on your ancient G80, it wouldn't surprise me at all if problems came up.

**Comment by VijayPande** [comment]
While this is true in a theoretical sense, in a practical sense (i.e. for calculations most researchers run), there are some GPUs which are not supported.

Peter:  Maybe we should describe this in terms of Cuda compute level requirements for GPUs to be able to run the JAC Benchmark?

**Comment by peastman** [comment]
On the OpenCL platform, the only thing that requires a slightly more recent GPU (Fermi) is CustomManyParticleForce.  The CUDA platform requires G200 as a base level, but I think pretty much everything works on that.  Those are GPUs so old that Nvidia doesn't even list them on its main "CUDA compatible GPUs" page anymore.  So I think it's quite reasonable to say we support everything listed on that page.

**Comment by jchodera** [comment]
Could we put together a page that explicitly states this and provides a
link to the nvidia page? I was asked this question a bunch of times at CUP.

Vertex, for example, has M2050s....

J

**Comment by peastman** [comment]
We already link to it from the download page.  And given how long it's been since we tested on the even older GPUs, I think it's fine to just say those are the ones we support and leave it at that.  If someone tries an older GPU there's a good chance it will work, but we shouldn't make any promises about it.

We also link to the corresponding page for AMD GPUs.
