### ISSUE TITLE
Bitwise-reversible integrators: Implement fix(x,nbits) operation for CustomIntegrator?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#916]
We're looking into experimenting with bitwise-reversible integrators:
https://qed.princeton.edu/main/User:Hammett/physics_notes/Time_Reversible_Algorithms

The fundamental operation required here is a `fix(x)` operation, where we fix implements a rounding operation that rounds the argument to a certain number of bits of precision.  See [this page](https://qed.princeton.edu/main/User:Hammett/physics_notes/Time_Reversible_Algorithms) for more detail on the implementation of `fix(x)`.

I wonder if it might be it might be useful to consider implementing a `fix(x,nbits)` operation in Lepton to allow these bitwise-reversible integrators to be easily implemented via `CustomIntegrator`.  (I believe the suggested implementation requires a "round to nearest integer" operation which means it is not possible to implement with the current available functions.)

**Comment by peastman** [comment]
floor(x*scale+0.5)/scale, where scale should be a power of 2.

**Comment by jchodera** [comment]
Will test this out---I was worried that this might have numerical issues if we're operating at close to the number of bits in the mantissa, but this should work fine (I think?) if we're in `mixed` or `double` precision on the GPU, right?

**Comment by peastman** [comment]
It should be fine as long as you're cutting off at least 2 bits at the end.  Possibly 1 would be OK too, but I'm not certain of that.

You're not going to get something meaningful out of this unless you're rounding to a number of bits that are guaranteed to be deterministic.  That's true whatever precision mode you're in.  If the last 5 bits vary from one force evaluation to another, you'd better be cutting off at least 5 bits.  Otherwise, your results still won't be reversible.

**Comment by jchodera** [comment]
> You're not going to get something meaningful out of this unless you're rounding to a number of bits that are guaranteed to be deterministic. That's true whatever precision mode you're in. If the last 5 bits vary from one force evaluation to another, you'd better be cutting off at least 5 bits. Otherwise, your results still won't be reversible.

You noted all platforms but CUDA should yield deterministic forces, so we should be OK experimenting with Reference, CPU, and OpenCL, yes?

Thanks again!  I'll give this a try and report back.

**Comment by peastman** [comment]
CPU isn't deterministic either.

**Comment by jchodera** [comment]
Attempted an initial stab at this:
https://github.com/choderalab/openmmtools/pull/65

**Comment by jchodera** [comment]
Actually, there is more information on how to implement this correctly in a patent filing (!!!) from DESRES:
https://www.google.com/patents/US7809535

**Comment by jchodera** [comment]
Note that the patent is full of typos, but the basic scheme seems to be:
```
v_h = v_0 + fix(0.5*dt*f/m)
x_1 = x_0 + fix(v_h*dt)
v_1 = v_h + fix(0.5*dt*f/m)
```
where the `fix(s)` operation truncates the quantity `s` to fixed-point arithmetic.

My own scheme was missing the `fix(...)` operation in the position update step, which was why I was concerned that it would accumulate additional digits of precision and quickly overwhelm the double-precision position and velocity accumulators for `mixed` or `double` precision modes.  However, I can't seem to get the method that uses `fix(...)` in that step to actually give bitwise-reversible trajectories when I use `floor(scale*s + 0.5)/scale` to perform this operation.  Could there be anything weird about how this particular way of truncating to fixed precision works that I'm overlooking?

**Comment by peastman** [comment]
Note that that's *precisely* equivalent to simply doing all your integration with fixed point values.  If the patent office actually grants it they have absolutely no clue what they're doing.  Oh right - they do have no clue what they're doing.  Sigh.

**Comment by jchodera** [comment]
I'm still having trouble here.  It seems that low-significance bits are sometimes randomly getting added to the double-precision positions and velocities that are retrieved from single-precision platforms, which is weird.  Still debugging.

**Comment by jchodera** [comment]
After more debugging, the differences I'm seeing between the forward and time-reversed positions look like this:
```
x1r  0 01111111101 0011000010010000000000000000000000000000000000000000
x0   0 01111111101 0011000010001111000000000000000000000000000000000000
```
It seems to me that this might be a rounding issue with the truncation step (currently `floor(scale*s + 0.5)/scale`).  The [Desres patent](https://www.google.com/patents/US7809535) makes reference to rounding in a way that breaks ties toward the even integer (in an integer representation of fixed point).  

Instead, `floor(scale*s + 0.5)/scale` breaks ties differently depending on whether the number is positive or negative, doesn't it?  Really we would want something like `sign(s) * floor(scale*abs(s) + 0.5)/scale)`, but I don't think `sign(x)` is available to Lepton, is it?

**Comment by swails** [comment]
> but I don't think sign(x) is available to Lepton, is it?

Easily derivable as `abs(x) / x` assuming `x` won't be zero.

**Comment by jchodera** [comment]
`x` can be zero.

**Comment by swails** [comment]
Then you can maybe throw in some `step` function to sidestep it?  I'd have to think about it and it's far too late for that right now.

**Comment by jchodera** [comment]
Might be easier to see if we can have a "truncate to fixed precision" operation added, since this could be useful.

**Comment by peastman** [comment]
We absolutely positively *cannot* implement anything based on a description in a patent, not unless they give us a license to it.  Even if we think it's a nonsense patent describing well known things.  Otherwise we're knowingly infringing it, which makes us responsible for triple damages.

If we didn't know this patent existed, we could reasonably implement the feature, given that it really just describes a set of standard techniques.  But now that we know it exists, we can't.  Even though it's nothing more than a set of standard techniques.  That's how our thoroughly messed up patent system works.

**Comment by jchodera** [comment]
I'm not asking that we implement the algorithm described in the patent; I'm asking that we add a `fix(x,nbits)` operation to Lepton that truncates the number of mantissa bits to `nbits`.  That is not the same thing as implementing the patent, which describes performing operations using integers.

**Comment by peastman** [comment]
That's not a decision you're qualified to make.  By law, *only* a patent lawyer is qualified to decide whether something infringes a patent or not.  You're asking for this feature because you read about it in a patent.  You want to use it to implement something closely related to what's described in the patent.  At this point, we legally only have two options:

1. Don't implement anything vaguely related to what you read in the patent.

2. Hire a patent lawyer to give us a written opinion on whether doing so would infringe the patent or not.

You probably think I'm getting carried away, but I'm not.  This is a very, *very* major problem in software development.  Our patent system is completely broken, and it creates major risks for anyone doing development.  At the companies I've worked for in the past, they brought in lawyers to give us training on how to safely navigate it, or at least as safely as possible.  It basically comes down to this rule:

*Do not ever read patents.*

Seriously.  If a patent is even tangentially related to anything you work on, *do not read it*.  Do not search for patents.  If you search for something else and a patent comes up in the results, do not click on the link.  As soon as you do, you instantly become liable for triple damages if a court later decides you infringed it.

**Comment by jchodera** [comment]
I appreciate your advice and viewpoint, but as a scientist, this whole situation is, frankly, beyond ridiculous.

I've emailed David Shaw sharing our concerns and asking for whether we can be assured there will be no litigation over us implementing bitwise-reversible integrators to do research in this area.

If we don't hear back by the time I get back to MSKCC, I'll sit down with our patent lawyers and ask them to produce some documentation that the features we want to implement do not infringe on the DESRES patent.

**Comment by peastman** [comment]
I totally agree it's ridiculous.  But like it or not, that's how the system works.  Laws are written by lawyers, not scientists.

And remember, this isn't just about science, and it isn't just about our own research.  Desmond is a commercial product.  OpenMM directly competes with it.  There's real money involved.  You need to see it from that perspective, because that's certainly how a lawyer would see it.  They would say we were "stealing" a competitor's "intellectual property" to better compete with them.
