### ISSUE TITLE
Custom Ewald force

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#933]
I've been looking into the possibility of creating a PME implementation for custom forces, since several people have asked about that.  It looks to me like that would be challenging at best, but perhaps one of you knows something about it I don't.

From what I've read, it looks like PME has only been derived for one very limited class of potentials: basically a_1*a_2/r^b, where a is a per-particle parameter and b>=1.  And even for that class, it hasn't been derived in a way that would be easy for a single program to support arbitrary values of b.  There isn't a simple formula you plug b into to get the equations.  It's more that there's a procedure to follow, involving a lot of algebra, for any value of b.  Furthermore, if b<=3, the sum is only conditionally convergent, so you have to use tricks to eliminate the infinity, and you can get different results (that have different physical interpretations) depending on how you apply them.

Can anyone provide more insight on this?

**Comment by jchodera** [comment]
Thanks for looking into this, @peastman!

This new paper is relevant in justifying the utility of supporting PME for Lennard-Jones:
http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00190

This uses the gromacs implementation, described in:
http://dx.doi.org/10.1021/ct400140n

which in turn references Appendix A of the Essmann et al paper (with Tom Darden):
http://dx.doi.org/10.1063/1.470117

If the straightforward generalization to other forms of a_1*a_2/r^b is of concern, I've found it much easier to start with the formulation in [this paper](http://dx.doi.org/10.1063/1.1324708).  Following [Smith](http://www.ccp5.ac.uk/infoweb/knowledge_center/smith.pdf)---which can also be extended to multipoles---everything can be computed using a family of functions B_n(r) are defined (Eq. 2.8) that have a simple recurrence relation where B_{n+1} = - (1/r) (d/dr B_n(r)).  

Here's my thought: If you let the user define an interaction kernel f(r), where B(r) = erf(alpha*r)*f(r), the recurrence series could presumably be computed with Lepton.

Not every choice of kernel f(r) would be convergent, but with some care from the user in this choice, it would probably be still of tremendous value.

**Comment by peastman** [comment]
Thanks.  I've read the Gromacs paper, and of course the Essmann one.  I'll take a look at the Toukmaji paper and see if their derivation would be easier to work with.

**Comment by jchodera** [comment]
I'll send you some notes that collect some of the relevant ideas.

**Comment by peastman** [comment]
It looks to me like the Toukmaji paper, and the B_n(r) functions you mentioned, are concerned with doing PME for dipoles.  That's a complication beyond anything I was considering.  I assumed we were only going to try to support spherically symmetric potentials?  But I also don't see how they help with the problems described above.  The B_n(r) functions are used in computing the direct space interaction, not the reciprocal space interaction.

**Comment by jchodera** [comment]
Sorry for the confusion here.

The Toukmaji paper *also* covers dipoles, but the main take-away message for us is that the computations involved in PME (for monopoles as well!) can be formulated using function recurrence relations of the form
```
(d/dr)A_n(r) = -r A_{n+1}(r)
```
from Eq. 2.9 in [the Toukmaji paper](http://dx.doi.org/10.1063/1.1324708).  Because this can be rewritten as
```
A_{n+1}(r) = -r^{-1} (d/dr)A_n(r)
```
I think that we can use Lepton to automatically generate the appropriate recurrence functions for a `CustomEwald` or `CustomPME` class, rather than have you grind out all the algebra for every specific case we want to support.

The description in [my note](https://static1.squarespace.com/static/530562f9e4b06fd3c041e221/t/5565b415e4b06e1248850097/1432728597900/pme-field.pdf) might be easiest to follow.  There are two sets of functions defined by recurrence relations that are relevant.  For standard Coulomb PME, these are
```
B_0(r) = erfc(\alpha r) / r
D_0(r) = - erf(\alpha r) / r
```
The computed terms in standard monopole PME can be computed using these functions and their recurrence-defined `B_n(r)` and `D_n(r)`, used in computing the direct and reciprocal-space interactions.  This form is actually used in one of the (many) PME codepaths in AMBER's `sander` code, with the relevant files mentioned at the end of the note.  `sander` is now part of [AmberTools](http://ambermd.org/#AmberTools) if you want to take a look.  It's actually the most readable of any of the PME implementations in there.

Here's my concrete suggestion:
* We allow the user to define an interaction potential of the form
```
U_{ij}(r) = f(p_i; g) * f(p_j; g) * h(r; g)
```
where `p` are the per-particle parameters, `g` is the set of global parameters, `f(p;g)` is a user-defined function that depends on both per-particle parameters `p` and global parameters `g`, and `h(r; g)` is the interaction kernel function that might also depend on global parameters `g`.
* We do a quick check of the kernel `h(r; g)`---perhaps using numerical integration against `4*pi*r^2` with global parameters `g` set to their defaults---to see if we can catch non-convergent kernels
* We then define the recurrence base functions using Lepton as:
```
B_0(r) = erfc(\alpha r) h(r;g)
D_0(r) = - erf(\alpha r) h(r;g)
```
and then compute the recurrence functions needed for the PME computation (both direct and reciprocal space) using Lepton's differentiation capabilities
* The rest of the PME code refers to the functions `B_n(r)` and `D_n(r)` to perform all computations with the user-specified kernel, with the charge `q_i` replaced by `f(p_i; g)`.

**Comment by peastman** [comment]
The recursively defined functions are used exclusively in calculating the real space contribution.  I'm not concerned about that.  I know how to compute arbitrary potentials in real space.  The hard part is the reciprocal space computation (eq. 19 in your writeup).  How can I compute that for arbitrary functions?

**Comment by jchodera** [comment]
Excellent point.  OK, I think I was totally wrong about whether it is straightforwardly possible to generalize PME for arbitrary interaction kernels of the form `U_{ij}(r) = a_i*a_j*h(r)`, though I think this can be done with some precomputed spline interpolations and Fourier transforms.  I've started to work through a derivation from scratch.  Will let you know if I get anywhere.

**Comment by jchodera** [comment]
Actually, I realize someone else may have tackled this generalization already.

Here is a nice derivation for potentials of the form `a_i*a_j*r^{-p}`:
http://arxiv.org/pdf/1107.5435v1.pdf

This generalized derivation may also be of use (though I haven't been able to get it yet):
http://journals.aps.org/pre/abstract/10.1103/PhysRevE.75.056706

**Comment by peastman** [comment]
Another possible approach might be to do the integrals numerically and then fit a spline to the result.  That might allow arbitrary potentials of the form you suggest, though I'm not sure how you'd handle the convergence issues.

**Comment by peastman** [comment]
More specifically, assume the potential has the form f(r)=a_i*a_j*h(r).  Split it into short and long range parts as f(r)=f(r)*erfc(r)+f(r)*erf(r).  Can we numerically compute the Fourier transform of h(r)*erf(r), fit a spline to it, and use that to compute the long range part with PME?

**Comment by peastman** [comment]
Have you had any more thoughts about this?

**Comment by swails** [comment]
I'm for it!

**Comment by jchodera** [comment]
I like this idea!  Note that it differs from PME and Ewald, where the
charge density is split into a a direct part (delta function minus
Gaussian) and a reciprocal part (Gaussian).  This makes some of the terms
analytically tractable, but we still need to use numerical methods in PME.

Given that we're already using numerical methods, it doesn't seem
unreasonable to just use numerical integrals for the Fourier space
component as well using the new splitting scheme.

We may have to pay some attention to whether the Fourier space sum
converges.  There may be some way to prove the conditions of convergence
(maybe important for a paper) but I imagine a numerical check is sufficient
for our purposes now.

**Comment by peastman** [comment]
Do you want to try to work out the theory and see whether it will really work, or should I try?  I'm willing make an attempt at it, but I may not get to it for a while.

**Comment by jchodera** [comment]
I had started on this with the traditional Ewald splitting.  Let me take a
stab at it with your proposed splitting.  I should have some notes ready on
Monday that we can look at when you return from your travels.

**Comment by peastman** [comment]
I've been looking into this, and I'm clearly confused about something.  The derivation for inverse power potentials in the Essmann paper looks to me like it's simply wrong.  They seem to be assuming that if they replace the point charges by Gaussians, the interaction between two charges is simply given by an integral over the interaction function times a Gaussian.  But that's only true for the very specific case of 1/r!  It comes from the fact that for a spherical shell of charge, the field outside the shell is identical to if all the charge were concentrated at the center, and the field inside the shell is zero.  But that isn't true for general potentials, only for the specific case of 1/r.

**Comment by peastman** [comment]
Here's another paper that does essentially the same thing: http://arxiv.org/abs/1107.5435.  That is, they define the splitting into short and long range components by multiplying the potential by erfc() and erf().  Which is fine for standard Ewald summation.  You can take the Fourier transform and it works.

But that isn't sufficient to do PME.  How are you supposed to spread the "charges" onto the grid?  In the very specific case of a 1/r potential, that division corresponds to a Gaussian distribution for each charge.  But for other potentials it doesn't.  That means we need to solve one of the following problems:

1. Spread the charge in a Gaussian (or some other smooth distribution), then compute how that modifies the form of an arbitrary potential.

2. Multiply the potential by erf(), then figure out what charge distribution that corresponds to for an arbitrary potential.

**Comment by peastman** [comment]
@jchodera are you still planning to do a writeup on this?  FWIW I've spent a lot of time looking into this, and I'm now very doubtful about whether it's possible.  But maybe you have some different ideas.

**Comment by leeping** [comment]
Hi Peter,

I'm late to this discussion, but I've become interested in PME treatments of Lennard-Jones recently.  I was wondering if you could point to a specific equation in the Essmann paper that you think is wrong.  

Thanks,

- Lee-Ping

**Comment by peastman** [comment]
They derive the equations for conventional Ewald summation.  They then assert, without justification, that they can use PME simply by using the conventional Gaussian spreading.  But that just isn't true.  The Ewald splitting only corresponds to a Gaussian charge distribution for the one specific case of a 1/r potential.

**Comment by leeping** [comment]
But it appears that for r^-6, the splitting does not seem to use Gaussian spreading as in the case of r^-1.  They are using a different function for r^-6.  (I'm sorry if I'm misunderstanding.)

![image](https://cloud.githubusercontent.com/assets/1441560/11128993/ef6d88aa-8931-11e5-9ba6-f3f82bae507b.png)

**Comment by peastman** [comment]
Appendix A just derives formulas for conventional Ewald summation.  It doesn't say anything about PME.

Section V is where they assert they can use PME just by spreading the charge in exactly the same way they do for Coulomb.  They're trying to interpret the weighting function as a charge density, which isn't valid.  It doesn't even matter whether it's Gaussian or something else.  Here's how I explained it in an earlier comment:

> But that's only true for the very specific case of 1/r! It comes from the fact that for a spherical shell of charge, the field outside the shell is identical to if all the charge were concentrated at the center, and the field inside the shell is zero. But that isn't true for general potentials, only for the specific case of 1/r.

For a r^-6 potential, the interaction with a spherical shell is *not* the same as the interaction with a point charge at the center of the shell.  So if you take a point charge and replace it with a spherical shell (or in this case, a continuous distribution made up of infinitely many spherical shells), you don't get the same result anymore.

**Comment by jchodera** [comment]
This recent paper may also be relevant:
http://pubs.acs.org/doi/pdf/10.1021/acs.jctc.5b00726

**Comment by leeping** [comment]
I understand your argument about Gauss's Law only being valid for r^-1 potentials.  However, I don't know how this implies PME cannot work, because it's not obvious to me where PME is making that assumption.  Also, I think PME is used for dipoles and quadrupoles in AMOEBA, and those interactions don't go as 1/r.  

It might help clear up my confusion if I could check specific equations in the paper; are (5.2) and (5.3) the ones that have problems?

**Comment by peastman** [comment]
It's the sentence immediately following those equations:

"From here the development is very similar to that for the Coulombic reciprocal sum, with the array Q replaced by an analogous array 􏰽, which is determined from the dispersion coefficients 􏱙 j using the same B-spline coefficient expansion as in Eq. (4.6)."

>  However, I don't know how this implies PME cannot work, because it's not obvious to me where PME is making that assumption.

Ewald summation begins by splitting the Coulomb interaction into two parts that are multiplied by erf() and erfc() respectively.  That particular splitting happens to be identical to what you get if you use a Gaussian charge distribution for one part, and subtract that same distribution from the other part.  PME makes use of that fact by explicitly forming a Gaussian charge distribution, then approximating it on a grid.  But that fact is true because of Newton's shell theorem, which only applies to 1/r potentials.

It isn't actually critical what splitting you use.  If you use a different one, that just corresponds to a different charge distribution.  But again, only for 1/r potentials.  In this case they've derived a different splitting, and hence different reciprocal space weight factors (eq. 5.2).  Then they incorrectly and without any attempt at justification claim they can be used as a charge distribution, just as if Newton's shell theorem still applied.

**Comment by leeping** [comment]
Hi Peter,

I read over the Essmann paper carefully to address your question.  I know it's been a few months.  :)

If we agree that (5.2) and (5.3) are correct, then PME proceeds from here - namely, finding a way to evaluate the structure factor (5.3) efficiently.  (5.3) involves the c6-coefficients, a reciprocal lattice vector **m** and the positions of atoms **r**_i.  

Next we go to equation (3.2) where exp(2π_i_**m·r**) is evaluated on a grid of points, and piecewise interpolation is used to evaluate the function in between the points.  I assume the specific kind of interpolating polynomial is not important for this argument; in the Essmann paper, they first introduce linear interpolation and then talk about the B-splines in section 4.

The interpolated complex exponential is inserted into the expression for the structure factor (3.6) which, for our case, contains c6 coefficients instead of point partial charges.  The result is that a variable _Q_ appears that corresponds to c6 coefficients on a grid of points (3.7).

Thus, from my reading it seems that the grid of c6-coefficients is a consequence of approximating the structure factors, and not by relying on Newton's shell theorem.  Thus there is no need to physically interpret the grid of c6-coefficients as a kind of Lennard-Jones "charge".

Let me know if this makes sense.  I am also interested in whether we could design some good numerical tests for the correctness of LJ-PME.

Thanks,

- Lee-Ping

**Comment by jchodera** [comment]
This recent paper may be relevant (though I haven't had a chance to look into it yet):

A Stochastic Algorithm for the Isobaric–Isothermal Ensemble with Ewald Summations for All Long Range Forces
http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00648

**Comment by jchodera** [comment]
That paper cites [this one](http://scripts.iucr.org/cgi-bin/paper?a07938) which shows how to decompose pairwise potentials for the form `q_i q_j r_{ij}^{-n}` for `n > 3` or `n > 0 with \sum_i q_i = 0`.

**Comment by andysim** [comment]
Hi, all.  Sorry to be so late onto this one, but I'd be happy to take a stab at getting this going in OpenMM.  Frank Pickard and I put dispersion PME (DPME as we call it) into CHARMM, with lots of helpful bug reports from Jing Huang from the MacKerell group, and the results look great so far.  We only have the 6th power version coded up right now, but I know how to generalize it to arbitrary powers greater than 2.  The nice thing about potentials with `n>3` is that they're already absolutely convergent;  we can get extremely good agreement between a standard LJ setup with huge cutoffs and a DPME run.  Another simple test of correctness is invariance of the energy, forces and virial, with respect to variation of the attenuation parameter, which is essentially how we debugged our hexadecapoles without having any reference code.

**Comment by jchodera** [comment]
This would be great!

**Comment by peastman** [comment]
We now support dispersion PME, and PME for arbitrary potentials probably isn't possible.
