### ISSUE TITLE
Automatic benchmarking with airspeed velocity?

### ISSUE THREAD

**Issue by rmcgibbo** [openmm/openmm#984]
It could be useful to track benchmarks on a couple different machines automatically over the life of the project. For example, using a cron tab and airspeed-velocity. 

http://asv.readthedocs.org/en/latest/index.html

examples: http://mdboom.github.io/astropy-benchmark/, https://pv.github.io/scipy-bench/

I believe scipy is now using this tool to track performance over time, so it's got some buyin https://github.com/scipy/scipy/issues/4277, https://github.com/scipy/scipy/pull/4501

**Comment by rmcgibbo** [comment]
That tool might been some customization to work with cmake / conda-build, or there might be other similar tools that accomplish the same thing.

**Comment by mpharrigan** [comment]
Yeah, wouldn't it be better to use something designed with cmake in mind?

**Comment by rmcgibbo** [comment]
I tried googling, but didn't find a tool like this for cmake. Perhaps I wasn't using the right search term though.

**Comment by peastman** [comment]
I don't have any experience with specific tools for doing this, but I agree it would be really useful.

**Comment by rmcgibbo** [comment]
I also found https://github.com/tobami/codespeed, and a presentation by the airspeed team at scipy2014 https://www.youtube.com/watch?v=OsxJ5O6h8s0.

**Comment by jchodera** [comment]
Automated benchmarking would be awesome.  If there is something we can help set up for OpenMM, we're happy to help.

I'm trying to figure out how we can get access to a heterogenous set of automated build hardware where we can deploy different software images in order to enable testing over a variety of cards, OSes, and drivers.  Unfortunately, there isn't a cloud solution for this, and VMs don't play well with GPUs yet, so it looks like we might end up just building a pile of PCs using micro-ATX cases and tossing a single graphics card into each box.  Not sure what provisioning system is easiest to use to automate the process of deploying images and running benchmarks, so if anybody has any suggestions, send them our way!

**Comment by rmcgibbo** [comment]
For continuous benchmarking, I was kind of assuming that we could get something practically useful with only one or two machines -- mostly you're interested in the differences between commits, not the differences between machines. I don't want to bite off more than we can chew, but if this works we could definitely scale it up.

**Comment by jchodera** [comment]
> For continuous benchmarking, I was kind of assuming that we could get something practically useful with only one or two machines -- mostly you're interested in the differences between commits, not the differences between machines. 

Some of the changes have positively impacted some hardware and negatively impacted other hardware.  We could certainly target a small number of cards, but I think it is useful to at least consider the combinations of a few cards x a few OSes x a few drivers.

**Comment by rmcgibbo** [comment]
Yeah, you're definitely right... I just want to test this out with baby steps.

**Comment by rmcgibbo** [comment]
We have something preliminary running. You can see it at http://rmcgibbo.github.io/openmm-bench/ The code is https://github.com/rmcgibbo/openmm-bench, and in my fork of asv.

**Comment by jchodera** [comment]
Awesome!  We can give this a try on some of our hardware.

**Comment by peastman** [comment]
Could you explain what the graphs are showing?  I'm a little unclear on what I'm actually looking at.

**Comment by leeping** [comment]
I couldn't really figure it out either.  It would be nice to have axis labels.

**Comment by rmcgibbo** [comment]
they're nanoseconds per day for the different benchmarks.

**Comment by rmcgibbo** [comment]
the web interface needs work, i know.

**Comment by leeping** [comment]
Is the x-axis the date for running the tests?  

I think this is a great idea, because the CI framework isn't good at catching performance regressions but these graphs can show it clearly.  I'm also not sure why the right-most part of some of these graphs looks "noisy" with a large dip in performance.

**Comment by rmcgibbo** [comment]
The x axis is the date of the commit. I think the noise is just the stochastic fluctuations of the tests, and the fact that I was running them at work when I was using my computer for other stuff. Once we get everything set up satisfactorily, we can delete the results cache and rerun everything, if necessary.

**Comment by rmcgibbo** [comment]
Okay, I've cleaned up the javascript a bit, so the site should be a little more usable now: http://rmcgibbo.github.io/openmm-bench/

**Comment by mpharrigan** [comment]
yay usable site!
